### PR TITLE
[Backport] Restart entire node on tunnel collapse (#8102)

### LINKED ISSUE #7606: Feature Request: Handle changes to tunnel_public_addr
### What
Currently, when the `tunnel_public_addr` is changed on the proxy server, existing node agents are disconnected and continuously poll the old address.  The node agent requires a restart to discover the new address and reconnect. 

The desired behavior is for disconnected node agents to poll the API for changes to the `tunnel_public_addr` so they can reconnect without a restart.

### Why
This will help teleport cloud migrate existing customers to a new load balancer design with minimal disruption. Without this feature, customers would have to restart all node agents for the nodes to reconnect to their teleport cloud instance.

The configuration changes look something like the following, where only the `public_addr` remains the same.

```diff
  public_addr: proxy.example.com:443
+ ssh_public_addr: proxy.example.com:11000
+ tunnel_public_addr: tunnel_proxy.example.com:11001
+ kube_public_addr: proxy.example.com:11002
+ mysql_public_addr: proxy.example.com:11003
- ssh_public_addr: proxy.example.com:3023
- tunnel_public_addr: proxy.example.com:3024
- kube_public_addr: proxy.example.com:3025
- mysql_public_addr: proxy.example.com:3036
```

### Workaround
Restarting the node agents will get the updated `tunnel_public_addr`.

### PR DESCRIPTION
**Pull request by tcsc**
Fixes #7606, where a node doesn't notice when the tunnel port changes.

Imagine you have a cluster with a node connected in via a tunnel through a proxy `proxy.example.com` on port `3024`

Now change the proxy config so that `tunnel_public_address` is `proxy.example.com:4024`. You either restart the proxy, or reload the proxy config with a `SIGHUP`.

...and then the node
  a) loses its connection to auth (because the tunnel is gone), and
  b)  _doesn't reconnect_, because even though the proxy address hasn't changed,
      the node has cached the old tunnel_public_address and keeps trying to connect
      to that.

You can always manually restart the node to have it reconnect, but that would be a pain if you have thousands of nodes.

In order to not have to manually restart all nodes, this change implements a check for a connection failures to the auth server, and re-starts the node if there are multiple connection failures in a given period of time. The check as-implemented piggybacks on the node's "common.rotate" service, which can already restart the node in certain circumstances, and uses the success of the periodic rotation sync as a proxy for the health of the node's connection to the auth server.

See-Also: #7606

### CODE REVIEW

**Review by russjones — APPROVED** [review]

**Comment by russjones** [comment]
@tcsc Remember to do some manual testing before merging since it's going onto a release branch.

**Comment by tcsc** [comment]
Manually tested a local build and it appears to work.

**Review by codingllama — APPROVED** [review]
LGTM - no changes from the original, correct?

Do you mind duplicating some of the original title too? Ideally someone reading the git logs of branch/v7 should have an idea of what this does without having to look up #8102 in GitHub.

**Comment by tcsc** [comment]
> LGTM - no changes from the original, correct?

Small change to port allocation in the integration test to match older code, but otherwise yes.

**Pull request merged**
