### PR TITLE
use stable/cloud repo for cloud tenants

### PR DESCRIPTION
**Pull request by stevenGravy**
Currently the node install uses the major version, not checking to see if it should use the cloud/stable.

### CODE REVIEW

**Review by r0mant — CHANGES_REQUESTED** [review]
@stevenGravy We should not be implementing this logic in the script. Whether to use stable/cloud repo is controlled by the web handlers, e.g.

https://github.com/gravitational/teleport/blob/v13.0.2/lib/web/join_tokens.go#L212

Looks like we may just need to remove `h.ClusterFeatures.AutomaticUpgrades` condition to always use this channel for all Cloud customers. This change needs to be applied to all other script handlers as well though:

https://github.com/gravitational/teleport/blob/v13.0.2/lib/web/join_tokens.go#L256
https://github.com/gravitational/teleport/blob/v13.0.2/lib/web/join_tokens.go#L286
https://github.com/gravitational/teleport/blob/v13.0.2/lib/web/apiserver.go#L1594

@marcoandredinis Is that right? Are there any other places that need changing?

@marcoandredinis @hugoShaka There shouldn't be any downside in using this channel now for all Cloud customers, is there? We won't actually install the "updater" package unless the Cloud tenant is actually enrolled in auto-upgrades, correct?

**Comment by r0mant** [comment]
@marcoandredinis We only update stable/cloud after Cloud control plane has been upgraded (using [this workflow](https://github.com/gravitational/cloud/blob/master/.github/workflows/deploy-auto-update-changes.yml) @fheinecke built) so we should be good.

@stevenGravy We'll take over this PR. @marcoandredinis Can you please make necessary changes?

**Comment by marcoandredinis** [comment]
@hugoShaka @stevenGravy Can you please take a look?

**Comment by stevenGravy** [comment]
> @hugoShaka @stevenGravy Can you please take a look?

Looks right to me!

**Review by hugoShaka — APPROVED** [review]

**Review by r0mant — APPROVED** [review]

**Pull request merged**
