### PR TITLE
[v10] Fix copy paste mistake in azure proto

### PR DESCRIPTION
**Pull request by GavinFrazar**
I made a mistake in https://github.com/gravitational/teleport/pull/15673 yesterday adding a field to Azure metadata protobuf, giving "ResourceID" the same json key as "Name".

Backports #15864

### CODE REVIEW

**Comment by greedy52** [comment]
Is this required for v10?

**Comment by smallinsky** [comment]
@GavinFrazar Lets wait with back-porting  to v10  till we will merge all PRs related to auto-discovery to master branch.

**Comment by GavinFrazar** [comment]
> Is this required for v10?

No but the protobuf mistake was backported to v10 and this fixes it

**Review by smallinsky — APPROVED** [review]

**Comment by greedy52** [comment]
> > Is this required for v10?
> 
> No but the protobuf mistake was backported to v10 (by an unrelated PR someone else made) and this fixes it

I don't see `ResourceID` existing on v10?
https://github.com/gravitational/teleport/blob/70d83e1fdbd90be06219d826716c4901e434efcf/api/proto/teleport/legacy/types/types.proto#L446-L450

**Comment by GavinFrazar** [comment]
> > > Is this required for v10?
> > 
> > 
> > No but the protobuf mistake was backported to v10 (by an unrelated PR someone else made) and this fixes it
> 
> I don't see `ResourceID` existing on v10? Or am I missing something
> 
> https://github.com/gravitational/teleport/blob/70d83e1fdbd90be06219d826716c4901e434efcf/api/proto/teleport/legacy/types/types.proto#L446-L450

Oh, huh. I saw a PR which moved types.proto and included the azure proto mistake: #15856
And then I saw that PR was being backported to v10 in: #15875
but I didn't notice that the backport didn't include the azure proto mistake (because it didn't cherry pick master). I guess we don't need this then

**Comment by GavinFrazar** [comment]
My bad guys, thought my mistake was propagated to v10 in a backport. I'll close this

**Pull request closed without merging**
