### PR TITLE
Allow custom webassets path if debug mode is on

### PR DESCRIPTION
**Pull request by codingllama**
Useful for debugging Teleport servers in modern IDEs.

### CODE REVIEW

**Comment by codingllama** [comment]
FYI @zmb3

**Comment by codingllama** [comment]
Friendly ping?

**Review by zmb3 — APPROVED** [review]

**Review by klizhentas — APPROVED** [review]
bot

**Comment by codingllama** [comment]
Thanks for the approvals, everyone.

**Pull request merged**
