### PR TITLE
Remove unused teleport-demo chart

### PR DESCRIPTION
**Pull request by webvictim**
This chart is being relocated to our internal ops repo.

### CODE REVIEW

**Comment by webvictim** [comment]
retest this please

**Review by awly — APPROVED** [review]
`+0 −3,176` :fire: 

LGTM, let's wait for @russjones or @benarent to sign off (in case they are aware of anyone using this)

**Review by benarent — APPROVED** [review]
LGTM. I've not been using the demo chart. I think for demos / quick starts it's best to instructions people to build off our existing base vs being too opinionated in a complete chart.

**Comment by benarent** [comment]
FYI @stevenGravy @jon-can in case you might of been using this.

**Comment by webvictim** [comment]
I spoke with Jon and Steven, they said it's OK to move it.

**Pull request merged**
