### PR TITLE
Set flush interval when forwarding application http requests

### LINKED ISSUE #7197: Application using EventSource to stream events to client does not stream events until end
### Description

**What happened**:

I am using JupyterHub https://jupyter.org/hub behind Teleport and have noticed that when loading the users instance the status is not showing, FWIW this works fine accessing the application when Teleport is not involved.

Jupyter uses an EventSource https://developer.mozilla.org/en-US/docs/Web/API/EventSource to report progress when loading an instance and from what I can see it begins the request, and does not receive any events until complete, i.e. the events are not being streamed back as expected.

**What you expected to happen**:

I expect Jupyter to show progress to show status iteratively and not just once at the end.

### Reproduction Steps
As minimally and precisely as possible, describe step-by-step how to reproduce the problem.
1. Run an JupyterHub instance
2. Spawn an notebook instance
3. Witness the lack of progress updates during instance spawning

### Server Details
- Teleport version (run `teleport version`): 6.2.1
- Server OS (e.g. from `/etc/os-release`): Ubuntu 20.04
- Where are you running Teleport? (e.g. AWS, GCP, Dedicated Hardware): AWS
- Additional details: Running Teleport using the teleport-cluster helm chart

### Client Details
- Tsh version (`tsh version`): v6.2.1
- Computer OS (e.g. Linux, macOS, Windows): Linux
- Browser version (for UI-related issues): Chrome  91.0.4472.77
- Installed via (e.g. apt, yum, brew, website download): apt
- Additional details:

### Debug Logs

Logs are not showing much here, can provide if needed.

### PR DESCRIPTION
**Pull request by stefansedich**
This PR fixes https://github.com/gravitational/teleport/issues/7197

From my digging I found that the reason the eventsources were not working was that the response was not sent back to the client until the completion of the request.

This change sets up the flush interval so that we send back data as it is received which from my testing shows that the Juptyer status reporting on instance startup to be working as expected.

I am not sure if the `FlushInterval` is needed in both places as I am not overly familiar with this codebase and what the difference between `srv/app` and `web/app` were so to be safe I put it in both for now.

### CODE REVIEW

**Comment by klizhentas** [comment]
@r0mant can you please review? I don't recall what this flush interval is doing, is it only triggering on the present data in the buffer or it's just a timer? What are performance implications to consider with 100ms interval?

**Comment by stefansedich** [comment]
> @r0mant can you please review? I don't recall what this flush interval is doing, is it only triggering on the present data in the buffer or it's just a timer? What are performance implications to consider with 100ms interval?

Thanks @klizhentas FWIW I took the interval from the kube proxy https://github.com/gravitational/teleport/blob/1d37ede93618c227d2ed9a49b5ad64b98e7f5fdf/lib/kube/proxy/forwarder.go#L1473 so am not sure 100ms is reasonable but hopefully @r0mant can provide more context on the wider implications that I am not aware of.

**Comment by stefansedich** [comment]
@klizhentas @r0mant do you have any more thoughts here? we are looking for a fix to get eventsources working as many of our apps are not working properly behind Teleport without them, this change appears to resolve things and everything works without issue.

Happy to take another route with the PR if this change will not work for some reasons I am not aware of.

**Comment by r0mant** [comment]
@stefansedich Sorry about the delay on this one, it's been busy with last/this week's releases coming out. I don't know off the top of my head all implications of using this setting. I think it should be fine since Kubernetes forwarder uses it too (and looking at git history it was introduced to fix a somewhat similar issue with K8s requests proxying) but I'd have to take a closer look at the source code. I'll try to get to it this week.

At a minimum we'd need to add test coverage to this PR.

Also, what would be a good eventsource-based application to test this?

**Comment by r0mant** [comment]
@stefansedich Thank you for your contribution and patience.

We are currently unable to run CI on external PRs. As such, I have created a "buddy" PR for this change (preserving your authorship) and also added a test covering this scenario: https://github.com/gravitational/teleport/pull/8359. Once it's approved, we'll merge it in and backport to v7 as well.

Going to close this PR and thanks again!

**Comment by stefansedich** [comment]
> #8359

Thanks @r0mant appreciate it!

**Pull request closed without merging**
