### PR TITLE
Update `crypto` to `0.6.0` and remove our replacement in `api`

### PR DESCRIPTION
**Pull request by jentfoo**
It was missed that cyrpto is being replaced in our `api` as well (previous PR #22564). This commit updates the version to match the one in the repo root.

### CODE REVIEW

**Review by espadolini — APPROVED** [review]

**Comment by jentfoo** [comment]
@zmb3, @r0mant, @jakule after discussing with @espadolini I decided to update this PR to remove this replacement.

Understanding that `api` should be referenced as an external module, this replacement value will not function for our users projects unless they additionally copy the replacement definition into to their projects `go.mod`.  For that reason I suggest we remove this to make sure we have API / testing compatibility that matches how our users are most likely using this module.

Let me know if you have any concerns with removing the `crypto` replacement in `api`.  Thank you!

**Comment by espadolini** [comment]
We should make sure that any functionality in `api` doesn't depend on changes in our fork (or that we're ok if that happens, like with the SSH client being stricter with regards to RSA).

**Review by espadolini — APPROVED** [review]

**Review by jakule — COMMENTED** [review]
>We should make sure that any functionality in api doesn't depend on changes in our fork 

I'm not entirely sure if the changes in our fork are not required in our API. As @espadolini mentioned, unless we're fine with having broken compatibility with CentOS 7 OpenSSH we should probably test these changes before merging.

**Comment by jentfoo** [comment]
> unless we're fine with having broken compatibility with CentOS 7 OpenSSH

My concern is that this is already the case for anyone dependent on this module.

**Review by jakule — APPROVED** [review]
@espadolini @jentfoo Thanks for the explanation. We should probably mention that this replace is/maybe needed in our docs.

**Pull request merged**
