### PR TITLE
Use the new endpoints in the assistant UI

### PR DESCRIPTION
**Pull request by ryanclark**
This changes the `/assistant` websocket so it no longer starts new conversations/pushes the conversation history to the UI through the websocket.

Instead, this uses the new REST endpoints for creating a conversation and fetching that conversation's history.

This also adds a back button to go back to the UI

### CODE REVIEW

**Comment by jakule** [comment]
@ryanclark Do we want to completely remove the messages from WS? I thought that we just add a flag as I described in the RFD https://github.com/gravitational/teleport.e/pull/1092/files#diff-58188149c0361ec517aaa184d723d56cf8dba708627bab86452582b5e477d41bR26-R29

**Comment by ryanclark** [comment]
> @ryanclark Do we want to completely remove the historical messages from WS on connect? I thought that we just add a flag as I described in the RFD https://github.com/gravitational/teleport.e/pull/1092/files#diff-58188149c0361ec517aaa184d723d56cf8dba708627bab86452582b5e477d41bR26-R29

I think so, I don't see a use case for it

**Comment by xacrimon** [comment]
This seems racy, though. To me it makes more sense to use the WS when we can.

**Comment by ryanclark** [comment]
> This seems racy, though. To me it makes more sense to use the WS when we can.

How so?

**Comment by ryanclark** [comment]
> Because there's some gap between us fetching what we think is the actual message log and us then "attaching" to what is the current one. May not matter a lot here in the end but still it seems wierd to split on this here.

I don't see this being an issue. OpenAI's UI does the same as we're doing in this PR.

**Review by xacrimon — APPROVED** [review]

**Pull request merged**
