### PR TITLE
Update WebAuthn and U2F dependencies

### PR DESCRIPTION
**Pull request by codingllama**
Update `duo-labs/webauthn` up to `20220122034320`, which is the latest version we can get without dipping into dependency hell (`etcd` and `opentelemetry` woes ensue after [2365c59d9f][1]).

`tstranex` could be dropped for a while now (we moved on to WebAuthn-like interfaces for mocks). `cfssl` was only imported due to what I assume was an IDE mishap.

I've elected to keep `fxamacker/cbor`, instead of trying to move to [webauthncbor][2]. fxamacker is solid, past v0, seems more appropriate for client-side libs and still backs webauthncbor.

There are no updates for `flynn/hid` and `flynn/u2f`.

Release notes for fxamacker/cbor: https://github.com/fxamacker/cbor/releases/tag/v2.4.0.

[1]: https://github.com/duo-labs/webauthn/commit/2365c59d9fb666cb5f5b6bbae86910632198a8d4
[2]: https://pkg.go.dev/github.com/duo-labs/webauthn@v0.0.0-20220815211337-00c9fb5711f5/protocol/webauthncbor

### CODE REVIEW

**Review by tobiaszheller — APPROVED** [review]
LGTM,
i think when https://github.com/duo-labs/webauthn/pull/150 it merged we can come back and bump webauthn lib

**Comment by codingllama** [comment]
> LGTM, i think when [duo-labs/webauthn#150](https://github.com/duo-labs/webauthn/pull/150) it merged we can come back and bump webauthn lib

Let's see if it lands, definitely makes life easier.

**Review by Joerger — APPROVED** [review]

**Comment by codingllama** [comment]
Friendly ping @jakule

**Review by jakule — APPROVED** [review]
@codingllama Friendly approve.

**Pull request merged**
