### PR TITLE
chore: Bump Buf to v1.20.0

### PR DESCRIPTION
**Pull request by codingllama**
Keep up with latest releases.

https://github.com/bufbuild/buf/releases/tag/v1.20.0

### CODE REVIEW

**Comment by codingllama** [comment]
No codegen changes and everything seems to work, but with the new version we now get the following warnings:

```
$ make grpc
> WARN	bufimagebuild	File "teleport/integration/v1/integration_service.proto" imports "teleport/legacy/types/types.proto", which is not found in your local files or direct dependencies, but is found in a local workspace unnamed module. Name the module and declare it in the deps key in buf.yaml.
> WARN	bufimagebuild	File "teleport/kube/v1/kube_service.proto" imports "teleport/legacy/types/types.proto", which is not found in your local files or direct dependencies, but is found in a local workspace unnamed module. Name the module and declare it in the deps key in buf.yaml.
> WARN	bufimagebuild	File "teleport/loginrule/v1/loginrule.proto" imports "teleport/legacy/types/types.proto", which is not found in your local files or direct dependencies, but is found in a local workspace unnamed module. Name the module and declare it in the deps key in buf.yaml.
> WARN	bufimagebuild	File "teleport/loginrule/v1/loginrule.proto" imports "teleport/legacy/types/wrappers/wrappers.proto", which is not found in your local files or direct dependencies, but is found in a local workspace unnamed module. Name the module and declare it in the deps key in buf.yaml.
> WARN	bufimagebuild	File "teleport/okta/v1/okta_service.proto" imports "teleport/legacy/types/types.proto", which is not found in your local files or direct dependencies, but is found in a local workspace unnamed module. Name the module and declare it in the deps key in buf.yaml.
> WARN	bufimagebuild	File "teleport/plugins/v1/plugin_service.proto" imports "teleport/legacy/types/types.proto", which is not found in your local files or direct dependencies, but is found in a local workspace unnamed module. Name the module and declare it in the deps key in buf.yaml.
> WARN	bufimagebuild	File "teleport/trust/v1/trust_service.proto" imports "teleport/legacy/types/types.proto", which is not found in your local files or direct dependencies, but is found in a local workspace unnamed module. Name the module and declare it in the deps key in buf.yaml.
> WARN	bufimagebuild	File "teleport/lib/teleterm/v1/usage_events.proto" imports "prehog/v1alpha/connect.proto", which is not found in your local files or direct dependencies, but is found in a local workspace unnamed module. Name the module and declare it in the deps key in buf.yaml.
```

Note that these happen when we mix proto generators - importing legacy in non-legacy mixes gogo and protoc-gen-go protos, importing prehog in teleterm mixes connect and protoc-gen-go. I think that's asking for trouble, so I'll move them all to the "least negotiable" generator (ie, gogo and prehog).

FYI @marcoandredinis @tigrato @nklaassen @mdwn @espadolini @ravicious.

**Comment by ravicious** [comment]
Why is mixing generators causing warnings about proto-level issues though? 🤔

**Comment by codingllama** [comment]
> Why is mixing generators causing warnings about proto-level issues though? 🤔

The origin of the warning is that we are passing/excluding certain paths to `buf generate`, but it figured out that we are importing protos from outside of those paths (which it thinks are separate modules).

**Comment by codingllama** [comment]
Friendly ping?

I could still use the approvals here, the warnings don't really change anything.

**Review by tigrato — APPROVED** [review]

**Review by ravicious — APPROVED** [review]

**Review by espadolini — APPROVED** [review]

**Pull request merged**
