### PR TITLE
return an error when attempting to join a session of an OpenSSH node

### LINKED ISSUE #31422: `tsh join <agentless-node>` fails
With a session open with an agentless node, running `tsh join` fails to connect

```
λ tsh join 4e0b69a3-5677-4b19-854d-9e0d6ac825d5
ERROR: access denied to -teleport-internal-join connecting to e990dc0a-c042-496d-a8c3-23a9b1dc38a0.localhost:0
```

### PR DESCRIPTION
**Pull request by capnspacehook**
Fixes https://github.com/gravitational/teleport/issues/31422.

### CODE REVIEW

**Comment by zmb3** [comment]
Just confirming, this was never supported, right? #31422 is written as-if joining is supposed to work, and this PR just changes the error message.

**Comment by marcoandredinis** [comment]
I don't know how join session works, but could we tap into the ssh connection bridge that happens at the proxy and act there to provide the feature?
Not saying this would be easy, but is it doable?

**Comment by capnspacehook** [comment]
I was looking into this for awhile yesterday and it is doable like you said @marcoandredinis, just would be a non-trivial change and one I don't have the load for right now. Talked to @r0mant about it and he said for now a clear error should be returned to the user.

**Review by marcoandredinis — APPROVED** [review]
LGTM

It would be good to add some tests to this

**Comment by tigrato** [comment]
> I don't know how join session works, but could we tap into the ssh connection bridge that happens at the proxy and act there to provide the feature? Not saying this would be easy, but is it doable?

I have been playing with this for a while because of TAG and the change isn't particularly difficult. The biggest issue is that the join process must change We need to route the request to the correct proxy instead of the target service but apart from that should follow the same principles. 

For Kube, we do something similar when the number of replicas is bigger than 1.

**Review by tigrato — APPROVED** [review]

**Comment by capnspacehook** [comment]
@marcoandredinis test added

**Comment by capnspacehook** [comment]
Not sure how the deploy triggered, tried to send the last comment, had to re-auth and when I refreshed the page it said I requested a deploy... weird

**Comment by capnspacehook** [comment]
@lsgunn-teleport @ptgott could one of you please approve this, I added a line to the Agentless docs so it's explicitly documented that OpenSSH sessions can't be joined/shared currently

**Review by ptgott — APPROVED** [review]

**Pull request merged**
