### PR TITLE
Return NotFound error when trait does not exist

### PR DESCRIPTION
**Pull request by marcoandredinis**
We were returning a trace.BadParameter, however we should return trace.IsNotFound.
The godoc suggests that error.
The tests suggests that error, but they were only matching for type which is the same for all the trace.XYZ errors.

Tests are now using the `trace.Is<Error>` helper method to correctly validate the error message.

The side effect of this change is that we were receiving a lot of logs when interpolating traits in a role.
That log is supressed when the error is NotFound.
That was not the case before this commit: the error was a BadParameter one, so the log is written (as debug, but still a lot of noise).

For the record, here's the log message
```log
2023-01-19T14:33:18Z DEBU             Skipping database user "{{internal.db_users}}". error:[
ERROR REPORT:
Original Error: *trace.BadParameterError variable not found: {internal db_users}
Stack Trace:
        github.com/gravitational/teleport/lib/utils/parse/parse.go:108 github.com/gravitational/teleport/lib/utils/parse.(*Expression).Interpolate.func1
        github.com/gravitational/teleport/lib/utils/parse/ast.go:149 github.com/gravitational/teleport/lib/utils/parse.(*VarExpr).Evaluate
        github.com/gravitational/teleport/lib/utils/parse/parse.go:114 github.com/gravitational/teleport/lib/utils/parse.(*Expression).Interpolate
        github.com/gravitational/teleport/lib/services/role.go:521 github.com/gravitational/teleport/lib/services.ApplyValueTraits
        github.com/gravitational/teleport/lib/services/role.go:434 github.com/gravitational/teleport/lib/services.applyValueTraitsSlice
.....
        google.golang.org/grpc@v1.51.0/server.go:1713 google.golang.org/grpc.(*Server).handleStream
        google.golang.org/grpc@v1.51.0/server.go:965 google.golang.org/grpc.(*Server).serveStreams.func1.2
User Message: variable not found: {internal db_users}] services/role.go:437
```

### CODE REVIEW

**Review by vitorenesduarte — APPROVED** [review]
Thanks! This was indeed a `NotFound` before #19696:
https://github.com/gravitational/teleport/blob/69a9dbf3a27c6a6da4eaafb89d69849c34beed1b/lib/utils/parse/parse.go#L114-L121

**Comment by marcoandredinis** [comment]
@vitorenesduarte Can you please add this commit (when merged) to the backport PRs you already created?

For `branch/v12` we'll need to backport it as well

**Review by nklaassen — APPROVED** [review]

**Review by xacrimon — APPROVED** [review]

**Comment by Tener** [comment]
This change has a negative effect on UX. For `trace.BadParameter` we are showing the error to the user:

image

With `trace.NotFound` we are not - it looks like the user doesn't exist:

image

**Comment by marcoandredinis** [comment]
This was mostly a revert of a error kind that broke other parts of the code.
Should we have a follow up on this? An issue maybe

**Comment by Tener** [comment]
Ah, ok then. I think it may be worth it from a usability perspective to at least inform the user there was _some_ kind of issue with their roles, perhaps not necessarily giving the exact error. They should escalate to their admins, who can investigate further. This is basically a UX improvement feature and perhaps not the most pressing one.

**Pull request merged**
