### PR TITLE
Omit change analysis when there is no base branch for comparison.

### PR DESCRIPTION
**Pull request by tcsc**
In some cases, PRs do not furnish the google cloud builder a  `$_BASE_BRANCH` value, in which case the build fails as it is missing a required parameter.

The `$_BASE_BRANCH` value is used when comparing the PR changes to the merge target to identify code-only or doc-only changes, in order to allow the build to skip running expensive tests for documentation-only changes. 

This patch updates the build scripts to allow the build trigger to omit the `_BASE_BRANCH`. If `_BASE_BRANCH` is not set the build assumes that there are code changes and executes a full test run.

### CODE REVIEW

**Review by espadolini — APPROVED** [review]
When do we not have a target branch?

**Comment by tcsc** [comment]
> When do we not have a target branch?

PRs form external forks (sometimes!) do not give a _BASE_BRANCH

**Comment by russjones** [comment]
@tcsc Let's find out why they sometimes don't have `_BASE_BRANCH` set before we merge this.

**Comment by tcsc** [comment]
> @tcsc Let's find out why they sometimes don't have `_BASE_BRANCH` set before we merge this.

Response from the GCB Community slack:
> not something we're aware of (I think). if you open a support case with the details, it should get routed to us.

Unfortunately it looks like we need to buy support to open a case...

**Comment by nklaassen** [comment]
Fwiw I have seen this issue on internal branches as well when trying to re-run integration or unit tests

**Comment by tcsc** [comment]
https://issuetracker.google.com/issues/219068019

**Comment by zmb3** [comment]
Closing since this is deprecated by the GHA work.

**Pull request closed without merging**
