### PR TITLE
Configure env for teleport-cluster chart

### PR DESCRIPTION
**Pull request by stefansedich**
We need to configure some environment variables on our teleport pod for configuration needs, this adds support for setting `extraEnv` on the teleport container.

### CODE REVIEW

**Comment by russjones** [comment]
@webvictim Can you review?

**Review by webvictim — CHANGES_REQUESTED** [review]
@stefansedich Changes look OK.

Please also add this value to the Helm chart reference at https://github.com/gravitational/teleport/blob/master/docs/pages/kubernetes-access/helm/reference.mdx so that it's kept up to date.

Thanks for the PR!

**Comment by stefansedich** [comment]
> @stefansedich Changes look OK.
> 
> Please also add this value to the Helm chart reference at https://github.com/gravitational/teleport/blob/master/docs/pages/kubernetes-access/helm/reference.mdx so that it's kept up to date.
> 
> Thanks for the PR!

Done @webvictim

**Review by webvictim — APPROVED** [review]
@stefansedich Thanks - this will be merged once it has another approving review.

**Review by inertial-frame — APPROVED** [review]

**Review by klizhentas — APPROVED** [review]

**Pull request merged**
