### PR TITLE
[v8] backport #9697 (improved Google OIDC) 

### PR DESCRIPTION
**Pull request by espadolini**
Backport of
* #9697

### CODE REVIEW

**Comment by espadolini** [comment]
Like #9697, I will wait for approvals here and for gravitational/teleport.e#387, I will merge `e` and I will update the e-ref commit to point to that before merging this one.

**Comment by Tener** [comment]
So, this looks to be a rather involved change (387 files, multiple dependencies) with the potential for unexpected issues. I'm not saying anything is particularly wrong, but perhaps we want to avoid backporting it to keep v8 stable?

**Comment by espadolini** [comment]
@Tener v8 still has the vendor directory, that's where the vast majority of those changes come from; do you want me to split off that part of the PR into a separate module upgrade instead?

**Review by russjones — APPROVED** [review]

**Comment by Tener** [comment]
@espadolini Nah, no need to split; I agree that the plain number of changed files may be a wrong metric to look at directly given that includes vendor/*. I was more concerned about the possibility of introducing bugs to an otherwise stable branch, but seeing that @russjones have approved, I'm guessing this wasn't a valid concern after all.

**Review by ibeckermayer — APPROVED** [review]

**Review by rosstimothy — APPROVED** [review]

**Pull request merged**
