### PR TITLE
[v11] DatabaseService: CRUD and hearbeat

### PR DESCRIPTION
**Pull request by marcoandredinis**
Backport of
#19363
#19475  
#19469 
#19570

### CODE REVIEW

**Comment by marcoandredinis** [comment]
This PR must include the fix from here
https://github.com/gravitational/teleport/pull/19475

**Review by ryanclark — APPROVED** [review]

**Review by codingllama — COMMENTED** [review]
Looks good, give me a nudge once we've got everything we need in and I'll approve.

**Comment by marcoandredinis** [comment]
We ended up removing the `GetAllDatabaseServices` rpc method in another PR
To avoid a breaking change, let's wait for that PR to merge and then cherry pick it to this PR as well
https://github.com/gravitational/teleport/pull/19469

Sorry :pray:

**Comment by codingllama** [comment]
No worries, @marcoandredinis. Just give us a nudge when you are good to go.

**Comment by marcoandredinis** [comment]
@codingllama I ended up backporting the entire functionality together
Can you please review it now?

@smallinsky @greedy52 Feel free to take another look at those changes :pray: 

Thank you

**Comment by marcoandredinis** [comment]
@r0mant Can you please take a look as well?
I need an admin approval

**Review by smallinsky — APPROVED** [review]

**Review by ryanclark — APPROVED** [review]

**Review by codingllama — APPROVED** [review]

**Review by r0mant — APPROVED** [review]
Bot.

**Pull request merged**
