### PR TITLE
feat: Implement the WebAuthn credProps extension

### PR DESCRIPTION
**Pull request by codingllama**
Implement the WebAuthn credProps extension for server-side and browsers.

The credProps extensions allows us to identify if a passkey was created, regardless of the requested registration being for "plain MFA". This happens because some authenticators are always passkeys (for example, keys created by Chrome and Safari).

At the time of implementation, only Chrome appears to support the extension.

tsh support for credProps is not added by this PR. That is because libfido2 keys (aka Yubikeys) tend to not spontaneously upgrade themselves, plus Touch ID registrations are always created as "passkeys". We may revisit this in the future.

- https://w3c.github.io/webauthn/#sctn-authenticator-credential-properties-extension

#39521.

Changelog: Added server and browser support for the WebAuthn credProps extension

### CODE REVIEW

**Comment by codingllama** [comment]
Branched from #45222 to make my life simpler.

- #45222

**Comment by codingllama** [comment]
FYI @espadolini.

**Comment by codingllama** [comment]
Here's a quick demo of what happens in practice. Noticed that the authenticator ends up as a passkey, even though we clicked on "Add MFA".

https://github.com/user-attachments/assets/338263f9-c1f0-4787-992e-a359687c5c32

**Comment by codingllama** [comment]
Friendly ping reviewers?

**Comment by codingllama** [comment]
Friendly ping @kiosion @ryanclark @rosstimothy ?

**Review by rosstimothy — APPROVED** [review]

**Comment by codingllama** [comment]
Friendly ping @kiosion @ryanclark ?

**Review by strideynet — APPROVED** [review]

**Pull request merged**
