### PR TITLE
Adds Rust 1.55.0 to CI buildbox

### PR DESCRIPTION
**Pull request by tcsc**

### CODE REVIEW

**Review by nklaassen — APPROVED** [review]

**Review by codingllama — APPROVED** [review]

**Review by webvictim — CHANGES_REQUESTED** [review]
Uh @tcsc this isn't the Dockerfile for the CI buildbox. I think you're looking for https://github.com/gravitational/teleport/blob/master/build.assets/Dockerfile?

**Review by quinqu — APPROVED** [review]

**Review by quinqu — COMMENTED** [review]
Looks good once changes are in `build.assets/Dockerfile`. Did you test out the image to ensure Rust was installed properly?

**Comment by tcsc** [comment]
> Uh @tcsc this isn't the Dockerfile for the CI buildbox. I think you're looking for https://github.com/gravitational/teleport/blob/master/build.assets/Dockerfile?

...aaaand this is why we do reviews. :grimacing:. I think I got lost copy/pasting between the multiple versions of `teleport` I have on my local machine for spiking out CI. Oops.

**Review by webvictim — APPROVED** [review]
LGTM! 😁

**Review by codingllama — APPROVED** [review]
Leaving pre-approved so you won't suffer another roundtrip. :)

Please take a look at the `COPY --from` solution, it could make much of the copy/paste from the Rust Dockerfile unnecessary (if it looks worse drop it, though).

**Review by codingllama — APPROVED** [review]

**Review by russjones — APPROVED** [review]
Bot.

**Pull request merged**
