### PR TITLE
Restore Assist file conf options for non-breaking deprecation

### PR DESCRIPTION
**Pull request by Joerger**
Fixes Teleport start error described here - https://github.com/gravitational/teleport/pull/42657#discussion_r1643600415

### CODE REVIEW

**Review by tigrato — APPROVED** [review]

**Review by jakule — COMMENTED** [review]
Can we merge this only in v16? Current master will be released as v17 so that PR will need to be reverted anyway.

**Comment by GavinFrazar** [comment]
why mark it to delete in v17? it will just be the same issue?

**Comment by jakule** [comment]
> why mark it to delete in v17?

I don't think it makes sense to leave the warning forever since assist is removed from Teleport.

>  it will just be the same issue?

Should we just fix the cloud config and not merge this PR? I agree that this only pushes the real issue for a few months.

**Comment by Joerger** [comment]
> I don't think it makes sense to leave the warning forever since assist is removed from Teleport.

There are several other cases in the file config where we keep a deprecated config field indefinitely to prevent unnecessary support load on misconfigurations. It would make sense to keep the option for at least 1 major version, if not longer.

> Should we just fix the cloud config and not merge this PR? I agree that this only pushes the real issue for a few months.

@jakule Is assist only supported for cloud? If not, any customer that had Assist enabled in v15 would run into this issue on upgrade.

**Comment by GavinFrazar** [comment]
self-hosted customers may have an assist config with empty values and will hit the issue, regardless of the feature flag being enabled. I think we should keep it for at least a few major versions, if not forever. We document that our config file is versioned, therefore a breaking change in config file format belongs in a new version - so we can delete this in config file v4 😉 

> In order to avoid breaking existing configurations, Teleport's configuration is
> versioned. The newer configuration version is `v3`. If a `version` is not
> specified in the configuration file, `v1` is assumed.

**Review by GavinFrazar — APPROVED** [review]
approving since I only disagree on the TODO comment - my suggestion is to change that to "DELETE IN CONFIG FILE V4" instead of v17

**Review by r0mant — CHANGES_REQUESTED** [review]
Let's please not keep accumulating old flags, especially for such a niche feature. This is an intended breaking change in a major release and people are supposed to remove these fields from their configuration when upgrading.

The only thing we should've done better is include instructions for removing these fields in the breaking changes section in release notes. @jakule Can you please update it? And this PR I think we should just close.

**Pull request closed without merging**
