### PR TITLE
Clean up dead code across the codebase

### PR DESCRIPTION
**Pull request by awly**
Spring cleaning!
A very mechanical cleanup using several linters (unused, deadcode,
structcheck). Build and tests still pass so no behavior should be
affected.

Part of #3551

### CODE REVIEW

**Comment by russjones** [comment]
@gravitational-jenkins retest this please

**Review by russjones — APPROVED** [review]

**Comment by awly** [comment]
@gravitational-jenkins retest this please

**Comment by awly** [comment]
@gravitational-jenkins retest this please

**Comment by awly** [comment]
@gravitational-jenkins retest this please

**Comment by awly** [comment]
@gravitational-jenkins retest this please

**Review by webvictim — COMMENTED** [review]
Red diffs, my favourite kind!

**Comment by awly** [comment]
@gravitational-jenkins retest this please

**Pull request merged**
