### PR TITLE
[v14] Expose ServerInfo resource in `tctl` (#34008)

### PR DESCRIPTION
**Pull request by atburke**
Backport #34008 to branch/v14

Changelog: Exposed ServerInfo resource in tctl

### CODE REVIEW

**Review by camscale — APPROVED** [review]

**Comment by codingllama** [comment]
It looks like the flaky detector found a race in TestCreateResources, mind taking a look? If you do apply any fixes don't forget to push them to master too.

**Comment by zmb3** [comment]
For posterity, here's the data race that tripped the flake detector:

```
WARNING: DATA RACE
Write at 0x00c001e0af10 by goroutine 98168:
  internal/poll.(*FD).destroy()
      /opt/go/src/internal/poll/fd_unix.go:83 +0xd5
  internal/poll.(*FD).decref()
      /opt/go/src/internal/poll/fd_mutex.go:213 +0x36
  internal/poll.(*FD).Close()
      /opt/go/src/internal/poll/fd_unix.go:104 +0x7d
  os.(*file).close()
      /opt/go/src/os/file_unix.go:315 +0x119
  os.(*File).Close()
      /opt/go/src/os/file_posix.go:23 +0x44
  github.com/gravitational/teleport/tool/teleport/testenv.NewTCPListener.func1()
      /__w/teleport/teleport/tool/teleport/testenv/test_server.go:195 +0xe
  testing.(*common).Cleanup.func1()
      /opt/go/src/testing/testing.go:1169 +0x182
  testing.(*common).runCleanup()
      /opt/go/src/testing/testing.go:1347 +0x1c2
  testing.tRunner.func2()
      /opt/go/src/testing/testing.go:1589 +0x50
  runtime.deferreturn()
      /opt/go/src/runtime/panic.go:477 +0x30
  testing.(*T).Run.func1()
      /opt/go/src/testing/testing.go:1648 +0x44

Previous read at 0x00c001e0af10 by goroutine 98516:
  os.(*File).Fd()
      /opt/go/src/os/file_unix.go:93 +0xa4
  net.dupSocket()
      /opt/go/src/net/file_unix.go:16 +0x36
  net.newFileFD()
      /opt/go/src/net/file_unix.go:31 +0x3b
  net.fileListener()
      /opt/go/src/net/file_unix.go:90 +0x2e
  net.FileListener()
      /opt/go/src/net/file.go:34 +0x2e
  github.com/gravitational/teleport/lib/service/servicecfg.(*FileDescriptor).ToListener()
      /__w/teleport/teleport/lib/service/servicecfg/config.go:591 +0x4a
  github.com/gravitational/teleport/lib/service.(*TeleportProcess).importListener()
      /__w/teleport/teleport/lib/service/signals.go:274 +0x264
  github.com/gravitational/teleport/lib/service.(*TeleportProcess).importOrCreateListener()
      /__w/teleport/teleport/lib/service/signals.go:239 +0x7b
  github.com/gravitational/teleport/lib/service.(*TeleportProcess).setupProxyListeners()
      /__w/teleport/teleport/lib/service/service.go:3484 +0x41a
  github.com/gravitational/teleport/lib/service.(*TeleportProcess).initProxyEndpoint()
      /__w/teleport/teleport/lib/service/service.go:3776 +0x484
  github.com/gravitational/teleport/lib/service.(*TeleportProcess).initProxy.func1()
      /__w/teleport/teleport/lib/service/service.go:3342 +0x84
  github.com/gravitational/teleport/lib/service.(*LocalService).Serve()
      /__w/teleport/teleport/lib/service/supervisor.go:550 +0x35
  github.com/gravitational/teleport/lib/service.(*LocalSupervisor).serve.func1()
      /__w/teleport/teleport/lib/service/supervisor.go:281 +0x206

Goroutine 98168 (running) created at:
  testing.(*T).Run()
      /opt/go/src/testing/testing.go:1648 +0x82a
  testing.runTests.func1()
      /opt/go/src/testing/testing.go:2054 +0x84
  testing.tRunner()
      /opt/go/src/testing/testing.go:1595 +0x238
  testing.runTests()
      /opt/go/src/testing/testing.go:2052 +0x896
  testing.(*M).Run()
      /opt/go/src/testing/testing.go:1925 +0xb57
  main.main()
      _testmain.go:147 +0x2e4

Goroutine 98516 (running) created at:
  github.com/gravitational/teleport/lib/service.(*LocalSupervisor).serve()
      /__w/teleport/teleport/lib/service/supervisor.go:276 +0x106
  github.com/gravitational/teleport/lib/service.(*LocalSupervisor).Start()
      /__w/teleport/teleport/lib/service/supervisor.go:307 +0x22b
  github.com/gravitational/teleport/lib/tbot/testhelpers.MakeAndRunTestAuthServer()
      /__w/teleport/teleport/lib/tbot/testhelpers/srv.go:95 +0x2be
  github.com/gravitational/teleport/tool/tctl/common.TestCreateResources()
      /__w/teleport/teleport/tool/tctl/common/resource_command_test.go:1348 +0x8f
  testing.tRunner()
      /opt/go/src/testing/testing.go:1595 +0x238
  testing.(*T).Run.func1()
      /opt/go/src/testing/testing.go:1648 +0x44
==================
```

**Comment by atburke** [comment]
PR for the data race is at #34183

**Comment by atburke** [comment]
Data race should be fixed as of #34537, friendly ping @codingllama

**Review by codingllama — APPROVED** [review]
LGTM. Apologies for the delay!

**Pull request merged**
