### PR TITLE
Add support for a defaults file to systemd service

### PR DESCRIPTION
**Pull request by pprkut**
The defaults file is a common location to define service specific
environment variables. Defining the variables is still up to the
admin, but like this at least the service file doesn't need to be
modified anymore.

### CODE REVIEW

**Comment by benarent** [comment]
Thanks for the PR @pprkut, I've requested @eldios to review as he recently updated some of our SystemD Examples.

**Comment by benarent** [comment]
Ok to test

**Review by eldios — APPROVED** [review]
LGTM :+1: 

Thanks for your contribution @pprkut

**Comment by eldios** [comment]
please upgrade the PR to include the latest changes from master and then we'll be able to merge it.

Thank you

**Comment by benarent** [comment]
Ok to test ( unsure why Jenkins is being flaky )

**Comment by benarent** [comment]
@wadells Do you have any thoughts on why this is failing?

**Comment by wadells** [comment]
> @wadells Do you have any thoughts on why this is failing?

Looking at the Jenkins logs I see:

```
Successfully built 9401fb908565
Successfully tagged teleport-buildbox:go1.13.2
docker run --rm=true -v "$(pwd)/../":/gopath/src/github.com/gravitational/teleport -v /tmp:/tmp -w /gopath/src/github.com/gravitational/teleport -h buildbox -v /var/lib/jenkins/ci.cluster/kubeconfig:/mnt/kube/config -e KUBECONFIG=/mnt/kube/config -e TEST_KUBE=true -u $(id -u):$(id -g) -t teleport-buildbox:go1.13.2 \
	/bin/bash -c \
	"examples/etcd/start-etcd.sh & sleep 1; \
	ssh-agent > external.agent.tmp && source external.agent.tmp; \
	cd /gopath/src/github.com/gravitational/teleport && make TELEPORT_DEBUG=0 FLAGS='-cover -race' clean test"
```

So not a build failure, but a tet failure.  Here is where things go off the rails:

```
[37mDEBU[0m [PROXY:AGE] Pool is closing agent. id:2614 target:localhost:20251 reversetunnel/agentpool.go:241
[37mDEBU[0m [PROXY:AGE] Pool is closing agent. id:2723 target:127.0.0.1:20321 reversetunnel/agentpool.go:241
[33mWARN[0m [NODE:BEAT] Heartbeat failed all SubConns are in TransientFailure, latest connection error: connection error: desc = "transport: Error while dialing dial tcp 127.0.0.1:20321: connect: connection refused". srv/heartbeat.go:240
panic: test timed out after 10m0sgoroutine 579478 [running]:
testing.(*M).startAlarm.func1()
	/opt/go/src/testing/testing.go:1377 +0xdf
created by time.goFunc
	/opt/go/src/time/sleep.go:168 +0x44goroutine 1 [chan receive, 10 minutes]:
testing.(*T).Run(0xc000566600, 0x20caaa4, 0x10, 0x21856d0, 0x4ce5b6)
	/opt/go/src/testing/testing.go:961 +0x377
testing.runTests.func1(0xc000566500)
	/opt/go/src/testing/testing.go:1202 +0x78
testing.tRunner(0xc000566500, 0xc00062bda0)
	/opt/go/src/testing/testing.go:909 +0xc9
testing.runTests(0xc0006912e0, 0x3811010, 0x1, 0x1, 0x0)
	/opt/go/src/testing/testing.go:1200 +0x2a7
testing.(*M).Run(0xc000380f80, 0x0)
	/opt/go/src/testing/testing.go:1117 +0x176
github.com/gravitational/teleport/integration.TestMain(0xc000380f80)
	/gopath/src/github.com/gravitational/teleport/integration/integration_test.go:99 +0x54
main.main()
	_testmain.go:42 +0x135
```

Not yet sure what this is indicative of, as I'm still a noob.  I suggest we wait for someone with better trained eyes.

**Comment by benarent** [comment]
@russjones This should be safe to merge? the PR only changes examples?

**Pull request merged**
