### PR TITLE
Update Terraform examples provider

### PR DESCRIPTION
**Pull request by adaadb6**
- Remove AWS version constraint in provider.tf. Update to use `>=` instead of `~>`
- Add suggestions to acm.tf to support AWS version 3

### CODE REVIEW

**Review by Travis-Wright-Systems — APPROVED** [review]
Looks good to me.

**Review by knisbet — APPROVED** [review]

**Comment by russjones** [comment]
@webvictim Can you review, if you're okay with this we'll merge.

**Comment by webvictim** [comment]
I'll have to test it first.

**Review by webvictim — APPROVED** [review]
Tested and it looks good to me. Thanks @adaadb6!

**Comment by adaadb6** [comment]
Thank you everyone!

**Review by russjones — APPROVED** [review]
Bot.

**Pull request merged**
