### PR TITLE
Add support for building ARM/ARM64 RPM/DEB packages

### PR DESCRIPTION
**Pull request by webvictim**
These changes are needed in the `build-package.sh` script for commands like `make -C e rpm-unsigned VERSION=6.0.1 OS=linux ARCH=arm64 RUNTIME=fips` to work.

I'm going to make the actual changes to get Drone to build these packages [using `dronegen`](https://github.com/gravitational/teleport/pull/5936) because editing the YAML manually is getting too cumbersome now.

This PR also removes support for Go 1.9.7 packages (which were used with RHEL 5) as we don't build those any more.

### CODE REVIEW

**Review by a-palchikov — APPROVED** [review]

**Comment by webvictim** [comment]
Ping CODEOWNERS

**Comment by russjones** [comment]
@awly Can you take a look?

**Comment by webvictim** [comment]
Yeah, I normally would've requested review from Andrew but I feel like he basically reviews all my PRs :)

**Review by awly — APPROVED** [review]

**Review by russjones — APPROVED** [review]
Bot.

**Pull request merged**
