### PR TITLE
add err check in lib/client NodeClient.listenAndForward

### PR DESCRIPTION
**Pull request by miolini**
add err check in lib/client NodeClient.listenAndForward

### CODE REVIEW

**Comment by miolini** [comment]
@kontsevoy add test doneErr with io.EOF

**Comment by kontsevoy** [comment]
miolini: first of all, thanks for the pull requests! :) But can you help me understand their purpose? The only two errors `io.Copy()` can generate are EOF and closed socket. 

Both are not actionable, the only thing you can do is log "connection lost" error (and we do this). 

This PR just adds more moving parts + code to achieve a slightly more detailed log message?

**Comment by miolini** [comment]
@kontsevoy thank you. 

Fix is for show the error in the connection while data transferring in both ways. Without this fix the user will see in logs only 'connection from %v to %v closed!' formatted log entry.

**Comment by kontsevoy** [comment]
@miolini I see. The improvement is not worth the extra code IMO. The error you'd get will be `connection closed by remote host` vs "connection to %v closed!". Thanks though!

**Pull request closed without merging**
