### PR TITLE
[v9] Add directory sharing to the ACL

### PR DESCRIPTION
**Pull request by ibeckermayer**
Backport https://github.com/gravitational/teleport/pull/14103 to branch/v9

### CODE REVIEW

**Review by jakule — APPROVED** [review]

**Comment by zmb3** [comment]
Is this one necessary? How will we ensure it never gets activated on v9?

**Comment by ibeckermayer** [comment]
> Is this one necessary? 

I was considering it as a piece of the "kitchen sink" approach discussed in a previous PR. I'm just backporting everything I do on directory sharing to v9/v10 in order to ensure that it all stays functional (protected by flags/config variables).

> How will we ensure it never gets activated on v9?

It's modulated by [a build flag](https://github.com/gravitational/teleport/pull/14655/files#diff-d0d78875d7396d7dad9cc4ab10f6da26554c8e8ff30f2b661c1377d9b959bd85R841-R842) here on the backend and [a config variable](https://github.com/gravitational/webapps/blob/teleport-v9/packages/teleport/src/config.ts#L26) on the frontend.

**Comment by zmb3** [comment]
So the plan is to eventually remove the build tag on v10 and master and not backport the removal to v9?

**Comment by ibeckermayer** [comment]
> So the plan is to eventually remove the build tag on v10 and master and not backport the removal to v9?

Yeah exactly

**Review by zmb3 — APPROVED** [review]

**Pull request merged**
