### PR TITLE
user creation command throws reviewer role error

### PR DESCRIPTION
**Pull request by WilliamLoy**
I replaced reviewer with auditor in add user commands since reviewer is not default on new clusters.

### CODE REVIEW

**Comment by zmb3** [comment]
The reviewer role was added in https://github.com/gravitational/teleport/pull/27673 which is in v14.0.0 and was also backported to v13.

**Comment by WilliamLoy** [comment]
> The reviewer role was added in #27673 which is in v14.0.0 and was also backported to v13.

tried to add a user on new cluster
Cluster version 14.1
tsh version 14.1

got the following error:
tctl users add reviewer-user --roles=access,editor,reviewer
ERROR: role reviewer is not found

**Comment by zmb3** [comment]
@mdwn any idea why Will is not seeing the preset reviewer role?

**Comment by mdwn** [comment]
Is this an enterprise or OSS cluster?

**Comment by WilliamLoy** [comment]
I ran into a license expiration issue. Working to get this tested soon.

**Comment by WilliamLoy** [comment]
Confirmed the same error on the new Enterprise license.

**Comment by WilliamLoy** [comment]
My mistake on this one. The cluster was in fact running on OSS. I'll close the issue.

**Pull request closed without merging**
