### PR TITLE
This commit improves log messages for kubeconfig.

### PR DESCRIPTION
**Pull request by klizhentas**
In cases when kubernetes config path does not contain
properly encoded certificates, teleport was not
showing any error messages in the logs. This commit
makes sure error message are shown and are meaningful.

### CODE REVIEW

**Review by webvictim — APPROVED** [review]

**Review by russjones — APPROVED** [review]

**Comment by klizhentas** [comment]
retest this please

**Comment by klizhentas** [comment]
retest this please

**Comment by klizhentas** [comment]
retest this please

**Comment by klizhentas** [comment]
retest this

**Comment by klizhentas** [comment]
retest this please

**Review by fspmarshall — APPROVED** [review]

**Comment by klizhentas** [comment]
retest this please

**Pull request merged**
