### PR TITLE
[v10] Add a guide to Desktop Access Directory Sharing

### PR DESCRIPTION
**Pull request by ptgott**
Backport #15650 to branch/v10

### CODE REVIEW

**Comment by ptgott** [comment]
**TODO:** I need to indicate that this will be in preview

**Review by zmb3 — APPROVED** [review]
LGTM, Let's not merge this until we cut the 10.2 release though.

**Review by ibeckermayer — APPROVED** [review]

**Comment by ptgott** [comment]
@zmb3 @ibeckermayer I'll be on PTO next week. If we release 10.2 then, would you mind merging this for me? Thanks!

**Comment by zmb3** [comment]
Enjoy the time off, @ptgott!

**Comment by benarent** [comment]
+1 I just came to demo this feature and had to search around to find it.

**Pull request merged**
