### PR TITLE
fix(generate-config): Always set TELEPORT_CLUSTER_NAME for auth_service

### PR DESCRIPTION
**Pull request by sklirg**
`auth_service.cluster_name` is set [here](https://github.com/gravitational/teleport/blob/master/assets/aws/files/bin/teleport-generate-config#L230), but not when Teleport is started as an ["all-in-one" cluster](https://github.com/gravitational/teleport/blob/master/assets/aws/files/bin/teleport-generate-config#L372-L426).

Note: If `$TELEPORT_CLUSTER_NAME` is not set, the value will be set to an empty value, which is probably not desired. I'm not familiar with the internal code handling this and how the default value is set, so if this should be omitted if empty or have a default value (hostname?), please advise.

### CODE REVIEW

**Review by r0mant — APPROVED** [review]
@webvictim This change looks good to me but I don't know what this script is used for. Do you recall?

**Review by webvictim — APPROVED** [review]
Yeah, this change is OK. `TELEPORT_CLUSTER_NAME` will always be set as it's a required Terraform variable.

**Review by zmb3 — APPROVED** [review]

**Comment by sklirg** [comment]
Just checking in again to see if you need anything from me for this 👍

**Comment by sklirg** [comment]
To get the outcome I expect without this patch I have to do the following:

```
[user@server ~]$ history
    1  sudo systemctl stop teleport-acm
    # apply this patch manually
    2  sudo vim /usr/local/bin/teleport-generate/config
    # delete the generated teleport.yaml
    3  sudo mv /etc/teleport.yaml /etc/teleport.yaml.bak
    # re-run config-generation-script
    4  sudo systemctl start teleport-generate-config.service
    # -- re-create DynamoDB (terraform destroy & create) --
    # delete local state
    5  sudo rm /var/lib/teleport/proc/sqlite.db
    # restart teleport(-acm)
    6  sudo systemctl start teleport-acm
    # create admin user +++
    # the cluster now has the wanted TELEPORT_CLUSTER_NAME 🥳
```

On the other hand, this process/`$ history` verifies that the change works as I expectit to 😁

**Pull request merged**
