### PR TITLE
helm: Add support for annotation on secrets generated by cert-manager.

### PR DESCRIPTION
**Pull request by vladlosev**
This adds support for putting annotation into a the secret generated by `cert-manager` from the `teleport-tls` certificate. This will enable one to tag the Teleport deployment for restart by a tool like [reloader](https://github.com/stakater/Reloader) when `cert-manager` renews the certificate and the secret is updated. Without such restart, Teleport continues to present the expired certificate.

### CODE REVIEW

**Review by webvictim — COMMENTED** [review]
@vladlosev Thanks for the PR. Looks good overall, but there are a few requests before we can merge:

1) Please add `annotations.certSecret` at the appropriate location in the `teleport-cluster` chart reference: https://github.com/gravitational/teleport/blob/master/docs/pages/kubernetes-access/helm/reference.mdx

2) Please add an example which sets `annotations.certSecret` so it can be validated by the linter - see other examples in https://github.com/gravitational/teleport/tree/master/examples/chart/teleport-cluster/.lint

Thank you!

**Comment by vladlosev** [comment]
Done and done!
I've noticed that some of the setting descriptions in `docs/pages/kubernetes-access/helm/reference.mdx` are repeated twice. Not sure whether it's intentional or accidental, so I only added the new description once there.

**Comment by webvictim** [comment]
The reference covers both `teleport-cluster` and `teleport-kube-agent` charts - some of the parameters are the same between both charts so are mentioned once for each.

**Comment by webvictim** [comment]
@vladlosev Thanks for the changes! We don't run CI directly against external PRs at the moment, so I've created a buddy PR (https://github.com/gravitational/teleport/pull/8872) to run CI against your PR. Once it's done I'll let you know the feedback.

**Comment by vladlosev** [comment]
Looks like there was a lint error. I've pushed a commit to fix it.

**Comment by webvictim** [comment]
@vladlosev Thank you! The buddy PR is looking good on lint now so I've requested review. It'll be merged and backported soon. I'm going to close this PR now - your contribution is much appreciated.

**Pull request closed without merging**
