### PR TITLE
Fix GitHub connector API endpoint URL path getting ignored when making HTTP requests

### LINKED ISSUE #24582: Github Enterprise SSO should respect custom endpoint path
In https://github.com/gravitational/teleport.e/pull/1009 we added ability to specify custom Github API URL for Github Enterprise SSO users. However, the code only respects the custom hostname right now and does not work for scenarios where user's custom API endpoint includes a path e.g. `https://git.prod.internal/api/v3`.

https://github.com/gravitational/teleport/blob/master/lib/auth/github.go#L959-L964

### PR DESCRIPTION
**Pull request by capnspacehook**
Fixes https://github.com/gravitational/teleport/issues/24582.

### CODE REVIEW

**Review by r0mant — COMMENTED** [review]
Can we add test coverage here?

**Comment by capnspacehook** [comment]
@r0mant done

**Review by r0mant — APPROVED** [review]
Code lgtm. @capnspacehook Let's make a dev release for the customer to verify first to make sure it works for them this time.

**Review by greedy52 — APPROVED** [review]

**Comment by dennisme** [comment]
Id be interested in testing this. Can you update the example docs / charts too?

**Comment by r0mant** [comment]
We've been waiting for the customer to confirm this fixes their issue but they haven't gotten back to us yet so @capnspacehook let's just ship it.

**Pull request merged**
