### PR TITLE
AMI: bump nginx1.12 to nginx1

### PR DESCRIPTION
**Pull request by programmerq**
amazon_linux_extras has marked nginx1.12 topic as EOL and nginx1 is the new stable topic to use.

### CODE REVIEW

**Comment by programmerq** [comment]
@webvictim I was able to build an AMI following the packer instructions in https://github.com/gravitational/teleport/blob/master/assets/aws/README.md and deploy an ha cluster instance using that built AMI. nginx 1.20 successfully came up with the existing grafana config and password I supplied in my Makefile and started serving up graphs right away.

**Comment by webvictim** [comment]
@programmerq Thank you!

**Review by webvictim — APPROVED** [review]

**Comment by russjones** [comment]
@webvictim @programmerq Did you two test this? I don't think we have any test coverage for AMIs?

**Comment by webvictim** [comment]
@russjones We have some test coverage for config generation, but not for actually building/starting the AMIs. As per @programmerq's comment above though, the AMI builds fine with this change, nginx starts and the Grafana dashboard is available - hence my approval.

**Review by russjones — APPROVED** [review]
Bot.

**Comment by russjones** [comment]
Will merge in #9323.

**Pull request closed without merging**
