### PR TITLE
teleport-kube-agent: Support multiple installations in a single cluster

### LINKED ISSUE #7045: Metadata validation fail
```
helm install teleport-agent ./teleport-kube-agent --set kubeClusterName=${CLUSTER?}\
>     --set proxyAddr=${PROXY?} --set authToken=${TOKEN?} --create-namespace --namespace=cookie
Error: rendered manifests contain a resource that already exists. Unable to continue with install: PodSecurityPolicy "teleport-agent" in namespace "" exists and cannot be imported into the current release: invalid ownership metadata; annotation validation error: key "meta.helm.sh/release-namespace" must equal "cookie": current value is "teleport-agent"
```

### PR DESCRIPTION
**Pull request by webvictim**
Attempting to install multiple copies of the `teleport-kube-agent` chart into a single Kubernetes cluster would fail with an error similar to:
```
Error: rendered manifests contain a resource that already exists. Unable to continue with install: ClusterRole "teleport-kube-agent" in namespace "" exists and cannot be imported into the current release: invalid ownership metadata; annotation validation error: key "meta.helm.sh/release-name" must equal "teleport-agent-two": current value is "teleport-kube-agent"; annotation validation error: key "meta.helm.sh/release-namespace" must equal "teleport-agent-two": current value is "teleport"
```

This error is caused by attempting to reuse the name of the `clusterRole` and `clusterRoleBinding`. It was possible to work around this with `--set clusterRole=new-name --set clusterRoleBinding=new-name`, but this is unfriendly to new users.

This PR removes the preset values for `clusterRole`, `clusterRoleBinding` and `serviceAccountName` in the `values.yaml` file (while still optionally allowing them to be overridden) and sets the defaults to match the name of the Helm release instead, which Helm guarantees to be unique. This avoids the previous conflict and allows multiple different agents to be installed in the same cluster (one for Kubernetes, one for applications, one for databases etc). This is more friendly to users who may be trying to keep their concerns separated by namespace etc.

I think the intention of allowing the values to be overridden previously may have been to allow advanced users to provision their own `clusterRole`, `clusterRoleBinding` and `serviceAccount` for the chart, but the implementation was only half-complete as the chart would fail to install if any of the names chosen had matching objects already existing in the cluster.

Backports required:
- `branch/v6.2`

Fixes #7045

### CODE REVIEW

**Comment by webvictim** [comment]
Backport #7060 along with this.

**Review by wadells — COMMENTED** [review]
Did you consider a default over removing these entirely:

In values.yml:

```
# Name of the ClusterRoleBinding, used by the agent's service account.
clusterRoleBindingName: ""
```

Where they're used:

```
{{ .Values.clusterRoleBindingName | default .Release.Name }}
```

This allows power users to override while providing a easy path for folks getting started.

**Comment by inertial-frame** [comment]
> Did you consider a default over removing these entirely:
> 
> In values.yml:
> 
> ```
> # Name of the ClusterRoleBinding, used by the agent's service account.
> clusterRoleBindingName: ""
> ```
> 
> Where they're used:
> 
> ```
> {{ .Values.clusterRoleBindingName | default .Release.Name }}
> ```
> 
> This allows power users to override while providing a easy path for folks getting started.

That might be helpful. After having gone through some of the Getting Started examples that require port `443` in terms of the CLI and/or config, I can definitely see the value in using something like `pipeline` in Helm templates (https://helm.sh/docs/chart_template_guide/functions_and_pipelines/) or default value setting in JS (https://www.samanthaming.com/tidbits/52-3-ways-to-set-default-value/). It could be done programmatically or at the template level.

Looks like the original `values.yaml` had some default values set for the three fields that are being replaced. If we go with the new default values (which I again agree is better), we should make sure to get the operator precedence correct for the superuser case - I think in JS it goes from left to right. We'd want the original values to be the defaults (I'd think?) and then overridden by the power user.

**Comment by webvictim** [comment]
> Did you consider a default over removing these entirely:

I did, but the issue with that is that Helm is still going to be expecting to create the resources so it wouldn't enable the "create your own `ClusterRole` and provide the name here" behaviour that I think might have been the original intention. I agree that the idea of setting a sane default with an optional override is still better though, so I'll make the modifications to do that.

> Being less familiar with this: is clusterRole, clusterRoleBinding, and serviceAccount often explicitly populated (referring back to the original three values that are now removed in this PR)?

Not really, most Helm charts that need these adding will automatically generate their own unique names to ensure that installation is successful. If someone's use case is esoteric enough that they need to generate all these resources themselves, the rest of the chart is probably not going to work well for them without modification anyway so I suspect the point is moot.

**Review by wadells — APPROVED** [review]

**Review by inertial-frame — APPROVED** [review]
Great and super helpful. Thanks for updating the tables and default values 💪

Looks like the https://www.ibm.com/cloud/auto-scaling link is gone, redirects to main landing. Might link to generic like https://www.ibm.com/blogs/cloud-computing/tag/autoscaling/?mhsrc=ibmsearch_a&mhq=autoscaling in the absence of an autoscaling-specific article.

**Comment by webvictim** [comment]
I'm going to go with https://cloud.ibm.com/docs/containers?topic=containers-ca as it looks like that's relevant!

**Review by awly — APPROVED** [review]
Since these resources are identical, I would prefer to re-use them across installations.
But if Helm doesn't allow that, the current approach LGTM

**Comment by webvictim** [comment]
I think it's probably easiest if each Helm chart is 100% in control of what it creates and destroys.

**Review by r0mant — APPROVED** [review]

**Comment by webvictim** [comment]
`branch/v6.2` backport: https://github.com/gravitational/teleport/pull/7257

**Pull request merged**
