### PR TITLE
Base 5.0 Docs Fork

### PR DESCRIPTION
**Pull request by benarent**
I'm creating a base fork; where I'll apply all of the other larger changes for Teleport 5.0. This is similar to https://github.com/gravitational/teleport/pull/4269 but since I'm making a lot of changes I'm going to propose 2 things.

1. We'll change the theme so we can publish beta docs, but default to the current version.
2. I'll be applying content changes to master, so it's easier to review the changes. 

I did investigate https://github.com/jimporter/mike as a solution for our docs; but it requires extra changes to our theme. So I'm recommend we review that afterwards.

### CODE REVIEW

**Comment by klizhentas** [comment]
let's hold back on this, `master` is already 5.0 branch, so if we tweak the build process using material theme, we can just treat `4.0` as the future base.

**Comment by benarent** [comment]
The way in which we currently have docs is different from git flow; do we want to keep looking at using `mike` to fix this?  On master, https://github.com/gravitational/teleport/tree/master/  this is has been our standard flow, create a new version.yaml and use the last version as it's base.

**Comment by webvictim** [comment]
The last time we cut one of these early forks it felt like lots of little things got lost or forgotten in merges, so my personal thinking is that if we have to cut a branch at all, it should be done as late as possible (i.e. at the same time as we cut the actual release branch, which should be when we're ready to release `5.0.0-rc.1`,so in a couple of days I think?)

In an ideal world I think we'd change to the git flow type methodology and look to serve a version's docs from the branch that was associated with it, but that will inevitably mean a lot of backport soup without some automatic tooling to help us.

**Comment by benarent** [comment]
I retested https://github.com/jimporter/mike today, and I managed to get it to work. I'll open another PR with my proposal for Docs versioning.

**Pull request closed without merging**
