### PR TITLE
Replace unmaintained CHANGELOG with link to docs and reference to release branch

### PR DESCRIPTION
**Pull request by webvictim**
A community Slack user pointed out that our changelog is outdated. They are correct!

### CODE REVIEW

**Review by codingllama — APPROVED** [review]
Thanks for the quick fix!

**Comment by zmb3** [comment]
I'm not seeing the link to docs, only the removal of CHANGELOG. Am I missing something?

**Comment by zmb3** [comment]
Also, we do update the changelog on the release branches, just not on master. `branch/v9` is up to date, so I don't think we want to remove this.

**Comment by webvictim** [comment]
Last line in the diff @zmb3. I’m not 100% sure why Github renders it this way, but it’s there.

Either way, the `master` change log is outdated and lacks information. It should either have everything in it, or nothing in it.

Forward-porting all the branch-specific changes adds work and doesn’t get done (which is part of why it’s stuck at 8.0) so I added a note saying that you can find branch-specific change logs on the branches themselves.

**Comment by webvictim** [comment]
Ping @zmb3 @russjones @r0mant

**Review by ryanclark — APPROVED** [review]

**Comment by ryanclark** [comment]
Approved but no idea if my approval does anything 😅

**Review by klizhentas — CHANGES_REQUESTED** [review]
Let's keep changelog up to date. It's easy to create a makefile target that takes content from the docs one on build.

**Comment by ptgott** [comment]
Have you tried viewing this change on the local dev server? [`changelog.mdx`](https://github.com/gravitational/teleport/blame/0f96f3891794ac90f3dcf7d51b6194ae87b08a24/docs/pages/changelog.mdx) just includes `CHANGELOG.md` as a partial.

**Comment by ptgott** [comment]
@webvictim Just checking if you still want to work on this change. Another option is to ensure that the we include updating the changelog in our [docs test plan](https://github.com/gravitational/teleport/pull/18179) checklist, which we'll go through with each new major release.

**Comment by webvictim** [comment]
Hey @ptgott - I was just trying to get an easy fix merged for this; it wasn't my intention to work on automating CHANGELOG generation. I'll close this PR - I agree that adding CHANGELOG update to the docs test plan checklist is a great interim workaround.

**Pull request closed without merging**
