### PR TITLE
[v15] fix: Address flakiness and revisit TestTeleportClient_Login_local

### PR DESCRIPTION
**Pull request by codingllama**
Backport #47406 to branch/v15.

### CODE REVIEW

**Comment by codingllama** [comment]
Exact same merge as v16.

**Comment by GavinFrazar** [comment]
was the `test := test` thing not needed on v15?

**Review by GavinFrazar — APPROVED** [review]

**Comment by codingllama** [comment]
> was the `test := test` thing not needed on v15?

Right! I didn't see failures locally, but better add it anyway.

**Review by zmb3 — APPROVED** [review]

**Comment by codingllama** [comment]
Friendly ping, @zmb3? Could I get an FTD exemption for the timeouts (it isn't flaking anymore).

**Pull request merged**
