### PR TITLE
Return errors from GetSession

### PR DESCRIPTION
**Pull request by russjones**
**Purpose**

`GetSession()` was hiding errors, this PR changes this behavior by returning errors other than `trace.NotFound` errors.

**Implementation**

* Update `GetSession` to return non `trace.NotFound` errors.
* Update `GetSessions` to propagate errors (this way we don't try and append a `nil` session to a slice).
* In `pollAndSync` propagate the error if either we have an error or if the session is `nil`.

**Related Issues**

Fixes https://github.com/gravitational/teleport/issues/1002

### CODE REVIEW

**Comment by russjones** [comment]
@kontsevoy The only thing I am a little concerned with in this PR is that this might be expected behavior and this PR will break things unexpectedly. In a couple of places in the code it seems we look for `session` being nil rather than an error.

**Comment by russjones** [comment]
@gravitational-jenkins test this please

**Review by kontsevoy — CHANGES_REQUESTED** [review]
Do we log the error from GetSessions() though? I do not see it anywhere. Would like to avoid silent errors.

**Comment by kontsevoy** [comment]
@russjones well... even if we return an error now, the returned session is still `nil` so the existing code should continue operating.

**Comment by russjones** [comment]
@kontsevoy I think we're logging it on some code paths. When I force an error in `GetSession()` I see logs in `web/stream.go` and `srv/sess.go` but I don't think that covers all code paths so I added another log line in `GetSessions()` like you suggested.

**Review by kontsevoy — APPROVED** [review]

**Pull request merged**
