### PR TITLE
[v15] Read the bearer token over websocket endpoints instead of query parameter

### PR DESCRIPTION
**Pull request by lxea**
Backport #37520 to branch/v15

changelog: Read bearer token via websocket on websocket endpoints

### CODE REVIEW

**Review by r0mant — APPROVED** [review]
@lxea Have you tested the backport?

**Comment by lxea** [comment]
> @lxea Have you tested the backport?

Tested it with node connection, this applied cleanly so should be okay, working on the v14/13 versions

**Review by zmb3 — CHANGES_REQUESTED** [review]
Playback of recorded desktop sessions appears broken on master.

image

**Review by ibeckermayer — APPROVED** [review]
Note: we forgot to update the desktop playback endpoint in the parent PR, we should refrain from cutting a release with this commit until https://github.com/gravitational/teleport/pull/37981 is merged (and backported).

cc @zmb3 this fixes playback.

**Comment by ibeckermayer** [comment]
Closed in favor of https://github.com/gravitational/teleport/pull/38032

**Pull request closed without merging**
