### PR TITLE
Remove recursive `latest` symlink in docs/

### LINKED ISSUE #3575: GO: Add Import is not working
### Description

**What happened**:
VS Code `GO: Add Import` is not working
image

**What you expected to happen**:
Can use  VS Code `GO: Add Import`

```
go env
gopkgs -format '{{.Name}};{{.ImportPath}}'
stat /Users/wanfintara/Documents/go/src/github.com/gravitational/teleport/docs/latest: too many levels of symbolic links
```

### Environment
- OS: MacOS Catalina 10.15.4

### PR DESCRIPTION
**Pull request by awly**
The symlink points to itself, seems like it's leftover from olden days.

Fixes #3575

### CODE REVIEW

**Comment by webvictim** [comment]
It seems to be added here: https://github.com/gravitational/teleport/blob/master/docs/build.sh#L35

My guess is that someone committed it by accident.

**Review by webvictim — APPROVED** [review]

**Comment by awly** [comment]
@gravitational-jenkins retest this please

**Comment by webvictim** [comment]
I added the symlink to `.gitignore` as well.

**Comment by awly** [comment]
@gravitational-jenkins retest this please

**Comment by russjones** [comment]
@gravitational-jenkins retest this please

**Review by russjones — APPROVED** [review]

**Pull request merged**
