### PR TITLE
Align atomics to prevent segmentation faults on ARMv7

### LINKED ISSUE #6642: SIGSEGV in Teleport on Arm7
I have a Teleport node+proxy+auth running in docker, with ports 3022, 3023, 3024, 3025, 3080 mapped in. Additionally, port 443 is proxied on the Docker host and forwarded to 443 on the container based on requested host name match. 

The web interface works and I can use "tsh login" with no problems. Further, I can connect to its "own" node via web console or tsh. I have added two nodes that show up as expected under tsh ls or on the web interface. However, when I attempt to connect to either of the two separate nodes (One Raspberry Pi 3B+, One Pi 4) the teleport ssh client on that node has a SIGSEGV error, and the other end of the connection receives "ERROR: EOF". I am presumptively assuming this arm-related, but I will set up an x86 linux node to verify.

Node & Auth Server:
$tsh version
Teleport v6.1.2 git:v6.1.2-0-g23ab88c00 go1.15.5 

### Node config:

```YAML
teleport:
  nodename: big-sister
  auth_token: "<redacted>"
  ca_pin: "<redacted>"
  advertise_ip: big-sister.baymaterials.local
  auth_servers:
   - teleport.baymaterials.com:3025
ssh_service:
    enabled: yes
    listen_addr: 0.0.0.0:3022
    commands:
      - name: hostname
        command: [hostname]
        period: 1m0s
      - name: machine
        command: [uname, -m]
        period: 1h0m0s
auth_service:
   enabled: false
proxy_service:
   enabled: false
```

### Auth/server config:

```YAML
teleport:
  nodename: teleport.baymaterials.com
  advertise_ip: 192.168.54.3
  data_dir: /var/lib/teleport
  log:
    output: stderr
    severity: INFO
  ca_pin: ""
auth_service:
  enabled: yes
  cluster_name: bmus-lan
ssh_service:
  # Do not advertise teleport.baymaterials.com here;
  # Docker internal network address is "correct" relative
  # to the proxy.
  enabled: yes
  labels:
    env: docker
  commands:
  - name: hostname
    command: [hostname]
    period: 1m0s
proxy_service:
  enabled: yes
  # listen_addr: 0.0.0.0:3023
  # tunnel_listen_addr: 0.0.0.0:3024
  # web_listen_addr: 0.0.0.0:3080
  https_keypairs: 
    - key_file: /var/lib/teleport_keys/privkey.pem
      cert_file: /var/lib/teleport_keys/fullchain.pem
```

### Log from the node after a connection attempt:
```log
Apr 27 19:20:54 big-sister systemd[1]: Started Teleport SSH Service.
Apr 27 19:20:55 big-sister teleport[20580]: [PROC:1]    INFO Connecting to the cluster bmus-lan with TLS client certificate. service/connect.go:132
Apr 27 19:20:55 big-sister teleport[20580]: [AUDIT:1]   INFO Creating directory /var/lib/teleport/log. service/service.go:1903
Apr 27 19:20:55 big-sister teleport[20580]: [AUDIT:1]   INFO Creating directory /var/lib/teleport/log/upload. service/service.go:1903
Apr 27 19:20:55 big-sister teleport[20580]: [AUDIT:1]   INFO Creating directory /var/lib/teleport/log/upload/sessions. service/service.go:1903
Apr 27 19:20:55 big-sister teleport[20580]: [AUDIT:1]   INFO Creating directory /var/lib/teleport/log/upload/sessions/default. service/service.go:1903
Apr 27 19:20:55 big-sister teleport[20580]: [AUDIT:1]   INFO Creating directory /var/lib/teleport/log. service/service.go:1903
Apr 27 19:20:55 big-sister teleport[20580]: [AUDIT:1]   INFO Creating directory /var/lib/teleport/log/upload. service/service.go:1903
Apr 27 19:20:55 big-sister teleport[20580]: [AUDIT:1]   INFO Creating directory /var/lib/teleport/log/upload/streaming. service/service.go:1903
Apr 27 19:20:55 big-sister teleport[20580]: [AUDIT:1]   INFO Creating directory /var/lib/teleport/log/upload/streaming/default. service/service.go:1903
Apr 27 19:20:55 big-sister teleport[20580]: [PROC:1]    INFO Service node is creating new listener on 0.0.0.0:3022. service/signals.go:213
Apr 27 19:20:55 big-sister teleport[20580]: [NODE:1]    INFO Service 6.1.2:v6.1.2-0-g23ab88c00 is starting on 0.0.0.0:3022 sqlite cache that will expire after connection to database is lost after 20h0m0s, will cache frequently accessed items for 2s. service/service.go:1774
Apr 27 19:20:55 big-sister teleport[20580]: [NODE:1]    INFO Service 6.1.2:v6.1.2-0-g23ab88c00 is starting on 0.0.0.0:3022. utils/cli.go:235
Apr 27 19:20:55 big-sister teleport[20580]: [NODE]         Service 6.1.2:v6.1.2-0-g23ab88c00 is starting on 0.0.0.0:3022.
Apr 27 19:20:55 big-sister teleport[20580]: [PROC:1]    INFO The new service has started successfully. Starting syncing rotation status with period 10m0s. service/connect.go:435
Apr 28 13:57:57 big-sister teleport[20580]: panic: runtime error: invalid memory address or nil pointer dereference
Apr 28 13:57:57 big-sister teleport[20580]:         panic: runtime error: invalid memory address or nil pointer dereference
Apr 28 13:57:57 big-sister teleport[20580]: [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x1f84c]
Apr 28 13:57:57 big-sister teleport[20580]: goroutine 312214 [running]:
Apr 28 13:57:57 big-sister teleport[20580]: runtime/internal/atomic.goXadd64(0x52060bc, 0x1, 0x0, 0x0, 0x0)
Apr 28 13:57:57 big-sister teleport[20580]:         /opt/go/src/runtime/internal/atomic/atomic_arm.go:103 +0x1c
Apr 28 13:57:57 big-sister teleport[20580]: go.uber.org/atomic.(*Int64).Add(...)
Apr 28 13:57:57 big-sister teleport[20580]:         /go/src/github.com/gravitational/teleport/vendor/go.uber.org/atomic/int64.go:50
Apr 28 13:57:57 big-sister teleport[20580]: go.uber.org/atomic.(*Int64).Inc(...)
Apr 28 13:57:57 big-sister teleport[20580]:         /go/src/github.com/gravitational/teleport/vendor/go.uber.org/atomic/int64.go:60
Apr 28 13:57:57 big-sister teleport[20580]: github.com/gravitational/teleport/lib/events.(*AuditWriter).EmitAuditEvent(0x5206000, 0x2433d38, 0x557ace0, 0x2447940, 0x52bc800, 0x0, 0x0)
Apr 28 13:57:57 big-sister teleport[20580]:         /go/src/github.com/gravitational/teleport/lib/events/auditwriter.go:270 +0x8c
Apr 28 13:57:57 big-sister teleport[20580]: github.com/gravitational/teleport/lib/srv.(*SessionRegistry).emitSessionLeaveEvent(0x557b200, 0x512d6c0)
Apr 28 13:57:57 big-sister teleport[20580]:         /go/src/github.com/gravitational/teleport/lib/srv/sess.go:274 +0x2a4
Apr 28 13:57:57 big-sister teleport[20580]: github.com/gravitational/teleport/lib/srv.(*SessionRegistry).leaveSession(0x557b200, 0x512d6c0, 0x0, 0x0)
Apr 28 13:57:57 big-sister teleport[20580]:         /go/src/github.com/gravitational/teleport/lib/srv/sess.go:303 +0x78
Apr 28 13:57:57 big-sister teleport[20580]: github.com/gravitational/teleport/lib/srv.(*party).Close.func1()
Apr 28 13:57:57 big-sister teleport[20580]:         /go/src/github.com/gravitational/teleport/lib/srv/sess.go:1418 +0xac
Apr 28 13:57:57 big-sister teleport[20580]: sync.(*Once).doSlow(0x512d724, 0x534f694)
Apr 28 13:57:57 big-sister teleport[20580]:         /opt/go/src/sync/once.go:66 +0xe4
Apr 28 13:57:57 big-sister teleport[20580]: sync.(*Once).Do(0x512d724, 0x534f694)
Apr 28 13:57:57 big-sister teleport[20580]:         /opt/go/src/sync/once.go:57 +0x44
Apr 28 13:57:57 big-sister teleport[20580]: github.com/gravitational/teleport/lib/srv.(*party).Close(0x512d6c0, 0x0, 0x0)
Apr 28 13:57:57 big-sister teleport[20580]:         /go/src/github.com/gravitational/teleport/lib/srv/sess.go:1416 +0x64
Apr 28 13:57:57 big-sister teleport[20580]: github.com/gravitational/teleport/lib/srv.closeAll(0x567e570, 0x6, 0x6, 0x6, 0x0)
Apr 28 13:57:57 big-sister teleport[20580]:         /go/src/github.com/gravitational/teleport/lib/srv/ctx.go:850 +0x68
Apr 28 13:57:57 big-sister teleport[20580]: github.com/gravitational/teleport/lib/srv.(*ServerContext).Close(0x56b6140, 0x0, 0x0)
Apr 28 13:57:57 big-sister teleport[20580]:         /go/src/github.com/gravitational/teleport/lib/srv/ctx.go:610 +0xac
Apr 28 13:57:57 big-sister teleport[20580]: panic(0x1d9c3b8, 0x3380420)
Apr 28 13:57:57 big-sister teleport[20580]:         /opt/go/src/runtime/panic.go:969 +0x158
Apr 28 13:57:57 big-sister teleport[20580]: runtime/internal/atomic.goXadd64(0x52060bc, 0x1, 0x0, 0x0, 0x0)
Apr 28 13:57:57 big-sister teleport[20580]:         /opt/go/src/runtime/internal/atomic/atomic_arm.go:103 +0x1c
Apr 28 13:57:57 big-sister teleport[20580]: go.uber.org/atomic.(*Int64).Add(...)
Apr 28 13:57:57 big-sister teleport[20580]:         /go/src/github.com/gravitational/teleport/vendor/go.uber.org/atomic/int64.go:50
Apr 28 13:57:57 big-sister teleport[20580]: go.uber.org/atomic.(*Int64).Inc(...)
Apr 28 13:57:57 big-sister teleport[20580]:         /go/src/github.com/gravitational/teleport/vendor/go.uber.org/atomic/int64.go:60
Apr 28 13:57:57 big-sister teleport[20580]: github.com/gravitational/teleport/lib/events.(*AuditWriter).EmitAuditEvent(0x5206000, 0x2433d38, 0x557ace0, 0x2447a60, 0x52c8900, 0x0, 0x0)
Apr 28 13:57:57 big-sister teleport[20580]:         /go/src/github.com/gravitational/teleport/lib/events/auditwriter.go:270 +0x8c
Apr 28 13:57:57 big-sister teleport[20580]: github.com/gravitational/teleport/lib/srv.(*session).startInteractive(0x5618200, 0x243ba00, 0x518aa00, 0x56b6140, 0x534fc64, 0x1)
Apr 28 13:57:57 big-sister teleport[20580]:         /go/src/github.com/gravitational/teleport/lib/srv/sess.go:773 +0x974
Apr 28 13:57:57 big-sister teleport[20580]: github.com/gravitational/teleport/lib/srv.(*SessionRegistry).OpenSession(0x557b200, 0x243ba00, 0x518aa00, 0x5322a00, 0x56b6140, 0x0, 0x0)
Apr 28 13:57:57 big-sister teleport[20580]:         /go/src/github.com/gravitational/teleport/lib/srv/sess.go:216 +0x284
Apr 28 13:57:57 big-sister teleport[20580]: github.com/gravitational/teleport/lib/srv.(*TermHandlers).HandleShell(0x5580230, 0x243ba00, 0x518aa00, 0x5322a00, 0x56b6140, 0x2, 0x2)
Apr 28 13:57:57 big-sister teleport[20580]:         /go/src/github.com/gravitational/teleport/lib/srv/termhandlers.go:113 +0xa8
Apr 28 13:57:57 big-sister teleport[20580]: github.com/gravitational/teleport/lib/srv/regular.(*Server).dispatch(0x546fd40, 0x243ba00, 0x518aa00, 0x5322a00, 0x56b6140, 0x0, 0x0)
Apr 28 13:57:57 big-sister teleport[20580]:         /go/src/github.com/gravitational/teleport/lib/srv/regular/sshserver.go:1303 +0x554
Apr 28 13:57:57 big-sister teleport[20580]: github.com/gravitational/teleport/lib/srv/regular.(*Server).handleSessionRequests(0x546fd40, 0x2433d38, 0x53494c0, 0x581dc20, 0x55314c0, 0x5, 0x0, 0x0, 0x54f5e98, 0x5, ...)
Apr 28 13:57:57 big-sister teleport[20580]:         /go/src/github.com/gravitational/teleport/lib/srv/regular/sshserver.go:1242 +0x524
Apr 28 13:57:57 big-sister teleport[20580]: github.com/gravitational/teleport/lib/srv/regular.(*Server).HandleNewChan.func1(0x546fd40, 0x2433d38, 0x53494c0, 0x581dc20, 0x55314c0, 0x5, 0x0, 0x0, 0x54f5e98, 0x5, ...)
Apr 28 13:57:57 big-sister teleport[20580]:         /go/src/github.com/gravitational/teleport/lib/srv/regular/sshserver.go:1022 +0x58
Apr 28 13:57:57 big-sister teleport[20580]: created by github.com/gravitational/teleport/lib/srv/regular.(*Server).HandleNewChan
Apr 28 13:57:57 big-sister teleport[20580]:         /go/src/github.com/gravitational/teleport/lib/srv/regular/sshserver.go:1021 +0xbd4
Apr 28 13:57:57 big-sister systemd[1]: teleport.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
Apr 28 13:57:57 big-sister systemd[1]: teleport.service: Failed with result 'exit-code'.
Apr 28 13:57:57 big-sister systemd[1]: teleport.service: Service RestartSec=100ms expired, scheduling restart.
Apr 28 13:57:57 big-sister systemd[1]: teleport.service: Scheduled restart job, restart counter is at 11.
Apr 28 13:57:57 big-sister systemd[1]: Stopped Teleport SSH Service.
Apr 28 13:57:57 big-sister systemd[1]: Started Teleport SSH Service.
Apr 28 13:57:57 big-sister teleport[941]: INFO [PROC:1]    Connecting to the cluster bmus-lan with TLS client certificate. service/connect.go:132
Apr 28 13:57:58 big-sister teleport[941]: INFO [AUDIT:1]   Creating directory /var/lib/teleport/log. service/service.go:1903
Apr 28 13:57:58 big-sister teleport[941]: INFO [AUDIT:1]   Creating directory /var/lib/teleport/log/upload. service/service.go:1903
Apr 28 13:57:58 big-sister teleport[941]: INFO [AUDIT:1]   Creating directory /var/lib/teleport/log/upload/sessions. service/service.go:1903
Apr 28 13:57:58 big-sister teleport[941]: INFO [AUDIT:1]   Creating directory /var/lib/teleport/log/upload/sessions/default. service/service.go:1903
Apr 28 13:57:58 big-sister teleport[941]: INFO [AUDIT:1]   Creating directory /var/lib/teleport/log. service/service.go:1903
Apr 28 13:57:58 big-sister teleport[941]: INFO [AUDIT:1]   Creating directory /var/lib/teleport/log/upload. service/service.go:1903
Apr 28 13:57:58 big-sister teleport[941]: INFO [AUDIT:1]   Creating directory /var/lib/teleport/log/upload/streaming. service/service.go:1903
Apr 28 13:57:58 big-sister teleport[941]: INFO [AUDIT:1]   Creating directory /var/lib/teleport/log/upload/streaming/default. service/service.go:1903
Apr 28 13:57:58 big-sister teleport[941]: INFO [PROC:1]    Service node is creating new listener on 0.0.0.0:3022. service/signals.go:213
Apr 28 13:57:58 big-sister teleport[941]: INFO [NODE:1]    Service 6.1.2:v6.1.2-0-g23ab88c00 is starting on 0.0.0.0:3022 sqlite cache that will expire after connection to database is lost after 20h0m0s, will cache frequently accessed items for 2s. service/service.go:1774
Apr 28 13:57:58 big-sister teleport[941]: INFO [NODE:1]    Service 6.1.2:v6.1.2-0-g23ab88c00 is starting on 0.0.0.0:3022. utils/cli.go:235
Apr 28 13:57:58 big-sister teleport[941]: [NODE]         Service 6.1.2:v6.1.2-0-g23ab88c00 is starting on 0.0.0.0:3022.
Apr 28 13:57:58 big-sister teleport[941]: INFO [PROC:1]    The new service has started successfully. Starting syncing rotation status with period 10m0s. service/connect.go:435
```

### LINKED ISSUE #6703: Teleport client on armv7: SIGSEGV on connect
### Description
We get a segmentation fault for the teleport client on armv7.

**What happened**:
The client connects successfully to the teleport proxy. The client then crashes when a connection through the web UI is established.

**What you expected to happen**:
The client should not crash. The web UI should connect normally.

### Reproduction Steps
As minimally and precisely as possible, describe step-by-step how to reproduce the problem.
1. connect client node to proxy 
2. try to connect through web UI

### Server Details (Teleport Proxy)
- Teleport version (run `teleport version`): docker image: quay.io/gravitational/teleport:6
- Server OS (e.g. from `/etc/os-release`): Debian GNU/Linux 10 (buster)
- Where are you running Teleport? (e.g. AWS, GCP, Dedicated Hardware): dedicated hardware
- Additional details:
amd64 clients work fine when connected to the same proxy machine

### Client Details (Node)
- Tsh version (`tsh version`): not applicable
- Teleport version (run `teleport version`): Teleport v6.1.3 git:v6.1.3-0-g16f4ea392 go1.15.5
- Computer OS (e.g. Linux, macOS, Windows): Raspbian GNU/Linux 10 (buster)
- Browser version (for UI-related issues): not applicable
- Installed via (e.g. apt, yum, brew, website download): download
- Additional details:
Raspberry Pi armv7

### Debug Logs
Please include or attach debug logs, when appropriate. Ob
fuscate sensitive information!
- Start Teleport with --debug flag (`teleport --debug`)
- Run tsh with --debug flag (`tsh --debug`)

Proxy:
```
teleport     | DEBU [PROXY:SER] Dialing from: "10.0.12.6:36408" to: "10.0.13.61:3022". trace.fields:map[cluster:localhost] reversetunnel/localsite.go:185
teleport     | DEBU [PROXY:SER] Error occurred while dialing through a tunnel. address:10.0.13.61:3022 error:[
teleport     | ERROR REPORT:
teleport     | Original Error: *trace.NotFoundError no tunnel connection found: no node reverse tunnel for xxxxx.localhost found
teleport     | Stack Trace:
teleport     |         /go/src/github.com/gravitational/teleport/lib/reversetunnel/localsite.go:265 github.com/gravitational/teleport/lib/reversetunnel.(*localSite).dialTunnel
teleport     |         /go/src/github.com/gravitational/teleport/lib/reversetunnel/localsite.go:289 github.com/gravitational/teleport/lib/reversetunnel.(*localSite).getConn
teleport     |         /go/src/github.com/gravitational/teleport/lib/reversetunnel/localsite.go:187 github.com/gravitational/teleport/lib/reversetunnel.(*localSite).DialTCP
teleport     |         /go/src/github.com/gravitational/teleport/lib/reversetunnel/localsite.go:180 github.com/gravitational/teleport/lib/reversetunnel.(*localSite).Dial
teleport     |         /go/src/github.com/gravitational/teleport/lib/srv/regular/proxy.go:427 github.com/gravitational/teleport/lib/srv/regular.(*proxySubsys).proxyToHost
teleport     |         /go/src/github.com/gravitational/teleport/lib/srv/regular/proxy.go:249 github.com/gravitational/teleport/lib/srv/regular.(*proxySubsys).Start
teleport     |         /go/src/github.com/gravitational/teleport/lib/srv/regular/sshserver.go:1390 github.com/gravitational/teleport/lib/srv/regular.(*Server).handleSubsystem
teleport     |         /go/src/github.com/gravitational/teleport/lib/srv/regular/sshserver.go:1279 github.com/gravitational/teleport/lib/srv/regular.(*Server).dispatch
teleport     |         /go/src/github.com/gravitational/teleport/lib/srv/regular/sshserver.go:1242 github.com/gravitational/teleport/lib/srv/regular.(*Server).handleSessionRequests
teleport     |         /opt/go/src/runtime/asm_amd64.s:1374 runtime.goexit
teleport     | User Message: no tunnel connection found: no node reverse tunnel for xxxxx.localhost found] trace.fields:map[cluster:localhost] reversetunnel/localsite.go:298
teleport     | DEBU [HTTP:PROX] No valid environment variables found. proxy/proxy.go:207
teleport     | DEBU [HTTP:PROX] No proxy set in environment, returning direct dialer. proxy/proxy.go:122
teleport     | DEBU [PROXY:SER] Succeeded dialing from: "10.0.12.6:36408" to: "10.0.13.61:3022". trace.fields:map[cluster:localhost] reversetunnel/localsite.go:191
teleport     | WARN [WEBSOCKET] Unable to stream terminal: EOF. web/terminal.go:463
```

Client node (crash log with --debug):
see attached file
[client-node.log](https://github.com/gravitational/teleport/files/6414256/client-node.log)

Sufficient nemory is available:
```
root@XXX:/mnt/storage/teleport# free -h
              total        used        free      shared  buff/cache   available
Mem:          927Mi        52Mi       287Mi        46Mi       587Mi       813Mi
Swap:            0B          0B          0B
```

### PR DESCRIPTION
**Pull request by xacrimon**
# What

Align various atomics to 64 bits.

# Why

Sometime between v6.0.0 and v6.1.13 a variable was introduced that triggers a misalignment
on 32 bit architectures. On ARMv7, atomics need to be 64 bit aligned but this isn't something the compiler
enforces or checks for you, resulting in the segfault. This is a `wontfix` by the Go compiler devs even though it is a rather serious bug as Go lacks a good way to configure alignment.

# How

The `uber-go/atomic` package is intended to be used in such a fashion that integers are boxed via the `NewInt**` family of functions. Currently this is not the case, triggering this issue. This patch simply uses the package in a boxed fashion which forces Go to align the variables correctly.

# Backports

This needs to be backported to `branch/v6` and `branch/v6.1`.

# Fixes

Fixes #6642 
Fixes #6703

### CODE REVIEW

**Comment by xacrimon** [comment]
note: not final, missed making it a draft

**Comment by xacrimon** [comment]
Confirmed and tested fix, massive thanks to @BinaryPaean

**Comment by maxdwit** [comment]
Works like a charm.

**Comment by russjones** [comment]
@fspmarshall @quinqu You two are the assigned reviewers, can you review to unblock @xacrimon?

**Review by quinqu — APPROVED** [review]

**Review by fspmarshall — APPROVED** [review]

**Review by klizhentas — APPROVED** [review]

**Review by russjones — APPROVED** [review]
Bot.

**Pull request merged**
