### PR TITLE
Improve error handling in Connect gateway integration test

### PR DESCRIPTION
**Pull request by ravicious**
A few small things that I missed when I added this test in #17950.

mockTSHDEventsClient will most likely be called outside of the test goroutine, so we shouldn't use require.NoError there.

helpers.SetupUserCreds returns an error which I did not inspect. The linter didn't warn me about it for some reason.

### CODE REVIEW

**Review by espadolini — APPROVED** [review]
Is this better than using `assert.NoError` instead?

**Comment by ravicious** [comment]
I suppose `assert.NoError` would be better at communicating where exactly the failure has happened.

If I understand correctly, `assert.NoError` continues the execution if the error is present but the test will ultimately fail. Does this mean that the implementation of `Relogin` should take the return value of `assert.NoError` into account?

That is, I'm not sure if I should do this:

```go
	err = helpers.SetupUserCreds(c.tc, c.pack.Root.Cluster.Config.Proxy.SSHAddr.Addr, *creds)
	assert.NoError(c.t, err)

	return &api.ReloginResponse{}, nil
```

or

```go
	err = helpers.SetupUserCreds(c.tc, c.pack.Root.Cluster.Config.Proxy.SSHAddr.Addr, *creds)
	if !assert.NoError(c.t, err) {
		return nil, trace.Wrap(err)
	}

	return &api.ReloginResponse{}, nil

```

From what I see, in the project we seem to use the first approach.

**Comment by ravicious** [comment]
This also reminds me that asserting something without failing the test immediately would also be helpful when checking the number of calls to the mock. I had a test that was failing on this check:

https://github.com/gravitational/teleport/blob/b2e1807d03683c7747a17d5a3730a3fbf750c1b3/integration/proxy/teleterm_test.go#L155-L158

but if these two were performed as assertions before that `require.NoError`, it'd have made debugging much easier:

https://github.com/gravitational/teleport/blob/b2e1807d03683c7747a17d5a3730a3fbf750c1b3/integration/proxy/teleterm_test.go#L168-L171

Would that be an okay approach or would you rather say it's misusing the assert package?

**Review by ryanclark — APPROVED** [review]

**Review by zmb3 — APPROVED** [review]

**Comment by ravicious** [comment]
@espadolini Could you offer an advice or an opinion on using `assert.NoError` inside a mocked function vs returning an error from that function? https://github.com/gravitational/teleport/pull/19145#issuecomment-1340995485

**Comment by espadolini** [comment]
I don't know if mocks should have access to the `*testing.T`, that seems kind of an overreach. The testing environment should set up and control the mock instead, so I think the change here is good.

**Pull request merged**
