### PR TITLE
Address Cloud users in guides

### PR DESCRIPTION
**Pull request by ptgott**
- Edit the Google Workspace SSO guide to mention Teleport
  Cloud in the Prerequisites and add scoped Tabs components.
  Also add clarity edits.

- Edit the Azure AD SSO guide to mention Teleport Cloud and
  included scoped Tabs components.

- Add compabitility warning to the HSM guide, scaling guide,
  Docker guide, restricted session, and aws-terraform guide.

- Mention the cloud in session recording prerequisites.

### CODE REVIEW

**Comment by ptgott** [comment]
@espadolini There were some conflicts with your recent Google Workspace SSO changes, so I'd appreciate a review from you if you have time.

**Review by espadolini — COMMENTED** [review]
`docs/pages/enterprise/sso/google-workspace.mdx` LGTM

@ptgott do you need me to also look at the other changes?

**Comment by ptgott** [comment]
@espadolini Nope! Thanks for looking.

**Comment by russjones** [comment]
@xinding33 Once you've approved, please just ping @r0mant @zmb3 or @russjones to get this approved.

**Review by zmb3 — APPROVED** [review]

**Review by russjones — APPROVED** [review]

**Review by klizhentas — APPROVED** [review]

**Pull request merged**
