### PR TITLE
DiscoveryConfig: add service and client

### PR DESCRIPTION
**Pull request by marcoandredinis**
This PR adds a Service and Client implementation for the DiscoveryConfig resource.

It does not add any initialization/usage to keep the PR small.

### CODE REVIEW

**Comment by marcoandredinis** [comment]
@probakowski @Tener Can you please take a look?

**Comment by Tener** [comment]
> @probakowski @Tener Can you please take a look?

Sorry for the delay. 

> It does not add any initialization/usage to keep the PR small.

Do you have the follow-up PR handy?

**Comment by marcoandredinis** [comment]
> > It does not add any initialization/usage to keep the PR small.
> 
> Do you have the follow-up PR handy?

https://github.com/gravitational/teleport/pull/32371
https://github.com/gravitational/teleport/pull/32399

**Review by Tener — APPROVED** [review]
I wish we could add new resource types without so much boilerplate.

**Review by probakowski — APPROVED** [review]
Sorry for the delay, LGTM

**Pull request merged**
