### PR TITLE
ALPN upgrade with custom X-Teleport-Upgrade header

### PR DESCRIPTION
**Pull request by greedy52**
During ALPN connection upgrade, client now sets `X-Teleport-Upgrade` header to the same value as the `Upgrade` header as some load balancers have seen dropping values from the `Upgrade` header. 

Server side will check both `Upgrade` and `X-Teleport-Upgrade` header values.

### CODE REVIEW

**Review by capnspacehook — COMMENTED** [review]
What issue/RFD is this related to? I'm confused why this new header is needed as it seems to be used the exact same way as `constants.WebAPIConnUpgradeHeader`

**Comment by greedy52** [comment]
> What issue/RFD is this related to? I'm confused why this new header is needed as it seems to be used the exact same way as `constants.WebAPIConnUpgradeHeader`

Good call. I've added an update to the RFD in this PR.

The fix will be accounted as part of #29156 but it comes from debugging customer setups in the field. Load balancers/reverse proxies may show different behaviors when handling connection upgrades. This particular change adds a safe guard when the official `Upgrade` header is removed by the load balancer

**Review by gabrielcorado — APPROVED** [review]

**Review by capnspacehook — APPROVED** [review]
Thanks for providing clarity, makes sense

**Review by smallinsky — APPROVED** [review]
LGTM,
@greedy52  Could you add a brief PR desc ?

**Pull request merged**
