### PR TITLE
Backport: get teleport /readyz state from heartbeats instead of cert rotation

### LINKED ISSUE #3743: Node readyz state takes too long to recover
### Description

**What happened**:

After a temporary proxy/auth server downtime, node's `/readyz` endpoint reports "recovering" state for up to 10min.
The problem is that the current readyz state is updated via certificate rotation checks, which happen every 10min. It should instead be tied to heartbeats, that happen way more frequently.

**What you expected to happen**:

Node should recover in <1m after proxy/auth server come back online.

### PR DESCRIPTION
**Pull request by awly**
Backport of https://github.com/gravitational/teleport/pull/4223 into 4.3

Fixes #3743

### CODE REVIEW

**Review by webvictim — APPROVED** [review]

**Comment by webvictim** [comment]
(assuming the linter/logic gets fixed)

**Review by webvictim — CHANGES_REQUESTED** [review]
Just marking this unapproved

**Comment by awly** [comment]
retest this please

**Review by fspmarshall — APPROVED** [review]

**Review by webvictim — APPROVED** [review]

**Comment by awly** [comment]
@russjones need approval for dependency changes

**Review by russjones — APPROVED** [review]

**Pull request merged**
