### PR TITLE
Add auto-enroll toggle to device trust config

### PR DESCRIPTION
**Pull request by codingllama**
Add the auto-enroll toggle to both proto and YAML-based configs.

https://github.com/gravitational/teleport.e/issues/826

### CODE REVIEW

**Comment by codingllama** [comment]
Not strictly required for 13.0, despite the backport label. I'll be necessary for 13.1, but I might delay the backport for now (unless it starts getting in the way).

**Review by rosstimothy — APPROVED** [review]

**Comment by codingllama** [comment]
Friendly ping @strideynet @ibeckermayer ?

**Review by ibeckermayer — APPROVED** [review]
You could add a test checking that it's set to false if not defined to be exhaustive.

**Comment by codingllama** [comment]
> You could add a test checking that it's set to false if not defined to be exhaustive.

Done: https://github.com/gravitational/teleport/pull/24747/commits/53754a01238e547bbf2785cd18497c6f74473d2a.

**Pull request merged**
