### PR TITLE
Release 15.0.2

### PR DESCRIPTION
**Pull request by fheinecke**
Reviewers, please take a look at the below items specifically:
* Fixed Opsgenie plugin creating alerts based on incorrect annotation. Action required for Opsgenie plugin users. [#38105](https://github.com/gravitational/teleport/pull/38105) - Is this a breaking change, and if so, does it need to wait for v16? Will users know what action is required, or does the changelog need to include something more specific?
* Added a tsh sessions ls command to list active sessions. [#37969](https://github.com/gravitational/teleport/pull/37969) - Does this require a minor version bump?
* Added option to validate hardware key serial numbers with hardware key support. [#38068](https://github.com/gravitational/teleport/pull/38068) - Does this require a minor version bump?

Changelog:
* Fixed a potential panic in the `tsh status` command. [#38305](https://github.com/gravitational/teleport/pull/38305)
* Fixed SSO user locking in the setup access step of the RDS auto discover flow in the web UI. [#38283](https://github.com/gravitational/teleport/pull/38283)
* Optionally permit the auth server to terminate client connections from unsupported versions. [#38182](https://github.com/gravitational/teleport/pull/38182)
* Fixed Assist obstructing the user dropdown menu when in docked mode. [#38156](https://github.com/gravitational/teleport/pull/38156)
* Improved the stability of Teleport during graceful upgrades. [#38145](https://github.com/gravitational/teleport/pull/38145)
* Added the ability to view and manage Machine ID bots from the UI. [#38122](https://github.com/gravitational/teleport/pull/38122)
* Fixed a bug that prevented desktop clipboard sharing from working when large amounts of text are placed on the clipboard. [#38120](https://github.com/gravitational/teleport/pull/38120)
* Fixed Opsgenie plugin creating alerts based on incorrect annotation. Action required for Opsgenie plugin users. [#38105](https://github.com/gravitational/teleport/pull/38105)
* Added option to validate hardware key serial numbers with hardware key support. [#38068](https://github.com/gravitational/teleport/pull/38068)
* Removed access tokens from URL parameters, preventing them from being leaked to intermediary systems that may log them in plaintext. [#38032](https://github.com/gravitational/teleport/pull/38032)
* Forced agents to terminate Auth connections if joining fails. [#38005](https://github.com/gravitational/teleport/pull/38005)
* Added a tsh sessions ls command to list active sessions. [#37969](https://github.com/gravitational/teleport/pull/37969)
* Improved error handling when idle desktop connections are terminated. [#37955](https://github.com/gravitational/teleport/pull/37955)
* Updated Go to 1.21.7. [#37846](https://github.com/gravitational/teleport/pull/37846)
* Discover flow now starts two instances of DatabaseServices when setting up access to Amazon RDS. [#37805](https://github.com/gravitational/teleport/pull/37805)

### CODE REVIEW

**Review by zmb3 — APPROVED** [review]
The last 2 bullets don't require a minor version bump. We don't strictly adhere to semver as it would require us to hold features back and we prefer to ship things when they're ready. 

I agree that the changelog entry is not clear. We need to describe what action is required of users.

**Comment by fheinecke** [comment]
@EdwardDowling can you please clarify what action is required by end users?

**Review by espadolini — APPROVED** [review]

**Comment by espadolini** [comment]
@fheinecke I disabled automerge because there's still some open question about the changelog, not sure if you'd rather fix it with a later PR.

**Comment by fheinecke** [comment]
@zmb3 @r0mant it looks like the author of https://github.com/gravitational/teleport/pull/38105 is out sick. What should I do here?

**Comment by EdwardDowling** [comment]
> @zmb3 @r0mant it looks like the author of #38105 is out sick. What should I do here?
@fheinecke 
Am back,.
The changes the users need to make is update the annotations used on the roles so they match the current descriptions in the Opsgenie plugin docs.

**Review by r0mant — CHANGES_REQUESTED** [review]
@fheinecke @EdwardDowling Let's hold off for a bit. It seems to me that the Opsgenie fix introduces a backwards incompatible behavior which we should not do in a patch release.

**Review by r0mant — APPROVED** [review]
@fheinecke Let's rebase, remove the Opsgenie changelog line and publish.

**Pull request merged**
