### PR TITLE
Fix integration tests inside container

### PR DESCRIPTION
**Pull request by webvictim**
The way that integration tests are called from the root directory `Makefile` versus the `build.assets` `Makefile` is currently different, meaning that if you run integration tests locally you get verbose output with a race detector, and if you run inside a container you get no verbose output and no race detector. This gives a different experience for local manual testing vs CI automated testing and also potentially changes the outcome of the tests.

This PR alters the process so that it just spawns a container and then runs `make integration` from the base `Makefile`, so any changes to the base `Makefile` will also be picked up and used in tests. This is similar to the approach that's currently being used for `make test`.

It also reformats the code to make the use of `cd $(SRCDIR)` vs `make -C $(SRCDIR)` more consistent throughout, improves comments and fixes some formatting.

### CODE REVIEW

**Comment by webvictim** [comment]
I'm not sure if there's a reason why we were deliberately disabling the race detector for CI tests. I've been running `make -C build.assets integration` locally and it fails each time because a race is detected.

**Comment by awly** [comment]
The race detector was explicitly turned off for all integration tests (in CI and local) until recently.
We should enable it in `build.assets/Makefile` for sure, just an oversight.

It is very peculiar that the race detector catches something when running in docker (`make -C build.assets integration`), but not when running on the host (`make integration`).

The race traces are very curious:
```
==================
WARNING: DATA RACE
Read at 0x00c001fe61e0 by goroutine 794:
  github.com/gravitational/teleport/vendor/golang.org/x/crypto/ssh.(*channel).WriteExtended()
      /gopath/src/github.com/gravitational/teleport/vendor/golang.org/x/crypto/ssh/channel.go:233 +0x56
  github.com/gravitational/teleport/vendor/golang.org/x/crypto/ssh.(*channel).Write()
      /gopath/src/github.com/gravitational/teleport/vendor/golang.org/x/crypto/ssh/channel.go:535 +0x83
  github.com/gravitational/teleport/vendor/golang.org/x/crypto/ssh.(*sessionStdin).Write()
      <autogenerated>:1 +0x87
  github.com/gravitational/teleport/lib/utils.(*PipeNetConn).Write()
      /gopath/src/github.com/gravitational/teleport/lib/utils/fakeconn.go:63 +0x77
  github.com/gravitational/teleport/lib/client.(*NodeSession).pipeInOut.func2()
      /gopath/src/github.com/gravitational/teleport/lib/client/session.go:553 +0x170
DEBU [PROC:81]   Creating in-memory backend for [auth]. service/service.go:1279
Previous write at 0x00c001fe61e0 by goroutine 197:
  [failed to restore the stack]
. srv/heartbeat.go:240
Goroutine 794 (running) created at:
  github.com/gravitational/teleport/lib/client.(*NodeSession).pipeInOut()
      /gopath/src/github.com/gravitational/teleport/lib/client/session.go:543 +0x9a
  github.com/gravitational/teleport/lib/client.(*NodeSession).interactiveSession()
      /gopath/src/github.com/gravitational/teleport/lib/client/session.go:229 +0x1d4
  github.com/gravitational/teleport/lib/client.(*NodeSession).runShell()
      /gopath/src/github.com/gravitational/teleport/lib/client/session.go:407 +0x72
  github.com/gravitational/teleport/lib/client.(*TeleportClient).runShell()
      /gopath/src/github.com/gravitational/teleport/lib/client/api.go:1490 +0x1f4
  github.com/gravitational/teleport/lib/client.(*TeleportClient).SSH()
      /gopath/src/github.com/gravitational/teleport/lib/client/api.go:1000 +0x50f
  github.com/gravitational/teleport/integration.(*IntSuite).TestPAM.func2()
      /gopath/src/github.com/gravitational/teleport/integration/integration_test.go:2931 +0x39c
==================
==================
WARNING: DATA RACE
Write at 0x00c002124068 by goroutine 794:
  github.com/gravitational/teleport/lib/client.(*NodeSession).pipeInOut.func2()
      /gopath/src/github.com/gravitational/teleport/lib/client/session.go:555 +0x1c1
DEBU [PROC]      Adding service to supervisor. service:common.rotate service/supervisor.go:181
Previous read at 0x00c002124068 by goroutine 197:
  [failed to restore the stack]
={\"testing\":[\"integration\"]},STREET=,L=jenkins 2020-04-25 16:17:49.746271405 +0000 UTC []}. common_n
Goroutine 794 (running) created at:
  github.com/gravitational/teleport/lib/client.(*NodeSession).pipeInOut()
      /gopath/src/github.com/gravitational/teleport/lib/client/session.go:543 +0x9a
  github.com/gravitational/teleport/lib/client.(*NodeSession).interactiveSession()
      /gopath/src/github.com/gravitational/teleport/lib/client/session.go:229 +0x1d4
  github.com/gravitational/teleport/lib/client.(*NodeSession).runShell()
      /gopath/src/github.com/gravitational/teleport/lib/client/session.go:407 +0x72
  github.com/gravitational/teleport/lib/client.(*TeleportClient).runShell()
      /gopath/src/github.com/gravitational/teleport/lib/client/api.go:1490 +0x1f4
  github.com/gravitational/teleport/lib/client.(*TeleportClient).SSH()
      /gopath/src/github.com/gravitational/teleport/lib/client/api.go:1000 +0x50f
  github.com/gravitational/teleport/integration.(*IntSuite).TestPAM.func2()
      /gopath/src/github.com/gravitational/teleport/integration/integration_test.go:2931 +0x39c
==================
the connection was closed on the remote side on  24 Apr 20 16:27 UTC
==================
WARNING: DATA RACE
Read at 0x00c0029db020 by goroutine 721:
  github.com/gravitational/teleport/vendor/golang.org/x/crypto/ssh.(*channel).WriteExtended()
      /gopath/src/github.com/gravitational/teleport/vendor/golang.org/x/crypto/ssh/channel.go:233 +0x56
  github.com/gravitational/teleport/vendor/golang.org/x/crypto/ssh.(*channel).Write()
      /gopath/src/github.com/gravitational/teleport/vendor/golang.org/x/crypto/ssh/channel.go:535 +0x83
  github.com/gravitational/teleport/vendor/golang.org/x/crypto/ssh.(*sessionStdin).Write()
      <autogenerated>:1 +0x87
  github.com/gravitational/teleport/lib/utils.(*PipeNetConn).Write()
      /gopath/src/github.com/gravitational/teleport/lib/utils/fakeconn.go:63 +0x77
  github.com/gravitational/teleport/lib/client.(*NodeSession).pipeInOut.func2()
      /gopath/src/github.com/gravitational/teleport/lib/client/session.go:553 +0x170
DEBU [PROC:80]   Service has started. service:auth.broadcast service/supervisor.go:242
Previous write at 0x00c0029db020 by goroutine 748:
  ??()
      -:0 +0xffffffffffffffff
  encoding/json.indirect()
      /opt/go/src/encoding/json/decode.go:532 +0x1de
  encoding/json.(*decodeState).literalStore()
      /opt/go/src/encoding/json/decode.go:916 +0x2d6
  encoding/json.(*decodeState).value()
      /opt/go/src/encoding/json/decode.go:443 +0x2dc
  encoding/json.(*decodeState).object()
      /opt/go/src/encoding/json/decode.go:823 +0x21db
  encoding/json.(*decodeState).value()
      /opt/go/src/encoding/json/decode.go:429 +0xaf
  encoding/json.(*decodeState).array()
      /opt/go/src/encoding/json/decode.go:616 +0x1e3
  encoding/json.(*decodeState).value()
      /opt/go/src/encoding/json/decode.go:419 +0x176
  encoding/json.(*decodeState).unmarshal()
      /opt/go/src/encoding/json/decode.go:179 +0x254
  encoding/json.Unmarshal()
      /opt/go/src/encoding/json/decode.go:106 +0x1e4
  github.com/gravitational/teleport/lib/client.(*ProxyClient).GetSites()
      /gopath/src/github.com/gravitational/teleport/lib/client/client.go:107 +0x4cc
  github.com/gravitational/teleport/lib/client.(*ProxyClient).currentCluster()
      /gopath/src/github.com/gravitational/teleport/lib/client/client.go:997 +0x50
  github.com/gravitational/teleport/lib/client.(*TeleportClient).SSH()
      /gopath/src/github.com/gravitational/teleport/lib/client/api.go:941 +0x106
  github.com/gravitational/teleport/integration.(*IntSuite).TestPAM.func2()
      /gopath/src/github.com/gravitational/teleport/integration/integration_test.go:2931 +0x39c
00&_sync=OFF, poll stream period: 100ms lite/lite.go:173
Goroutine 721 (running) created at:
  github.com/gravitational/teleport/lib/client.(*NodeSession).pipeInOut()
      /gopath/src/github.com/gravitational/teleport/lib/client/session.go:543 +0x9a
  github.com/gravitational/teleport/lib/client.(*NodeSession).interactiveSession()
      /gopath/src/github.com/gravitational/teleport/lib/client/session.go:229 +0x1d4
  github.com/gravitational/teleport/lib/client.(*NodeSession).runShell()
      /gopath/src/github.com/gravitational/teleport/lib/client/session.go:407 +0x72
  github.com/gravitational/teleport/lib/client.(*TeleportClient).runShell()
      /gopath/src/github.com/gravitational/teleport/lib/client/api.go:1490 +0x1f4
  github.com/gravitational/teleport/lib/client.(*TeleportClient).SSH()
      /gopath/src/github.com/gravitational/teleport/lib/client/api.go:1000 +0x50f
  github.com/gravitational/teleport/integration.(*IntSuite).TestPAM.func2()
      /gopath/src/github.com/gravitational/teleport/integration/integration_test.go:2931 +0x39c
==================
==================
WARNING: DATA RACE
Write at 0x00c0039f4de8 by goroutine 721:
  github.com/gravitational/teleport/lib/client.(*NodeSession).pipeInOut.func2()
      /gopath/src/github.com/gravitational/teleport/lib/client/session.go:555 +0x1c1
DEBU [SQLITE]    Connected to: file:/tmp/cluster-site-B119144280/cache/reverse/site-B/sqlite.db?_busy_ti
Previous read at 0x00c0039f4de8 by goroutine 748:
  ??()
      -:0 +0xffffffffffffffff
  encoding/json.indirect()
      /opt/go/src/encoding/json/decode.go:532 +0x1de
  encoding/json.(*decodeState).literalStore()
      /opt/go/src/encoding/json/decode.go:916 +0x2d6
  encoding/json.(*decodeState).value()
      /opt/go/src/encoding/json/decode.go:443 +0x2dc
  encoding/json.(*decodeState).object()
      /opt/go/src/encoding/json/decode.go:823 +0x21db
  encoding/json.(*decodeState).value()
      /opt/go/src/encoding/json/decode.go:429 +0xaf
  encoding/json.(*decodeState).array()
      /opt/go/src/encoding/json/decode.go:616 +0x1e3
  encoding/json.(*decodeState).value()
      /opt/go/src/encoding/json/decode.go:419 +0x176
  encoding/json.(*decodeState).unmarshal()
      /opt/go/src/encoding/json/decode.go:179 +0x254
  encoding/json.Unmarshal()
      /opt/go/src/encoding/json/decode.go:106 +0x1e4
  github.com/gravitational/teleport/lib/client.(*ProxyClient).GetSites()
      /gopath/src/github.com/gravitational/teleport/lib/client/client.go:107 +0x4cc
  github.com/gravitational/teleport/lib/client.(*ProxyClient).currentCluster()
      /gopath/src/github.com/gravitational/teleport/lib/client/client.go:997 +0x50
  github.com/gravitational/teleport/lib/client.(*TeleportClient).SSH()
      /gopath/src/github.com/gravitational/teleport/lib/client/api.go:941 +0x106
  github.com/gravitational/teleport/integration.(*IntSuite).TestPAM.func2()
      /gopath/src/github.com/gravitational/teleport/integration/integration_test.go:2931 +0x39c
ion error: desc = "transport: Error while dialing dial tcp 127.0.0.1:20254: connect: connection refused"
Goroutine 721 (running) created at:
  github.com/gravitational/teleport/lib/client.(*NodeSession).pipeInOut()
      /gopath/src/github.com/gravitational/teleport/lib/client/session.go:543 +0x9a
  github.com/gravitational/teleport/lib/client.(*NodeSession).interactiveSession()
      /gopath/src/github.com/gravitational/teleport/lib/client/session.go:229 +0x1d4
  github.com/gravitational/teleport/lib/client.(*NodeSession).runShell()
      /gopath/src/github.com/gravitational/teleport/lib/client/session.go:407 +0x72
  github.com/gravitational/teleport/lib/client.(*TeleportClient).runShell()
      /gopath/src/github.com/gravitational/teleport/lib/client/api.go:1490 +0x1f4
  github.com/gravitational/teleport/lib/client.(*TeleportClient).SSH()
      /gopath/src/github.com/gravitational/teleport/lib/client/api.go:1000 +0x50f
  github.com/gravitational/teleport/integration.(*IntSuite).TestPAM.func2()
      /gopath/src/github.com/gravitational/teleport/integration/integration_test.go:2931 +0x39c
==================
```
(ignore some inter-mixed log output)

It looks like they happen withn `golang.org/x/crypto/ssh`, in stdin/stdout pipes. Those should be thread-safe.
Some other traces come from unmarshaling some JSON copied over from those pipes, which is even more odd (the bytes should get deep-copied).

I'll play more with this.

**Comment by webvictim** [comment]
In that case, I'll avoid merging this until such time as we have a fix for the data races.

**Comment by russjones** [comment]
@webvictim @awly What's the status of this? Should we close this PR temporarily?

**Comment by webvictim** [comment]
I think we can close this for now.

**Pull request closed without merging**
