### PR TITLE
kms: allow multi-region kms keys to be enabled

### PR DESCRIPTION
**Pull request by dboslee**
This adds the ability to enable multi-region keys. This doesn't currently expose any way to configure replica keys but adding this can be extended in the future.

The configuration looks as follows

```yaml
  ca_key_params:
    aws_kms:
      account: 11111111
      region: us-west-2
      multi_region:
        enabled: true
```

### CODE REVIEW

**Comment by nklaassen** [comment]
what's the plan for adding support adding support for replica keys? mostly I'm wondering how well this config change supports that plan and if we need to make any changes now or later to `awsKMSKeyID`

**Comment by dboslee** [comment]
> what's the plan for adding support adding support for replica keys? mostly I'm wondering how well this config change supports that plan and if we need to make any changes now or later to `awsKMSKeyID`

@nklaassen I believe all we need is a list of regions in the config. Replica keys share the same keyID as the primary key. The only issue is that removing regions from the config risks orphaning replica keys in regions. so we could also consider storing the list of regions a key is replicated to in backend CA resource as replicas are created. Its also worth noting the deletion of the primary key is blocked until replica keys are deleted.

Anyways theres a few possible solutions and edge cases but the keyID is consistent across regions, we just need to figure how we want to handle replica key deletion.

```yaml
  ca_key_params:
    aws_kms:
      account: 11111111
      region: us-west-2
      multi_region:
        enabled: true
        replicas:
        - us-east-1
  ```

**Comment by nklaassen** [comment]
@dboslee so I think that is mostly good enough. The single possible concern I have is this related to an individual auth deciding if it is able to use a given existing key created by a different auth server in a different region, as it is stored in the teleport backend basically as the AWS ARN.

So say an auth is configured with
```
  ca_key_params:
    aws_kms:
      account: 11111111
      region: us-east-1
      multi_region:
        enabled: true
        replicas:
        - us-west-2
        - us-east-1
```
and it sees a `us-west-2` key in the Teleport backend with arn `arn:aws:kms:us-west-2:278576220453:key/mrk-45b3ad7b9fb74a51bf097ed75a275080`

Should this auth just assume that a replica exists in `us-east-1`, try to use it, and fail to sign things if that replica doesn't exist? I think that's maybe okay, but actually it could get hairy if we add regions to the replicas list after some keys have already been created

**Comment by nklaassen** [comment]
I pushed up a commit with some unit tests, hope you don't mind

**Review by nklaassen — APPROVED** [review]
We should be able to solve the replica issue later one way or another, i think this is a good first step to making sure we are at least able to create multi-region keys

**Review by atburke — APPROVED** [review]

**Pull request merged**
