### PR TITLE
[v14] Web: Add new supported aws region (il-central-1) to selector

### PR DESCRIPTION
**Pull request by kimlisa**
Backport #31825 to branch/v14

### CODE REVIEW

**Review by avatus — APPROVED** [review]

**Comment by zmb3** [comment]
I thought discovery still doesn't support this region in older branches? @greedy52

**Comment by marcoandredinis** [comment]
> I thought discovery still doesn't support this region in older branches? @greedy52

This is not used by the `discovery_service`
It will only fetch a single database information and add it as a Database to teleport (the same as adding the info to the `db_service` or using a `tctl create <database>.yaml`)

**Review by marcoandredinis — APPROVED** [review]

**Comment by marcoandredinis** [comment]
@kimlisa Sorry for removing the auto-merge, let's clarify Zac's question first

**Comment by greedy52** [comment]
> I thought discovery still doesn't support this region in older branches? @greedy52

AWS SDK in general works with "unknown" regions so this should be fine. 

For discovery, an error was thrown if an unknown region was found when parsing the discovery service's config. I've changed this behaviour to do a regex validation instead of testing against a list of known regions. That change will be backported today as well.

**Pull request merged**
