### PR TITLE
Add docs for the new Slack helm chart values

### PR DESCRIPTION
**Pull request by dancmeyers**
This goes alongside https://github.com/gravitational/teleport-plugins/pull/872, it shouldn't be merged until/unless that PR is accepted and merged.

### CODE REVIEW

**Comment by dancmeyers** [comment]
N.B. a buddy PR has been created in https://github.com/gravitational/teleport-plugins/pull/872, because I don't have the necessary permissions to cause the tests to pass.

**Comment by dancmeyers** [comment]
The referenced PR is now merged, so this should be as well so that the website documentation is kept up to date with the next Slack plugin release.

**Review by zmb3 — APPROVED** [review]

**Review by ptgott — COMMENTED** [review]
In all of these entries, what does "should be applied" mean? Are there instances where these annotations are not applied? If not, I would say something like,

"Kubernetes annotations that the chart applies to the `<resource>` it creates".

**Comment by ptgott** [comment]
@dancmeyers Are we backporting this? If so, we'll want to add `backport` labels

**Comment by dancmeyers** [comment]
> In all of these entries, what does "should be applied" mean? Are there instances where these annotations are not applied? If not, I would say something like,
> 
> "Kubernetes annotations that the chart applies to the `<resource>` it creates".

🤷🏼‍♂️ I copied the exact same wording that already exists for these annotations where they already exist on the `teleport-cluster` and `teleport-kube-agent` charts, to keep things consistent between docs. If you want to change the wording that's fine but you should probably raise a PR to do it uniformly across all chart docs...

**Comment by dancmeyers** [comment]
> @dancmeyers Are we backporting this? If so, we'll want to add `backport` labels

I don't think there's anything in it that wouldn't be backwards compatible, so I don't see any reason _not_ to backport, but I lost control of the original PR because I didn't have the permissions necessary to cause tests to pass on your repo, so I guess that would be a question for @tigrato.

For my company's purposes, we're already on Teleport 13 so it's not an issue for us if it doesn't get backported.

**Comment by tigrato** [comment]
> > @dancmeyers Are we backporting this? If so, we'll want to add `backport` labels
> 
> I don't think there's anything in it that wouldn't be backwards compatible, so I don't see any reason _not_ to backport, but I lost control of the original PR because I didn't have the permissions necessary to cause tests to pass on your repo, so I guess that would be a question for @tigrato.
> 
> For my company's purposes, we're already on Teleport 13 so it's not an issue for us if it doesn't get backported.

Unfortunately, `teleport-plugins` don't support backporting and all new releases are shipped directly from the `master` branch so we only want to backport it to `branch/v13`

**Comment by ptgott** [comment]
> 🤷🏼‍♂️ I copied the wording for these annotations where they already exist and are documented against the teleport-cluster and teleport-kube-agent charts, to keep things consistent between docs. If you want to change the wording that's fine but you should probably raise a PR to do it uniformly across all chart docs...

I would rather have inconsistently clear descriptions in the docs than consistently less clear ones. We can start by making these docs clear and open a PR later to apply the same approach to other docs.

**Review by ptgott — APPROVED** [review]

**Comment by dancmeyers** [comment]
This has been approved by 2 reviewers, which I think is the first 👍 I needed. But the CI pipeline hasn't run because a maintainer has to OK that to happen. Could someone do that?

**Comment by tigrato** [comment]
Hi @dancmeyers,

Thanks for your contribution. We are currently unable to run our tests on
external contributions. As such, I'll be helping you validate and
merge your pull request. I've created an internal PR here:

https://github.com/gravitational/teleport/pull/30128

Please the re-approval process and I'll get your
code merged.

Thanks!

**Pull request closed without merging**
