### PR TITLE
Condense docs sections into "Enroll Resources"

### PR DESCRIPTION
**Pull request by ptgott**
The number of sections on the left sidebar makes the documentation difficult to navigate. This change reduces the number of sidebar sections by creating an "Enroll Resources" section from sidebar sections related to protecting infrastructure resources with Teleport.

This change configures the sidebar for the Enroll Resources section to be automatically generated. Since the generator expects each subdirectory of a section to have a corresponding table of contents page, this change also adds missing table of contents pages.

In some cases, we can repurpose an existing section introduction page for a section's table of contents page. In other cases, the introduction spends too much time on providing context to make for a useful table of contents, so this change adds a separate table of contents page. Table of contents pages use the `(!toc!)` syntax to list links automatically based on the file system.

This change also adds redirects based on mentions of Teleport docs URLs in the Web UI source, and removes all other redirects to avoid exceeding the maximum number of routes in Vercel.

### CODE REVIEW

**Review by xinding33 — APPROVED** [review]
I'm approving the PR as is but I do have some thoughts, see below:

- Remove the "Teleport Auto-Discovery" subsection and move the content under their respective resource subsection (e.g. move "Kubernetes Clusters Discovery" under "Kubernetes Clusters")
- Rename the "Server" subsection to "Linux Server" because some users get confused about whether Windows Servers belong under "Server"

**Comment by ptgott** [comment]
👍 I've renamed the "Servers" section to "Linux Servers" in a540738fb5b2aab4cf45a6b2a2176051f281c8b8. I'll make time to restructure the auto-discovery section in another PR.

**Comment by zmb3** [comment]
> Remove the "Teleport Auto-Discovery" subsection and move the content under their respective resource subsection (e.g. move "Kubernetes Clusters Discovery" under "Kubernetes Clusters")

Didn't we just do the opposite of this? Now that Teleport has a dedicated `discovery_service` that handles discovery of all types of resources, I think it makes sense to reflect that in the docs.

**Review by zmb3 — APPROVED** [review]

**Comment by ptgott** [comment]
> Didn't we just do the opposite of this? Now that Teleport has a dedicated discovery_service that handles discovery of all types of resources, I think it makes sense to reflect that in the docs.

We did! @xinding33 was the reasoning in [this comment](https://github.com/gravitational/teleport/pull/43979#pullrequestreview-2169890374) that we would categorize the first-level child directories of "Enroll Resources" around kinds of resources, rather than the services we would use to enroll them?

In any case, we can revisit this question in a separate PR as we look for a more cohesive way to structure "Enroll Resources" to help users find their way through it. This PR was more of a rough-and-ready move that prioritized reducing the size of the sidebar.

**Pull request merged**
