### PR TITLE
[v13] - differentiate discovered resource names

### PR DESCRIPTION
**Pull request by jentfoo**
~~v13 Backport of PRs #28845 #30086 and #30054.  These PR's build on each other and include refactoring that makes it best to backport them together.~~

Backports fetcher refactoring from #28845 to branch/v13 without the renaming scheme applied

### CODE REVIEW

**Review by zmb3 — APPROVED** [review]

**Review by gabrielcorado — APPROVED** [review]

**Comment by jentfoo** [comment]
I discussed this with @greedy52 in DM.  We may not want to bring all these changes in the backport.  He is going to help review and dissect this PR.

**Review by greedy52 — CHANGES_REQUESTED** [review]
@GavinFrazar I don't think #28845 should be backported. Could you confirm?


As discussed with @jentfoo , at the mean time, I will try backport the refactoring change separately

**Comment by greedy52** [comment]
backport of https://github.com/gravitational/teleport/pull/30086:
- https://github.com/gravitational/teleport/pull/30461

No conflict for #30054 after this one ⬆️

**Comment by GavinFrazar** [comment]
> @GavinFrazar I don't think #28845 should be backported. Could you confirm?
> 
> As discussed with @jentfoo , at the mean time, I will try backport the refactoring change separately

yes please don't backport the renaming stuff

**Comment by greedy52** [comment]
> > @GavinFrazar I don't think #28845 should be backported. Could you confirm?
> > As discussed with @jentfoo , at the mean time, I will try backport the refactoring change separately
> 
> yes please don't backport the renaming stuff
> 
> edit: you can keep the changes from that PR, just remove `renaming.go`, `renaming_test.go` and all references to the `Apply...Suffix` funcs.
> 
> edit: applied in [3c5e686](https://github.com/gravitational/teleport/pull/30456/commits/3c5e68607ea69ce776b2c54b772e0d6013bfa252)

Thanks for removing the renaming. I think we can either merge this one, or #30461 + #30462

**Review by greedy52 — APPROVED** [review]

**Comment by GavinFrazar** [comment]
how about we merge #30461  and #30462 and then rebase this one onto those, just to pull the refactored fetchers into v13 (to make future backports easier)

**Pull request merged**
