### PR TITLE
Fix header levels in the authorization docs page

### PR DESCRIPTION
**Pull request by bl-nero**

### CODE REVIEW

**Review by alexfornuto — APPROVED** [review]

**Comment by alexfornuto** [comment]
Thanks for the fix @bl-nero! Because of our CI/CD security I'll need to make/merge a buddy PR to merge your commit.

**Comment by zmb3** [comment]
Alternatively, just wait a couple days until @bl-nero is added to the gravitational org.

**Comment by alexfornuto** [comment]
> Alternatively, just wait a couple days until @bl-nero is added to the gravitational org.

Couldn't have known that.

**Review by ptgott — APPROVED** [review]

**Comment by ptgott** [comment]
@bl-nero Welcome to Teleport!

**Pull request closed without merging**
