### PR TITLE
Add support to configure `tsh` directory for data 

### LINKED ISSUE #3375: Configurable home location for tsh configuration and data
**What happened**:

> Configurable home location for tsh configuration and data. For example on Linux it would be default as "tsh -C /home/oliver/.tsh". However the use case is actually for Windows where we have systems that have home folder on a network drive that is cross mounted from Linux systems, but the Windows AppData and other default home locations are not to be used.

**What you expected to happen**:
As part of https://github.com/gravitational/teleport/issues/3089 we should provide options to set `TSH_CONFIG_FILE` as an environment variable.   TBD final design and UX

### PR DESCRIPTION
**Pull request by quinqu**
### Purpose 

This PR adds support for configurable home location for `tsh` configuration and data. 

### Implementation 

Read in environment variable (if there is one) and store `tsh` data in configured path. 

Fixes #3375

### CODE REVIEW

**Comment by russjones** [comment]
Please add test coverage to this PR.

**Review by fspmarshall — COMMENTED** [review]
Looks like `.tsh` is always being appended to the custom path.  Is there a specific reason for this?  Seems unnecessary and potentially confusing to me.  I think it would be better if we used the path specified by the user directly.  Especially since `.tsh` is a hidden directory, meaning that users would likely believe that their custom path simply wasn't being set if no visible changes appear in their target directory.

**Comment by quinqu** [comment]
@fspmarshall there was not a specific reason for it, I was just following the default, storing profiles in a hidden directory, but I can remove the appending of `.tsh`.

**Comment by fspmarshall** [comment]
@quinqu Makes sense.  Lets do that.  I think it'll be more intuitive.

**Review by fspmarshall — APPROVED** [review]

**Review by xacrimon — APPROVED** [review]

**Review by russjones — APPROVED** [review]
Bot.

**Pull request merged**
