### PR TITLE
Split RDS Proxy guides per protocol

### LINKED ISSUE #32318: Align RDS proxy Database Access support per protocol
## Applies To

https://goteleport.com/docs/database-access/guides/rds-proxy/

## Details

Split RDS Proxy docs per database protocols [mysql,postgres,mssql] for better discoverability. 

Currently the RDS proxy docs focus on RDS MySQL where postgres,mssql access is only mentioned and Teleport SQLServer RDS proxy integration is not explicitly marked in our docs page.

### PR DESCRIPTION
**Pull request by gabrielcorado**
Related to #32318.

Creates one page per protocol supported by RDS proxy integration. The pages have the same contents.

Note: One AWS console image relates to MySQL (the only difference is the authentication mechanism). I couldn't find a good way of changing this image depending on the protocol, so I'm leaving them as it is for now.

### CODE REVIEW

**Review by ptgott — COMMENTED** [review]
Would you mind providing more context about why we're making this change?

Since the content of the guide we're splitting will not have changed, I'm wondering if we need to make the split. We can think about better clarifying the databases that a user will be able to configure access to by following the guide. For example, we can mention the supported databases in the introductory section of the page.

One downside of increasing the number of pages in `/database-access/guides` is that this section already includes a ton of pages. On my 4k monitor with the default display setting, the "Guides" section almost encompasses the entire docs sidebar.

**Comment by zmb3** [comment]
@ptgott more context here: https://gravitational.slack.com/archives/C02MEM3K2BA/p1695311709220009

**Review by ptgott — APPROVED** [review]
Approving. Assuming users tend to search for "AWS RDS Proxy" in the context of a specific database, this will give us an SEO boost.

**Comment by ptgott** [comment]
@gabrielcorado Are we backporting this, or is this slated for v15?

**Review by smallinsky — APPROVED** [review]

**Pull request merged**
