### PR TITLE
[v12] chore: Bump protoc-gen-go and protoc-gen-grpc-go

### PR DESCRIPTION
**Pull request by codingllama**
Update to versions 1.30.0 and 1.3.0, respectively.

* https://github.com/protocolbuffers/protobuf-go/releases/tag/v1.30.0
* https://github.com/protocolbuffers/protobuf-go/releases/tag/v1.29.1
* https://github.com/protocolbuffers/protobuf-go/releases/tag/v1.29.0
* https://github.com/grpc/grpc-go/releases/tag/cmd%2Fprotoc-gen-go-grpc%2Fv1.3.0

This does bring codegen changes, but generated code is functionally equivalent.

Backports #22976 to branch/v12.

### CODE REVIEW

**Comment by codingllama** [comment]
This will likely require the same dance as https://github.com/gravitational/teleport/pull/22976, but I think that's easier to achieve on `branch/v12`.

**Review by rosstimothy — APPROVED** [review]

**Review by mdwn — APPROVED** [review]

**Comment by codingllama** [comment]
I've been thinking, I could push this one as 2 separate PRs - the buildbox change and then the updated protos, or I could do the on.pull_request dance. I'm kind of leaning towards the former here. WDYT? @mdwn @rosstimothy

**Comment by codingllama** [comment]
Ping @mdwn and @rosstimothy? Any thoughts on the last comment?

**Comment by codingllama** [comment]
I'll prepare the 2-step, I think I prefer that to the buildbox dance.

**Comment by codingllama** [comment]
Mailed https://github.com/gravitational/teleport/pull/23545, will change base to branch/v12 once this lands. PTAL.

**Pull request merged**
