### PR TITLE
Backport branch32 fix 3252

### PR DESCRIPTION
**Pull request by klizhentas**

### CODE REVIEW

**Review by russjones — APPROVED** [review]

**Review by r0mant — APPROVED** [review]

**Comment by klizhentas** [comment]
retest this

**Comment by klizhentas** [comment]
retest this

**Comment by klizhentas** [comment]
retest this

**Comment by klizhentas** [comment]
retest this

**Comment by klizhentas** [comment]
retest this

**Comment by klizhentas** [comment]
retest this please

**Pull request merged**
