### PR TITLE
Address problems in concurrent sqlite access

### LINKED ISSUE #10332: CA rotation is unstable
### Description

While investigating a flaky test, `TestRotateTrustedClusters`, it appears the root cause is that CA rotation is unstable. Graceful restarts may also be unstable for same reasons outlined below.

`TestRotateTrustedClusters` frequently fails while waiting for the Teleport service to reload. Service reloading is needed during CA rotation to allow for picking up of new certificates. _Note: service here means the function run within a Teleport process by the supervisor._ 

https://github.com/gravitational/teleport/blob/0534d43/integration/integration_test.go#L3926
https://github.com/gravitational/teleport/blob/0534d43/lib/service/supervisor.go

The problem is all encapsulated in `waitAndReload`. During each phase of CA rotation this function is called and it starts a new Teleport process, waits for it to start, then shuts down the old Teleport process. This test often fails with the error `database is locked.`

https://github.com/gravitational/teleport/blob/master/lib/service/service.go#L527-L601

What happening is the following:

* The tests use a sqlite backend for auth.
* The initial service create a sqlite database and sets `db.SetMaxOpenConns(1)` to allow multiple goroutines to use sqlite at the same time.
* During CA rotation a new auth service is started before the old one is shut down.
* Two different services are trying to access sqlite at the same time but not using the same `db`.
* Both reading is fine, one writing and the other reading is fine, but when both try and write this test times out.
* The write that consistently gets `TestRotateTrustedClusters` to fail are in resource migration during auth initialization.

https://github.com/gravitational/teleport/blob/0534d43/lib/backend/lite/lite.go#L155
https://github.com/gravitational/teleport/blob/0534d43/lib/auth/init.go#L486-L494
https://www.sqlite.org/faq.html#q5

### Resolution

Above I've outlined issues with the sqlite backend which means this might only be a test issue because production deployments use etcd or DynamoDB.

However, I don't think this is the case (but @fspmarshall should confirm). It might be that auth is more stable in production deployment, but proxies and nodes often use a sqlite cache which would have the same issues outlined above, but perhaps less pronounced. In addition all components use sqlite for process identity which would have the same issues.

The fix appears to be simple: create `db`'s for the backend, cache, and process identity as the first step during process initialization so the same db can be passed to the new service during reloading. This will allow all requests to sqlite to be correctly serialized.

I suspect graceful restart has the same issue, but it's unclear how the resolve the issue for graceful restarts because that involves two processes which prevent the above solution from working.

### PR DESCRIPTION
**Pull request by espadolini**
This PR addresses an issue related to our use of sqlite during restarts, both in-process (typically as a result of CA rotation) and across processes (as a result of a user-initiated graceful restart, with SIGHUP or SIGUSR2/SIGQUIT): the sqlite backend can't handle multiple processes working over the same database, as the "busy" error that's returned when a transaction must be retried due to concurrent access is treated as a fatal database error.

The issue is fixed by changing a `go-sqlite3` parameter that changes how locks are acquired in transactions; by starting every transaction with `BEGIN IMMEDIATE`, the write lock is acquired unconditionally at the very beginning of the transaction, so there's never any need for a forced rollback and the busy timeout can handle concurrency while multiple processes are handling the same database (which only happens during restarts).

In addition, this PR cleans up some of the sqlite backend code (including the removal of in-memory sqlite, which has significantly worse performance than our radix tree in-memory backend), adds a way for users to specify the [journal mode](https://www.goodreads.com/book/show/29437996) for sqlite auth backends, and sets the sync mode for process storage to `FULL`, as process storage is quite important and seldom written to (a corrupted process storage db requires wiping the db and rejoining the cluster with a token).

No changes are made to the default sync mode of `OFF` and to the default journal mode (not specified by the code, and thus defaulting to the deferred `DELETE` mode) which applies both to test code that spawns sqlite backends and, more importantly, to sqlite auth backends, because of performance concerns; we ought to document that "light" production use with the sqlite backend should specify a stronger filesystem sync mode, however.

Partially fixes the sqlite issues in #10332, #9815, #5083 and most other occurrences of `database is closed`, however our use of the same cache backend storage across restarts is still problematic, and will be addressed in #11022.

### CODE REVIEW

**Comment by programmerq** [comment]
@espadolini is it possible that this will also address #5083?

**Comment by espadolini** [comment]
Hopefully yes; if the underlying cause is the same (and I think it is), it should also get fixed by this. There's still some other problems that we'll address in this PR related specifically to caches rather than just the backend, which could also be contributing to the issue.

**Comment by espadolini** [comment]
After just 06442679abd2e118c9f4a1b5c98be39de292eec6 I still got a failure after about 300 runs of `TestIntegrations/RotateTrustedCluster` (massive improvements over the spurious failures after 5 or so runs); with 7e7459508078277440868be15659fccef2364ea0 I'm at 1300 successful runs and counting.

**Comment by xacrimon** [comment]
Otherwise LGTM

**Review by xacrimon — DISMISSED** [review]

**Comment by espadolini** [comment]
Cache directory cleanup while a sqlite database is still open can cause errors during `(*TeleportProcess).Close()`, as shown by repeatedly testing `RotateTrustedCluster` in on-disk cache mode; it might be possible to just try to delete the directory a few times while `RemoveAll` reports `unlinkat datadir/cache-XXXX/component: directory not empty`.

**Comment by espadolini** [comment]
Split off the cache changes in #11022 to better address concerns about cold starts and restarts while auth is not available there.

**Review by rosstimothy — APPROVED** [review]

**Review by xacrimon — APPROVED** [review]

**Pull request merged**
