### PR TITLE
docs: remove duplicate content in oracle guide

### PR DESCRIPTION
**Pull request by stevenGravy**
Only required to backport to `branch/v12` and `branch/v13`

### CODE REVIEW

**Review by smallinsky — APPROVED** [review]

**Review by pschisa — COMMENTED** [review]
The step numbers are off now.  looks like step 3 was always missing too

**Comment by stevenGravy** [comment]
> The step numbers are off now. looks like step 3 was always missing too

thanks, fixed!

**Review by pschisa — COMMENTED** [review]
I think the numbers are still off, we are missing step 3 and there is still a step 7/7

**Comment by stevenGravy** [comment]
> I think the numbers are still off, we are missing step 3 and there is still a step 7/7

Yes, there's only 6 steps, fixed correctly!

**Review by pschisa — APPROVED** [review]
lgtm

**Review by ptgott — COMMENTED** [review]
Does this still include the `install-linux.mdx` partial for installing Teleport on the Database Service host?

**Comment by stevenGravy** [comment]
> Does this still include the `install-linux.mdx` partial for installing Teleport on the Database Service host?

Yes, it's still there. the step was duplicated. 
image

**Comment by stevenGravy** [comment]
> > Does this still include the `install-linux.mdx` partial for installing Teleport on the Database Service host?
> 
> Yes, it's still there. the step was duplicated. image

That step removed also did not include the `teleport configure` which is in the step left in

**Review by ptgott — APPROVED** [review]

**Pull request merged**
