### PR TITLE
Complete empty uploads

### PR DESCRIPTION
**Pull request by zmb3**
The upload completer scans for uploads that need to be completed,
likely due to an error or process restart. Prior to this change,
it only completed uploads that had 1 or more parts. Since completing
an upload is what cleans up the directory on disk, it was possible
for us to leave behind empty directories for uploads with no parts.

This change makes it valid to complete uploads with no parts, which
ensures that these directories get cleaned up.

In addition, the upload completer checks the upload for a session.end
event, and emits one if there is not already an end event present.
This logic only handled session.end, and not
windows.desktop.session.end, so that has been updated as well.

Updates #9646

### CODE REVIEW

**Review by greedy52 — APPROVED** [review]

**Review by fspmarshall — APPROVED** [review]
Code looks good, but I'm fairly certain that a multipart upload with zero parts is rejected by the s3 API.  Please verify against s3 before merging.

**Review by fspmarshall — APPROVED** [review]

**Comment by zmb3** [comment]
Note to myself and others, please do not squash these commits - they were intentionally rebased and separated this way because some of them need to be backported further than others.

**Comment by russjones** [comment]
@zmb3 Looks like this was approved, can you merge?

**Comment by zmb3** [comment]
> @zmb3 Looks like this was approved, can you merge?

Just waiting on tests to pass. Rotate trusted clusters is still a bit flaky.

**Pull request merged**
