### PR TITLE
Updated saml.md.

### PR DESCRIPTION
**Pull request by russjones**
**Purpose**

Updated SAML docs and included a few more images.

**Implementation**

n/a

### CODE REVIEW

**Comment by russjones** [comment]
@gravitational-jenkins test this please

**Comment by russjones** [comment]
@gravitational-jenkins test this please

**Comment by russjones** [comment]
@gravitational-jenkins test this please

**Comment by russjones** [comment]
@gravitational-jenkins test this please

**Review by klizhentas — APPROVED** [review]

**Pull request merged**
