### PR TITLE
Remove "namespace" parameters from various helpers

### PR DESCRIPTION
**Pull request by codingllama**
Remove the namespace parameters from various helpers that flow into authz checks.

This serves a dual purpose:

1. Simplify existing code
2. Make it clearer when only apidefaults.Namespace is used

I've painstakingly followed the changed calls to make sure they always passed apidefaults.Namespace as the parameter, so assuming I didn't miss anything this PR is largely a noop.

Exceptions to the above are on commit 86943f6dac6fe104deaefaefdcef507928c3efa4 - Nodes/Servers already don't accept non-"default" namespaces (see ae99259f41276f9261592068c8c9ae8f17f8b781) and "saml_idp_service_provider" seems to be only following the surrounding code (as in it doesn't really work for non-default namespaces).

After the changes it's clear that only 14-ish calls to ServerWithRoles.actionNamespace remain. These are largely contained to Nodes/Servers, Apps and Databases, the older Teleport resources that use namespaced storage keys.

#49509

### CODE REVIEW

**Comment by codingllama** [comment]
I suggest reviewing commit-by-commit, as it should make the changes more obvious.

**Comment by codingllama** [comment]
Rebased onto fresh master to fix a few newly-added tests.

**Comment by codingllama** [comment]
Friendly ping @Joerger @rosstimothy @fspmarshall ?

**Review by fspmarshall — APPROVED** [review]

**Review by Joerger — APPROVED** [review]

**Comment by codingllama** [comment]
Thanks!

**Pull request merged**
