### PR TITLE
Add imagePullSecrets to predeploy tests

### PR DESCRIPTION
**Pull request by ebdekock**
Follow up from this PR: https://github.com/gravitational/teleport/pull/23927/

They added imagePullSecrets to the deployments, but not the test jobs. This fixes it so that all pods will be able to pull the docker images from a private repo.

### CODE REVIEW

**Review by r0mant — APPROVED** [review]
@hugoShaka Mind taking a look at this as well?

**Review by hugoShaka — APPROVED** [review]

**Comment by ebdekock** [comment]
Thanks for the approvals! How do I proceed/get this merged? :)

**Comment by ebdekock** [comment]
@jimbishopp @klizhentas @russjones @zmb3 Sorry for the mass ping, would one of you be able to assist in reviewing/approving so I can merge this in? Please let me know if theres something else I should be doing to get this merged!

```
2023/07/24 08:09:46 Workflow check failed: at least two approvals required from [jimbishopp klizhentas r0mant russjones zmb3]
```

**Comment by zmb3** [comment]
@hugoShaka can you buddy this one?

**Comment by hugoShaka** [comment]
Hi @ebdekock,
Thanks for your contribution. We are currently unable to run our tests on
external contributions. As such, I'll be helping you validate and
merge your pull request. I've created an internal PR here: https://github.com/gravitational/teleport/pull/30125

**Pull request closed without merging**
