### PR TITLE
docs: Clarify language around outbound IPs used

### PR DESCRIPTION
**Pull request by webvictim**
We didn't use the word "outbound" anywhere in this heading, so it wasn't obvious that it meant a different thing to the one below.

All other changes are my editor trimming whitespace.

### CODE REVIEW

**Review by stevenGravy — APPROVED** [review]

**Comment by zmb3** [comment]
IMO this is more confusing than it was before.

_Outbound IPs used by Teleport Cloud_ sounds like things that Teleport Cloud would connect to.

This is the opposite.

**Comment by webvictim** [comment]
> Outbound IPs used by Teleport Cloud sounds like things that Teleport Cloud would connect to.

Well, that's because that's exactly what I thought it meant.

So this list is essentially every IP that `<x>.teleport.sh` might resolve to?

**Comment by zmb3** [comment]
> So the list in ips.mdx is essentially every IP that <x>.teleport.sh might resolve to?

Yes, that's correct. These are outbound IPs from the perspective of the customer's infra, but they are inbound from the perspective of Teleport Cloud

**Review by zmb3 — APPROVED** [review]
Looks better now, thanks.

**Review by tenaciousdlg — APPROVED** [review]

**Pull request merged**
