### PR TITLE
(4.1) Fix CreateWebSession method.

### PR DESCRIPTION
**Pull request by r0mant**
https://github.com/gravitational/teleport/pull/3076 port.

### CODE REVIEW

**Review by russjones — APPROVED** [review]

**Comment by r0mant** [comment]
retest this please

**Comment by r0mant** [comment]
retest this please

**Comment by r0mant** [comment]
retest this please

**Comment by r0mant** [comment]
retest this please

**Comment by r0mant** [comment]
retest this please

**Pull request merged**
