### PR TITLE
Release 4.4.0-alpha.1

### PR DESCRIPTION
**Pull request by webvictim**

### CODE REVIEW

**Review by awly — APPROVED** [review]

**Comment by awly** [comment]
We already have a 4.4 branch?
Let the backports begin! :grimacing:

**Comment by webvictim** [comment]
It's hot off the press! :fire:

**Comment by klizhentas** [comment]
@webvictim @russjones What do you folks think about cutting off branch/x after we roll the final release, not alpha to keep it easier for development

**Comment by webvictim** [comment]
I like the idea, it's easy enough to do that.

**Comment by awly** [comment]
@klizhentas we'll have to be careful not to merge any non-trivial PRs while doing release testing.
But this eliminates the toil of backports and the risk of forgetting them.

**Comment by webvictim** [comment]
I'd say we cut alphas and betas from `master`, then cut `branch/4.4` once we're ready for `4.4.0-rc.1`. The question is at what point we execute the full test plan.

**Comment by klizhentas** [comment]
@webvictim we should execute the test plans from tags, not a branch. SO for now we are continuing to use master for 4.4 before we cut rc.1 then cc @fspmarshall @awly @webvictim @russjones

**Comment by webvictim** [comment]
retest this please

**Comment by webvictim** [comment]
retest this please

**Pull request merged**
