### PR TITLE
Add v8 to older-versions docs page

### PR DESCRIPTION
**Pull request by avatus**
Includes v8 on the [older versions](https://goteleport.com/docs/older-versions/) docs page in prep for v11 release.

### CODE REVIEW

**Comment by avatus** [comment]
In the future, I'd like to work on something for the docs to have "default" pages that do not differ from branch to branch. There would be one source of truth regardless (master) regardless of the currently viewed branch. That would eliminate any backporting needed for stuff like this.

**Review by nklaassen — APPROVED** [review]

**Review by greedy52 — APPROVED** [review]

**Review by alexfornuto — APPROVED** [review]
I disabled auto-merge since this PR should likely sit until V11 stable is released.

**Comment by nklaassen** [comment]
> I disabled auto-merge since this PR should likely sit until V11 stable is released.

we've already removed v8 from the version dropdown on the live site, we should either add it back or merge this imo

**Comment by avatus** [comment]
I think merging this is fine. That way there is a way to view v8 docs (even if its just a link to the github branch). v11 will be out today anyway.

**Pull request merged**
