### PR TITLE
Fix issue "redis" engine is not registered

### PR DESCRIPTION
**Pull request by greedy52**
Error when connecting Redis database
```
Original Error: *trace.NotFoundError database engine &#34;redis&#34; is not registered
```

Related PR
- #18776

(interestingly, this is not caught by test, likely because test has different importing path)

### CODE REVIEW

**Review by smallinsky — APPROVED** [review]
Does the init call was for redis engine in previous version was called from https://github.com/gravitational/teleport/pull/18776/files#diff-054e31280a78f4aea4759cd740f8d8bcecf563679d7fe6b79991fdb944e8c611L64 ? 

LGTM to me though I think that we should clean when and how our db engines are registered to prevent this to happen again.

**Comment by greedy52** [comment]
> Does the init call was for redis engine in previous version was called from
No. My guess was we were calling `redis.ParseRedisAddress` before so the `redis` lib gets implicitly inited. With that change, the new `connection.ParseRedisAddress` is used instead so we have to explicitly import the lib now.

 > LGTM to me though I think that we should clean when and how our db engines are registered to prevent this to happen again.
Agreed. The test didn't catch the problem as the test has to import redis for other setups. Need to ensure this won't happen again. How about checking if every engine type is registered at server start?

**Review by zmb3 — APPROVED** [review]

**Comment by smallinsky** [comment]
> Agreed. The test didn't catch the problem as the test has to import redis for other setups. Need to ensure this won't happen again. How about checking if every engine type is registered at server start(or New)?

Yes that will work but I wonder if we can be more explict  and insteam of calling `_ db/engine/import`   we can just init everything from one place like: 
```
// db/server.go
func init() {
  common.RegisterEngine(redis.NewEngine, defaults.ProtocolRedis)
  common.RegisterEngine(msql.NewEngine, defaults.ProtocolMySQL)
}
```

and makes things more readable.

**Comment by greedy52** [comment]
> Yes that will work but I wonder if we can be more explict and insteam of calling `_ db/engine/import` we can just init everything from one place like:
> 
> ```
> // db/server.go
> func init() {
>   common.RegisterEngine(redis.NewEngine, defaults.ProtocolRedis)
>   common.RegisterEngine(msql.NewEngine, defaults.ProtocolMySQL)
> }
> ```
> 
> and makes things more readable.

@smallinsky really like that. Will do that separately. The test registers  fake engine in `init()` so need to make sure the ordering.

**Pull request merged**
