### PR TITLE
Add initial saml support

### PR DESCRIPTION
**Pull request by tidalf**
as (briefly) described in #797 this pr implement initial saml support with the help of github.com/crewjam/saml library.

it's tested with Microsoft ADFS and seems to work quite well with a few tests from different users, including tsh logins from osx and linux.
There is no real big design choices, it's mainly a duplicate and rename of oidc to saml.

tell me if you could merge it or if it needs more work.
Thanks!

### CODE REVIEW

**Comment by klizhentas** [comment]
@tidalf thanks a lot for your PR. This looks very promising. We will review it and will send comments ASAP. Currently team is focusing on pushing 2.0 in the next couple of days, once we release 2.0 we will try to get this into 2.1 release.

**Comment by tidalf** [comment]
congratz for the 2.0 release :) I love it. this pr is rebased on the the 2.0.0 release commit

**Comment by klizhentas** [comment]
@tidalf thanks! Our plan is to work on your SAML integration into 2.1 which is upcoming release.

**Comment by russjones** [comment]
@tidalf Great work, Can you rebase off master and resolve conflicts?

**Comment by tidalf** [comment]
thanks ! It's rebased

**Comment by klizhentas** [comment]
ok to test

**Comment by Oneiroi** [comment]
I think this PR needs rebasing again ?

**Comment by tidalf** [comment]
Hello :)
Something I could do (apart regular rebasing) to help ?

**Comment by klizhentas** [comment]
@tidalf 

We have decided to roll out different implementation from the on you have submitted that will be only available in the enterprise version of Teleport.

The core library part is available in the OSS and you can see the work on it here: 

https://github.com/gravitational/teleport/compare/sasha/saml2

We are currently doing pen tests and integration tests on behalf of our customers for our implementation.

We would like to offer you several options though as it's not nice to just reject your work:

* We can give you free enterprise license so you can simply use our SAML implementation as a reward for your effort

* You can use teleport as a library, and compile your version of `teleport` binary with configuration exposed to maintain on your own.

We had discussions internally on how to handle these cases better in the future and have come up with the idea of community supported plugins - we would like to make core of teleport easily extendable so folks can maintain their community versions of everything. If you are interested to participate in adding auth plugins support to teleport, let me know and we will work with you on this - your SAML version can be the first auth plugin available as a community-managed effort.

Thanks for understanding - we have to control core SAML piece though as we are investing both engineering and pen test resources for our commercially supported versions.

**Comment by tidalf** [comment]
Hello @klizhentas, 

I completely understand your decision.

Since we love your product here, we'd be happy to get a free license, tell me how to proceed.
Thanks a lot !

And to finish I'd also be glad to try and adapt the saml to your future auth plugin framework, tell me how I can contribute :)

**Comment by klizhentas** [comment]
@tidalf can you send me your email to sasha@gravitational.io and I will set it all up!

**Comment by tidalf** [comment]
Thanks you, so let's close this PR.

**Pull request closed without merging**
