### PR TITLE
[v15]: Backport the new wizard for adding authentication devices

### PR DESCRIPTION
**Pull request by bl-nero**
This is a combined backport of the following pull requests:
* #37747 
* #38100 
* #38260 
* #38353 
* #38393 

There was 1 conflict to resolve - between #38393 and #37743. The conflict appeared in the code that is being removed, as the conflicting PR was a bugfix on the old dialog. The conflict was resolved by removing the file.

**Do not submit** until tested by @avatus.

Contributes to https://github.com/gravitational/teleport/issues/37616

Changelog: Updated the dialog for adding new authentication methods in the account settings screen.

### CODE REVIEW

**Comment by bl-nero** [comment]
@avatus To test it, please go to the account settings screen and try adding passkeys and MFA devices. Make sure that you can verify your identity using various methods. Corner cases:

- A user that doesn't have _any_ MFA device or passkey registered (possible if MFA is set to optional in the auth server settings), in which case there should be no verification step.
- Passkeys disabled in the auth server settings (`auth_service.authentication.passwordless` set to `false`
- MFA turned off completely (`auth_service.authentication.second_factor` set to `"off"`).

**Comment by avatus** [comment]
I tested as many paths as I could think of and didn't run into anything that seemed out of the ordinary. So, LGTM.

a couple things that errored for me (but i believe are expected and/or my fault)
1. how do i log in as a user without a key if i already have a user created and then passwordless/mfa is turned on? my guess is this wouldn't happen in a normal deployment and would probably have to do a "set to optional and then have a deadline for everyone to add". so, not part of this project
2. i added an mfa device and it wouldn't let me have the same name as my passwordless device. which makes sense i guess but just pointing it out

**Review by avatus — APPROVED** [review]

**Comment by bl-nero** [comment]
Thank you, @avatus!

> 1. how do i log in as a user without a key if i already have a user created and then passwordless/mfa is turned on? my guess is this wouldn't happen in a normal deployment and would probably have to do a "set to optional and then have a deadline for everyone to add". so, not part of this project

Yeah, we have never supported this scenario in any way other than relying on internal processes in users' organizations.

> 2. i added an mfa device and it wouldn't let me have the same name as my passwordless device. which makes sense i guess but just pointing it out

That's a good point. I'll look into it, but my gut says it's not worth changing the data model constraints just because of this.

**Review by gzdunek — APPROVED** [review]
I haven't tested it and only went over the commits, everything appears to be fine.

**Pull request merged**
