### PR TITLE
Update MongoDB Driver to master commit

### PR DESCRIPTION
**Pull request by jentfoo**
This updates the MongoDB driver to use a recent master commit in order to incorporate the fix: https://github.com/mongodb/mongo-go-driver/pull/1291 (which has not been released to a tag yet)

In addition a fuzz seed was added to cover this condition.  After not finding more issues this also re-enables the MongoDB fuzzing in oss-fuzz.

This should be the last change needed to resolve https://github.com/gravitational/security-findings/issues/21

### CODE REVIEW

**Review by codingllama — APPROVED** [review]

**Review by r0mant — COMMENTED** [review]
Overall no objections but I would like to ask database access team to verify it doesn't break MongoDB access before merging, esp. considering we're upgrading to a pre-release version. cc @smallinsky @greedy52

**Comment by greedy52** [comment]
I couldn't find this `v1.13.0-prerelease.0.20230726045955-5ee10b94cc66` from the public repo. Do we know when the official release will happen? Seems they release frequently.

**Comment by jentfoo** [comment]
> Do we know when the official release will happen? Seems they release frequently.

@greedy52 It is a commit on master.  I have been waiting for over a month for a release tag.  I wish they had a release as well, but I don't think depending on a commit is a huge deal.  It is important that we include this update before the Teleport 14 release, and it would be nice to finish re-enabling oss-fuzz and closing out the remaining work that has been waiting on this release.

**Comment by greedy52** [comment]
i see. so we got unlucky that your change didn't make it to v1.12.0 and they used to release every month but it didn't happen in July. I will approve it but I think we should replace it with an official release if that happens before v14 testing.

**Review by greedy52 — APPROVED** [review]

**Comment by jentfoo** [comment]
@rosstimothy No backports needed on this one.  The version increase in this PR looks minor, but that is because I did a major version update in #27429.  As discussed in that PR, that version increase drops support for older MongoDB servers.  For that reason this update will be first introduced in Teleport 14.

**Comment by jentfoo** [comment]
> I think we should replace it with an official release

Absolutely, this is just a short term solution to ensure we get an update in Teleport 14.  Thank you for the help!

**Pull request merged**
