### PR TITLE
add TLS routing support to helm chart

### PR DESCRIPTION
**Pull request by bcg62**

### CODE REVIEW

**Review by webvictim — COMMENTED** [review]
@bcg62 Thanks for the PR. There are a few requests before we can merge:

1. Please add `proxyListenerMode` at the appropriate location in the teleport-cluster chart reference: https://github.com/gravitational/teleport/blob/master/docs/pages/kubernetes-access/helm/reference.mdx

2. Please add `proxyListenerMode` to https://github.com/gravitational/teleport/blob/master/examples/chart/teleport-cluster/values.schema.json

3. Please add an example which sets `proxyListenerMode` so it can be validated by the linter - see other examples in https://github.com/gravitational/teleport/tree/master/examples/chart/teleport-cluster/.lint

Thank you!

**Comment by bcg62** [comment]
@webvictim no problem, done.

**Comment by russjones** [comment]
@bcg62 We're good to go once @webvictim approves.

**Review by webvictim — APPROVED** [review]

**Comment by russjones** [comment]
Will buddy merge in https://github.com/gravitational/teleport/pull/9484.

**Pull request closed without merging**
