### PR TITLE
Cleanup `regular.Server`

### PR DESCRIPTION
**Pull request by ibeckermayer**
Out of curiosity I was hunting down the codepath that actually starts a shell and I noticed that `regular.Server` had several fields which appear to be defunct. Easiest to confirm that they are indeed defunct commit by commit.

### CODE REVIEW

**Review by GavinFrazar — APPROVED** [review]

**Review by rosstimothy — APPROVED** [review]
Thanks for the clean up! 🧹 🧼 🪣

**Comment by ibeckermayer** [comment]
> /excludeflake *

@zmb3 I'm not sure that this worked, I'm still stuck on a `Flaky Tests Detector` failure. I can't decipher what's actually failed though:

https://github.com/gravitational/teleport/actions/runs/8757586476/job/24036543322?pr=40723

**Comment by GavinFrazar** [comment]
@ibeckermayer looks like our aws e2e test infra failed to recreate the eks test cluster (it's done every sunday): https://teleport.app.spacelift.io/stack/aws-teleport-integration-test-prod/run/01HVZQBEY2GQNNJSVB3NXSG9K0

so that's why you cant merge today.

**Pull request merged**
