### PR TITLE
Add WEBASSETS_SKIP_BUILD to Makefile

### PR DESCRIPTION
**Pull request by jakule**
WEBASSETS_SKIP_BUILD allows skipping webassets build for development purposes. Teleport build in that mode displays a blank page instead of WebUI, but the build is significantly faster.

`make full` - always builds webassets
`make WEBASSETS_SKIP_BUILD=0` - works the same as `full`
`make WEBASSETS_SKIP_BUILD=1` - skips webassets build.

### CODE REVIEW

**Review by timothyb89 — APPROVED** [review]
Seems to work well on my machine.

**Comment by hatched** [comment]
While not specifically caused by this branch, this change exposes an issue where the UI dev server will not load if the Teleport binary is built without webassets. I'm just adding a note here while I debug this issue so we don't land this change until this is investigated.

**Comment by hatched** [comment]
The UI devserver serves the index file from the Teleport binary which fetches the necessary configuration values. So I changed this to copy over that index file instead of serving an empty `index.html`.

**Review by hatched — APPROVED** [review]

**Comment by jakule** [comment]
@hatched Thanks for the fixes.

**Pull request merged**
