### PR TITLE
Replace deprecated duo-labs/webauthn with go-webauthn/webauthn

### PR DESCRIPTION
**Pull request by tobiaszheller**
Previous library is no longer maintained:
https://github.com/duo-labs/webauthn#this-library-is-deprecated

We are switching to fork out of it, which is now actively maintained.
It is using trimmed down version of cloudflare/cfssl (https://github.com/go-webauthn/revoke) which allows us to drop a lot deps. 

I have tested it with old server + new client, new server + old client, new server + new client on mac.

### CODE REVIEW

**Comment by tobiaszheller** [comment]
@codingllama first PR that can cause issues is https://github.com/go-webauthn/webauthn/pull/82 but it just got merged to master.

**Review by strideynet — APPROVED** [review]

**Review by codingllama — APPROVED** [review]
Many thanks!

**Comment by codingllama** [comment]
A few comments:

1. Let's backport this one as far as possible, as I'd rather not have to deal with library skew for this particular lib. I'll add the tags, but it may be easier to redo it manually because of conflicts. (We could wait for after the testplan for the backports, your call.)

2. Re the commit below, let's try and pull it in soon too. It doesn't look _that_ problematic to me, but I'd rather deal with it before the testplan. It looks like it would break in-flight challenges, so let's note that in our release notes.

> @codingllama first PR that can cause issues is [go-webauthn/webauthn#82](https://github.com/go-webauthn/webauthn/pull/82) but it just got merged to master.

Thanks again for keeping this up to date!

**Comment by codingllama** [comment]
FYI @rosstimothy

**Review by zmb3 — APPROVED** [review]

**Comment by tobiaszheller** [comment]
I will wait with backporting until we test it through testplan

**Pull request merged**
