### PR TITLE
Change EC2 discovery matchers in the fileconfig to include a configuration section

### PR DESCRIPTION
**Pull request by lxea**
Updated the RFD to account for this

Changes the SSH config matchers section from this: 
```yaml
ssh_service:
  enabled: "yes"
  aws:
  - types: ["ec2"]
    regions: ["us-west-1"]
    tags:
      "teleport": "yes" # aws tags to match
    ssm_command_document: ssm_command_document_name
```

To this:
```yaml
ssh_service:
  enabled: "yes"
  aws:
    invite_token: "iam-token-name"
    matchers:
    - types: ["ec2"]
      regions: ["us-west-1"]
      tags:
        "teleport": "yes" # aws tags to match
      ssm_command_document: ssm_command_document_name
```

### CODE REVIEW

**Comment by Tener** [comment]
> Updated the RFD to account for this

Where can I read that?

**Review by r0mant — COMMENTED** [review]
@lxea Why are we changing the fileconfig structure? For respective database access section, we specifically wanted to avoid using "matchers" as it feels like it's spilling out some internal implementation details. It's now also inconsistent with database access section.

Any reason we can't keep the original one?

**Comment by r0mant** [comment]
@lxea Why do we need an IAM token there at all? I thought that Teleport would create a short-lived auth token and parametrize the script with it? Same as you do when you join manually e.g. using `tctl nodes add` command.

**Comment by nklaassen** [comment]
> > @lxea Why do we need an IAM token there at all? I thought that Teleport would create a short-lived auth token and parametrize the script with it? Same as you do when you join manually e.g. using `tctl nodes add` command.
> 
> I'm not sure how to use a shortlived token in that case, I'd suggested it in the RFD originally but I changed it to use an IAM token instead as the endpoint for the script needs to be unauthenticated as AWS doesnt know anything about it when it downloads the script to the ec2 instance, so it seems less than ideal to have it so that anytime anyone calls `/webapi/scripts/installer` it creates a token for whoever wants one

I left a comment on the RFD re: IAM vs EC2 tokens, long story short there are drawbacks to both but it _may_ be easier than using short-lived tokens https://github.com/gravitational/teleport/pull/12410#discussion_r921485851

There is a flow I kind think of to securely use short-lived tokens: make the token a parameter of the SSM script, have the ssh agent generate a new short-lived token for each node (or batch of nodes?) and send it to the instance via `aws:runCommand` as a parameter for the SSM script. Assuming that's possible, I'm not so familiar with SSM. But this way you don't expose any token publicly.

**Comment by r0mant** [comment]
> There is a flow I kind think of to securely use short-lived tokens: make the token a parameter of the SSM script, have the ssh agent generate a new short-lived token for each node (or batch of nodes?) and send it to the instance via aws:runCommand as a parameter for the SSM script. Assuming that's possible, I'm not so familiar with SSM. But this way you don't expose any token publicly.

@nklaassen @lxea Yeah, exactly - this is how I assumed it would work. @lxea since you mentioned before scripts can be parametrized. So we would not pre-populate the script with the token but rather send it as a parameter when executing an SSM document.

**Comment by nklaassen** [comment]
@r0mant @lxea One security consideration we should be very careful about with this approach: we would have to grant the service role `Node` the ability to create provisioning tokens, or create some new service role which is allowed to create provisioning tokens. We should probably avoid giving every ssh node the ability to create tokens in the process, we definitely don't want to allow privilege escalation through this

**Comment by r0mant** [comment]
Yes, only agents doing auto-discovery should have this permission. We can probably intro a new [system role](https://github.com/gravitational/teleport/blob/master/api/types/system_role.go#L33) e.g. `RoleNodeDiscovery` which would be implicitly assumed by nodes that have auto-discovery enabled and grant permissions to create provision tokens.

**Pull request closed without merging**
