### PR TITLE
Add Handler for Generating Join Tokens

### PR DESCRIPTION
**Pull request by atburke**
New handler does the same thing as `tctl tokens add` but for the web UI. Backend implementation of #7537.

### CODE REVIEW

**Comment by russjones** [comment]
@r0mant @kimlisa We have a few questions.

1. Looks like you need `RW` on `KindToken` to use this Database Wizard, what is the expected behavior if the user does not have `RW` on `KindToken`? Do we display an error message and what does that look like?
2. Do we want an installer script like we have to SSH servers that will also pull down the Teleport binary?

**Comment by r0mant** [comment]
@russjones @atburke Good questions!

> Looks like you need RW on KindToken to use this Database Wizard, what is the expected behavior if the user does not have RW on KindToken? Do we display an error message and what does that look like?

Instead of displaying an error message, can we fallback to the current version of the dialog that shows how to generate the token manually?

> Do we want an installer script like we have to SSH servers that will also pull down the Teleport binary?

Eventually, but the scope of this particular issue was only related to the "manual" way.

> The other endpoints for join scripts are Enterprise only, do we want this to be an Enterprise only feature as well?

This particular change is OSS. The installer script, when we have it, we can do Enterprise for consistency with node join script, although didn't we also want to move it to OSS? Seems a little strange to me that it's Enterprise.

**Comment by russjones** [comment]
> Instead of displaying an error message, can we fallback to the current version of the dialog that shows how to generate the token manually?

Hrm, that might be more of a @kimlisa question. @kimlisa I think we pass role information to the web client so we actually know ahead of time which dialog to display right? Any suggestions on how to implement this?

> Eventually, but the scope of this particular issue was only related to the "manual" way.
> This particular change is OSS. The installer script, when we have it, we can do Enterprise for consistency with node join script, although didn't we also want to move it to OSS? Seems a little strange to me that it's Enterprise.

To be honest, feels easier to just make a few changes to the installer script than this approach, anything I am missing?

**Comment by r0mant** [comment]
> To be honest, feels easier to just make a few changes to the installer script than this approach, anything I am missing?

@russjones I thought about this too, however as I kept thinking about it, I wanted to first make these tweaks to the "manual" (as we call it) add dialog for the following reasons:

* Last I looked, updating the installer script is not "just a few changes" unfortunately... It's a monster bash script and adding db support to it didn't seem very trivial to me. Ideally, we'd refactor much of it into Go and leave only a thin bash layer.
* I think that what we call a "manual" way of adding dbs (or server/app/etc.) has its uses. For example, when somebody wants to get the teleport start command and play with the flags, etc. Generating a token as a part of it, on the other hand, seems superfluous - so this would simplify that part.

**Comment by kimlisa** [comment]
> Hrm, that might be more of a @kimlisa question. @kimlisa I think we pass role information to the web client so we actually know ahead of time which dialog to display right? Any suggestions on how to implement this?

Yup. Just let us know when its ready to change. This is what we already do in the front if users don't have access, we just disable the whole button like below, but we can make it so it only shows manual:

image

**Comment by russjones** [comment]
@r0mant That sounds reasonable.

@kimlisa Let's me you and @atburke sync on this tomorrow.

**Comment by russjones** [comment]
@atburke Let's close this PR and re-open when we come back to wizards later.

**Pull request closed without merging**
