### PR TITLE
[v13] Automatically perform `tsh app login`.

### PR DESCRIPTION
**Pull request by Tener**
Backport #26239 and #27108 to branch/v13

### CODE REVIEW

**Review by greedy52 — APPROVED** [review]
BTW, seems the quiet only applies to `tsh proxy app` not `tsh aws`.

**Comment by Tener** [comment]
@smallinsky PTAL. 
@greedy52 I'll raise another PR for the quiet fix, thanks.

**Review by smallinsky — COMMENTED** [review]
@Tener 
LGTM but please don't merge this without the `tsh aws` fix.

**Review by smallinsky — APPROVED** [review]

**Review by greedy52 — APPROVED** [review]
> https://github.com/gravitational/teleport/pull/27108 is merged to master, I have cherry-picked that commit onto this branch, so merging it will apply both https://github.com/gravitational/teleport/pull/26239 and https://github.com/gravitational/teleport/pull/27108 to branch/v13.

Thanks!

**Pull request merged**
