### PR TITLE
Organize docs guide sections chronologically

### PR DESCRIPTION
**Pull request by ptgott**
This change aims to make docs navigation easier by organizing some docs
sections according to the sequence of steps a user would take to set up
Teleport.

The current docs organization uses a variety of categories and schemes
to organize the docs. For example, there is a "Home" section that
includes the Changelog, Installation page, and Getting Started guides; a
"Setup" section that includes references and admin guides; and
edition-specific sections (Enterprise, Cloud). For a user who is setting
up Teleport--or who has already done some setup work and wants more
advanced instructions--it's difficult to know where in the docs to find
the right information.

This change organizes our how-to guides into the following categories
that describe the process of setting up Teleport:

- Try out Teleport
- Deploy a Cluster (including choosing an edition)
- Configure Access (including SSO, RBAC, and Access Requests)
- Manage your Cluster (admin guides, operations, etc.)
- Use Teleport (this section already exists)

I moved the Reference section after this chronology, since users can
access the reference guides anywhere in the setup process.

As part of the change, I have also moved the content from the
"Enterprise" and "Cloud" sections into "Deploy a Cluster", since this
content has to do with how to deploy a specific edition of Teleport.

Note that this change does _not_ attempt to reorganize our
protocol-specific sections. While adding resources is part of the
Teleport setup process, we have a lot of content in our
protocol-specific sections, and moving it all into a single section
related to adding resources to a cluster would (a) exceed the maximum
depth for subsections in the nav bar and (b) cause more confusion than
it alleviates.

### CODE REVIEW

**Comment by ptgott** [comment]
Note to reviewers: I'll update links within docs pages and fix other linting errors after we confirm the new organization.

**Comment by ptgott** [comment]
One question I had is where the SOC 2 guide should go. It's currently in the "Enterprise" subsection, but this isn't quite accurate, as it also applies to Cloud.

**Comment by klizhentas** [comment]
I will take a closer look today, but meanwhile re: SOC2 question:


> One question I had is where the SOC 2 guide should go. It's currently in the "Enterprise" subsection, but this isn't quite accurate, as it also applies to Cloud.

SOC2 and FedRamp are compliance frameworks, they should be in access control section

**Review by klizhentas — APPROVED** [review]
The new layout looks good, I think it creates a good user journey.

**Comment by klizhentas** [comment]
One afterthought - I was trying to find a better name for "Use teleport" section. Technically it's all using teleport. I think a better name would be to "connect your client". Then adding some desktop client manuals for DBs and machines would be relevant there.

**Comment by ptgott** [comment]
@klizhentas I have incorporated your feedback

**Review by zmb3 — APPROVED** [review]
Looks great, sorry for the delay!

**Pull request merged**
