### PR TITLE
[v15] Update latest release in CHANGELOG to correct version

### PR DESCRIPTION
**Pull request by webvictim**
Update latest release to 15.4.11 rather than 15.4.10

### CODE REVIEW

**Comment by ptgott** [comment]
We'll want to forward port this to v16 so the change appears on the docs site as well

**Review by ptgott — APPROVED** [review]

**Comment by webvictim** [comment]
> We'll want to forward port this to v16 so the change appears on the docs site as well

@ptgott Is this expected to be done on every changelog update to `branch/v15` or `branch/v14` as well? I would argue yes, but it's certainly not being done as we're missing entries.

**Comment by ptgott** [comment]
For the docs site, we only need to edit `branch/v16`, since the docs engine only renders the default version of the changelog.

I'm not sure how many users visit the `gravitational/teleport` changelog on `master` or the release branches, but I would agree that we need to keep these up to date if the numbers are significant. I'm working on a small tool to merge different versions of the changelog so we can keep these consistent, and have a PR up to add some releases to v16: https://github.com/gravitational/teleport/pull/44940

**Review by zmb3 — APPROVED** [review]

**Comment by webvictim** [comment]
This PR is no longer needed, the changelog for v15 has since been updated.

**Pull request closed without merging**
