### PR TITLE
Deprecate `site` param in `auth/export` HTTP endpoint

### PR DESCRIPTION
**Pull request by marcoandredinis**
Discussed here
https://github.com/gravitational/teleport/pull/15491#discussion_r1132193887

### CODE REVIEW

**Review by hugoShaka — COMMENTED** [review]
Code LGTM but I can't estimate the implications of the API change

**Comment by zmb3** [comment]
Yeah, we don't really know who is using this or depends on it being at the old location. The best option is probably just to keep both and not delete the original.

**Comment by marcoandredinis** [comment]
This is barely documented, so IMO, removing it in the currentMajor+2 (v14) seems alright.

Well, can I at least keep the `Deprecated` note? :sweat_smile: 
I think it's relevant to let devs know why we have the same handler for both endpoints

**Comment by zmb3** [comment]
Yes, you can keep the deprecated note.

Documented or not, the whole point of this endpoint was for customers to be able to automate setups. We don't want to break their automation.

**Comment by marcoandredinis** [comment]
Done :+1: 

@hugoShaka @zmb3 Can you please take another look?

**Review by zmb3 — APPROVED** [review]
Looks good. Please don't forget to document this too!

**Review by hugoShaka — APPROVED** [review]

**Pull request merged**
