### PR TITLE
New videos for MongoDB and GCP Postgres CloudSQL

### PR DESCRIPTION
**Pull request by benarent**
New videos for MongoDB and GCP Postgres CloudSQL

### CODE REVIEW

**Comment by russjones** [comment]
@benarent Looks good to me, but please wait 1 week (September 15th).

**Review by russjones — APPROVED** [review]
Bot.

**Comment by russjones** [comment]
@benarent We can merge this now.

**Comment by benarent** [comment]
@russjones I was coming to merge and cleanup this PR but it's just failing. Do I need to fast-forward these updates?

**Comment by russjones** [comment]
Will buddy in https://github.com/gravitational/teleport/pull/9304.

**Pull request closed without merging**
