### PR TITLE
gha(amplify-preview): use custom action to generate Amplify previews for Teleport Docs

### PR DESCRIPTION
**Pull request by taraspos**
### Summary

This PR adds new custom workflow which will prepare Amplify preview URLs using custom action [`amplify-preview`](https://github.com/gravitational/shared-workflows/tree/main/tools/amplify-preview) instead of native Amplify's integration with Github because of following problems:
- Hard limit of 50 previews per app[^1]
    [^1]: https://docs.aws.amazon.com/general/latest/gr/amplify.html
- Lack of functionality to filter PRs based on modified path (we need previews only for PRs when `docs/` were modified)
   - https://github.com/aws-amplify/amplify-hosting/issues/3960

Existing `aws-amplify-us-west-2` bot will be disabled separately via AWS APIs.

### Testing 

https://github.com/gravitational/teleport/pull/48512#issuecomment-2548342535

### CODE REVIEW

**Comment by hugoShaka** [comment]
By any chance would it be possible to tweak the job summary to output informations about how/where we can see the amplify deployment result to troubleshoot?

Currently the check indicates

> This check concluded as failure.
>
> `<link to some AWS resource without any AWS account ID so I have no idea in which account I should log in to see this, or if I even have enough rights>`

And I've been unable to find the deployment logs and understand why my PR is red.

**Comment by taraspos** [comment]
> By any chance would it be possible to tweak the job summary to output informations about how/where we can see the amplify deployment result to troubleshoot?
> 
> Currently the check indicates
> 
> > This check concluded as failure.
> > `<link to some AWS resource without any AWS account ID so I have no idea in which account I should log in to see this, or if I even have enough rights>`
> 
> And I've been unable to find the deployment logs and understand why my PR is red.

This makes sense, however the action itself is very generic and I didn't want to include to include any Teleport specific information in there publicly. What we could do is to:
1. Create notion page with debugging information
2. Add step to print link to the notion page in case of failures

**Comment by hugoShaka** [comment]
> > By any chance would it be possible to tweak the job summary to output informations about how/where we can see the amplify deployment result to troubleshoot?
> > Currently the check indicates
> > > This check concluded as failure.
> > > `<link to some AWS resource without any AWS account ID so I have no idea in which account I should log in to see this, or if I even have enough rights>`
> > 
> > 
> > And I've been unable to find the deployment logs and understand why my PR is red.
> 
> This makes sense, however the action itself is very generic and I didn't want to include to include any Teleport specific information in there publicly. What we could do is to:
> 
> 1. Create notion page with debugging information
> 2. Add step to print link to the notion page in case of failures

I think # 2 would be perfect :)

Documenting on Notion is nice but most developpers won't know where to find the page when they see the error. Having a job printing the basic troubleshooting steps (e.g. open AWS account X, go there, check job X) and maybe [surfacing it in the PR with an error message](https://docs.github.com/en/actions/writing-workflows/choosing-what-your-workflow-does/workflow-commands-for-github-actions#setting-an-error-message) would save us a lot of time.

**Comment by taraspos** [comment]
@hugoShaka, done see: https://github.com/gravitational/teleport/actions/runs/12435005179/job/34719898001?pr=48512

image

**Review by hugoShaka — APPROVED** [review]

**Review by r0mant — APPROVED** [review]

**Review by zmb3 — APPROVED** [review]

**Pull request merged**
