### PR TITLE
Bump to libbpfgo v0.2.5

### PR DESCRIPTION
**Pull request by eyakubovich**

### CODE REVIEW

**Comment by russjones** [comment]
@jakule @nklaassen Can you review?

**Comment by nklaassen** [comment]
There are some build errors in CI
```
# github.com/aquasecurity/libbpfgo
/go/pkg/mod/github.com/aquasecurity/libbpfgo@v0.2.5-libbpf-0.7.0/libbpfgo.go:1157:37: could not determine kind of name for C.BPF_TC_CUSTOM
/go/pkg/mod/github.com/aquasecurity/libbpfgo@v0.2.5-libbpf-0.7.0/libbpfgo.go:1155:37: could not determine kind of name for C.BPF_TC_EGRESS
/go/pkg/mod/github.com/aquasecurity/libbpfgo@v0.2.5-libbpf-0.7.0/libbpfgo.go:1163:26: could not determine kind of name for C.BPF_TC_F_REPLACE
/go/pkg/mod/github.com/aquasecurity/libbpfgo@v0.2.5-libbpf-0.7.0/libbpfgo.go:1154:37: could not determine kind of name for C.BPF_TC_INGRESS
/go/pkg/mod/github.com/aquasecurity/libbpfgo@v0.2.5-libbpf-0.7.0/libbpfgo.go:100:9: could not determine kind of name for C.LIBBPF_MAJOR_VERSION
/go/pkg/mod/github.com/aquasecurity/libbpfgo@v0.2.5-libbpf-0.7.0/libbpfgo.go:105:9: could not determine kind of name for C.LIBBPF_MINOR_VERSION
/go/pkg/mod/github.com/aquasecurity/libbpfgo@v0.2.5-libbpf-0.7.0/libbpfgo.go:1260:10: could not determine kind of name for C.bpf_tc_attach
/go/pkg/mod/github.com/aquasecurity/libbpfgo@v0.2.5-libbpf-0.7.0/libbpfgo.go:1271:10: could not determine kind of name for C.bpf_tc_detach
/go/pkg/mod/github.com/aquasecurity/libbpfgo@v0.2.5-libbpf-0.7.0/libbpfgo.go:1241:10: could not determine kind of name for C.bpf_tc_hook_create
/go/pkg/mod/github.com/aquasecurity/libbpfgo@v0.2.5-libbpf-0.7.0/libbpfgo.go:1250:10: could not determine kind of name for C.bpf_tc_hook_destroy
/go/pkg/mod/github.com/aquasecurity/libbpfgo@v0.2.5-libbpf-0.7.0/libbpfgo.go:1282:10: could not determine kind of name for C.bpf_tc_query
/go/pkg/mod/github.com/aquasecurity/libbpfgo@v0.2.5-libbpf-0.7.0/libbpfgo.go:1206:12: could not determine kind of name for C.sizeof_struct_bpf_tc_hook
/go/pkg/mod/github.com/aquasecurity/libbpfgo@v0.2.5-libbpf-0.7.0/libbpfgo.go:1183:12: could not determine kind of name for C.sizeof_struct_bpf_tc_opts
cgo: 
gcc errors for preamble:
/go/pkg/mod/github.com/aquasecurity/libbpfgo@v0.2.5-libbpf-0.7.0/libbpfgo.go: In function 'init_perf_buf':
/go/pkg/mod/github.com/aquasecurity/libbpfgo@v0.2.5-libbpf-0.7.0/libbpfgo.go:68:12: error: 'struct perf_buffer_opts' has no member named 'sz'
     pb_opts.sz = sizeof(struct perf_buffer_opts);
            ^
/go/pkg/mod/github.com/aquasecurity/libbpfgo@v0.2.5-libbpf-0.7.0/libbpfgo.go:70:10: error: too many arguments to function 'perf_buffer__new'
     pb = perf_buffer__new(map_fd, page_cnt, perfCallback, perfLostCallback,
          ^~~~~~~~~~~~~~~~
In file included from /go/pkg/mod/github.com/aquasecurity/libbpfgo@v0.2.5-libbpf-0.7.0/libbpfgo.go:11:0:
/usr/include/bpf/libbpf.h:559:1: note: declared here
 perf_buffer__new(int map_fd, size_t page_cnt,
 ^~~~~~~~~~~~~~~~
```

**Comment by eyakubovich** [comment]
I tested with `make docker` but is that the make target to run to test a CI build in docker? I think the CI is running with the old version of libbpf.

**Comment by jakule** [comment]
@eyakubovich Drone (our release pipeline) builds the docker image from the Dockerfile (so that shouldn't be a problem), but our CI uses the image from our Docker registry which contains older version of the library. We cannot update the libbpf first, because then Drone build will fail. 
@tcsc Any suggestions on how can we update our code and libbpf at the same time? Force merge and hope?

@eyakubovich Also regarding the PR itself, do we need to update anything else: LLVM, `vmlinux.h` etc?

**Comment by eyakubovich** [comment]
Can we put multiple libbpf versions side by side into the image? Maybe even better to vendor libbpf?

**Comment by tcsc** [comment]
> @tcsc Any suggestions on how can we update our code and libbpf at the same time? Force merge and hope?

Is it possible to split the PR into a few separate parts:

1. Add new deps to build image side by side with old
2. Update code/build process to use new deps
3. Remove old deps from build image

?

**Review by jakule — APPROVED** [review]

**Review by zmb3 — APPROVED** [review]

**Review by r0mant — APPROVED** [review]

**Pull request merged**
