### PR TITLE
Add Helm chart for Teleport application access

### PR DESCRIPTION
**Pull request by webvictim**
Adds a small Helm chart for running an agent for Teleport Application Access.

### CODE REVIEW

**Comment by klizhentas** [comment]
I would like to end up with two charts - one for the cluster and another one for all sorts of agents. How hard would it be to add support in `teleport-kube-agent` to support applications and database access features?

**Comment by klizhentas** [comment]
@webvictim if possible, I would like the kube-agent chart to mirror our `--roles` for `teleport start`:

```
$ helm intstall teleport-kube-agent --set=roles=app,db
```

to start teleport agent with app and db roles.

To preserve backwards compatibility the default set of roles would be kube service.

**Comment by webvictim** [comment]
> How hard would it be to add support in teleport-kube-agent to support applications and database access features?

The only issue with this is that the `teleport-kube-agent` name is confusing if it supports other services too. I think we would need to rename it `teleport-agent` or similar (which is also a little confusing, but less so, maybe `teleport-service-agent` or something instead) and then rework the functionality to support all modes.

> `helm install teleport-agent --set=roles=app,db`

Something like this may be possible - I'll take a look. It's going to get harder to validate that all values have been provided correctly, though. I kinda liked the simplicity of the one-chart-per-service model for that reason, although unfortunately it does result in a fair bit of boilerplate code.

> To preserve backwards compatibility the default set of roles would be kube service.

This point would be moot if we rename the chart. We could take references to the `teleport-kube-agent` chart off the index page and out of the documentation but leave the actual code/repo chart around for a while so people can still use it.

**Comment by webvictim** [comment]
This is probably superseded by https://github.com/gravitational/teleport/pull/5348 but I will leave it open temporarily.

**Pull request closed without merging**
