### PR TITLE
add kubeClusterName to teleport-cluster helm chart

### PR DESCRIPTION
**Pull request by timothy-spencer**
add optional kube_cluster_name to try to make kubeconfig not have such a giant ugly name in it

### CODE REVIEW

**Comment by russjones** [comment]
@timothy-spencer Thank you for your contribution!

@webvictim You're reworking Helm charts in #6344, can you take a look at this and see if these changes make sense in the context of new Helm charts?

**Comment by webvictim** [comment]
@klizhentas What do you think about this? We're trying to keep the chart simple, is adding an override for this something we want to support?

**Comment by timothy-spencer** [comment]
This is definitely a cosmetic change.  Happy to close it if you are unhappy with it.

**Comment by webvictim** [comment]
@timothy-spencer We'd prefer not to merge this as it adds an additional configuration value which users may find confusing and solely addresses a cosmetic issue. Having the names generated from a combination of Teleport proxy address and Kubernetes cluster name is at least predictable and easier to handle for support purposes, even if perhaps a little untidy.

Thank you for your contribution, and please feel free to raise other PRs in future!

**Pull request closed without merging**
