### PR TITLE
docs: updates for GCP discovery instructions

### PR DESCRIPTION
**Pull request by stevenGravy**
- correction to `gcloud` step
- Teleport config
- include public proxy address in installer section
- iam service account permissions

### CODE REVIEW

**Comment by atburke** [comment]
Thanks for fixing these! Can you do me a huge favor and also add `iam.serviceAccountUser` to the required roles?

**Review by zmb3 — APPROVED** [review]

**Comment by stevenGravy** [comment]
@atburke, please confirm if the required permissions needs updating too.

**Comment by atburke** [comment]
@stevenGravy Yes, `iam.serviceAccountUser` should be added to the required roles.

**Comment by stevenGravy** [comment]
> @stevenGravy Yes, `iam.serviceAccountUser` should be added to the required roles.

thanks, will add those in too

**Comment by stevenGravy** [comment]
> @stevenGravy Yes, `iam.serviceAccountUser` should be added to the required roles.

@atburke please see the updates and approve if no other changes.

**Review by atburke — APPROVED** [review]

**Pull request merged**
