### PR TITLE
Update TypeScript to 5.4.2

### PR DESCRIPTION
**Pull request by ravicious**
https://devblogs.microsoft.com/typescript/announcing-typescript-5-4/

"Preserved Narrowing in Closures Following Last Assignments" seems to be quite useful.

I ran `yarn build-ui && yarn build-term` along with `yarn type-check` just to see if there are any errors or deprecation warnings and everything seems fine.

### CODE REVIEW

**Review by ryanclark — APPROVED** [review]

**Comment by ravicious** [comment]
There's also support for package.json#imports, but I don't know what exactly it means for us and I didn't check if it works with our setup out of the box.

* https://twitter.com/anthonysheww/status/1765757547850481968
* https://twitter.com/anthonysheww/status/1765864072543666366

**Comment by gzdunek** [comment]
Usually we also update `@typescript-eslint/eslint-plugin`, otherwise a warning like that is printed:

```
WARNING: You are currently running a version of TypeScript which is not officially supported by @typescript-eslint/typescript-estree.

You may find that it works just fine, or you may not.

SUPPORTED TYPESCRIPT VERSIONS: >=4.3.5 <5.4.0

YOUR TYPESCRIPT VERSION: 5.4.2

Please only submit bug reports when using the officially supported version.
```

But from what I see, there is no update yet https://github.com/typescript-eslint/typescript-eslint/issues/8314. Do we want to wait?

**Comment by ravicious** [comment]
Sure, let's wait in that case.

**Comment by gzdunek** [comment]
Cool, it work with no changes to the config?

**Comment by ravicious** [comment]
Yup, since it still imports `@typescript-eslint/parser` and `@typescript-eslint/eslint-plugin` underneath.

**Review by gzdunek — APPROVED** [review]

**Comment by ravicious** [comment]
I also have an update for eslint-plugin-jest ready if you want to take a look. https://github.com/gravitational/teleport/pull/39226

I wanted to do it since the old version imported some old utils `@typescript-eslint` package, but the update turned out to be more complex than I thought. ;f I didn't realize we were using `plugin:jest/all`.

**Pull request merged**
