### PR TITLE
feat: Backfill WebauthnDevice.ResidentKey field

### PR DESCRIPTION
**Pull request by codingllama**
Authenticators registered for "MFA" may actually hold resident keys. This PR makes it so that, if those authenticators are used for passwordless, we update our storage records accordingly.

#39521

Changelog: Mark authenticators used for passwordless as a passkey, if not previously marked as such

### CODE REVIEW

**Comment by codingllama** [comment]
Branched from #45174 to avoid merge conflicts. (Technically this could land separately.)

- #45174

**Comment by codingllama** [comment]
FYI @espadolini.

This takes care of already-registered authenticators. I'll take a look at the [credProps extension][1] next.

[1]: https://www.w3.org/TR/webauthn-2/#sctn-authenticator-credential-properties-extension

**Comment by codingllama** [comment]
Friendly ping reviewers ?

**Review by gabrielcorado — APPROVED** [review]

**Comment by codingllama** [comment]
Friendly ping @fspmarshall @rosstimothy ?

**Review by rosstimothy — APPROVED** [review]

**Pull request merged**
