### PR TITLE
Edwarddowling/recording ls bugs

### LINKED ISSUE #15537: `tsh recordings ls` fails to parse its own recommended time format
There are several issues with the new `tsh recordings ls` command:

1. It doesn't parse the time format that its own `--help` message recommends:

```
➜ ./build/tsh recordings ls -h
usage: tsh recordings ls [<flags>]

List recorded sessions.

Flags:
      --from-utc                 Start of time range in which recordings are listed. Format 2006-01-02T15:04:05Z07:00. Defaults to 24 hours ago.
      --to-utc                   End of time range in which recordings are listed. Format 2006-01-02T15:04:05Z07:00. Defaults to current time.
```

```
❯ ./build/tsh recordings ls --from-utc 2006-01-02T15:04:05Z07:00
ERROR: failed to parse session recording listing start time: expected format 2006-01-02T15:04:05Z07:00, got 2006-01-02T15:04:05Z07:00.
```

It looks like the help message should say `2006-01-02T15:04:05Z` instead.

2. The error message `invalid days` is not clear to the user. Provide a better error message when the date (or dates) are invalid. For example: "cannot request recordings, --from-utc is in the future" or "--to-utc must be after --from-utc".

3. When an invalid range is provided, `tsh` should terminate. The current build (90f34c3a5ef4a36af9d57c33a2bee7f5f0f97ad4) prompts me to re-login even though my credentials are valid and have not expired:

```
❯ ./build/tsh recordings ls --from-utc 2022-10-12T07:20:50Z
Enter password for Teleport user zac:
ERROR: invalid days
```

### PR DESCRIPTION
**Pull request by EdwardDowling**
closes [15537](https://github.com/gravitational/teleport/issues/15537)

The time.RFC3339 format string was used in the error message previously which is not a valid RFC3339 time.
This Pr swaps to using the YYYY-MM-DD for the --from-utc and --to-utc flags, and adds a --since flag that allows specifying a duration in the past to list recordings in. 
Also adds some checks so clearer error messages for invalid time ranges can be provided.

Example outputs

```
$ build/tsh recordings ls --from-utc="2022-05-22T07:20:50" --to-utc="2022-08-16T07:20:50" --limit=10 
ERROR: cannot request recordings: failed to parse session recording listing start time: expected format 2006-01-02, got 2022-05-22T07:20:50.

$ build/tsh recordings ls --since="174h17m30s" --limit=10 
ID                                   Type Participants Hostname          Timestamp           
------------------------------------ ---- ------------ ----------------- ------------------- 
74a07328-96f5-4b8a-8efc-f99cfcfed73a      edward       edward-21a0003xus Aug  9 08:44:13 UTC 
45c398f1-51fe-48c6-a418-7b61c5394468      edward       edward-21a0003xus Aug  9 08:44:04 UTC

$ build/tctl recordings ls --from-utc="2022-05-22" --to-utc="2022-08-16" --since="24h"
ERROR: cannot request recordings: use of 'since' is mutually exclusive with 'from-utc' and 'to-utc' flags

$ build/tctl recordings ls --from-utc="2022-05-22" --to-utc="2024-08-16"
ERROR: cannot request recordings: invalid '--to-utc': '--to-utc' cannot be in the future

$ build/tsh recordings ls --from-utc="2022-08-17" --to-utc="2022-08-16" 
ERROR: cannot request recordings: invalid '--from-utc' time: 'from' must be before '--to-utc'

$ ./build/tsh recordings ls --from-utc=2022-08-18
ERROR: cannot request recordings: invalid '--from-utc': '--from-utc' cannot be in the future




```

### CODE REVIEW

**Comment by zmb3** [comment]
Hate to be pedantic, but IMHO `--since` is the wrong choice of name for this flag. It seems grammatically incorrect.

"Since" should refer to a point in time. For example, "show me all recordings since last Tuesday at 13:00 UTC."

That's not what we're doing here. We're referring to a duration, not a point in time. Alternative suggestions:

- `tsh recordings ls --last=24h`
- `tsh recordings ls --within=24h`

**Review by r0mant — APPROVED** [review]
I don't have a strong opinion on the flag name. IMO `--since` is fine, but I would also be fine with `--last`. @xinding33 Do you have an opinion on this?

**Review by GavinFrazar — APPROVED** [review]
I'm fine with using the simpler date format, but we did lose the ability to be precise with the `--from-utc` and `--to-utc` flags, both in being able to specify a fine-grain range and in being able to specify the timezone. Tested on master I can do `tsh recordings ls --from-utc 2022-01-01T00:00:00.00-07:00 --to-utc 2022-01-01T13:21:00.00-07:00 --limit 10`. In words: "recordings on January 1st 2022, from 12am to 1:21pm PDT" - not possible with the simple format.

I see the value in having a simpler format though - could we allow both? We could try parsing with RFC3339 format and if that fails try the new format you defined. If both fail then print a message with our supported formats, and show that for RFC3339 time you can either use Z for zulu time or +-HH:MM for a specific timezone offset from UTC.

Only a suggestion. LGTM otherwise, I'm approving so my review isn't a blocker.

**Comment by EdwardDowling** [comment]
> I'm fine with using the simpler date format, but we did lose the ability to be precise with the `--from-utc` and `--to-utc` flags, both in being able to specify a fine-grain range and in being able to specify the timezone. Tested on master I can do `tsh recordings ls --from-utc 2022-01-01T00:00:00.00-07:00 --to-utc 2022-01-01T13:21:00.00-07:00 --limit 10`. In words: "recordings on January 1st 2022, from 12am to 1:21pm PDT" - not possible with the simple format.
> 
> I see the value in having a simpler format though - could we allow both? We could try parsing with RFC3339 format and if that fails try the new format you defined. If both fail then print a message with our supported formats, and show that for RFC3339 time you can either use Z for zulu time or +-HH:MM for a specific timezone offset from UTC.
> 
> Only a suggestion. LGTM otherwise, I'm approving so my review isn't a blocker.

@GavinFrazar 
How about this, where we have both as options but for simplicity we always suggest the simpler format in the error messages?

**Comment by GavinFrazar** [comment]
> > I'm fine with using the simpler date format, but we did lose the ability to be precise with the `--from-utc` and `--to-utc` flags, both in being able to specify a fine-grain range and in being able to specify the timezone. Tested on master I can do `tsh recordings ls --from-utc 2022-01-01T00:00:00.00-07:00 --to-utc 2022-01-01T13:21:00.00-07:00 --limit 10`. In words: "recordings on January 1st 2022, from 12am to 1:21pm PDT" - not possible with the simple format.
> > I see the value in having a simpler format though - could we allow both? We could try parsing with RFC3339 format and if that fails try the new format you defined. If both fail then print a message with our supported formats, and show that for RFC3339 time you can either use Z for zulu time or +-HH:MM for a specific timezone offset from UTC.
> > Only a suggestion. LGTM otherwise, I'm approving so my review isn't a blocker.
> 
> @GavinFrazar How about this, where we have both as options but for simplicity we always suggest the simpler format in the error messages?

That sounds good to me, as long as there is info in `--help` where they can see the rfc3339 supported format, but explicit that they need to choose either Z or offset, not both: `Format 2006-01-02T15:04:05Z or 2006-01-02T15:04:05+00:00`

**Comment by zmb3** [comment]
Less is often more, folks. Until we see a real need for finer-grained searching I think we should keep it simple.  The more options you support the harder it is for new users to figure out how to use.

We've had filtering at the day-level granularity in the web UI for years and I can't find any record of a single request to also allow specifying specific times and time zones.

**Comment by EdwardDowling** [comment]
> Less is often more, folks. Until we see a real need for finer-grained searching I think we should keep it simple. The more options you support the harder it is for new users to figure out how to use.
> 
> We've had filtering at the day-level granularity in the web UI for years and I can't find any record of a single request to also allow specifying specific times and time zones.

I've removed the option for RFC3339 for now then, if we get a request for it later its trivial to add back in.

**Pull request merged**
