### PR TITLE
feat(teleport-cluster chart): Add nodeSelector field

### PR DESCRIPTION
**Pull request by yanntoque**
see https://kubernetes.io/docs/concepts/scheduling-eviction/assign-pod-node/#nodeselector

### CODE REVIEW

**Comment by ankitjain28may** [comment]
Need this one in teleport helm chart

**Comment by ptgott** [comment]
@webvictim @hugoShaka Bringing this to your attention

**Comment by hugoShaka** [comment]
Hello @yanntoque, thank you for the contribution 👍 

On one hand I'm not especially happy with introducing a new parameter that has been superseded by `affinity` and whose presence in the Kubernetes API is only due to the fact they were not allowed to remove it (because it landed in a GA api, now we're stuck with two ways to assign pods to nodes). On the other hand it's not the first time I see the feature request and it seems users are expecting to be able to set this parameter, most popular charts I checked are exposing the feature.

@webvictim WDYT?

**Comment by webvictim** [comment]
I think that adding this next to `affinity` in the values (with a warning that `nodeSelector` is deprecated and `affinity` is preferred) would be an acceptable compromise. We can always remove it as and when Kubernetes eventually does.

**Comment by hugoShaka** [comment]
> I think that adding this next to affinity in the values (with a warning that nodeSelector is deprecated and affinity is preferred) would be an acceptable compromise. 

Fair, let's add the feature :)

> when Kubernetes eventually does.

This sadly won't happen, they cannot remove things from a GA API and I don't think they have plans for an apps/v2.

**Comment by hugoShaka** [comment]
Hi @yanntoque 

Thanks for your contribution 🎉 . Sorry for the delay. I spent the last moths revamping the Helm chart and wanted to finish this before accepting external contributions. We are currently unable to run our tests on external contributions. As such, I've created an internal PR here with your changes rebased on the `master` branch:

https://github.com/gravitational/teleport/pull/20162

Please wait another couple of days and your code will be merged :).

**Comment by hugoShaka** [comment]
Merged in https://github.com/gravitational/teleport/pull/20162

**Pull request closed without merging**
