### PR TITLE
Remove DigitalOcean docs. These guides will be published as a blog post

### PR DESCRIPTION
**Pull request by flyinghermit**
Publishing these getting started guides as a blog post seems more efficient (for future copy updates), and will allow promoting them as a marketing copy.

### CODE REVIEW

**Comment by ptgott** [comment]
@sshahcodes It'd be great to have more context around this. Would it be possible to talk about Teleport on Digital Ocean in the blog as well as in the docs?

If we do decide to revert, we'll need redirects in `config.json` in case Google shows stale search results for these pages.

**Comment by sshahcodes** [comment]
@ptgott The only reason to remove these guides from docs and publish them as a blog post is to speed up the publication process and lessen the review burden to our doc team. These guides need to be updated on each new Teleport release, so publishing them as a blog post seems a faster option. 

I did check with the google search with incognito mode to see if these pages are already cached in the SERPs but I did not see these docs any search results. But to be safe, I can update this PR with redirection added to `config.json`. Let me know.

**Comment by ptgott** [comment]
What would we need to update about each guide with each new Teleport release? Is there a way to prevent us from having to update that information with each release while retaining the release-agnostic parts of the two guides? 

For example, in the Getting Started guide, the Marketplace screenshot shows an out-of-date version, but I imagine that readers can tolerate this and, if not, we can do something like blurring the version number. The Marketplace link URL itself does not include versioning information.

What do you think?

**Comment by sshahcodes** [comment]
Yes, the changes would be to update the screenshots and our getting started scripts (if there are any changes to accommodate the new release). But I agree that we can blur the screenshot or readers might tolerate reference to older version (if it's not significantly old). 

Again, the only reason is to speed up the publish and update process and lessen the review burden for the doc team. It's okay to me as long as you think this should go into the docs :)

**Comment by ptgott** [comment]
@sshahcodes Sounds good—I think the DigitalOcean guides would be great to have in the docs so users visiting the docs site can discover them as they browse. Some users may not be aware that Teleport works well with DigitalOcean, for example, but would appreciate the possibility of experimenting with Teleport on a low-cost cloud platform.

**Comment by sshahcodes** [comment]
@ptgott Okay. Thank you for this. I wIll close this PR and reopen the backport PR.

**Pull request closed without merging**
