### PR TITLE
Change the README.md header image temporarily to promote Teleport's user conference

### PR DESCRIPTION
**Pull request by xinding33**

### CODE REVIEW

**Comment by zmb3** [comment]
Have we considered changing the social preview instead? The README of an open core product feels like a poor place to advertise.

Also, what's with the RFD in here? Is that a mistake?

**Comment by zmb3** [comment]
Also, looks like a duplicate of https://github.com/gravitational/teleport/pull/16741

**Comment by xinding33** [comment]
> Have we considered changing the social preview instead? The README of an open core product feels like a poor place to advertise.

What do you mean by "social preview"?

> Also, what's with the RFD in here? Is that a mistake?

Yes, my mistake. I removed the extra commits.

**Comment by xinding33** [comment]
Oh, you're talking about the image that's shown when the repo is shared on social media. We can update that as well but I was thinking that the README header image will be the best (i.e. most visible) way to promote the user conference. It's similar to (albeit not exactly the same as) adding a plug for the commercial version of an open source product. For example https://github.com/mongodb/mongo does that for Atlas. I agree it's not best practice but I think the tradeoffs are worth it in this instance.

**Review by klizhentas — APPROVED** [review]

**Comment by zmb3** [comment]
Yeah, the social preview is in the repo's settings and gets rendered any time you share a link to the repo (slack, twitter, etc). I'd argue that would have many more views than our README and is a more appropriate place, but your call.

**Review by zmb3 — APPROVED** [review]

**Pull request merged**
