### PR TITLE
Standardized language on enterprise/cloud version warning for enterprise guides

### PR DESCRIPTION
**Pull request by stevenGravy**
Added a page include for the version warning you need enterprise or teleport cloud.  Also added version warning to HSM page that wasn't there before.

### CODE REVIEW

**Review by ptgott — COMMENTED** [review]
The current changes look good, though I have three questions I'm not sure the best answer to:

1. Assuming the risk we're preventing with this change is that a user arrives via organic search and doesn't realize they're in the Enterprise section, should we add the warning to all pages in the Enterprise section that don't mention Enterprise? Pages not included yet:
    - `/docs/enterprise/workflow/`
    - `/docs/enterprise/fedramp/`
    - `/docs/enterprise/soc2/`

2. Should we change the visibility of the warning depending on scope? Currently the only way to do this is via the `Details` box, though I have two issues in `gravitational/next` re: doing this for Admonitions and arbitrary markdown (https://github.com/gravitational/next/issues/931, https://github.com/gravitational/next/issues/867).

3. Should we include a link to our pricing page in the version warnings so users can easily sign up for Enterprise when they see the warning? The downside is that it clutters the warning a bit, which might not be worth it if users can easily sign up for Enterprise. On the other hand, there doesn't seem to be an explicit link to an Enterprise signup page if you're looking at a docs guide.

**Comment by stevenGravy** [comment]
thanks @ptgott .  The Workflow part should probably be moved out since that's not specific to Enterprise. I will follow up on the linking to enterprise pricing/sales.

**Comment by r0mant** [comment]
@stevenGravy Are you planning to make the changes @ptgott suggested?

**Comment by ptgott** [comment]
@stevenGravy If we do want to change the visibility of the warning based on scope while still using an Admonition (I definitely think we should change the visibility based on scope), we can now use the `ScopedBlock` component, which reveals its child elements if the `scope` matches the selector and hides them otherwise:

```md
<ScopedBlock scope={["oss"]}>
<Admonition
  type="warning"
  title="Version Warning"
>
  This guide requires an Enterprise version of Teleport.
</Admonition>
</ScopedBlock>
```
As before, we can also use a `Notice` component, which might work better here than an Admonition since the title and body text are very similar:

```md
<Notice
  type="warning"
  scope={["oss"]}
>
  This guide requires either an Enterprise version of Teleport or a Teleport Cloud account.
</Notice>
```

**Comment by stevenGravy** [comment]
I will look at making the changes @r0mant

**Comment by zmb3** [comment]
@stevenGravy do you still plan to make these changes or should I close this one out?

**Comment by stevenGravy** [comment]
already exists, closing

**Pull request closed without merging**
