### PR TITLE
[v6.1] Editorial Pass/Review - Home

### PR DESCRIPTION
**Pull request by inertial-frame**
This PR supports: https://github.com/gravitational/teleport/issues/6534 and represents a quick editorial pass through the `home` docs!

In general, I tried to use my best judgement. I tried to avoid ruling on docs-wide conventions except where there was already some pattern implicit to an article (header casing in "Getting Started" for example).

Specifically:

1. Corrected typos.
1. Oxford commas.
1. Added tic marks to assist with user skimming and search.
1. Rewording in several places to improve grammar.
1. Stylistic improvements. (IMO these improve the readability and ease in reading the docs.)

I avoided making any significant changes to content (since I'm still onboarding and learning about everything). I figure once the team has firmly decided on best docs practices and best approaches to those (plugin or manual edit, etc.) a greater effort can be made.

Wanted to get these changes in early on since this is the main landing "concept module" (home) for the current docs. Am happy to squash the merges. Figured it's fine to condense these into one PR since most changes are minor. 

I'll work my way through the rest of 6.1 in subsequent PR's.

### CODE REVIEW

**Review by klizhentas — APPROVED** [review]

**Comment by klizhentas** [comment]
Looks good, you'd have to backport to branch/v6 and master + fix the linter errors:

content/docs/pages/faq.mdx
--
163 | 85:1-85:51  warning  Marker style should be `-`  unordered-list-marker-style  remark-lint
164 | 86:1-86:35  warning  Marker style should be `-`  unordered-list-marker-style  remark-lint
165 | 87:1-87:31  warning  Marker style should be `-`  unordered-list-marker-style  remark-lint

**Comment by klizhentas** [comment]
@webvictim can we please give Adam access to drone logs view? @russjones can we make Adam's account docs code owner for branches 4.4, 5, 6, 6.1 and master?

**Comment by webvictim** [comment]
@klizhentas Drone access is gated on the same permissions as Github, so he should be able to see them if he has read/write access to the repo.

@inertial-frame Can you see https://drone.gravitational.io/gravitational/teleport/10259/2/3?

**Comment by inertial-frame** [comment]
@webvictim , @klizhentas - thanks! I can. Let's chalk that up to getting familiar with the CI/CD pipeline? 😬 🤦‍♂️ I'll correct those issues here and rebase.

**Pull request merged**
