### PR TITLE
helm: Allow to define static join tokens in helm chart

### LINKED ISSUE #8003: Make it possible to specify static join token in helm chart teleport-cluster
### What
Specify static join token in helm chart teleport-cluster

### How
Add to helm chart template

### Why
I want a simpler setup without the complexity of dynamic join tokens

### Workaround
Use helm chart in custom mode, however this disables a lot of the helm chart I still want to have, like acme support.

### PR DESCRIPTION
**Pull request by gabrielbiasi**
This PR is aiming to resolve #8003, allowing to specify static join tokens in the helm chart of teleport-cluster.

### CODE REVIEW

**Review by r0mant — COMMENTED** [review]
@webvictim Do we want this in? IIRC previously we didn't want to include it in the Helm chart as to not to encourage the use of static tokens?

**Comment by gabrielbiasi** [comment]
> @webvictim Do we want this in? IIRC previously we didn't want to include it in the Helm chart as to not to encourage the use of static tokens?

Another solution(?) is to allow to set any extra variables on each service section, like `extraAuthServiceOptions`, `extraProxyServiceOptions`, `extraDbServiceOptions`, `extraSshServiceOptions` and let the users set whatever they want.

**Comment by webvictim** [comment]
@r0mant Yep, my opinion is that we shouldn't allow users to easily set static tokens as it's an anti-pattern. Teleport's philosophy is centred around eliminating passwords and a static token is basically a password. Dynamic tokens with a short TTL should always be used and for situations where people really, really want to use static tokens, it isn't a huge undertaking for them to fork the chart and add that functionality.

> Another solution(?) is to allow to set any extra variables on each service section, like extraAuthServiceOptions, extraProxyServiceOptions, extraDbServiceOptions, extraSshServiceOptions and let the users set whatever they want.

The chart currently has a lot of extra logic which sets additional Teleport config options in the right place based on specific values. Allowing freely structured YAML to be written to the config file is likely to break a lot of these use cases and make it much easier to generate a non-working Teleport configuration. I'd rather we don't go down that road. The chart provides `chartMode: custom` to use your own custom config at present, and we're regularly adding new functionality.

@gabrielbiasi Thank you for your work here and for considering a contribution. Please feel free to submit other PRs in future!

**Pull request closed without merging**
