### PR TITLE
tooling: Add a flaky test report to render-tests

### PR DESCRIPTION
**Pull request by camscale**
Add a reporting mode to render-tests to report the top N flaky tests.
Flaky tests are just tests that fail in the context of all tests
expecting to pass.

To test flakiness, tests can be run multiple times with the new `rerun`
tool to run tests up to N times with a timeout. The json output of these
test runs is piped to `render-tests -report-by flakiness -top X` to
report the top X test failures. e.g.

    rerun -n 200 -t 2h \
        go test -shuffle on -cover -json ./... | \
	render-tests -report-by flakiness -top 10 -summary-file flake.txt

This will run `go test ./...` up to 200 times, stopping after 2h,
whichever comes first. The top 10 flaky tests are reported and are
written to a summary file `flake.txt`.

This is intended to be run from CI nightly, with the summary file posted
to a slack channel so flaky tests are surfaced within 24 hours of being
committed but not require long tests on each PR before it can be merged.

Issue: https://github.com/gravitational/teleport/issues/24169

### CODE REVIEW

**Comment by zmb3** [comment]
FYI @rosstimothy (who is trying to get rid of the `render-tests` tool)

**Review by r0mant — APPROVED** [review]
Don't really have comments here, if it works - :shipit:

**Review by tcsc — APPROVED** [review]
When you say "add", you mean "rewrite my terrible script from scratch", yes? :-)

**Comment by camscale** [comment]
> Often times we only get logs that a race has been detected but the stack trace which indicates where the race occurred is not included.

@rosstimothy I think I see what is going wrong here and why there may be times when the stack trace is not included. I ran a test and this has helped me understand one case in render-tests that did not make much sense to me (when a package fails but no tests within it fail - this can happen when a race is detected). It now makes sense and this will not be hard to ensure that render-tests emits the output I think with a little bit of tweaking.

**Pull request merged**
