### PR TITLE
Update Terraform code to support Terraform 0.12.x and AWS provider 2.x

### PR DESCRIPTION
**Pull request by webvictim**
Big PR for upgrading from Terraform 0.11.7 to 0.12.x (current latest version is 0.12.20)

Details on the big changes here: https://www.terraform.io/upgrade-guides/0-12.html

I'm going to avoid pinning this to a specific 0.12.x version and instead keep us up to date on the latest 0.12 version - this should make us catch bugs/problems with upgrades quicker and generally keep this more up to date.

This also updates us from using AWS provider version 1.18 to the latest 2.x version (tested with v2.46). Version 3.0 will be coming at some point in the near future, so I'll keep an eye on that and make a new PR when it drops.

Tested by creating provisioning both non-ACM and ACM versions, logging in, looking at the instances/configs etc.

### CODE REVIEW

**Comment by webvictim** [comment]
Closes #3304

**Comment by webvictim** [comment]
Fixes #3304

**Comment by wadells** [comment]
Some meta reflections:

1) Re:
> I'm going to avoid pinning this to a specific 0.12.x version and instead keep us up to date on the latest 0.12 version - this should make us catch bugs/problems with upgrades quicker and generally keep this more up to date.

Floating dependencies are the enemy of determinism.  I'd **strongly** council against this.  Instead, I'd recommend we put a process in place to upgrade deps a regular cadence.  A floating ref will only externalize the work of keeping current to engineers who know less about it than you.  If you want to build up TF knowledge, do that in a structured way by having key people shadow/reverse shadow during planned upgrades.

2) Much of the meat of this PR seems to be minor formatting changes: stripping `${}` and whitespace reflow.  Do we have a static analysis or style tool (the equiv of `gofmt`) run as part of the build to make sure .tf files follow best practices going forward?  This stuff isn't really worth having humans review.

Perhaps there are some 11 -> 12 upgrade docs that can provide context as to these changes?  I didn't see anything in the description or commit messages to this effect.

3) Related to #2, it is difficult to review this PR for actual content changes vs stylistic stuff.  Are there any particular areas you'd like to call out?  I looked at 96332c67b030, and that all seemed reasonable, but if there are meaty changes hidden in d590671972, they're lost in the noise.

4) What sort of testing did you do?  Is there automatic testing that covers any portion of this?  I'm still learning the repo & toolchain, so forgive me if I'm asking basic questions.

**Comment by wadells** [comment]
> What sort of testing did you do? Is there automatic testing that covers any portion of this? I'm still learning the repo & toolchain, so forgive me if I'm asking basic questions.

Whoops, you answered this in the description.  Sorry for the redundant Q!

**Comment by wadells** [comment]
In short, I didn't see any ship blockers.  My only big concern is the floating dependency and that I may have overlooked something hidden in the stylistic noise.  If you're comfortable those aren't a problem: :ship:

**Comment by webvictim** [comment]
Thanks for the review @wadells. 

> Perhaps there are some 11 -> 12 upgrade docs that can provide context as to these changes? I didn't see anything in the description or commit messages to this effect.
The 0.11 -> 0.12 upgrade document was in the linked issue (which I didn't really do a good job of referencing) - I've edited the description here to add it.

> Much of the meat of this PR seems to be minor formatting changes: stripping ${} and whitespace reflow.
Yes, you're right - that's exactly what most of it is. Terraform actually did a lot of the work for me when I ran the `terraform 0.12checklist` and terraform 0.12upgrade` commands.

> Do we have a static analysis or style tool (the equiv of gofmt) run as part of the build to make sure .tf files follow best practices going forward? This stuff isn't really worth having humans review.
Not currently - I'll look into it. There's `terraform validate` but that doesn't actually do any formatting, just checks syntax. You're certainly correct that it probably isn't worth having humans go over it for most things - I mostly just wanted to make sure (some) people were aware that we'd done a Terraform upgrade in case it became an issue for anyone going forward.

> Floating dependencies are the enemy of determinism. I'd strongly council against this. Instead, I'd recommend we put a process in place to upgrade deps a regular cadence. 
Yes, I suppose this is true. I was just trying to avoid getting into a situation like before where we had Terraform code that was over a year out of date version-wise but hadn't experienced much in the way of breaking changes during that time. Probably pinning to a specific tested version which works is a better idea, then keeping an eye on major Terraform/AWS provider version upgrades.

**Review by wadells — APPROVED** [review]
LGTM.

**Pull request merged**
