### PR TITLE
Copy Terraform provider from teleport-plugins repo

### PR DESCRIPTION
**Pull request by hugoShaka**
This PR copies the code from the TF provider from the teleport-plugins repo (we are consolidating everything into one repo).

The changes are:
- replace all occurrences of `gravitational/teleport-plugins/terraform` by `gravitational/teleport/integrations/terraform`
- add a dedicated go.mod to avoid TF deps to pollute the main go mod (and add replace directives for teleport and teleport/api)
- skip all non-OSS test when run against OSS
- use the new AuthHelper and integration test suite to start an auth server instead of using a binaries and relying on logs to control the execution flow
- switch the `github` connector in the test fixtures from `gravitational` to `octocat` as gravitational has SSO enabled and the tests were not happy with this

>[!TIP]
> For reviewers: you will want to look at the `integrations/terraform/tests/main_test.go` file as it's the one where I wrote code. The reset of the project is essentially untouched.

### CODE REVIEW

**Comment by hugoShaka** [comment]
`make test` and `make gen-tfschema` are passing

**Review by tigrato — APPROVED** [review]
Reviewed 0.35% of the lines. LGTM :laughing:

**Review by strideynet — APPROVED** [review]
image

**Review by marcoandredinis — APPROVED** [review]
image :scream: 

If you can please the CI, go for it 💪

**Review by r0mant — APPROVED** [review]
Bot.

**Comment by hugoShaka** [comment]
Blocked by https://github.com/gravitational/teleport/pull/40224

**Pull request merged**
