### PR TITLE
Update docs structure for branch/4.3 to use with the new docs engine

### PR DESCRIPTION
**Pull request by iAdramelk**
4.3 docs was linking some `/examples/*` files that was not available in the `branch/4.3`, so I copied them too.

### CODE REVIEW

**Comment by klizhentas** [comment]
@russjones @webvictim please approve

**Comment by webvictim** [comment]
@iAdramelk Could you please see whether you can cherry-pick 186f9738fb0f7cf799aff836f4037c277206f372 into this branch? It should fix the docs checks in Drone by adding the necessary rules to the Makefile.

**Review by russjones — APPROVED** [review]

**Review by r0mant — APPROVED** [review]

**Review by webvictim — APPROVED** [review]

**Comment by klizhentas** [comment]
@webvictim is this one good to merge?

**Comment by webvictim** [comment]
@klizhentas Yes

**Pull request merged**
