### PR TITLE
Fix ParseLabelSpec to support unicode characters

### PR DESCRIPTION
**Pull request by klizhentas**

### CODE REVIEW

**Review by r0mant — APPROVED** [review]

**Comment by klizhentas** [comment]
retest this please

**Review by russjones — APPROVED** [review]

**Comment by klizhentas** [comment]
retest this please

**Comment by klizhentas** [comment]
retest this please

**Comment by klizhentas** [comment]
retest this please

**Comment by klizhentas** [comment]
retest this please

**Pull request merged**
