### PR TITLE
Fix parameter in the code example

### PR DESCRIPTION
**Pull request by gdubicki**
as `--proxy-server` returns an error
a `--auth-server` works

### CODE REVIEW

**Comment by gdubicki** [comment]
Hm... There are few other occurrences of the old param in the code: https://github.com/search?q=repo%3Agravitational%2Fteleport%20%20--proxy-server%3Dexample.teleport.sh%3A443&type=code

Please wait, I'll add fixes to this PR.

**Comment by zmb3** [comment]
This is correct as is. The proxy server flag is new. If you're getting an error, you may need to update to a newer version.

**Comment by gdubicki** [comment]
> This is correct as is. The proxy server flag is new. If you're getting an error, you may need to update to a newer version.

Yeah, I found that in the code that it's new.

But there is another problem here: the docs for v14 (my cloud instance's version) also uses the new parameter: https://goteleport.com/docs/ver/14.x/machine-id/getting-started/

Screenshot 2024-03-19 at 21 29 08

**Comment by gdubicki** [comment]
Can you please take a look at my last comment, @zmb3?

**Pull request closed without merging**
