### PR TITLE
Teleport lab - open 3024 port in and copy changes.

### PR DESCRIPTION
**Pull request by flyinghermit**
- open port `3024` in `teleport-lab.yml`. 
- updated the doc to highlight running lab commands from inside the term container.
- reference to`proxy.luna.teleport` host instead of`localhost`

### CODE REVIEW

**Comment by russjones** [comment]
@sshahcodes Let's merge this in in 1 week (September 15th).

**Review by klizhentas — APPROVED** [review]

**Comment by klizhentas** [comment]
@sshahcodes to verify, have you forward-ported it to master branch?

**Comment by sshahcodes** [comment]
@klizhentas It's not forward ported to the master branch.

**Comment by klizhentas** [comment]
@sshahcodes let's forward port it then when you have a chance :+1:

**Pull request merged**
