### PR TITLE
Getting started with Kubernetes

### PR DESCRIPTION
**Pull request by benarent**
I've been testing this, I've found a couple small issues in this PR.

### CODE REVIEW

**Comment by benarent** [comment]
@klizhentas I'm currently unable to get this working. Using the new helm chart, I'm getting.

```
kubectl logs service/teleport-cluster
error: unrecognized configuration key: 'acme'
```

**Comment by klizhentas** [comment]
@webvictim should we be updating helm charts to point to `6.0.1` too or there is a way to make it automatic last  patch version?

**Comment by webvictim** [comment]
@klizhentas See #5983, I'm configuring all the charts to use the `:6` tag in quay.io by default which is the latest 6.x version of Teleport.

**Comment by benarent** [comment]
@klizhentas PTAL, I've tested the getting started guide and fixed a few small issues I found along the way.

**Review by klizhentas — APPROVED** [review]

**Pull request merged**
