### PR TITLE
Updated the README

### PR DESCRIPTION
**Pull request by kontsevoy**
- Fixed obsolete links
- Removed heavy SSH focus
- More modern language to describe what Teleport is

### CODE REVIEW

**Comment by twakes** [comment]
@kontsevoy This looks to still be using links to our community discourse site. I think we want people to use Github discussions now.

**Comment by benarent** [comment]
It looks good, can you also update the video to be this one https://www.youtube.com/watch?v=0HlyGk8dihM ( I would add a suggestion but it's at the bottom of the doc ) and update the community forum.

**Review by klizhentas — APPROVED** [review]

**Comment by klizhentas** [comment]
updated in #5884

**Comment by klizhentas** [comment]
merged in https://github.com/gravitational/teleport/pull/5884

**Pull request closed without merging**
