### PR TITLE
Move lib/web tests to new web login helpers

### PR DESCRIPTION
**Pull request by codingllama**
A bit of housekeeping, following up from #38754.

Tests that call /webapi/sessions/new now use the same set of helper functions. Helpers are not tied to particular environments and function correctly (eg, always do CSRF).

No production code is changed.

### CODE REVIEW

**Comment by codingllama** [comment]
I recommend reviewing commit-by-commit, so you won't be staring at a bunch of moved code.

The first commit (7a83508) does the moves, everything else does actual changes.

TestWebSessionsBadInput was all kinds of broken (no CSRF, incorrect cluster settings, etc), so it gets a commit all by itself.

FYI @flyinghermit

**Comment by codingllama** [comment]
I expected the FTD to cause problems here. I'll ask for an exemption after approvals.

**Review by Joerger — APPROVED** [review]

**Comment by codingllama** [comment]
@zmb3 I could use a review and a flake exemption here, if you have the time.

**Review by zmb3 — APPROVED** [review]

**Comment by codingllama** [comment]
Many thanks!

**Pull request merged**
