### PR TITLE
Fix UTF-8 character parse

### PR DESCRIPTION
**Pull request by LuRenJiasWorld**
## Intro
This bug exists when using UTF-8 Character in labels, which is common in non-english countries like China.

## How to reproduce this bug: 
For example, Executing teleport like `teleport start --labels 服务器环境=测试,操作系统类别=Linux,机房=华北` will cause an error message: `Original Error: *errors.errorString invalid label spec: '服务器环境=测试,操作系统类别=Linux,机房=华北', should be 'key=value'`

## What cause this bug
In function `ParseLabelSpec` located at `lib/client/api.go`, it use `i+1 == specLen` to judge if the pointer has pointed to the end of the string, but it only worked on ascii strings (or other encoding just use one byte for one word), for UTF-8, it didn't work at all, which will get key-values like `服务器环境=测试,操作系统类别=Linux,机房=` (the end of the key-value is missing), so it just throws an error.

## How did I fix it
Simply by individually judge if the pointer has pointed to the end, adding a `i+3 == specLen` after. It's not perfect, but it did work.

### CODE REVIEW

**Comment by klizhentas** [comment]
thanks for your pull request. we will review and get back to you!

**Comment by LuRenJiasWorld** [comment]
Hey, I've mentioned that you had not update this pull request since January, so do you have something that I can help with? 

For a lot of non-english users, the feature that can use any characters besides ascii is so necessary, and I remember at the early version of Teleport, it did support non-ascii characters in labels, but after some versions you've released, this feature just disappeared some how.

So if there are some other work I should do to make this feature being merged into your code base and being released ASAP, I'd glad to do it.

Thanks.

**Comment by klizhentas** [comment]
sorry for the delay, we will make sure it lands in the upcoming release.

**Comment by klizhentas** [comment]
@LuRenJiasWorld thanks for the PR, I've reviewed it, and ended up with a slightly different implementation + tests, that we are going to merge instead (as it's more generic):

https://github.com/gravitational/teleport/pull/2673

**Pull request closed without merging**
