### PR TITLE
docker-compose: Update default images used to version 6

### PR DESCRIPTION
**Pull request by webvictim**
Updates default Docker image number in `docker-compose` files.

Backports required:
- `branch/v6`
- `branch/v6.1`
- `branch/v6.2`

Updates #7030

### CODE REVIEW

**Review by wadells — APPROVED** [review]
Should these be at 7 for master, and 6 for the backports?

**Comment by webvictim** [comment]
> Should these be at 7 for master, and 6 for the backports?

We don't publish Docker images from `master` (at least currently), so the `7` tag doesn't exist. Arguably it should, though.

**Comment by wadells** [comment]
> > Should these be at 7 for master, and 6 for the backports?
> 
> We don't publish Docker images from `master` (at least currently), so the `7` tag doesn't exist. Arguably it should, though.

Hmm ... definately not something for this PR (6 is great) but perhaps we have a floating and obviosly pre-release tag for use with master.  Then when 7.0 is cut the release process would include changing that to 7.  Just spitballing ideas.

**Comment by webvictim** [comment]
#6970 covered `teleport-quickstart.yml` but missed `teleport-ent-quickstart.yaml`. As such, that PR should also be included when backporting this one.

**Review by awly — APPROVED** [review]

**Review by russjones — APPROVED** [review]
Bot.

**Pull request merged**
