### PR TITLE
Update docker-compose docs

### PR DESCRIPTION
**Pull request by stevenGravy**
- include x86 only statement as in the docker install page 
- remove Teleport as a pre-req as it is not required.  The docker-compose provides Teleport.

### CODE REVIEW

**Review by zmb3 — CHANGES_REQUESTED** [review]
This is not accurate any more is it? I thought we shipped multi-arch images.

**Comment by stevenGravy** [comment]
Yes we need to change this to include the arm extension. Let me take a look. The arm version doesn't automatically load

**Comment by stevenGravy** [comment]
> This is not accurate any more is it? I thought we shipped multi-arch images.

@zmb3 confirmed as accurate.  The Teleport lab docker images are only built for `x86_64`.  We are building multi-arch for the teleport, teleport-ent docker images.

**Review by ptgott — APPROVED** [review]
Approved with a suggestion. Disabled auto-merge so you can apply it

**Comment by stevenGravy** [comment]
> > This is not accurate any more is it? I thought we shipped multi-arch images.
> 
> @zmb3 confirmed as accurate. The Teleport lab docker images are only built for `x86_64`. We are building multi-arch for the teleport, teleport-ent docker images. I've updated to clarify that.

@zmb3 please see latest updates.  should be good to go.

**Review by evanfreed — APPROVED** [review]
Confirmed this is still the behavior.

```
➜ docker-compose -f teleport-lab.yml up -d
[+] Running 5/9
 ⠿ Network tmp_teleport                                                                                                                                     Created                   0.0s
 ⠿ Container teleport                                                                                                                                       S...                      0.4s
 ⠏ teleport The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested                            0.0s
 ⠿ Container teleport-bootstrap                                                                                                                             Started                   0.5s
 ⠇ bootstrap The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested                           0.0s
 ⠿ Container term                                                                                                                                           Start...                  0.8s
 ⠿ Container openssh                                                                                                                                        St...                     0.8s
 ⠇ openssh The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested                             0.0s
 ⠇ term The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested                                0.0s
```

**Review by zmb3 — APPROVED** [review]

**Pull request merged**
