### PR TITLE
Unparallel racy test

### PR DESCRIPTION
**Pull request by codingllama**
Fixes raciness on TestInit_bootstrap.

### CODE REVIEW

**Review by r0mant — APPROVED** [review]

**Comment by codingllama** [comment]
Ran the culprits I recognized from https://drone.teleport.dev/gravitational/teleport/3835/1/7 a bunch of times using `go test -race -count N`, it looks like @r0mant was spot on about the `t.Parallel`.

**Comment by zmb3** [comment]
What is the race that this is preventing? Does `Init` modify shared state?

**Comment by codingllama** [comment]
> What is the race that this is preventing? Does `Init` modify shared state?

I think the problem stems from calling Init with similar parameters in a bunch of tests. TBH I didn't dig down too deeply - I assume this is breaking other PRs, do I took off the `t.Parallel()`, ran the tests a bunch of times and called it a day.

**Comment by zmb3** [comment]
Yeah, I'm good with merging if it seems to fix the issue, but I don't actually see the race so was curious if you had details.

**Review by zmb3 — APPROVED** [review]

**Pull request merged**
