### PR TITLE
Adds variable substitution to access request and review specs

### LINKED ISSUE #7135: Support for access requests, reviews specifications in roles for variable substitution
### What
Support  usage of `regexp` functions and external traits in requests and reviews in roles.

```yaml
    request:
      roles:
      - '{{regexp.replace(user.spec.traits[groups-request], ^product(.*)$, "$1-admin")}}'
      - '{{external.additionalroles}}'

    review_requests:
      roles:
     - '{{regexp.replace(user.spec.traits[groups-request], ^product(.*)$, "$1-admin")}}'
```
### How
Extend current role mapping to include these parts of the role to allow usage of functions and external traits.

### Why
Allows for doing dynamic mapping in roles with the traits coming from the SSO>

### Workaround
Manually specifying in roles

### PR DESCRIPTION
**Pull request by tcsc**
Adds variable substitution and regex replace functionality to the
Role Request and Review Request blocks in a Role.

Also includes a minor refactor for the trait application code to reduce
repetition.

See-Also: #7135

### CODE REVIEW

**Review by nklaassen — APPROVED** [review]

**Comment by russjones** [comment]
@fspmarshall @timothyb89 Can you review?

**Review by timothyb89 — APPROVED** [review]

**Review by fspmarshall — COMMENTED** [review]
First off, love the refactor/cleanup, so lets definitely merge that.

Second, I need to apologize.  I think you did extra work on account of my poor documentation.

I'm fairly certain that the access-request specific part of this won't work, and I don't think adding it is actually necessary.  We already have a mechanism for variable substitution that should meet the needs of #7135.  It just isn't explained properly in the docs.

The access request & review permission checkers doesn't use `ApplyTraits` or any roles that have gone through that process.  They load all user and role resources directly from the backend.  There are various reasons for this, but the most relevant bit for this discussion is that the access request system treats role strings as *patterns* that match the roles which the user is allowed to request (e.g. `roles: ["dev-*"]`).  The access request/review permission evaluators need to perform substitutions internally because they track whether or not a substitution occurred, and disable non-literal matching for those values specifically.  Basically, values can be matchers or substitutions, but not both.  This is both a protection against potentially confusing behavior, and a guarantee that we won't have to deal with potential injection attacks related to any current or future matcher syntax.  Syntax-agnostic escaping basically.

How substitutions are performed in `request`/`review` blocks are via the `claims_to_roles` mapping, which is an alternative to supplying a simple list of matchers via `roles`.  Here's an example that achieves the same effect as what was proposed in #7135:

```yaml
kind: role
metadata:
  name: employee
spec:
  allow:
    request:
      roles: [...]
      claims_to_roles:
        - claim: 'groups-request'
          value: '^product-(.*)$'
          roles: ['$1-admin']
version: v3
```

It is definitely possible to update the `roles: [...]` list to also support the more common `{{...}}` substitution syntax, but I'd rather not if it can be avoided. If we were to introduce variable substitution to the `roles: [...]` list, I'd prefer we used the more explicit and flatter namespace style that is used in the predicate syntax of the `review` and `threshold` blocks (e.g. `requestor.traits` rather than `user.spec.traits`).  Custom namespaces like this are used because the access request system is unique in being the only part of teleport's rbac where we can refer to the properties of a user other than the role's holder (e.g. the requestor's role might contain the predicate `contains(reviewer.roles,"proletariat")`... this predicate is accessing the role list of a *different* user).

---

Sorry for the wall of text.  Point is, how about we strip the access-request specific parts of this, merge it, and re-assign #7135 to me as a docs issue?

**Comment by tcsc** [comment]
@fspmarshall - I'm happy to do that.

I'll split out the refactor/tidy and push it up in a separate PR, and leave this one here for now now for the purposes of discussion. It can be closed if/when everyone agrees that the use case is covered by the existing `claims_to_roles` mechanism.

**Comment by tcsc** [comment]
@russjones are you happy with @fspmarshall's approach above?

**Comment by tcsc** [comment]
Documentation updates in PR #7791.

**Comment by russjones** [comment]
@tcsc Are we still keeping this or getting rid of it?

**Comment by tcsc** [comment]
Obsoleted by #7791

**Pull request closed without merging**
