### PR TITLE
Variable exporting fix on AWS Terraform Guide

### PR DESCRIPTION
**Pull request by webvictim**
There was an issue with the formatting when exporting the bastion and auth IP. 

The name-value pairs must be enclosed in their own set of quotes, they should not be lumped together under a single set of quotes. 
There must be a space between the two pairs of name/value pairs. 

(I ensured I was running the latest version of AWS CLI 2 and the latest version of Terraform)

Signed-off-by: Gus Luxton <gus@goteleport.com>

### CODE REVIEW

**Comment by webvictim** [comment]
PR buddy for #6565

**Review by benarent — APPROVED** [review]

**Review by russjones — APPROVED** [review]
Bot.

**Comment by webvictim** [comment]
@klizhentas @inertial-frame Could we get a CODEOWNER stamp please?

**Review by inertial-frame — APPROVED** [review]
Related to: https://github.com/gravitational/teleport/pull/6565

**Pull request merged**
