### PR TITLE
Skip userinfo if provider doesn't support it.

### PR DESCRIPTION
**Pull request by jplana**
While integrating the CoreOS Dex  oidc (https://github.com/coreos/dex) with teleport we found a problem during the claim validation process:

Dex doesn't implement the UserInfo endpoint, which seems to be optional anyway according to the standard  (see coreos/dex#376).

Teleport auth service crashes when requesting this endpoint as in:

```go 
func claimsFromUserInfo(oidcClient *oidc.Client, issuerURL string, accessToken string) (jose.Claims, error) {
        err := isHTTPS(issuerURL)
        if err != nil {
                return nil, trace.Wrap(err)
        }

        oac, err := oidcClient.OAuthClient()
        if err != nil {
                return nil, trace.Wrap(err)
        }
        hc := oac.HttpClient()

        // go get the provider config so we can find out where the UserInfo endpoint is
        pc, err := oidc.FetchProviderConfig(oac.HttpClient(), issuerURL)
        if err != nil {
                return nil, trace.Wrap(err)
        }
        endpoint := pc.UserInfoEndpoint.String()
````
`pc.UserInfoEndpoint` is casted to String.

This PR tries to avoid this crash by checking for the UserInfoEndpoint presence in the provider configuration, using just the token claims in this case. 

Do you think this would be a good approach?

### CODE REVIEW

**Comment by russjones** [comment]
@jplana Good catch, I'll review your PR shortly.

**Comment by russjones** [comment]
@gravitational-jenkins okay to test

**Comment by russjones** [comment]
@gravitational-jenkins test this please

**Review by klizhentas — APPROVED** [review]

**Review by russjones — APPROVED** [review]

**Comment by russjones** [comment]
@gravitational-jenkins test this please

**Comment by jplana** [comment]
Great! :-)

**Pull request merged**
