### PR TITLE
[Assist] Implement in-memory vector DB

### PR DESCRIPTION
**Pull request by jakule**
In order to include embeddings in the Assist conversations, we need a way to store and retrieve when needed. This PR adds vector store/search implementation based on k-d tree.

Closes https://github.com/gravitational/teleport.e/issues/1555

### CODE REVIEW

**Review by xacrimon — APPROVED** [review]

**Review by flyinghermit — APPROVED** [review]
LGTM at code level (not a KNN expert). 
Any particular reason we chose to use `https://github.com/kyroy/kdtree`? (pardon if that's already discussed elsewhere)

**Comment by jakule** [comment]
> Any particular reason we chose to use https://github.com/kyroy/kdtree? (pardon if that's already discussed elsewhere)

It's the best from what I found. We do not have enough data to run our own DB (benefits are not worth the maintenance cost), and it's better than naive implementation (search time `O(n)` vs `O(lg n)`). If we ever hit some issues with it should be easy to replace (my implementation doesn't leak any implementation details for that reason).

**Comment by jakule** [comment]
Friendly ping @ravicious

**Review by ravicious — APPROVED** [review]
bot

**Pull request merged**
