### PR TITLE
[v14] DiscoveryConfig: Update status after each run

### PR DESCRIPTION
**Pull request by tigrato**
Backport #40267 to branch/v14

### CODE REVIEW

**Review by codingllama — APPROVED** [review]

**Comment by codingllama** [comment]
Compile problems here too?

**Comment by tigrato** [comment]
> Compile problems here too?

This backport depends on the other back port (the derive one).
Once the other merged, I will rebase this one

**Review by r0mant — APPROVED** [review]
Looks like you made a lot of CI gods unhappy with this PR.

**Comment by tigrato** [comment]
@r0mant can I get `/excludeflake *` as I had to adapt several existing tests that now run with flaky test checker

**Pull request merged**
