### PR TITLE
Docs: expand user creation or update for MySQL/Mariadb

### PR DESCRIPTION
**Pull request by alexfornuto**
The current guide covers altering an existing user to use certificates, but not to remove an existing password, which breaks Teleport's auth:

```
❯ tsh db connect aDatabase                                    at  12:31:38 PM
ERROR 1105 (HY000): ERROR 1045 (28000): Access denied for user 'alice'@'localhost' (using password: NO)
ERROR: exit status 1
```

This PR adds a tip-styled admonition explaining the issue, and providing instructions to set a null password.

### CODE REVIEW

**Review by ptgott — APPROVED** [review]

**Comment by jentfoo** [comment]
Question, as someone new (pardon my ignorance).

I am a little concerned about the recommendations to manipulate an existing user.  This may break existing integrations a customer has.  Also if the customer fails to update the user to require the CN / mutual auth, it may leave the customer exposed.

Instead would it be better to only recommend the creation of a new user which we can more predictably know the configuration for?  In addition when defining the new user we may want to consider recommending specifying a connecting host limitation (I would expect in general this would be localhost only).

**Comment by alexfornuto** [comment]
@jentfoo all good points. I made this PR because of a technical issue I ran into following the guide as-is. All I can say for sure is that _something_ needs to change, but I have no strong opinion on the best change.

Pinging @rsyracuse as our Database Access SME on the docs team for their input.

**Comment by rsyracuse** [comment]
> Question, as someone new (pardon my ignorance).
> 
> I am a little concerned about the recommendations to manipulate an existing user. This may break existing integrations a customer has. Also if the customer fails to update the user to require the CN / mutual auth, it may leave the customer exposed.
> 
> Instead would it be better to only recommend the creation of a new user which we can more predictably know the configuration for? In addition when defining the new user we may want to consider recommending specifying a connecting host limitation (I would expect in general this would be localhost only).

I agree that with how the guide is currently written, it's strange to mention adjusting permissions for a pre-existing database user, especially without bringing up any caveats. Something else I also find concerning is we mention setting the very permissive permissions ```GRANT ALL ON `%`.*``` with a confusingly formatted delineation between the new user/existing user.

Though this goes beyond the requested changes in this PR alone, I'm in favor of adding some cautionary notes for pre-existing/prod databases as part of an introduction in this and other db docs to help ensure that users understand that making changes in production has risks if the environment is not well understood by the db admins implementing the change. We can clearly state that we describe requirements for a working secure teleport configuration, and that this guide relies on a simplified sandbox environment using a new isolated database user to best highlight Teleport functionality.  We can then reduce scope a bit to help avoid these kinds of issues. Thoughts?  @alexfornuto @jentfoo

**Comment by jentfoo** [comment]
@rsyracuse Your recommendations sound great to me!  Thank you for looking at this PR with me

**Comment by alexfornuto** [comment]
I'd echo the sentiment above, the suggested plan sounds great! I haven't looked at our other DB docs for parity, but if there's a similar section in each one I wonder how much content we can re-use, especially with [partial parameters](https://goteleport.com/docs/contributing/documentation/reference/#partial-parameters). At the very least, we could write an internal template to standardize how we discuss this and adjust for each DB environment.

I'm happy to add the suggestion cautions to this PR, or increase the scope and have this branch used to work on the changes suggested.

**Comment by rsyracuse** [comment]
> I'd echo the sentiment above, the suggested plan sounds great! I haven't looked at our other DB docs for parity, but if there's a similar section in each one I wonder how much content we can re-use, especially with [partial parameters](https://goteleport.com/docs/contributing/documentation/reference/#partial-parameters). At the very least, we could write an internal template to standardize how we discuss this and adjust for each DB environment.
> 
> I'm happy to add the suggestion cautions to this PR, or increase the scope and have this branch used to work on the changes suggested.

Partials sound like a really good call. I know there are a few database docs where we're currently context switching between new and pre-existing users, or are otherwise making changes that we may want to treat with more sensitivity. We can spend some time workshopping a partial here, and I can work on updating the library in parity with the changes we make to this doc in a new PR once that's done.

**Comment by ptgott** [comment]
@alexfornuto Just following up on whether this one needs any more work/whether we should get another review. Thanks!

**Comment by alexfornuto** [comment]
@ptgott I think rsyracuse was gonna work on this back when we last talked about it. It needs more work, and the scoped has creeped based on the discussion above. I'll block some time for this next week.

**Comment by ptgott** [comment]
@alexfornuto Is this one still mergeable? If so, I can see if I can find someone else to review it.

**Comment by alexfornuto** [comment]
@ptgott this is not mergable as is. It has finally risen back to the top of my queue to review and update.

**Comment by alexfornuto** [comment]
@jentfoo @ptgott I re-did this change to now use tabs to split between creating a new mysql user or use an existing one. The new user creation has a warning about following the principle of least privilege, and the existing user instruction warns about existing integrations before removing the password.

Please have another look!

**Review by jentfoo — APPROVED** [review]
Reads much better to me, thank you for iterating on this!

**Review by ptgott — APPROVED** [review]

**Pull request merged**
