### PR TITLE
Update Helm to v3.9.0

### PR DESCRIPTION
**Pull request by zmb3**
This update to helm adds a `--quiet` flag to helm lint, which will
clean up our linter output. A subsequent PR will enable the use of
this new flag so as not to break the build.

### CODE REVIEW

**Review by espadolini — APPROVED** [review]

**Review by Joerger — APPROVED** [review]

**Comment by zmb3** [comment]
Note: do not enable auto-merge. Looks like we need to remove the pod security policy before linting with this version will succeed.

**Comment by zmb3** [comment]
Blocked on #11287

**Comment by hugoShaka** [comment]
The charts are now compatible with 1.25 but lint is still not passing with helm 3.9 because helm declares the `policy/v1beta1` capability when templating/linting. This is not really configurable, they [only added a flag to add capabilities](https://github.com/helm/helm/pull/5392) and [it only works for the `template` subcommand](https://github.com/helm/helm/issues/10190).

I see several workarounds, all of them imply to stop linting/testing PSPs:
- Change the capability check to something that evaluates to false by default but true against a real cluster (check `API.Has` on PSPs instead of the resource group?)
- Rely on kube and helm version (our helm3-unit fork lacks a lot of feature, including version control, it always reports Kube 1.16, this will be an issue)
- Lint with `--set psp: false` a bit dirty but ensures PSPs are still tested

**Comment by hugoShaka** [comment]
Replaced by https://github.com/gravitational/teleport/pull/12760

**Pull request closed without merging**
