### PR TITLE
Try to fix `TestAppAccess/TestAppInvalidateAppSessionsOnLogout` flaky test

### PR DESCRIPTION
**Pull request by gabrielcorado**
Related to #16200.

After reproducing this issue on a lower-end machine running on Linux, the cause of the test failure is due to the gRPC call [`DeleteUserAppSessions`](https://github.com/gravitational/teleport/blob/master/lib/web/sessions.go#L809) being canceled with the context deadline exceeded, causing the endpoint `DELETE /webapi/sessions`  to return with status code `504`.

After troubleshooting, this endpoint had to [list, filter, and delete app sessions](https://github.com/gravitational/teleport/blob/master/lib/services/local/session.go#L226) from the entire test suite. It was able to delete most of the sessions but failed before removing all of them.

The solution in this PR is to keep the number of app sessions low, so when it comes the the `TestAppAccess/TestAppInvalidateAppSessionsOnLogout` test, it has to drop a single app session. After the change, I couldn't reproduce the error again, but it is worth letting it run until closing the issue.

**Note: Although this change makes the test more stable, it doesn't seem to be the root cause. The endpoint should handle a significant number of app sessions better. I'll perform more tests to see if this issue is related to the memory backend or if it happens with other backends, too.**

### CODE REVIEW

**Comment by jakule** [comment]
If this test is flaky I'd personally prefer to disable it for now rather than covering up the root cause. Have you tried to increase the timeout to make this test more stable? I know this is probably also not an ideal solution, but I think it's still better than ignoring the error in this test.

**Review by zmb3 — APPROVED** [review]
> but I think it's still better than ignoring the error in this test.

He's not ignoring the error in the test. He's making it less likely to occur by cleaning up app sessions at the end of each test.

He's ignoring the error from the cleanup because some of the tests may do their own cleanup. This is better than simply increasing the timeout IMO.

LGTM

**Comment by gabrielcorado** [comment]
> If this test is flaky I'd personally prefer to disable it for now rather than covering up the root cause.

I see what you mean. I thought this test should only validate that this functionality (invalidate sessions on logout) works correctly. If any issue affects it, we should add a new test that reproduces it reliably (instead of a flaky test), guaranteeing that we solved the problem. So, removing the flakiness by making all tests on this suite more isolated seems an overall good improvement for now, and then we can focus on identifying and solving the root cause.

> Have you tried to increase the timeout to make this test more stable?

I've tested with a hard-coded greater timeout, improving the success rate but not solving it. Still, it requires more troubleshooting to identify and provide reliable reproduction steps for this issue.

**Comment by jakule** [comment]
> > but I think it's still better than ignoring the error in this test.
> 
> He's not ignoring the error in the test. He's making it less likely to occur by cleaning up app sessions at the end of each test.
> 
> He's ignoring the error from the cleanup because some of the tests may do their own cleanup. This is better than simply increasing the timeout IMO.
> 
> LGTM

@zmb3 Why must the test delete the session at the end? Is this something that we should also do in the production code? What if the session is left anyways? This change only helps to increase the pass rate of our tests. We should focus on fixing the code instead of optimizing the pass rate.
Second, if we decide to remove the session, we should not ignore the error. I think that we should be explicit about what is happening and what our testing conditions are. We should either always remove the session in the clean-up block or always require the test to remove it (probably the first, as it's less error-prone).
If we want to go this route, we should not ignore the error in the cleanup and fix all tests that already do that. Then, we're explicit about the session cleaning logic and do not "try" to remove it, as this may help to make a test pass. We can also catch potential errors related to session removal logic.
In parallel, we should analyze why this test is failing, as we still don't know how to fix it permanently.

**Comment by zmb3** [comment]
Fair enough.

**Comment by gabrielcorado** [comment]
I've updated the PR to delete app sessions inside the tests explicitly.

**Comment by jakule** [comment]
I think that @rosstimothy is right. I tested "unbundled" version, and it seems to work fine (the current configuration fails on my machine every time). I've created a PR with the change https://github.com/gravitational/teleport/pull/20027
I've tried to separate all the tests, but that adds minutes to the runtime. Looks like the tests are CPU bounded, and here is a CPU profile from the unbundled version: 

Screenshot from 2023-01-10 00-32-31

I'm not sure what exactly is happening there, and I'll try to look at it later this week. It sounds a bit crazy that this test suite is CPU bound on 24-core machines and takes 5 minutes to run when unbundled...

**Comment by gabrielcorado** [comment]
Closing in favor of #20027.

**Pull request closed without merging**
