### PR TITLE
[v16] Include 15.4.3 and 15.4.4 changes in v16 changelog

### PR DESCRIPTION
**Pull request by stevenGravy**

### CODE REVIEW

**Review by fheinecke — COMMENTED** [review]
AFAIK we don't usually do this once a new major is cut. Are there entries here that are missing from v16, which also describe entries that are currently in v16?

Why do these need to be in the v16 branch changelog instead of just on v15?

Also, has the changelog generation tool been tested against this to confirm that adding these entries will not break changelog generation?

**Review by r0mant — APPROVED** [review]
Yeah we're not consistent about this but changelog on the docs site is displayed off of "active" branch so no harm in including these.

**Review by fheinecke — APPROVED** [review]

**Comment by stevenGravy** [comment]
> AFAIK we don't usually do this once a new major is cut. Are there entries here that are missing from v16, which also describe entries that are currently in v16?
> 
> 
> 
> Why do these need to be in the v16 branch changelog instead of just on v15?
> 
> 
> 
> Also, has the changelog generation tool been tested against this to confirm that adding these entries will not break changelog generation?

The changelog in the docs will only show the current version you are on, even if you change versions. Especially that a new binary introduced in v15.4.3 was introduced seems important to include that's not mentioned in v16.

**Comment by fheinecke** [comment]
> The changelog in the docs will only show the current version you are on, even if you change versions. Especially that a new binary introduced in v15.4.3 was introduced seems important to include that's not mentioned in v16.

We should probably rework that page (if technically feasible) and/or our changelog process at some point. Completely get the need for this now, but this isn't something we typically do so it's probably not a great experience for customers.

**Pull request merged**
