### PR TITLE
Bump cloud docs to 12.1.5

### PR DESCRIPTION
**Pull request by evanfreed**
Upgrade docs to use the latest cloud version.

### CODE REVIEW

**Review by ptgott — APPROVED** [review]

**Comment by zmb3** [comment]
Was cloud actually updated to 12.1.5? I thought we might go straight to 12.2.0.

**Comment by evanfreed** [comment]
@zmb3 Cloud upgrades occur on Wednesday, but we base the decision (loosely) to upgrade or not based on what has been released as of Friday.  In this case, `12.1.5` came out Friday so that's our current target.  If there's reasons to delay feel free to let me know.

**Review by zmb3 — APPROVED** [review]

**Comment by evanfreed** [comment]
It sounds like if 12.2 gets out the door today we'll switch to that.  I won't merge until I know for sure 👍

**Comment by evanfreed** [comment]
Bumped to `12.2.0` Jim clarified we're waiting for this release which is probably what you were eluding to 😄

**Comment by jimbishopp** [comment]
We're proceeding with 12.1.5

**Pull request merged**
