### PR TITLE
Fix azure protobuf

### PR DESCRIPTION
**Pull request by GavinFrazar**
I made a mistake in #15673 yesterday adding a field to Azure metadata protobuf, giving "ResourceID" the same json key as "Name".

### CODE REVIEW

**Review by r0mant — APPROVED** [review]

**Review by gabrielcorado — APPROVED** [review]

**Review by zmb3 — APPROVED** [review]
Change looks good, but feels like there should be a linter that can catch this and prevent it from happening again. Mind investigating?

**Comment by r0mant** [comment]
Wouldn't https://github.com/gravitational/teleport/pull/15856 catch things like this? cc @codingllama

**Comment by zmb3** [comment]
I would think it best to have a Go linter that catches this in the generated code, as opposed to trying to teach buf about `gogoproto.jsontag`.

**Comment by zmb3** [comment]
In fact, looks like gopls does catch this:

image

**Comment by codingllama** [comment]
> Wouldn't #15856 catch things like this? cc @codingllama
> 
> Although it looks like "legacy" protobufs are ignored there.

I don't think linters would go as deep as gogo JSON tags, sadly.

Btw, since we are talking about this, I do have a follow up to enable some linting in legacy protos. Just wait for it.  :)

**Pull request merged**
