### PR TITLE
Update Go toolchain to 1.20

### PR DESCRIPTION
**Pull request by codingllama**
Update Go toolchain to 1.20. Source level is still 1.19.

* https://go.dev/doc/go1.20

### CODE REVIEW

**Comment by codingllama** [comment]
e/ counterpart: https://github.com/gravitational/teleport.e/pull/788. Please take a look too, I'll pull the correct commit once that lands.

I've tagged backports, but I'll hold those for after v12.0 is out.

**Comment by codingllama** [comment]
As mentioned elsewhere, these drew my attention:

crypto/tls
> For a handshake failure due to a certificate verification failure, the TLS client and server now return an error of the new type [CertificateVerificationError](https://go.dev/pkg/crypto/tls/#CertificateVerificationError), which includes the presented certificates.

math/rand
> The [math/rand](https://go.dev/pkg/math/rand/) package now automatically seeds the global random number generator (used by top-level functions like Float64 and Int) with a random value, and the top-level [Seed](https://go.dev/pkg/math/rand/#Seed) function has been deprecated. Programs that need a reproducible sequence of random numbers should prefer to allocate their own random source, using rand.New(rand.NewSource(seed)).

> Programs that need the earlier consistent global seeding behavior can set GODEBUG=randautoseed=0 in their environment.

os
> On Windows, the name NUL is no longer treated as a special case in [Mkdir](https://go.dev/pkg/os/#Mkdir) and [Stat](https://go.dev/pkg/os/#Stat).

I've been running 1.20-rc for a while and didn't see anything untoward happen, so I figured I'd ship the PRs to get started.

**Review by jakule — APPROVED** [review]
@codingllama Thanks for the PR.

**Review by r0mant — APPROVED** [review]

**Comment by codingllama** [comment]
e/ reference is correct and I've got the go ahead for master, so going ahead. I'll hold v12/11/10 for after v12.0, as promised.

**Pull request merged**
