### PR TITLE
[v16] Check if binary exists before passing it to node-pty

### PR DESCRIPTION
**Pull request by ravicious**
Backport #44440.

changelog: Fixed terminal sessions with a database CLI client in Teleport Connect hanging indefinitely if the client cannot be found

### CODE REVIEW

**Review by gzdunek — APPROVED** [review]
You need to rebase this one, `pnpm` is merged to v16.

**Comment by ravicious** [comment]
@ryanclark ping

**Review by ryanclark — APPROVED** [review]
Sorry, was waiting for the rebase as auto merge was enabled :)

**Comment by ravicious** [comment]
hehe np; though it wouldn't get merged because of a merge conflict

**Comment by ryanclark** [comment]
> hehe np; though it wouldn't get merged because of a merge conflict

ah very true!

**Pull request merged**
