### PR TITLE
Add tunnel listener and target group to Terraform example for use with ACM

### PR DESCRIPTION
**Pull request by webvictim**
A customer recently discovered that our Terraform example code doesn't make it possible to use trusted clusters with ACM "out of the box". If they'd been using Letsencrypt, this would have been possible without any modifications due to Teleport's ability to multiplex tunnel and web traffic over the same port. This multiplexing doesn't work when using ACM because it requires the use of an ALB for AWS to terminate the SSL traffic (rather than passing the traffic straight through via NLB as it does for Letsencrypt, allowing Teleport to inspect the traffic and determine the correct protocol)

This PR adds the extra listener and target group needed to make tunnel connections work straight away with ACM and facilitate the use of trusted clusters. It also fixes a couple of typos and bumps the Teleport version in the AMI `Makefile`.

### CODE REVIEW

**Review by benarent — APPROVED** [review]

**Comment by benarent** [comment]
Looks good, one future improvement would be to add a node that has enhanced session recording setup as part of the setup.

**Comment by webvictim** [comment]
@benarent Yes, agreed. I'm planning to do another PR shortly to update from Terraform v0.11.7 to v0.12.20 (which I think is the most recent) so once that's done and everything is working, I'll look at getting enhanced session recording into the mix.

**Comment by benarent** [comment]
The v0.12 should be fun upgrade https://www.terraform.io/upgrade-guides/0-12.html

**Comment by webvictim** [comment]
Yeahhhh, not looking forward to that one. It needs doing though!

**Pull request merged**
