### PR TITLE
Move `UnifiedResourcePreferences` to `shared`

### PR DESCRIPTION
**Pull request by gzdunek**
The `UnifiedResourcePreferences` interface, `UnifiedTabPreference` and `UnifiedViewModePreference` types are already used in Connect code. We shouldn't import from `teleport`, so I move them to shared. 

Ideally, instead of declaring the types and enums on our own, we should auto-generate them from a `.proto` file. I spent some time trying to make it work, but unfortunately with no success. The two problems that I encountered:
* Vite doesn't work with CommonJS code, I'd have to somehow convert it to ESM (probably with a plugin).
* We not only want to import types, but also the runtime code (enums) which means that importing an enum would also mean importing all that `google-protobuf` stuff, so Web UI size would grow :( Perhaps it could be tree-shaked, but idk.

I gave up on that and only changed keys of enums to look like in the generated JS files (this will make my life a bit easier when adding resource pinning to Connect). I also left a comment that they should be kept in sync with `.proto` definition.

### CODE REVIEW

**Review by avatus — APPROVED** [review]

**Comment by ibeckermayer** [comment]
@gzdunek did you try [this native vite solution](https://vitejs.dev/guide/dep-pre-bundling.html#monorepos-and-linked-dependencies) for converting CommonJS to ESM?

**Comment by gzdunek** [comment]
This seems to work for production builds:
```
build: {
    commonjsOptions: {
      include: [/proto/, /node_modules/],
    },
  },
```
But:
* I see the following warnings when building:
```
../../../node_modules/google-protobuf/google-protobuf.js (23:206) Use of eval in "../../../node_modules/google-protobuf/google-protobuf.js" is strongly discouraged as it poses security risks and may cause issues with minification.
../../../node_modules/google-protobuf/google-protobuf.js (25:315) Use of eval in "../../../node_modules/google-protobuf/google-protobuf.js" is strongly discouraged as it poses security risks and may cause issues with minification.
../../../node_modules/google-protobuf/google-protobuf.js (47:475) Use of eval in "../../../node_modules/google-protobuf/google-protobuf.js" is strongly discouraged as it poses security risks and may cause issues with minification.
```
* The size of `index.js` is now 960.28 kB instead of 655.29 kB.

I import the enum like this:
```
import { DefaultTab } from 'gen-proto-js/...'
```
so it could take only it and drop the `protobuf` code, but this is not the case.

**Review by rudream — APPROVED** [review]

**Comment by ibeckermayer** [comment]
> But:
> 
> * I see the following warnings when building:
> 
> ```
> ../../../node_modules/google-protobuf/google-protobuf.js (23:206) Use of eval in "../../../node_modules/google-protobuf/google-protobuf.js" is strongly discouraged as it poses security risks and may cause issues with minification.
> ../../../node_modules/google-protobuf/google-protobuf.js (25:315) Use of eval in "../../../node_modules/google-protobuf/google-protobuf.js" is strongly discouraged as it poses security risks and may cause issues with minification.
> ../../../node_modules/google-protobuf/google-protobuf.js (47:475) Use of eval in "../../../node_modules/google-protobuf/google-protobuf.js" is strongly discouraged as it poses security risks and may cause issues with minification.
> ```

Sounds like a fundamental incompatibility between how the protobuf runtime works and what vite wants from us.

> * The size of `index.js` is now 960.28 kB instead of 655.29 kB.
> 
> I import the enum like this:
> 
> ```
> import { DefaultTab } from 'gen-proto-js/...'
> ```
> 
> so in theory, it could take only that enum and drop the `protobuf` code, but it doesn't do it. I don't see a way to configure it in Vite.

Gotcha, it was worth a shot anyways, thanks for double checking.

**Comment by gzdunek** [comment]
One more change:
I found out that to assign one enum to another, not only their values must be the same, but also the names of the enums.
Because of that, I rename `UnifiedTabPreference` to `DefaultTab`, `UnifiedViewModePreference` to `ViewMode`. I also moved them to the separate file.

Without the rename, I would have to do these manual conversions in Connect code 🥴
```ts
      const mapTabPreference = (t: UnifiedTabPreference): DefaultTab => {
        switch (t) {
          case UnifiedTabPreference.DEFAULT_TAB_UNSPECIFIED:
            return DefaultTab.DEFAULT_TAB_UNSPECIFIED;
          case UnifiedTabPreference.DEFAULT_TAB_ALL:
            return DefaultTab.DEFAULT_TAB_ALL;
          case UnifiedTabPreference.DEFAULT_TAB_PINNED:
            return DefaultTab.DEFAULT_TAB_PINNED;
        }
      };
```

**Comment by avatus** [comment]
> One more change:
> 
> I found out that to assign one enum to another, not only their values must be the same, but also the names of the enums 

Woah I had no idea. TIL

**Review by avatus — APPROVED** [review]

**Pull request merged**
