### PR TITLE
Add tests for AMR notification routing for discord plugin

### PR DESCRIPTION
**Pull request by EdwardDowling**
Part of [42856](https://github.com/gravitational/teleport/issues/42856)

### CODE REVIEW

**Review by marcoandredinis — APPROVED** [review]
Looks good, but it would be nice to have some testing

**Review by tigrato — COMMENTED** [review]
Is there a way of testing this?

**Comment by EdwardDowling** [comment]
> Is there a way of testing this?
Adding in some test coverage at the moment.

**Review by tigrato — APPROVED** [review]

**Review by r0mant — COMMENTED** [review]
@EdwardDowling Is this finished? Can we get this merged?

**Comment by EdwardDowling** [comment]
> @EdwardDowling Is this finished? Can we get this merged?

Waiting on https://github.com/gravitational/teleport/pull/43714 being merged first so we dont' run into another case of the AMR watcher failing to start and preventing plugins working for people who aren't using it.

**Comment by EdwardDowling** [comment]
Changes made in refactor [here](https://github.com/gravitational/teleport/pull/43298) means the explicit enabling of Discord is no longer needed. Going to only add the tests in this PR

**Comment by EdwardDowling** [comment]
@marcoandredinis Can you take another look at this when you get a chance?

**Review by marcoandredinis — APPROVED** [review]

**Review by tigrato — APPROVED** [review]

**Pull request merged**
