### PR TITLE
Update release table to 6.0.0

### PR DESCRIPTION
**Pull request by r0mant**
https://github.com/gravitational/teleport/pull/5838 forward-port.

### CODE REVIEW

**Comment by webvictim** [comment]
As per https://github.com/gravitational/teleport/pull/5838#issuecomment-790843292 I feel like we shouldn't have a second set of links for download now that database access is GA.

**Comment by klizhentas** [comment]
I agree with @webvictim please just point to downloads page.

**Comment by klizhentas** [comment]
@r0mant we removed the releases table completely, can you please update this forward port and the original PR?

**Comment by r0mant** [comment]
@klizhentas Done, links to it were already removed from the docs as well so now this PR just fixes a couple of traling slashes.

**Review by webvictim — APPROVED** [review]

**Review by klizhentas — APPROVED** [review]

**Pull request merged**
