### PR TITLE
Fix typo which prevents certificate renewal on all-in-one AMI installs

### PR DESCRIPTION
**Pull request by webvictim**
Fixes a clumsy typo which meant that the LetsEncrypt certificate never gets renewed when running with role `all`

### CODE REVIEW

**Review by benarent — APPROVED** [review]

**Review by fspmarshall — APPROVED** [review]

**Comment by webvictim** [comment]
@russjones ping

**Review by benarent — APPROVED** [review]

**Review by russjones — APPROVED** [review]

**Comment by webvictim** [comment]
retest this please

**Comment by webvictim** [comment]
retest this please

**Comment by webvictim** [comment]
retest this please

**Comment by webvictim** [comment]
retest this please

**Comment by webvictim** [comment]
retest this please

**Comment by webvictim** [comment]
retest this please

**Comment by webvictim** [comment]
retest this please

**Comment by webvictim** [comment]
retest this please

**Pull request merged**
