### PR TITLE
CodeQL: Rename from codeql-analysis.yml to codeql.yml

### PR DESCRIPTION
**Pull request by jentfoo**
Renaming from the currently used `codeql-analysis.yml` to the GitHub default naming of `codeql.yml`.  The default naming was already committed to 3 other repo's.  By using the default hopefully we will be more likely to stay consistent in our naming.

### CODE REVIEW

**Comment by zmb3** [comment]
I see the _what_ in the title, but I'm missing the _why_. Any particular reason we need to do this?

**Comment by jentfoo** [comment]
@zmb3, I had committed to three repo's the config file using GitHub's default naming of  `codeql.yml`.

@reedloden pointed out that this was previously named `codeql-analysis.yml` and asked that we pick a consistent naming scheme.

To me when picking between the two names I lean towards the GitHub default naming.  I feel like using the default naming reduces the risk of any future inconsistency.  But if we prefer the more verbose `codeql-analysis`, I don't have a strong preference.  I will just need to open 3 different PR's to rename those committed files to remain consistent with this project.

Let me know what you think, thank you!

**Comment by reedloden** [comment]
I think GitHub used to suggest `codeql-analysis.yml` as the default, so they must have changed that to `codeql.yml` at some point. I have zero preference as to which is used, but yeah, would be nice to keep them in sync across all our repositories.

Note that this change will need to be backported.

**Review by reedloden — APPROVED** [review]

**Review by zmb3 — APPROVED** [review]
Got it. Thanks @jentfoo.

I have no preference what it is named, I was just looking at the commit message to try and understand the purpose of the change and found it lacking.

**Pull request merged**
