### PR TITLE
Pin now time during the access request creation

### PR DESCRIPTION
**Pull request by jakule**
To prevent time drift, this change pins the time during access time calculations.
Remove the fake clock from the tests to better simulate the real-time behavior.

changelog: Fix `invalid session TTL` when creating access request with `tsh`

### CODE REVIEW

**Review by mdwn — APPROVED** [review]

**Review by kimlisa — APPROVED** [review]
🙏

**Review by zmb3 — APPROVED** [review]
Looks good, but I also think its odd that we do a time comparison (without rounding times) and then log the rounded version of the time. This makes troubleshooting difficult.

Should we either round before comparing, or log the exact values that we used to do the comparison?

**Comment by jakule** [comment]
> Looks good, but I also think its odd that we do a time comparison (without rounding times) and then log the rounded version of the time. This makes troubleshooting difficult.
> 
> Should we either round before comparing, or log the exact values that we used to do the comparison?

I changed the logger to log the exact value.

**Pull request merged**
