### PR TITLE
Remove all pixels besides google tag manager

### PR DESCRIPTION
**Pull request by aberoham**
See related PR in gravitational/web

### CODE REVIEW

**Comment by aberoham** [comment]
squash attempted

**Comment by klizhentas** [comment]
ok to test

**Comment by klizhentas** [comment]
retest this please

**Comment by klizhentas** [comment]
ok, LGTM, if looks good to @alexwolfe

**Review by alexwolfe — APPROVED** [review]

**Comment by klizhentas** [comment]
@aberoham can you please resolve the conflicts and rebase?

**Pull request merged**
