### PR TITLE
[sec_scan][3] add `PrivateKey`, `AuthorizedKey` and `Device` to Access Graph resources

### PR DESCRIPTION
**Pull request by tigrato**
This PR extends the Access Graph resources to be able to include the newly added `teleport.access_graph.v1.PrivateKey`, `teleport.access_graph.v1.AuthorizedKey` and existing device trust information `teleport.devicetrust.v1.Device`.

Part of https://github.com/gravitational/access-graph/issues/637

### CODE REVIEW

**Review by ibeckermayer — APPROVED** [review]
Not sure what all these lint failures are about (bug in the linter?)

image

**Comment by tigrato** [comment]
Friendly ping @smallinsky

**Review by smallinsky — APPROVED** [review]
Sorry for delay

**Review by marcoandredinis — APPROVED** [review]
Bot

**Pull request merged**
