### PR TITLE
chore: Bump Go dependencies

### PR DESCRIPTION
**Pull request by codingllama**
Keep up with latest releases.

Supersedes the following Dependabot PRs. See originals for detailed release notes.

* https://github.com/gravitational/teleport/pull/19455
* https://github.com/gravitational/teleport/pull/19456
* https://github.com/gravitational/teleport/pull/19457
* https://github.com/gravitational/teleport/pull/19458
* https://github.com/gravitational/teleport/pull/19461
* https://github.com/gravitational/teleport/pull/19462
* https://github.com/gravitational/teleport/pull/19493
* ~https://github.com/gravitational/teleport/pull/19501~ (reverted to 1.1.19)

### CODE REVIEW

**Comment by codingllama** [comment]
FYI @rosstimothy @tobiaszheller @nklaassen.

I'm holding out on k8s update for now, might try those in a separate PR. Running tests locally right now.

**Comment by codingllama** [comment]
Trace 1.1.20 breaks account recovery tests (`go test ./lib/auth -run=AccountRecovery`, for example, `TestCompleteAccountRecovery`). I won't look into it now, so rolling back. FYI @kimlisa @Tener @strideynet.

`go test ./lib/web -run=Terminal` (eg, `TestResizeTerminal` and `TestTerminalRouting/ambiguous_host`) are also flaking heavily for me, even on master, which makes updates like these hard to reason about. FYI @rosstimothy.

**Comment by codingllama** [comment]
Example `TestCompleteAccountRecovery` failure logs:

```
go test ./lib/auth -run=TestCompleteAccountRecovery
=== Failed
=== FAIL: lib/auth TestCompleteAccountRecovery (0.67s)
{"caller":"services/watcher.go:210","component":null,"level":"debug","message":"Starting watch.","resource-kind":"lock","timestamp":"2022-12-20T14:55:12-03:00"}
{"caller":"backend/buffer.go:262","component":"buffer","level":"debug","message":"Add Watcher(name=auth, prefixes=/locks, capacity=1024, size=0).","timestamp":"2022-12-20T14:55:12-03:00"}
{"caller":"keygen/keygen.go:139","component":null,"level":"debug","message":"Generated SSH host certificate for role Auth with principals: [test-tls-server.localhost test-tls-server localhost 127.0.0.1 ::1].","timestamp":"2022-12-20T14:55:13-03:00"}
{"caller":"tlsca/ca.go:1037","common_name":"test-tls-server.localhost","component":"ca","dns_names":["*.teleport.cluster.local","teleport.cluster.local"],"level":"info","locality":[],"message":"Generating TLS certificate {0xc000170060 0xc000449600 1.3.9999.1.7=#13096c6f63616c686f7374,CN=test-tls-server.localhost,O=Auth,POSTALCODE=null,STREET= 1994-04-02 00:00:00 +0000 UTC [*.teleport.cluster.local teleport.cluster.local] [] 5 []}.","not_after":"1994-04-02T00:00:00Z","org":["Auth"],"org_unit":[],"timestamp":"2022-12-20T14:55:13-03:00"}
{"caller":"auth/grpcserver.go:4432","component":"auth","level":"debug","message":"GRPC(SERVER): keep alive 1m0s count: 3.","timestamp":"2022-12-20T14:55:13-03:00"}
{"caller":"services/role.go:267","component":null,"level":"debug","message":"Skipping login llama3112047980440909222@goteleport.com, not a valid Unix login.","timestamp":"2022-12-20T14:55:13-03:00"}
{"caller":"keygen/keygen.go:169","component":null,"level":"debug","message":"generated user key for [-teleport-nologin-0212867b-da64-456d-8693-20cfe9a9be27 -teleport-internal-join] with expiry on (449928000) 1984-04-04 12:00:00 +0000 UTC","timestamp":"2022-12-20T14:55:13-03:00"}
{"caller":"auth/auth.go:1641","component":"auth","level":"debug","message":"Failed setting default kubernetes cluster for user login (user did not provide a cluster); leaving KubernetesCluster extension in the TLS certificate empty","timestamp":"2022-12-20T14:55:13-03:00"}
{"caller":"tlsca/ca.go:1037","common_name":"llama3112047980440909222@goteleport.com","component":"ca","dns_names":null,"level":"info","locality":["-teleport-nologin-0212867b-da64-456d-8693-20cfe9a9be27","-teleport-internal-join"],"message":"Generating TLS certificate {0xc000170060 0xc0008fc080 1.3.9999.1.15=#13046e6f6e65,1.3.9999.1.7=#13096c6f63616c686f7374,CN=llama3112047980440909222@goteleport.com,O=user:llama3112047980440909222@goteleport.com,POSTALCODE=null,STREET=localhost,L=-teleport-nologin-0212867b-da64-456d-8693-20cfe9a9be27+L=-teleport-internal-join 1984-04-04 12:00:00 +0000 UTC [] [] 5 []}.","not_after":"1984-04-04T12:00:00Z","org":["user:llama3112047980440909222@goteleport.com"],"org_unit":[],"timestamp":"2022-12-20T14:55:13-03:00"}
{"caller":"services/role.go:267","component":null,"level":"debug","message":"Skipping login llama3112047980440909222@goteleport.com, not a valid Unix login.","timestamp":"2022-12-20T14:55:13-03:00"}
{"caller":"keygen/keygen.go:169","component":null,"level":"debug","message":"generated user key for [-teleport-nologin-30a62db4-a731-40bd-bcf8-d1fbbeeca345 -teleport-internal-join] with expiry on (449888400) 1984-04-04 01:00:00 +0000 UTC","timestamp":"2022-12-20T14:55:13-03:00"}
{"caller":"auth/auth.go:1641","component":"auth","level":"debug","message":"Failed setting default kubernetes cluster for user login (user did not provide a cluster); leaving KubernetesCluster extension in the TLS certificate empty","timestamp":"2022-12-20T14:55:13-03:00"}
{"caller":"tlsca/ca.go:1037","common_name":"llama3112047980440909222@goteleport.com","component":"ca","dns_names":null,"level":"info","locality":["-teleport-nologin-30a62db4-a731-40bd-bcf8-d1fbbeeca345","-teleport-internal-join"],"message":"Generating TLS certificate {0xc000170060 0xc0004132d0 1.3.9999.1.15=#13046e6f6e65,1.3.9999.1.7=#13096c6f63616c686f7374,CN=llama3112047980440909222@goteleport.com,O=user:llama3112047980440909222@goteleport.com,POSTALCODE=null,STREET=localhost,L=-teleport-nologin-30a62db4-a731-40bd-bcf8-d1fbbeeca345+L=-teleport-internal-join 1984-04-04 01:00:00 +0000 UTC [] [] 5 []}.","not_after":"1984-04-04T01:00:00Z","org":["user:llama3112047980440909222@goteleport.com"],"org_unit":[],"timestamp":"2022-12-20T14:55:13-03:00"}
{"caller":"auth/middleware.go:690","component":"auth","level":"debug","message":"ClientCertPool -\u003e cert(localhost issued by localhost:222723411203725947803181124775945992090)","timestamp":"2022-12-20T14:55:13-03:00"}
{"caller":"auth/middleware.go:690","component":"auth","level":"debug","message":"ClientCertPool -\u003e cert(localhost issued by localhost:18496652423648024346080401752452414428)","timestamp":"2022-12-20T14:55:13-03:00"}
{"caller":"auth/middleware.go:315","component":"auth","level":"debug","message":"Server certificate cert(test-tls-server.localhost issued by localhost:222723411203725947803181124775945992090).","timestamp":"2022-12-20T14:55:13-03:00"}
{"caller":"services/role.go:267","component":null,"level":"debug","message":"Skipping login llama3112047980440909222@goteleport.com, not a valid Unix login.","timestamp":"2022-12-20T14:55:13-03:00"}
{"caller":"auth/auth.go:1893","component":"auth","level":"debug","message":"llama3112047980440909222@goteleport.com user has less than 5 failed login attempts","timestamp":"2022-12-20T14:55:13-03:00"}
{"caller":"auth/methods.go:210","component":"auth","level":"debug","message":"User llama3112047980440909222@goteleport.com failed to authenticate: invalid username or password.","timestamp":"2022-12-20T14:55:13-03:00"}
{"caller":"auth/auth.go:1893","component":"auth","level":"debug","message":"llama3112047980440909222@goteleport.com user has less than 5 failed login attempts","timestamp":"2022-12-20T14:55:13-03:00"}
{"caller":"auth/methods.go:210","component":"auth","level":"debug","message":"User llama3112047980440909222@goteleport.com failed to authenticate: invalid username or password.","timestamp":"2022-12-20T14:55:13-03:00"}
{"caller":"auth/auth.go:1893","component":"auth","level":"debug","message":"llama3112047980440909222@goteleport.com user has less than 5 failed login attempts","timestamp":"2022-12-20T14:55:13-03:00"}
{"caller":"auth/methods.go:210","component":"auth","level":"debug","message":"User llama3112047980440909222@goteleport.com failed to authenticate: invalid username or password.","timestamp":"2022-12-20T14:55:13-03:00"}
{"caller":"auth/auth.go:1893","component":"auth","level":"debug","message":"llama3112047980440909222@goteleport.com user has less than 5 failed login attempts","timestamp":"2022-12-20T14:55:13-03:00"}
{"caller":"auth/methods.go:210","component":"auth","level":"debug","message":"User llama3112047980440909222@goteleport.com failed to authenticate: invalid username or password.","timestamp":"2022-12-20T14:55:13-03:00"}
{"caller":"auth/auth.go:1897","component":"auth","level":"debug","message":"llama3112047980440909222@goteleport.com exceeds 5 failed login attempts, locked until Wed Apr  4 00:20 UTC","timestamp":"2022-12-20T14:55:13-03:00"}
{"caller":"auth/methods.go:210","component":"auth","level":"debug","message":"User llama3112047980440909222@goteleport.com failed to authenticate: too many incorrect attempts, please try again later.","timestamp":"2022-12-20T14:55:13-03:00"}
    accountrecovery_test.go:1304: 
        	Error Trace:	/Users/alan/workspace/teleport/lib/auth/accountrecovery_test.go:1304
        	            				/Users/alan/workspace/teleport/lib/auth/accountrecovery_test.go:632
        	Error:      	Not equal: 
        	            	expected: "invalid username, password or second factor"
        	            	actual  : "too many incorrect attempts, please try again later"
        	            	
        	            	Diff:
        	            	--- Expected
        	            	+++ Actual
        	            	@@ -1 +1 @@
        	            	-invalid username, password or second factor
        	            	+too many incorrect attempts, please try again later
        	Test:       	TestCompleteAccountRecovery
{"caller":"backend/buffer.go:280","component":"buffer","level":"debug","message":"Removing watcher 0xc001068180 via external close.","timestamp":"2022-12-20T14:55:13-03:00"}
{"caller":"backend/buffer.go:283","component":"buffer","level":"debug","message":"Could not find watcher Watcher(name=auth, prefixes=/locks, capacity=1024, size=0).","timestamp":"2022-12-20T14:55:13-03:00"}

DONE 9 tests, 1 failure in 11.148s
```

**Review by rosstimothy — APPROVED** [review]

**Comment by strideynet** [comment]
> Trace 1.1.20 breaks account recovery tests (`go test ./lib/auth -run=AccountRecovery`, for example, `TestCompleteAccountRecovery`). I won't look into it now, so rolling back. FYI @kimlisa @Tener @strideynet.
> 
> `go test ./lib/web -run=Terminal` (eg, `TestResizeTerminal` and `TestTerminalRouting/ambiguous_host`) are also flaking heavily for me, even on master, which makes updates like these hard to reason about. FYI @rosstimothy.

Failures on 1.1.20 are due to https://github.com/gravitational/trace/pull/83 introducing a change in behaviour from mutating the current error to returning a new error when adding fields. https://github.com/gravitational/trace/pull/85 is investigating potential fixes here, and will probably involve a new clearer API. So we'll skip `trace` for this specific dependency update.

**Comment by codingllama** [comment]
Friendly ping @marcoandredinis @timothy-spencer ?

**Review by marcoandredinis — APPROVED** [review]

**Pull request merged**
