### PR TITLE
Fix `yum config-manager` invocation in installers and docs

### LINKED ISSUE #34538: Auto-discovery install script doesn't work on AL2023
## Expected behavior:

EC2 auto-discovery can successfully enroll instances running Amazon Linux 2023.

## Current behavior:

AL2023 instances fail to enroll because the SSM install script runs `yum-config-manager` command which is not recognized:

```
 "documentStatus": "InProgress",
  "documentTraceOutput": "",
  "runtimeStatus": {
    "runShellScript": {
      "status": "Failed",
      "code": 1,
      "name": "aws:runShellScript",
      "output": "\n----------ERROR-------\nsudo: yum-config-manager: command not found\nfailed to run commands: exit status 1",
      "startDateTime": "2023-11-09T08:18:49.275Z",
      "endDateTime": "2023-11-09T08:18:49.342Z",
      "outputS3BucketName": "",
      "outputS3KeyPrefix": "",
      "stepName": "",
      "standardOutput": "",
      "standardError": "sudo: yum-config-manager: command not found\nfailed to run commands: exit status 1"
    }
  }
}
```

Changing the command to `yum config-manager` (note "config-manager" here is a subcommand of yum) fixed the issue for the customer.

Let's:

- [ ] Reproduce this.
- [ ] Fix the install script to support AL2023.
- [ ] Check other install scripts as well for the same issue.
- [ ] Check the installation commands in the documentation for the same issue.

### PR DESCRIPTION
**Pull request by atburke**
This change fixes the invocation of the yum config manager in both the default installers and the docs.

Fixes #34538.

Changelog: Fixed default installer yum error on RHEL and Amazon Linux

### CODE REVIEW

**Review by fheinecke — CHANGES_REQUESTED** [review]
This change not work on CentOS 7 out of the box. `yum-config-manager` needs to be installed on 8 forward, but works on all RHEL based distros. I would recommend adding a check for centos7, install yum-config-manager, or download and parse the repo config file manually.

**Comment by fheinecke** [comment]
Also, if this logic changes then [this test](https://github.com/gravitational/teleport.e/blob/master/.github/workflows/deploy-packages.yaml#L505) must be updated as well.

**Review by hugoShaka — APPROVED** [review]

**Review by r0mant — COMMENTED** [review]
@atburke Yeah, echoing @fheinecke's comment, sorry if the ticket description wasn't clear but this only affects AL2023, other distros should keep using existing command.

**Review by ptgott — APPROVED** [review]

**Review by fheinecke — APPROVED** [review]
LGTM

This test step line should move to the next step as well, to capture the specifics of our install docs: https://github.com/gravitational/teleport.e/blob/master/.github/workflows/deploy-packages.yaml#L557-L558

**Pull request merged**
