### PR TITLE
[v14] terraform: Add support for TLS routing and other improvements

### PR DESCRIPTION
**Pull request by webvictim**
Backport #31237 to branch/v14

### CODE REVIEW

**Review by stevenGravy — APPROVED** [review]

**Comment by hugoShaka** [comment]
This is a significant refactoring which potentially introduces new regressions. We should either hold this PR until the test plan is over and v14 is released or merge it and re-test everything Terraform-related (plus, we might want to update the test matrix based on the cases @webvictim mentioned in the original PR).

**Comment by webvictim** [comment]
If we do merge this, I'm happy to redo the Terraform deployment-related sections of the test plan myself using 14.0.0-beta.2 or 14.0.0-rc.1, whatever's appropriate.

**Review by hugoShaka — APPROVED** [review]
LGTM, in this case can you ping @camscale, as this was assigned to him and run the tests against the v14 branch or a test release after the merge?

Could you also add your tests to [the test plan issue](https://github.com/gravitational/teleport/issues/31122) and commit them to the repo so we'll check them for the next major?

**Review by r0mant — CHANGES_REQUESTED** [review]
@webvictim @hugoShaka TBH I would be a bit hesitant to merge a big refactor like this that can potentially introduce new regressions so close to a major release. We've broken things 3 days before release before and I'd like to avoid that.

I suggest we hold this until after 14 and test this properly before merging so we don't have to rush this.

**Comment by hugoShaka** [comment]
TF has a single test item in the test plan which has not even be checked yet. IMO Blocking this PR makes no sense as the only outcome would be that we would have better test coverage compared to today. If something were to break here, we would not have caught it in the test plan anyway.

**Comment by webvictim** [comment]
Yeah, I agree with @hugoShaka that I don't think this is a high risk PR. I agree it's a large change to the Terraform code overall, but the only parts that could block the release are:
- the test plan fails (I've already executed a much more comprehensive test plan than the one in line item in https://github.com/gravitational/teleport/issues/31122)
- shell tests fail (they're already passing on the PR)
- AMI publishing fails (will be tested as part of the `14.0.0-beta.2` or `14.0.0-rc.1` release, and I'd be happy to fix this immediately or revert the PR to unblock it if needed)

I'd like to get this out for the 14.0.0 release so we can make a concrete statement in the release notes that "TLS routing is supported via Terraform deployments from 14.0.0 onwards".

**Review by zmb3 — APPROVED** [review]
I'm okay with it going in for 14.

**Review by r0mant — APPROVED** [review]
Okay you folks convinced me :) Let's get this in, it's a good change.

**Pull request merged**
