### PR TITLE
Properly load app certificates in `tsh proxy app` for virtual profiles

### LINKED ISSUE #42257: `tbot proxy app` fails: `identity is not allowed to reissue certificates`
Expected behavior:

`tbot proxy app` open a local proxy for an app

Current behavior:

The proxy fails with this message:

```
$ tbot proxy --destination-dir=./tbot-app --proxy-server=teleport.ethernet.fyi:443 app httpbin
Proxying connections to httpbin on 127.0.0.1:38123
To avoid port randomization, you can choose the listening port using the --port flag.
ERROR: access denied: identity is not allowed to reissue certificates

ERROR: executing `tsh proxy`
        unable to execute tsh
                exit status 1
```

<details><summary>Debug log</summary>

```
tbot -d proxy --destination-dir=./tbot-app --proxy-server=teleport.ethernet.fyi:443 app httpbin
2024-05-31T19:24:29-06:00 DEBU [TBOT]      Defaulting to SSHConfigModeOn config/output_identity.go:158
2024-05-31T19:24:29-06:00 DEBU [TBOT]      executing binary path:/home/tim/bin/tsh env:map[TSH_VIRTUAL_PATH_APP:tbot-app/tlscert TSH_VIRTUAL_PATH_CA_DB:tbot-app/teleport-database-ca.crt TSH_VIRTUAL_PATH_CA_HOST:tbot-app/teleport-host-ca.crt TSH_VIRTUAL_PATH_CA_USER:tbot-app/teleport-user-ca.crt TSH_VIRTUAL_PATH_DB:tbot-app/tlscert TSH_VIRTUAL_PATH_KEY:tbot-app/key] args:[-d -i tbot-app/identity proxy --proxy=teleport.ethernet.fyi:443 app httpbin] tshwrap/wrap.go:111
2024-05-31T19:24:29-06:00 INFO [CLIENT]    ALPN connection upgrade required for "teleport.ethernet.fyi:443": false. client/api.go:785
2024-05-31T19:24:29-06:00 INFO [CLIENT]    no host login given. defaulting to tim client/api.go:1123
2024-05-31T19:24:29-06:00 DEBU [CLIENT]    Skipping connection to the local ssh-agent. client/keyagent.go:139
2024-05-31T19:24:29-06:00 DEBU [KEYSTORE]  Teleport TLS certificate valid until "2024-06-01 02:20:02 +0000 UTC". client/client_store.go:111
2024-05-31T19:24:29-06:00 INFO [KEYAGENT]  Loading SSH key for user "bot-robot" and cluster "teleport.ethernet.fyi". client/keyagent.go:198
2024-05-31T19:24:29-06:00 DEBU [TSH]       Pinging the proxy to fetch listening addresses for non-web ports. common/tsh.go:3705
2024-05-31T19:24:29-06:00 DEBU [CLIENT]    not using loopback pool for remote proxy addr: teleport.ethernet.fyi:443 client/api.go:4415
2024-05-31T19:24:29-06:00 DEBU  Attempting request to Proxy web api method:GET host:teleport.ethernet.fyi:443 path:/webapi/ping trace_id:bdfe393122b23b51408dbafaa71ac1ce span_id:3f38ce4b45b0a5aa webclient/webclient.go:131
2024-05-31T19:24:30-06:00 DEBU  ALPN connection upgrade test complete address:teleport.ethernet.fyi:443 upgrade_required:false trace_id:bdfe393122b23b51408dbafaa71ac1ce span_id:3f38ce4b45b0a5aa client/alpn_conn_upgrade.go:96
2024-05-31T19:24:30-06:00 DEBU [KEYSTORE]  Teleport TLS certificate valid until "2024-06-01 02:20:02 +0000 UTC". client/client_store.go:111
2024-05-31T19:24:30-06:00 DEBU [KEYSTORE]  Teleport TLS certificate valid until "2024-06-01 02:20:02 +0000 UTC". client/client_store.go:111
2024-05-31T19:24:30-06:00 DEBU [KEYSTORE]  Teleport TLS certificate valid until "2024-06-01 02:20:02 +0000 UTC". client/client_store.go:111
2024-05-31T19:24:30-06:00 DEBU [KEYSTORE]  Teleport TLS certificate valid until "2024-06-01 02:20:02 +0000 UTC". client/client_store.go:111
2024-05-31T19:24:30-06:00 DEBU [KEYSTORE]  Teleport TLS certificate valid until "2024-06-01 02:20:02 +0000 UTC". client/client_store.go:111
2024-05-31T19:24:30-06:00 DEBU [KEYSTORE]  Teleport TLS certificate valid until "2024-06-01 02:20:02 +0000 UTC". client/client_store.go:111
Proxying connections to httpbin on 127.0.0.1:43003
To avoid port randomization, you can choose the listening port using the --port flag.
2024-05-31T19:24:30-06:00 DEBU [LOCALPROX] checking local proxy certs alpnproxy/local_proxy.go:383
2024-05-31T19:24:30-06:00 DEBU [CLIENT]    local proxy tunnel certificates need to be reissued error:[
ERROR REPORT:
Original Error: *trace.NotFoundError local proxy has no TLS certificates configured
Stack Trace:
        github.com/gravitational/teleport/lib/srv/alpnproxy/local_proxy.go:388 github.com/gravitational/teleport/lib/srv/alpnproxy.(*LocalProxy).CheckCert
        github.com/gravitational/teleport/lib/client/local_proxy_middleware.go:90 github.com/gravitational/teleport/lib/client.(*CertChecker).ensureValidCerts
        github.com/gravitational/teleport/lib/client/local_proxy_middleware.go:85 github.com/gravitational/teleport/lib/client.(*CertChecker).OnStart
        github.com/gravitational/teleport/lib/srv/alpnproxy/local_proxy.go:177 github.com/gravitational/teleport/lib/srv/alpnproxy.(*LocalProxy).start
        github.com/gravitational/teleport/lib/srv/alpnproxy/local_proxy.go:171 github.com/gravitational/teleport/lib/srv/alpnproxy.(*LocalProxy).Start
        github.com/gravitational/teleport/tool/tsh/common/proxy.go:435 github.com/gravitational/teleport/tool/tsh/common.onProxyCommandApp
        github.com/gravitational/teleport/tool/tsh/common/tsh.go:1456 github.com/gravitational/teleport/tool/tsh/common.Run
        github.com/gravitational/teleport/tool/tsh/common/tsh.go:594 github.com/gravitational/teleport/tool/tsh/common.Main
        github.com/gravitational/teleport/tool/tsh/main.go:26 main.main
        runtime/proc.go:271 runtime.main
        runtime/asm_amd64.s:1695 runtime.goexit
User Message: local proxy has no TLS certificates configured] client/local_proxy_middleware.go:91
2024-05-31T19:24:30-06:00 DEBU [KEYSTORE]  Teleport TLS certificate valid until "2024-06-01 02:20:02 +0000 UTC". client/client_store.go:111
2024-05-31T19:24:30-06:00 DEBU [KEYSTORE]  Teleport TLS certificate valid until "2024-06-01 02:20:02 +0000 UTC". client/client_store.go:111
2024-05-31T19:24:30-06:00 DEBU [KEYSTORE]  Teleport TLS certificate valid until "2024-06-01 02:20:02 +0000 UTC". client/client_store.go:111
2024-05-31T19:24:30-06:00 DEBU [KEYSTORE]  Teleport TLS certificate valid until "2024-06-01 02:20:02 +0000 UTC". client/client_store.go:111
2024-05-31T19:24:30-06:00 DEBU [KEYSTORE]  Teleport TLS certificate valid until "2024-06-01 02:20:02 +0000 UTC". client/client_store.go:111
2024-05-31T19:24:30-06:00 DEBU [KEYSTORE]  Teleport TLS certificate valid until "2024-06-01 02:20:02 +0000 UTC". client/client_store.go:111
2024-05-31T19:24:30-06:00 DEBU [KEYSTORE]  Teleport TLS certificate valid until "2024-06-01 02:20:02 +0000 UTC". client/client_store.go:111
2024-05-31T19:24:30-06:00 DEBU [CLIENT]    MFA not required for access. client/cluster_client.go:480
2024-05-31T19:24:30-06:00 DEBU [KEYSTORE]  Teleport TLS certificate valid until "2024-06-01 02:20:02 +0000 UTC". client/client_store.go:111

ERROR REPORT:
Original Error: *interceptors.RemoteError access denied: identity is not allowed to reissue certificates
Stack Trace:
        github.com/gravitational/teleport/api@v0.0.0/client/client.go:1032 github.com/gravitational/teleport/api/client.(*Client).GenerateUserCerts
        github.com/gravitational/teleport/lib/client/cluster_client.go:208 github.com/gravitational/teleport/lib/client.(*ClusterClient).generateUserCerts
        github.com/gravitational/teleport/lib/client/cluster_client.go:481 github.com/gravitational/teleport/lib/client.(*ClusterClient).IssueUserCertsWithMFA
        github.com/gravitational/teleport/lib/client/local_proxy_middleware.go:211 github.com/gravitational/teleport/lib/client.(*AppCertIssuer).IssueCert.func1
        github.com/gravitational/teleport/lib/client/api.go:593 github.com/gravitational/teleport/lib/client.RetryWithRelogin
        github.com/gravitational/teleport/lib/client/local_proxy_middleware.go:189 github.com/gravitational/teleport/lib/client.(*AppCertIssuer).IssueCert
        github.com/gravitational/teleport/lib/client/local_proxy_middleware.go:96 github.com/gravitational/teleport/lib/client.(*CertChecker).ensureValidCerts
        github.com/gravitational/teleport/lib/client/local_proxy_middleware.go:85 github.com/gravitational/teleport/lib/client.(*CertChecker).OnStart
        github.com/gravitational/teleport/lib/srv/alpnproxy/local_proxy.go:177 github.com/gravitational/teleport/lib/srv/alpnproxy.(*LocalProxy).start
        github.com/gravitational/teleport/lib/srv/alpnproxy/local_proxy.go:171 github.com/gravitational/teleport/lib/srv/alpnproxy.(*LocalProxy).Start
        github.com/gravitational/teleport/tool/tsh/common/proxy.go:435 github.com/gravitational/teleport/tool/tsh/common.onProxyCommandApp
        github.com/gravitational/teleport/tool/tsh/common/tsh.go:1456 github.com/gravitational/teleport/tool/tsh/common.Run
        github.com/gravitational/teleport/tool/tsh/common/tsh.go:594 github.com/gravitational/teleport/tool/tsh/common.Main
        github.com/gravitational/teleport/tool/tsh/main.go:26 main.main
        runtime/proc.go:271 runtime.main
        runtime/asm_amd64.s:1695 runtime.goexit
User Message: access denied: identity is not allowed to reissue certificates

ERROR REPORT:
Original Error: *exec.ExitError exit status 1
Stack Trace:
        github.com/gravitational/teleport/lib/tbot/tshwrap/wrap.go:125 github.com/gravitational/teleport/lib/tbot/tshwrap.(*Wrapper).Exec
        github.com/gravitational/teleport/tool/tbot/proxy.go:82 main.onProxyCommand
        github.com/gravitational/teleport/tool/tbot/main.go:313 main.Run
        github.com/gravitational/teleport/tool/tbot/main.go:58 main.main
        runtime/proc.go:271 runtime.main
        runtime/asm_amd64.s:1695 runtime.goexit
User Message: executing `tsh proxy`
        unable to execute tsh
                exit status 1
```

</details>

Auth doesn't have much to say: <details><summary>auth log</summary>

```
Jun 01 01:22:16 teleport teleport[128395]: 2024-06-01T01:22:16Z DEBU [PROXY:SER] Skipping admin action MFA check for bot identity: {bot-robot bot-robot [access kube-access tbot-db-role tbot-app-role] [] [] [tim -teleport-internal-join] [viewers] [] 2024-06-01 02:20:02 +0000 UTC teleport.ethernet.fyi  map[logins:[tim]] {9505ede39edad49297c7b3973949d441c1931c0f7b4debf22c3454559ef9717c httpbin.teleport.ethernet.fyi teleport.ethernet.fyi httpbin   } teleport.ethernet.fyi Database(Service=, Protocol=, Username=, Database=, Roles=[]) [demo] [demo]  0001-01-01 00:00:00 +0000 UTC 192.168.10.144  [] [] [] [] true false 0 robot [] none  {  } } pid:128395.1 authz/permissions.go:491
Jun 01 01:22:16 teleport teleport[128395]: 2024-06-01T01:22:16Z DEBU [AUTH:1]    Skipping admin action MFA check for bot identity: {bot-robot bot-robot [access kube-access tbot-db-role tbot-app-role] [] [] [tim -teleport-internal-join] [viewers] [] 2024-06-01 02:20:02 +0000 UTC teleport.ethernet.fyi  map[logins:[tim]] {9505ede39edad49297c7b3973949d441c1931c0f7b4debf22c3454559ef9717c httpbin.teleport.ethernet.fyi teleport.ethernet.fyi httpbin   } teleport.ethernet.fyi Database(Service=, Protocol=, Username=, Database=, Roles=[]) [demo] [demo]  0001-01-01 00:00:00 +0000 UTC 192.168.10.144  [] [] [] [] true false 0 robot [] none  {  } } pid:128395.1 authz/permissions.go:491
Jun 01 01:22:16 teleport teleport[128395]: 2024-06-01T01:22:16Z DEBU [PROXY:SER] Skipping admin action MFA check for bot identity: {bot-robot bot-robot [access kube-access tbot-db-role tbot-app-role] [] [] [tim -teleport-internal-join] [viewers] [] 2024-06-01 02:20:02 +0000 UTC teleport.ethernet.fyi  map[logins:[tim]] {9505ede39edad49297c7b3973949d441c1931c0f7b4debf22c3454559ef9717c httpbin.teleport.ethernet.fyi teleport.ethernet.fyi httpbin   } teleport.ethernet.fyi Database(Service=, Protocol=, Username=, Database=, Roles=[]) [demo] [demo]  0001-01-01 00:00:00 +0000 UTC 192.168.10.144  [] [] [] [] true false 0 robot [] none  {  } } pid:128395.1 authz/permissions.go:491
Jun 01 01:22:16 teleport teleport[128395]: 2024-06-01T01:22:16Z DEBU [AUTH:1]    Skipping admin action MFA check for bot identity: {bot-robot bot-robot [access kube-access tbot-db-role tbot-app-role] [] [] [tim -teleport-internal-join] [viewers] [] 2024-06-01 02:20:02 +0000 UTC teleport.ethernet.fyi  map[logins:[tim]] {9505ede39edad49297c7b3973949d441c1931c0f7b4debf22c3454559ef9717c httpbin.teleport.ethernet.fyi teleport.ethernet.fyi httpbin   } teleport.ethernet.fyi Database(Service=, Protocol=, Username=, Database=, Roles=[]) [demo] [demo]  0001-01-01 00:00:00 +0000 UTC 192.168.10.144  [] [] [] [] true false 0 robot [] none  {  } } pid:128395.1 authz/permissions.go:491
Jun 01 01:22:16 teleport teleport[128395]: 2024-06-01T01:22:16Z DEBU [AUTH:1]    Skipping admin action MFA check for bot identity: {bot-robot bot-robot [access kube-access tbot-db-role tbot-app-role] [] [] [tim -teleport-internal-join] [viewers] [] 2024-06-01 02:20:02 +0000 UTC teleport.ethernet.fyi  map[logins:[tim]] {9505ede39edad49297c7b3973949d441c1931c0f7b4debf22c3454559ef9717c httpbin.teleport.ethernet.fyi teleport.ethernet.fyi httpbin   } teleport.ethernet.fyi Database(Service=, Protocol=, Username=, Database=, Roles=[]) [demo] [demo]  0001-01-01 00:00:00 +0000 UTC 192.168.10.144  [] [] [] [] true false 0 robot [] none  {  } } pid:128395.1 authz/permissions.go:491
Jun 01 01:22:16 teleport teleport[128395]: 2024-06-01T01:22:16Z DEBU [AUTH:1]    Skipping admin action MFA check for bot identity: {bot-robot bot-robot [access kube-access tbot-db-role tbot-app-role] [] [] [tim -teleport-internal-join] [viewers] [] 2024-06-01 02:20:02 +0000 UTC teleport.ethernet.fyi  map[logins:[tim]] {9505ede39edad49297c7b3973949d441c1931c0f7b4debf22c3454559ef9717c httpbin.teleport.ethernet.fyi teleport.ethernet.fyi httpbin   } teleport.ethernet.fyi Database(Service=, Protocol=, Username=, Database=, Roles=[]) [demo] [demo]  0001-01-01 00:00:00 +0000 UTC 192.168.10.144  [] [] [] [] true false 0 robot [] none  {  } } pid:128395.1 authz/permissions.go:491
Jun 01 01:22:16 teleport teleport[128395]: 2024-06-01T01:22:16Z DEBU             generated user key for [tim -teleport-internal-join] with expiry on (1717229229) 2024-06-01 08:07:09.599026141 +0000 UTC keygen/keygen.go:153
Jun 01 01:22:16 teleport teleport[128395]: 2024-06-01T01:22:16Z DEBU [CA]        Generating TLS certificate common_name:tim dns_names:[] key_usage:5 not_after:2024-06-01 08:07:09.603422695 +0000 UTC tlsca/ca.go:1201
Jun 01 01:22:16 teleport teleport[128395]: 2024-06-01T01:22:16Z INFO [AUDIT]     cert.create cert_type:user cluster_name:teleport.ethernet.fyi code:TC000I ei:0 event:cert.create client_ip:192.168.10.144 database_names:[demo] database_users:[demo] expires:2024-06-01T08:07:09.603422695Z kubernetes_groups:[viewers] logins:[tim -teleport-internal-join] prev_identity_expires:0001-01-01T00:00:00Z private_key_policy:none roles:[access editor] route_to_cluster:teleport.ethernet.fyi teleport_cluster:teleport.ethernet.fyi aws_role_arns:<nil> azure_identities:<nil> db_names:<nil> db_roles:<nil> db_users:<nil> gcp_service_accounts:<nil> host_user_gid:[] host_user_uid:[] kubernetes_groups:[viewers] kubernetes_users:<nil> logins:[tim] windows_logins:<nil> user:tim time:2024-06-01T01:22:16.216Z uid:bdad781e-f4fd-4cc8-9942-68c908c1f841 events/emitter.go:288
```

</details>

I suspect tsh has changed how identities are loaded: it should not attempt to fetch new app certs when using virtual identities with `-i`.

Workaround: connect directly to apps via the proxy, in my case `https://httpbin.teleport.ethernet.fyi`.

Bug details:
- Teleport version: v16.0.0-alpha.3
- Recreation steps
- Debug logs

### PR DESCRIPTION
**Pull request by timothyb89**
This adds a fix for `tsh proxy app` when used with virtual profiles (i.e. `tsh -i <app identity file> proxy app ...`). Among other use cases, virtual profiles are used by `tbot proxy app` to open an authenticated tunnel to an app.

After #40857, `onProxyCommandApp()` [no longer loads existing app certificates](https://github.com/gravitational/teleport/pull/40857/files#diff-a164fa8e9c23a61d0712cdd10cf9e8dea95094bbe5344cf138e85c012fbcaec6L345) and seems to rely on the new `CertChecker`'s `ensureValidCerts()` to issue a new cert on every run.

This change in behavior is reasonable for tsh where relogin (and MFA checks) are possible, but this isn't feasible for bot use and, moreover, is explicitly impossible as bot certs have a `disallow-reissue` flag set, leading to errors like this:
```
2024-06-03T19:17:04-06:00 DEBU [CLIENT]    local proxy tunnel certificates need to be reissued error:[
ERROR REPORT:
Original Error: *trace.NotFoundError local proxy has no TLS certificates configured
Stack Trace:
        github.com/gravitational/teleport/lib/srv/alpnproxy/local_proxy.go:388 github.com/gravitational/teleport/lib/srv/alpnproxy.(*LocalProxy).CheckCert
        github.com/gravitational/teleport/lib/client/local_proxy_middleware.go:90 github.com/gravitational/teleport/lib/client.(*CertChecker).ensureValidCerts
        github.com/gravitational/teleport/lib/client/local_proxy_middleware.go:85 github.com/gravitational/teleport/lib/client.(*CertChecker).OnStart
        github.com/gravitational/teleport/lib/srv/alpnproxy/local_proxy.go:177 github.com/gravitational/teleport/lib/srv/alpnproxy.(*LocalProxy).start
        github.com/gravitational/teleport/lib/srv/alpnproxy/local_proxy.go:171 github.com/gravitational/teleport/lib/srv/alpnproxy.(*LocalProxy).Start
        github.com/gravitational/teleport/tool/tsh/common/proxy.go:395 github.com/gravitational/teleport/tool/tsh/common.onProxyCommandApp
        github.com/gravitational/teleport/tool/tsh/common/tsh.go:1453 github.com/gravitational/teleport/tool/tsh/common.Run
        github.com/gravitational/teleport/tool/tsh/common/tsh.go:594 github.com/gravitational/teleport/tool/tsh/common.Main
        github.com/gravitational/teleport/tool/tsh/main.go:26 main.main
        runtime/proc.go:271 runtime.main
        runtime/asm_amd64.s:1695 runtime.goexit
User Message: local proxy has no TLS certificates configured] client/local_proxy_middleware.go:91

[...]

ERROR REPORT:
Original Error: *interceptors.RemoteError access denied: identity is not allowed to reissue certificates
Stack Trace:
        github.com/gravitational/teleport/api@v0.0.0/client/client.go:1032 github.com/gravitational/teleport/api/client.(*Client).GenerateUserCerts
        github.com/gravitational/teleport/lib/client/cluster_client.go:208 github.com/gravitational/teleport/lib/client.(*ClusterClient).generateUserCerts
        github.com/gravitational/teleport/lib/client/cluster_client.go:481 github.com/gravitational/teleport/lib/client.(*ClusterClient).IssueUserCertsWithMFA
        github.com/gravitational/teleport/lib/client/local_proxy_middleware.go:211 github.com/gravitational/teleport/lib/client.(*AppCertIssuer).IssueCert.func1
        github.com/gravitational/teleport/lib/client/api.go:593 github.com/gravitational/teleport/lib/client.RetryWithRelogin
        github.com/gravitational/teleport/lib/client/local_proxy_middleware.go:189 github.com/gravitational/teleport/lib/client.(*AppCertIssuer).IssueCert
        github.com/gravitational/teleport/lib/client/local_proxy_middleware.go:96 github.com/gravitational/teleport/lib/client.(*CertChecker).ensureValidCerts
        github.com/gravitational/teleport/lib/client/local_proxy_middleware.go:85 github.com/gravitational/teleport/lib/client.(*CertChecker).OnStart
        github.com/gravitational/teleport/lib/srv/alpnproxy/local_proxy.go:177 github.com/gravitational/teleport/lib/srv/alpnproxy.(*LocalProxy).start
        github.com/gravitational/teleport/lib/srv/alpnproxy/local_proxy.go:171 github.com/gravitational/teleport/lib/srv/alpnproxy.(*LocalProxy).Start
        github.com/gravitational/teleport/tool/tsh/common/proxy.go:435 github.com/gravitational/teleport/tool/tsh/common.onProxyCommandApp
        github.com/gravitational/teleport/tool/tsh/common/tsh.go:1456 github.com/gravitational/teleport/tool/tsh/common.Run
        github.com/gravitational/teleport/tool/tsh/common/tsh.go:594 github.com/gravitational/teleport/tool/tsh/common.Main
        github.com/gravitational/teleport/tool/tsh/main.go:26 main.main
        runtime/proc.go:271 runtime.main
        runtime/asm_amd64.s:1695 runtime.goexit
User Message: access denied: identity is not allowed to reissue certificates
```

As a workaround, this change manually attempts to load the certificate if the loaded profile is virtual.

Fixes #42257

### CODE REVIEW

**Comment by timothyb89** [comment]
FYI, I'm not sure if this fix is the best solution or even necessarily correct. It does fix the issue and loads certs when passed an identity file, but I'm not familiar enough with the new `alpnproxy` cert checking machinery to say for sure that these certs aren't better off being loaded somewhere else.

**Review by strideynet — APPROVED** [review]

**Comment by zmb3** [comment]
Is there any way we can get some test coverage on this? Any time we introduce a regression that was only caught via manual testing I like to ask whether it's something we can catch with automated tests going forward.

**Comment by timothyb89** [comment]
> Is there any way we can get some test coverage on this? Any time we introduce a regression that was only caught via manual testing I like to ask whether it's something we can catch with automated tests going forward.

I'll keep hacking at it and find some solution, but I think I've discovered _why_ we have no test coverage here. I wanted a mostly E2E test but it turns out it's (seemingly?) impossible to generate identity files in the tsh client test suite. Everything needed either depends on `ServerWithRoles` (which I don't think is accessible) and/or adds a dependency on `tctl` in `tsh`'s tests. In any case, I'll sort something out here, but it might be ugly 😅

**Comment by timothyb89** [comment]
> FYI this should also be fixed by #40985 which re-introduces loading existing app certs before reissuing

Can confirm this also fixes the issue. I'm happy to close this in favor of the more general solution, though it might still be worth adding a test to catch regressions.

**Comment by timothyb89** [comment]
I've added a unit test that ensures we can start an app proxy with an identity file and that a simple GET succeeds. It's a bit of a hack but I tried to make it as minimally evil as I could manage.

I also chatted a bit with @Joerger and think we can potentially merge this to resolve the regression, then remove my workaround in favor of his generalized solution once it's ready. I've added a TODO to that effect.

(Alternately, we can wait on #40985 and I can remove my workaround and just keep the new unit test - anything's fine by me.)

**Review by Joerger — APPROVED** [review]

**Pull request merged**
