### PR TITLE
Update install-linux.mdx for AWS Linux

### PR DESCRIPTION
**Pull request by benarent**
I just recorded the Teleport 9 getting started video on AWS and I ran into this issue.  We fix out AMI with this https://github.com/gravitational/teleport/blob/master/assets/aws/files/install.sh#L104 . 

Let me know if this is a good place, or if we should call it out somewhere else.

### CODE REVIEW

**Review by zmb3 — COMMENTED** [review]
I think updating the docs to recommend `sudo -i` instead would be a better option, because that applies only for the individual command rather than modifying system defaults.

**Review by ptgott — APPROVED** [review]
Approved once Zac's feedback is addressed

**Review by stevenGravy — APPROVED** [review]

**Comment by zmb3** [comment]
@benarent do we still want this?

**Comment by benarent** [comment]
> @benarent do we still want this?

Yes, I've not found another work around for it.

**Pull request merged**
