### PR TITLE
Deprecate DeleteMFADevice and move tests to its "sync" variant

### PR DESCRIPTION
**Pull request by codingllama**
Deprecate DeleteMFADevice, various of its top-level messages and interface appearances, and move all tests (but one) to DeleteMFADeviceSync.

I've taken the opportunity to consolidate our "last device" deletion tests as well.

This paves the ground for an easy code cleanup when the time comes.

#20343

### CODE REVIEW

**Comment by codingllama** [comment]
Branched from #32767 to avoid a deprecation warning (and a conflicting change for me). If this happens to be approved first I can drop that commit and add a temporary nolint instead.

May be reviewed commit-by-commit if you prefer, although there's a tiny bit of churn between afedcf1 and 2176700.

**Comment by codingllama** [comment]
Test failures look unrelated, I'll take a closer look later.

**Review by kimlisa — APPROVED** [review]

**Comment by codingllama** [comment]
Friendly ping @AntonAM ?

**Review by AntonAM — APPROVED** [review]

**Comment by codingllama** [comment]
Thanks for the quick review, everyone! If the base is not ready by Monday I'll drop that commit and merge only the changes you reviewed.

**Pull request merged**
