### PR TITLE
buddy: Fix incorrect use of loop variables

### PR DESCRIPTION
**Pull request by r0mant**
Buddy PR for https://github.com/gravitational/teleport/pull/16291.

### CODE REVIEW

**Review by russjones — APPROVED** [review]

**Review by zmb3 — APPROVED** [review]

**Review by tigrato — APPROVED** [review]

**Comment by zmb3** [comment]
FYI @rosstimothy - it seems `TestTraceProvider/spans_exported_with_gRPC+TLS` has actually always failed with:

```
--- FAIL: TestTraceProvider (0.00s)
    --- FAIL: TestTraceProvider/spans_exported_with_gRPC+TLS (1.00s)
        tracing_test.go:360:
            	Error Trace:	tracing_test.go:360
            	Error:      	Received unexpected error:
            	            	failed to connect to tracing exporter grpc://0.0.0.0:61305: context deadline exceeded
            	Test:       	TestTraceProvider/spans_exported_with_gRPC+TLS
FAIL
FAIL	github.com/gravitational/teleport/lib/observability/tracing	1.156s
FAIL
```

We never noticed this due to the bug that this PR fixes. You can recreate it by commenting out all the other test cases, removing the inner `t.Parallel` call, or just running the test with the changes in this PR.

**Comment by hugoShaka** [comment]
The operator behaviour has been fixed (now we don't delete `created_by`) and the test adapted. https://github.com/gravitational/teleport/pull/16306/commits/7f26d6e71ea236b9de43981062ecbe04162418c7

**Comment by r0mant** [comment]
@rosstimothy @hugoShaka Are we good to merge this now folks?

**Comment by hugoShaka** [comment]
LGTM

**Pull request merged**
