### PR TITLE
Update enhanced session recording docs for Amazon 2 Linux

### PR DESCRIPTION
**Pull request by stevenGravy**
Expanded instructions to include installing BCC within a Amazon 2 Linux.  Moved some instruction steps for flow since amazon 2 linux doesn't require building the bcc tools.

### CODE REVIEW

**Review by benarent — APPROVED** [review]
looks good, just a best practice. I would suggest a branch name `stevengravy/docs/enhancedsession2`

**Comment by stevenGravy** [comment]
@gravitational-jenkins please retest

**Comment by stevenGravy** [comment]
@gravitational-jenkins  retest this please

**Comment by stevenGravy** [comment]
@gravitational-jenkins retest this please

**Comment by stevenGravy** [comment]
@gravitational-jenkins retest this please

**Comment by benarent** [comment]
@stevenGravy I used my admin privileges to squash and merge, since these are just in the docs and the failing test isn't a concern.

**Pull request merged**
