### PR TITLE
Fix cgroup resolution to work on Debian distros.

### PR DESCRIPTION
**Pull request by russjones**
**Description**

Replaced the cgroup resolution function to work on Debian distributions instead of just RHEL based ones. This implementation comes from the Linux kernel tests.

### CODE REVIEW

**Review by fspmarshall — APPROVED** [review]

**Review by klizhentas — APPROVED** [review]

**Comment by russjones** [comment]
@gravitational-jenkins retest this please

**Comment by russjones** [comment]
@gravitational-jenkins retest this please

**Comment by russjones** [comment]
@gravitational-jenkins retest this please

**Comment by russjones** [comment]
@gravitational-jenkins retest this please

**Pull request merged**
