### PR TITLE
fix(helm-chart): adjust to entrypoint within dockerfile

### LINKED ISSUE #43669: Broken reference to exec command in the event handler helm chart
**Expected behavior:**
Successfully started Event Handler plugin after executing the helm install command. 

**Current behavior:**
Back-off restarting failed container teleport-plugin-event-handler in pod teleport-plugin-event-handler-xxx

**Bug details:**
- Teleport version: `16.0.1`
- Recreation steps: 
```
helm repo add teleport https://charts.releases.teleport.dev
helm install teleport-plugin-event-handler teleport/teleport-plugin-event-handler --version 16.0.1 -f values.yaml
```
- Debug logs
```
# kubectl describe pod teleport-plugin-event-handler-xxx
...
  Normal   Pulling                 32s                kubelet                  Pulling image "public.ecr.aws/gravitational/teleport-plugin-event-handler:16.0.1"
  Normal   Pulled                  28s                kubelet                  Successfully pulled image "public.ecr.aws/gravitational/teleport-plugin-event-handler:16.0.1" in 3.966321778s (3.966331377s including waiting)
  Normal   Created                 13s (x3 over 28s)  kubelet                  Created container teleport-plugin-event-handler
  Warning  Failed                  13s (x3 over 28s)  kubelet                  Error: failed to create containerd task: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: exec: "/usr/local/bin/teleport-event-handler": stat /usr/local/bin/teleport-event-handler: no such file or directory: unknown
```

A root cause is the difference within the [Dockerfile](https://github.com/gravitational/teleport/blob/v16.0.1/integrations/event-handler/Dockerfile#L26) and the [deployment template](https://github.com/gravitational/teleport/blob/v16.0.1/examples/chart/event-handler/templates/deployment.yaml#L38).

### PR DESCRIPTION
**Pull request by pudovd**
fix #43669

### CODE REVIEW

**Review by evanfreed — APPROVED** [review]

**Review by r0mant — COMMENTED** [review]
@hugoShaka @fheinecke Do you know why the entrypoint changed? Was this a side-effect of plugins migration to teleport repository? I think we should fix the entrypoint back rather.

**Review by fheinecke — APPROVED** [review]

**Comment by fheinecke** [comment]
Thanks for the fix @pudovd. I updated this entrypoint for all plugins when we moved the plugins code into this repo a couple of months ago, but I forgot to update this Helm chart.

@r0mant this was an intentional change - I just forgot to update the chart for the event handler specifically.

**Review by r0mant — APPROVED** [review]

**Comment by zmb3** [comment]
@fheinecke this will need to be buddied

**Comment by fheinecke** [comment]
Hi @pudovd,

Thanks for your contribution. We are currently unable to run our tests on external contributions. As such, I'll be helping you validate and merge your pull request. I've created an internal [PR here](https://github.com/gravitational/teleport/pull/44607) and the CI checks came up clean.

Please wait for another approver and I'll get your code merged. You will retain authorship of your commits.

**Comment by pudovd** [comment]
Hi @fheinecke,

Thanks for your concern about my authorship :heart: 
But I just wanted to draw attention to the issue, because I hadn't wanted to build custom helm chart.
So, I don't mind if we just close this PR.

**Comment by fheinecke** [comment]
Hi @pudovd,

Thanks for discovering and fixing the issue. We've merged your fix [here](https://github.com/gravitational/teleport/pull/44607) to our `master` branch, and it should be in a v16 and v15 release within the next week. Let me know if you have any questions!

**Pull request closed without merging**
