### PR TITLE
Rebuild FIDO2 dependencies on failure

### PR DESCRIPTION
**Pull request by codingllama**
Attempt to detect builder environment inconsistencies by compiling a toy FIDO2 program - if this fails, then clear the cache and try again.

Builders are sometimes getting into inconsistent states, this should help avoiding manual intervention in order to fix them.

### CODE REVIEW

**Comment by espadolini** [comment]
@codingllama according to https://superuser.com/a/187105, files in `/tmp` are cleared out after 3 days of not being accessed - which aligns suspiciously with the amount of time that passes between EoB on friday and SoB on monday 👀 

Perhaps we just need to move the build cache away from `/tmp` and into `~/.teleport-fido-build-cache`?

**Comment by codingllama** [comment]
@espadolini yep, it does look like a period cleanup. The interesting part is that it deletes a bunch of headers but has tendency to keep libs around (even dylibs that we don't use), whereas I was (innocently) expecting a folder-wipe kind of deal.

Drone changes $HOME to a per-build temporary directory, that's why many of our "script caches" use /tmp instead.

**Comment by codingllama** [comment]
Friendly ping @EdwardDowling @smallinsky ?

**Review by smallinsky — APPROVED** [review]
LGTM. 

The other approach is to calculated and store in a file the directory checksum for each lib dir content like: `find $CBOR_PATH -type f -exec shasum {} \; | sort -k 2 | shasum`  and compare the saved value with value calculated based on current build state.

**Comment by codingllama** [comment]
@espadolini and I discussed a few options, the only persistent path that builders can write to is `$HOME` (or `/Users/$(whoami)`). The latter is easy enough to do, just a bit outside of what a Drone script should do (although one could argue this ship kind of sailed already).

What do you say we give this a try? If it bites us again then I'll backpedal into separate library builds for every pipeline, which is of course slower but nicely isolated.

**Comment by codingllama** [comment]
Friendly ping @EdwardDowling @espadolini ? Could we get this one in?

**Review by espadolini — APPROVED** [review]
+1 for just using `/Users/$(whoami)/.teleport-fido2-cache` too

**Comment by codingllama** [comment]
Thanks for the quick reply.

I'm hoping this script will go away in favor of a better solution in the near future, so I'll push as-is. I may revisit with the `shasum`/`/Users/$(whoami)` ideas if I get some spare time soon.

**Pull request merged**
