### PR TITLE
[Backport v7] Update DNS instructions in the AWS+EKS+Helm guide

### PR DESCRIPTION
**Pull request by codingllama**
Assuming `service/teleport` points to an ELB, which it does according to
the guide, then the change-resource-record-sets input needs to contain
an "AliasTarget" (instead of "ResourceRecords.Value").

Note that the hosted zone ID for `aws route53
change-resource-record-sets` remains as the DNS zone (ie, the zone for
"example.com"), but the hosted zone ID for the "ResourceRecordSet" is
the zone of the ELB (which doesn't necessarily match the zone for
"example.com"). I found that out by chance because I deployed my cluster
on sa-east-1 (instead of the more usual us-west or us-east).

Old change-resource-record-sets action:

```json
{
  "Action": "CREATE",
  "ResourceRecordSet": {
    "Name": "teleport.example.com",
    "Type": "A",
    "TTL": 300,
    "ResourceRecords": {
      "Value": "dualstack.a559a6696e58f48d6814781231623dc8-1207026150.sa-east-1.elb.amazonaws.com" // not allowed anymore!
    }
  }
}
```

New change-resource-record-sets action:

```json
{
  "Action": "CREATE",
  "ResourceRecordSet": {
    "Name": "teleport.example.com",
    "Type": "A",
    "AliasTarget": {
      "HostedZoneId": "<ELB_ZONE_ID>",
      "DNSName": "dualstack.a232d92df01f940339adea0e645d88bb-1576732600.us-east-1.elb.amazonaws.com",
      "EvaluateTargetHealth": false
    }
  }
}
```

### CODE REVIEW

**Comment by codingllama** [comment]
Note 1: I haven't touched https://github.com/gravitational/teleport/blob/branch/v7/docs/pages/kubernetes-access/getting-started.mdx, as that one actually pictures a service with an external IP, for which I believe the snippet is correct.

Note 2: added the "dualstack." prefix due to instructions at https://aws.amazon.com/premiumsupport/knowledge-center/alias-resource-record-set-route53-cli/.

Link to modified page: https://goteleport.com/docs/ver/7.0/kubernetes-access/getting-started/cluster/#step-13-install-teleport

**Comment by codingllama** [comment]
We should cherry pick this one to branch/v7 to get the correct docs in the site.

**Review by webvictim — APPROVED** [review]
Looks good to me. Thanks for the thorough investigation!

**Comment by codingllama** [comment]
Friendly ping @russjones ?

**Review by klizhentas — APPROVED** [review]

**Pull request merged**
