### PR TITLE
Remove client side port guessing from tsh puttyconfig

### PR DESCRIPTION
**Pull request by rosstimothy**
If no port was provided puttyconfig would default to 3022. That is not guaranteed to be the correct port and causes UX issues. To allow the port to be optional and guarantee the correct port is used puttyconfig is updated to use 0 instead of 3022. This is a special port that indicates to Teleport to use whatever port is defined in the node when making dial request. Since the value from puttyconfig is fed into tsh proxy ssh this value is honored by Teleport during connections.

Changelog: Use the registered port of the target host when tsh puttyconfig is invoked without --port.

### CODE REVIEW

**Review by zmb3 — APPROVED** [review]
Gotta love when you can add features by removing code.

**Comment by webvictim** [comment]
Not to ask an obvious question, but did you test this with actual PuTTY and a fresh config? I have a weird recollection that PuTTY does something odd if you don't explicitly specify the port.

**Comment by webvictim** [comment]
(there's also a mention or two of needing to explicitly set the port when using OpenSSH in our PuTTY docs, which I don't think will be needed after this merges)

**Comment by webvictim** [comment]
Awesome - it might be worth testing an agentless OpenSSH host too just in case (although I have no real reason to believe it won't just pass through)

**Review by espadolini — APPROVED** [review]

**Pull request merged**
