### PR TITLE
add the new/changed SAML connector to create and update audit events

### LINKED ISSUE #33274: Audit Events: `saml.created` event should include the SAML connector
## What would you like Teleport to do?
When SAML connectors are changed, the audit log is a bit sparse. Teleport should reflect the changes, or complete SAML metadata/spec document into the `saml.created` audit record.

Teleport should probably explicitly exclude some sensitive fields like `signing_key_pair.private_key` from the Audit log, and perhaps just log that the field changed at all.

## What problem does this solve?
When auditing a Teleport cluster from historical information in the log, it is important to be able to reason about the state of the authentication configuration at any point. Without the critical SAML connector information in the audit log, there is not a way to reconstruct historical state.
It could be possible for an administrator with access to update SAML connectors to install a malicious SAML connector config to a new IdP, log in maliciously as another Teleport User, and alter privileged cluster configuration. (As a privilege escalation)
Afterwards, by setting the SAML connector back to the old values, it could be possible to evade detection.

## If a workaround exists, please include it.
It might be possible to (ab)use the Teleport APIs to regularly export and log changes to important resources like SAML connectors (but leaves open the possibility of timing and race attacks)

### PR DESCRIPTION
**Pull request by capnspacehook**
Fixes: https://github.com/gravitational/teleport/issues/33274

changelog: add the new/changed SAML connector to create and update audit events

### CODE REVIEW

**Comment by zmb3** [comment]
We already have indirect dependencies on a few similar libs:

- sigs.k8s.io/structured-merge-diff/v4
- github.com/pmezard/go-difflib (looks unmaintained, but that might be fine for such a small focused library)

Do either of these fit the bill?

**Review by r0mant — COMMENTED** [review]
Why do we need a diff? Can we keep it simple and just include the updated connector? We wouldn't need another library either.

**Review by r0mant — APPROVED** [review]

**Comment by zmb3** [comment]
Please update the PR description and squash the commits before merging this so we can an accurate commit message.

**Comment by capnspacehook** [comment]
@nklaassen @fheinecke friendly ping

**Review by tigrato — APPROVED** [review]

**Review by AntonAM — APPROVED** [review]

**Pull request merged**
