### PR TITLE
docs: replacing images with old logo

### PR DESCRIPTION
**Pull request by mmcallister**
For [46300](https://github.com/gravitational/teleport/issues/46300). Working through replacing all the images that are using the old logo. This will take a few iterations.

### CODE REVIEW

**Comment by mmcallister** [comment]
Running all replacements through ImageOptim to reduce size

**Comment by zmb3** [comment]
@mmcallister it might make more sense to target `branch/v16` on this, and put a backport label on it for v15.

- there's no need to go to master first, as master and v17 need different screenshots for the new nav
- there's probably no need to go to v14, because we'll remove v14 from our docs site in less than 2 weeks

**Comment by mmcallister** [comment]
@zmb3 sounds good! Nixing v14 and changed the target branch. I'll set up a separate PR for master/v17

**Comment by mmcallister** [comment]
This has a bunch of content pulled in from master, since we're dividing these tasks up I'll close this and start a fresh PR just targeting branch/v16 and v15 backport.

**Pull request closed without merging**
