### PR TITLE
Enforce SHA-512 for RSA SSH signatures

### LINKED ISSUE #3742: Teleport server certs are signed with ssh-rsa-cert-v01@openssh.com, which was deprecated in OpenSSH 8.2
### Description

Starting with OpenSSH 8.2, teleport server certificates are no longer accepted as valid, when the cluster CA has been added to `~/..ssh/known_hosts`. Rolling back to 8.1 solves the issue. OpenSSH 8.2 changelog (https://www.openssh.com/releasenotes.html) mentions that they have deprecated SHA1 cert signing.

**What happened**:
OpenSSH does not accept the server's certificate as valid, and asks if you want to continue connecting. 

**What you expected to happen**:
OpenSSH should validate the server certificate, trust the CA, and connect without user intervention.

**How to reproduce it (as minimally and precisely as possible)**:
* Add `@cert-authority * ssh-rsa <...> type=host` to `~/.ssh/known_hosts` on Ubuntu 20.04 with OpenSSH 8.2.
* Attempt to connect to a node within the cluster using normal openssh client. 
* The server certificate should be accepted, but isn't.

### Environment
- Teleport version (use `teleport version`): 4.2.9
- Tsh version (use `tsh version`): 4.2.9
- OS (e.g. from `/etc/os-release`): Ubuntu 20.04 (focal)

```
root@9c0397b1e1ea:~# ssh -v test-node1
OpenSSH_8.2p1 Ubuntu-4, OpenSSL 1.1.1f  31 Mar 2020
debug1: Reading configuration data /root/.ssh/config
debug1: /root/.ssh/config line 8: Applying options for cluster1*
debug1: Reading configuration data /etc/ssh/ssh_config
debug1: Connecting to test-node1 [192.168.1.1] port 3022.
debug1: Connection established.
debug1: identity file /root/.ssh/id_rsa type -1
debug1: identity file /root/.ssh/id_dsa type -1
debug1: identity file /root/.ssh/id_ecdsa type -1
debug1: identity file /root/.ssh/id_ecdsa_sk type -1
debug1: identity file /root/.ssh/id_ed25519 type -1
debug1: identity file /root/.ssh/id_ed25519_sk type -1
debug1: identity file /root/.ssh/id_xmss type -1
debug1: certificate file /root/.tsh/keys/cluster1/user@cluster1-cert.pub type 4
debug1: Local version string SSH-2.0-OpenSSH_8.2p1 Ubuntu-4
debug1: Remote protocol version 2.0, remote software version Teleport
debug1: no match: Teleport
debug1: Authenticating to test-node1:3022 as 'user'
debug1: SSH2_MSG_KEXINIT sent
debug1: SSH2_MSG_KEXINIT received
debug1: kex: algorithm: curve25519-sha256@libssh.org
debug1: kex: host key algorithm: ssh-rsa-cert-v01@openssh.com
debug1: kex: server->client cipher: chacha20-poly1305@openssh.com MAC: <implicit> compression: none
debug1: kex: client->server cipher: chacha20-poly1305@openssh.com MAC: <implicit> compression: none
debug1: expecting SSH2_MSG_KEX_ECDH_REPLY
debug1: Server host certificate: ssh-rsa-cert-v01@openssh.com SHA256:RYFwODfulkHn+2idMFDk0XyDs/wFDNuxoLBHMKrRUs0, serial 0 ID "" CA ssh-rsa SHA256:ftKXNjA4qUD9HuE9MsedDrvjJudXkS3Msg9QQiwpmQk valid after 2020-04-14T03:42:34
debug1: Host '[test-node1]:3022' is known and matches the RSA-CERT host certificate.
debug1: Found CA key in /root/.ssh/known_hosts:1
check_host_cert: certificate signature algorithm ssh-rsa: signature algorithm not supported
debug1: No matching CA found. Retry with plain key
debug1: checking without port identifier
The authenticity of host '[test-node1]:3022 ([192.168.1.1]:3022)' can't be established.
RSA key fingerprint is SHA256:RYFwODfulkHn+2idMFDk0XyDs/wFDNuxoLBHMKrRUs0.
Are you sure you want to continue connecting (yes/no/[fingerprint])? 
```

### PR DESCRIPTION
**Pull request by awly**
Motivation:

    x/crypto/ssh defaults to using SHA-1 for signatures:
    https://github.com/golang/crypto/blob/master/ssh/keys.go#L963-L982
    Because Teleport uses RSA for user, host and CA keys, we end up with
    SHA-1 by default.

    SHA-1 is now considered weak and OpenSSH plans to deprecate it:
    https://www.openssh.com/txt/release-8.3

Fix:

    Wrap all RSA `ssh.Signer`s and override `SignWithAlgorithm` to
    provide `SigAlgoRSASHA2512` if not otherwise specified. This will
    only affect new certs, existing certs will use `SigAlgoRSA` until
    rotated. For CA certs (e.g. exported with `tctl auth export`) users
    might need to manually rotate.

I somewhat blindly wrapped all non-test places where we create `ssh.Signer`s. If you think there's unnecessary calls or missing ones, please comment.

Limited local testing with openssh 8.2 client and
`-oHostKeyAlgorithms=-ssh-rsa` confirms that this works with a new
cluster and fails with an old one.

Fixes #3742

### CODE REVIEW

**Comment by russjones** [comment]
@awly Releases of OpenSSH below 7.2 will not support SHA-512 signed certificates. The good news is that Ubuntu 16.04+, CentOS 7+, and macOS 10.12 (Sierra) all have releases greater than OpenSSH 7.2.

The bad news is that CentOS 6 has an older release and we have customers still on CentOS 6. This means we'll have to add a flag to allow those customers to continue issuing `ssh-rsa` signatures with OpenSSH clients.

I like making this the default behavior, but we should do some more testing around compatibility before we make it the default behavior. We don't want someone to upgrade their cluster and no longer have access to it.

**Comment by russjones** [comment]
@gravitational-jenkins retest this please

**Comment by awly** [comment]
> The bad news is that CentOS 6 has an older release and we have customers still on CentOS 6. This means we'll have to add a flag to tell the Auth Server to continue issuing ssh-rsa signatures.

Ahh, ok. It's unfortunate that we support outdated OSs **and** integration with outdated userspace software on them.

I'll add a config file field, next to the [other crypto settings](https://github.com/gravitational/teleport/blob/master/lib/config/fileconf.go#L386-L400) we have. OpenSSH has a similar field called `CASignatureAlgorithms`.

**Comment by awly** [comment]
@russjones PTAL

I added a config field for this, which defaults to SHA-512.
This field only needs to be set on the auth server. Then it propagates like so:
- all new user/host certs get signed by the CA using the specified algo
- user/host cert consumers use the same signature algo as was used by the CA to sign certs (taken from `ssh.Certificate.Signature.Format` field)

**Comment by awly** [comment]
OK, reworked this per our convo with @russjones 
High-level overview:
- signature algorithm is stored along with CA in the backend
  - if missing, assume SHA1 (the old behavior)
- startup/upgrade:
  - existing CAs are unchanged
  - new CAs default to SHA2-256
  - setting `ca_signature_algo` in `teleport.yaml` can override the behavior for new CAs
- rotation:
  - existing CAs are unchanged by default
  - setting `ca_signature_algo` in `teleport.yaml` **will** change the algorithm on next rotation
- to migrate to SHA2, users need to update their config and do a rotation

PTAL

**Review by russjones — APPROVED** [review]

**Comment by russjones** [comment]
@gravitational-jenkins retest this please

**Comment by awly** [comment]
Good thing we had those integration tests!
I was actually silently skipping the new signing algo when using a user cert to do handshakes, which is why things worked in manual testing. Host-to-host authn (with trusted clusters) exposed the bug.

[This check](https://github.com/golang/crypto/blob/master/ssh/server.go#L285-L292) on the server side of the handshake is preventing our new signing algorithm. There doesn't seem to be a way around it.

Which means that:
- we can sign user/host certs with SHA2-512
- we can NOT use SHA2-512 for SSH handshakes

And I'm pretty sure the way I change cert signing is against the spec (SSH certs should be using formats like `rsa-sha2-512-cert-v01@openssh.com`, not `rsa-sha2-512`).

This leaves us with 3 options:
1. fork `x/crypto/ssh` with a one-line change to allow our signing algorithms and use this PR
2. fork `x/crypto/ssh` with https://go-review.googlesource.com/c/crypto/+/220037 and use only the parts of this PR that deal with switching alg on rotation
3. keep that part of this PR that switches to SHA2 for cert signing ONLY and wait until OpenSSH deprecates SHA-1 for actual handshakes or `x/crypto/ssh` patch lands upstream

Need some guidance here @russjones

**Comment by awly** [comment]
OK, I reverted the changes that affect SSH handshakes. This is option No.3.
This PR now only uses SHA2 for cert signing, which makes OpenSSH happy. Upcoming OpenSSH releases will deprecate SHA2 for handshakes as well, so we'll have to revisit this problem.

This also unblocks 4.3 testing, since currently `ssh` will always fail against our SHA1-signed certs.

**Pull request merged**
