### PR TITLE
[v8] Fix nindent of `service.spec` in teleport-cluster chart

### PR DESCRIPTION
**Pull request by lord-kyron**
Fix nindent problems for service spec, preventing to use the option

### CODE REVIEW

**Comment by zmb3** [comment]
Thanks for the contribution!

Is this also broken on master? If so, it's usually best that we merge to master first and then backport as necessary.

**Comment by lord-kyron** [comment]
I believe master is following the latest changes which is branch v9. In v9 this is fixed, but this means that we have to wait till teleport 9 release to get the fix. I wanted to backport this to branch v8 so that we ca use it with 8.2.0 and 8.3.x charts.

**Comment by lord-kyron** [comment]
@zmb3 does this explanation makes sense?

**Review by zmb3 — APPROVED** [review]

**Comment by zmb3** [comment]
> @zmb3 does this explanation makes sense?

Yep, thanks!

**Comment by lord-kyron** [comment]
@r0mant do you approve it also?

**Review by r0mant — APPROVED** [review]

**Comment by lord-kyron** [comment]
@zmb3 @r0mant  since we have the approvals, can someone merge this as I don't have write access to the repo, or?

**Comment by russjones** [comment]
Will buddy merge in https://github.com/gravitational/teleport/pull/10778.

**Pull request closed without merging**
