### PR TITLE
Connect: Update Electron to 25.1 and TypeScript to 5.1

### PR DESCRIPTION
**Pull request by gzdunek**
Updates Electron and TS to the latest versions.

While testing, I noticed that force focusing a minimized window no longer works on Windows. That is, the window did not unminimize or even blink on the taskbar. I made an attempt to fix this, and the solution I found is to restore the window if it is minimized, and then just call `app.focus`. 
I hoped that I fixed an issue that we had on Windows, when the window was not moved to the foreground when `forceFocus` was called, and the window was in the background. It worked fine when I tested it in dev mode, but today I tested the packaged app and it worked like before, that is, the window didn't go to the foreground if it was in the background 😵‍💫.

I also tried to replace [deprecated](https://www.electronjs.org/blog/electron-25-0#breaking-changes) `protocol.interceptFileProtocol`, but I failed. I used `protocol.handle('file', (request) => {}))`, but the callback was not invoked and I don't know why. Isn't `file` a valid protocol? I think we can leave it for now, and see how others implement it? It's hard to find any examples of that.

Tag build https://drone.platform.teleport.sh/gravitational/teleport/25192/2/8.

### CODE REVIEW

**Comment by avatus** [comment]
Will try this out tomorrow on my windows/linux boxes and report back. a bit behind today

**Comment by ravicious** [comment]
25.1.1 came out yesterday with fixes to `protocol.handle`. https://github.com/electron/electron/pull/38587

**Comment by gzdunek** [comment]
>Will try this out tomorrow on my windows/linux boxes and report back. a bit behind today

I've tested that on my VMs, but a test on a real machine is always welcome!

>25.1.1 came out yesterday with fixes to protocol.handle. https://github.com/electron/electron/pull/38587

I didn't notice any difference :(

**Review by avatus — APPROVED** [review]

**Review by ravicious — APPROVED** [review]
Thanks for updating TS as well. I think it might be best to update TS in a separate PR in the future since it affects not only Connect. I think it might be best to update the PR title to reflect that TS was updated as well.

**Comment by gzdunek** [comment]
>I also tried to replace [deprecated](https://www.electronjs.org/blog/electron-25-0#breaking-changes) protocol.interceptFileProtocol, but I failed. I used protocol.handle('file', (request) => {})), but the callback was not invoked and I don't know why. Isn't file a valid protocol? I think we can leave it for now, and see how others implement it? It's hard to find any examples of that.

There was a bug in handling `file` protocol https://releases.electronjs.org/release/v25.3.0.
We can take care of this when updating to next version.

**Pull request merged**
