### PR TITLE
Bump x/crypto to 20220518 and remove custom algorithm signer

### PR DESCRIPTION
**Pull request by marcoandredinis**
This commit upgrades the version of x/crypto we use, to the current latest
`go get -u golang.org/x/crypto`

We also replaced the deprecated variables and updated the tests to match the
current default KEX Algos

The x/crypto didn't support RSA-SHA2 algos, so we developed our own algorithm
signer. This is no longer the case, and after upgrading x/crypto to 20220518 we
can safely remove the custom code we have.

TODO (from https://github.com/gravitational/teleport/pull/11178#issuecomment-1115504375)
- [x] Set `ca_signature_algo` to `ssh-rsa` and make sure that:
  - [x] OpenSSH clients < 8.2 work fine.
  - [x] OpenSSH 8.2 which deprecated SHA1 work with `PubkeyAcceptedKeyTypes` workaround mentioned above.
  - [x] OpenSSH 8.8 removed support for SHA1, does it still work with the workaround above?
- [x] Set `ca_signature_algo` to `rsa-sha2-512` and make sure that:
  - [x] All OpenSSH clients work fine _if we apply the workaround above, otherwise 8.8+ clients fail_

### CODE REVIEW

**Comment by marcoandredinis** [comment]
After a couple of tests, I got the following matrix
| Teleport Version             | `ca_signature_algo` | SSH V | Result |
|------------------------------|---------------------|-------|--------|
| 9.2.3                        | _not set_           |   8.2 | ✅     |
| 9.2.3                        | _not set_           |   8.9 | ❌     |
| 9.2.3                        | `rsa-sha2-512`      |   8.2 | ✅     |
| 9.2.3                        | `rsa-sha2-512`      |   8.9 | ❌     |
| `marco/bump_crypto_20220513` | _not set_           |   8.2 | ✅     |
| `marco/bump_crypto_20220513` | _not set_           |   8.9 | ❌     |
| `marco/bump_crypto_20220513` | `rsa-sha2-512`      |   8.2 | ✅     |
| `marco/bump_crypto_20220513` | `rsa-sha2-512`      |   8.9 | ❌     |


The good news is that, it looks like we didn't break anything with the lib bump
The bad news is that, it seems we don't handle OpenSSH v8.9 clients (probably, anything greater than v8.8)

I'll do some digging as to why we don't 

(using the comments as log)

**Review by rosstimothy — APPROVED** [review]
The changes here all seem reasonable to me. Just a couple questions around the OpenSSH 8.9 incompatibility:
- Do we have an open issue regarding OpenSSH 8.9 clients not functioning without the workaround?
-  Is the workaround documented anywhere else but here?

**Comment by marcoandredinis** [comment]
We have one issue [here](https://github.com/gravitational/teleport/issues/10239), with the workaround
I failed to find he workaround in our docs

Do you think we should add it?

**Review by r0mant — COMMENTED** [review]
@marcoandredinis Thank you for pushing this through, great job!

One question I have is regarding backwards compatibility. Since we've removed the "alg signers" workaround, will clusters that set `ca_signature_algo` configuration field be impacted in any way?

**Review by xacrimon — APPROVED** [review]

**Comment by marcoandredinis** [comment]
> @marcoandredinis Thank you for pushing this through, great job!
> 
> One question I have is regarding backwards compatibility. Since we've removed the "alg signers" workaround, will clusters that set `ca_signature_algo` configuration field be impacted in any way?

They should not be impacted
I did some tests locally
- starting with no explicit algorithm
- restarting with `ssh-rsa`
- restarting with `rsa-sha2-512`

In between each step, I connected with the OpenSSH client successfully.

I'm pretty confident we can remove that property
After this PR, we will rely on the `x/crypto` to decide what Signature Algorithm to use ([default is sha512](https://github.com/golang/crypto/blob/6f7dac9698988af7b704298c9fd8adf58e1d30c0/ssh/certs.go#L444)), during the server/client negotiation

Removing the configuration option in this PR will delay the version bump which is more important, so I don't think we should do it know.
I'll open an issue for that and merge this PR

**Pull request merged**
