### PR TITLE
Add a Cloud compatibility warning to Helm guides

### PR DESCRIPTION
**Pull request by ptgott**
Our Helm guides show readers how to use the teleport-cluster
chart, which deploys the Auth and Proxy services. This change adds
a note that Cloud users should use our teleport-kube-agent chart
instead.

### CODE REVIEW

**Comment by stevenGravy** [comment]
@ptgott the Guide should probably state more that this can deploy Teleport and provide access to a k8s cluster.  The agent should be used to provide k8s, app and db access

**Comment by ptgott** [comment]
@stevenGravy Do you mean that I should edit the second paragraph in the `Details` box to mention that you can use the `teleport-kube-agent` chart for k8s, app, and db access?

**Comment by stevenGravy** [comment]
> @stevenGravy Do you mean that I should edit the second paragraph in the `Details` box to mention that you can use the `teleport-kube-agent` chart for k8s, app, and db access?

Yes, that's the thought

**Review by zmb3 — APPROVED** [review]

**Comment by ptgott** [comment]
@stevenGravy I've suggested a change—does this work for you?

**Review by russjones — APPROVED** [review]

**Review by klizhentas — APPROVED** [review]

**Comment by stevenGravy** [comment]
> @stevenGravy I've suggested a change—does this work for you?

that's great!

**Pull request merged**
