### PR TITLE
Connect: Update Electron to 22.3.2

### PR DESCRIPTION
**Pull request by gzdunek**
Dev build: 12.1.0-dev.gzdunek.1

Tested on: macOS, Windows, Ubuntu, Fedora (for Linux I created local builds)
I didn't not find any issues.

### CODE REVIEW

**Review by ryanclark — APPROVED** [review]

**Comment by gzdunek** [comment]
Before 🫣

**Comment by ravicious** [comment]
Could you make local Linux and macOS builds then to verify that the shell is still working correctly? I'm making one on Windows at the moment.

**Comment by gzdunek** [comment]
Sure 🫡

**Review by hatched — APPROVED** [review]

**Comment by gzdunek** [comment]
Mac and Linux work fine 👍

**Review by ravicious — APPROVED** [review]
It seems to work fine on Windows.

**Pull request merged**
