### PR TITLE
chore: Bump AWS modules

### PR DESCRIPTION
**Pull request by codingllama**
Update AWS dependencies to their latest versions.

This is a significant part of the monthly updates, so I've opted to do it separately from #42262.

### CODE REVIEW

**Review by rosstimothy — APPROVED** [review]
Thanks @codingllama !

**Review by hugoShaka — APPROVED** [review]

**Review by tigrato — APPROVED** [review]

**Comment by codingllama** [comment]
Added "eu-isoe-west-1" as a valid AWS region (see a2e215baefaa31da6a8b02f3cf62a0009f410f17). Fixes test breakage.

**Comment by codingllama** [comment]
I'll keep the auto-merge as the fix seems simple enough, shout if you want any other changes.

**Comment by greedy52** [comment]
> Added "eu-isoe-west-1" as a valid AWS region (see [a2e215b](https://github.com/gravitational/teleport/commit/a2e215baefaa31da6a8b02f3cf62a0009f410f17)). Fixes test breakage.

lol. I don't know if Teleport will work or not in those secret regions.

**Review by greedy52 — APPROVED** [review]

**Comment by codingllama** [comment]
> > Added "eu-isoe-west-1" as a valid AWS region (see [a2e215b](https://github.com/gravitational/teleport/commit/a2e215baefaa31da6a8b02f3cf62a0009f410f17)). Fixes test breakage.
> 
> lol. I don't know if Teleport will work or not in those secret regions.

Feel free to follow up as you see fit. Maybe we should just filter this one out?

**Pull request merged**
