### PR TITLE
Update region list/Teleport version for Terraform

### PR DESCRIPTION
**Pull request by webvictim**

### CODE REVIEW

**Comment by webvictim** [comment]
retest this please

**Review by benarent — APPROVED** [review]

**Review by benarent — CHANGES_REQUESTED** [review]
I double checked the AMI , it looks like we need to get AWS to approve our 4.2 releases.
image

**Comment by webvictim** [comment]
I haven’t released the AMIs to Marketplace in a fair while as it seemed like nobody was using them. I’ll get us updated to the latest 4.2.3 tomorrow.

**Comment by webvictim** [comment]
retest this please

**Comment by webvictim** [comment]
retest this please

**Comment by webvictim** [comment]
retest this please

**Comment by webvictim** [comment]
FYI @benarent this doesn't actually block anyone from using Teleport 4.2.3 with Terraform, if that's the reason you requested changes. We have two different sets of AMIs which are generated by the release process.

1) We make an AMI for each version (with the name format `gravitational-teleport-ami-[oss|ent]-<version>`) public automatically:
```
$ aws ec2 describe-images --owners 126027368216 --region us-east-1 --filters 'Name=name,Values=gravitational-teleport-ami-ent*'| jq -r '.Images[] | .Name + " [" + .ImageId + "]: " + (.Public|tostring)' | sort -V
gravitational-teleport-ami-ent-3.1.7 [ami-076ccfed8a4a85fed]: true
gravitational-teleport-ami-ent-3.1.8 [ami-075acd58b5cd74325]: true
gravitational-teleport-ami-ent-3.2.0 [ami-0835eba202364b8e0]: true
gravitational-teleport-ami-ent-3.2.1 [ami-067a6e409b3cf2cb5]: true
gravitational-teleport-ami-ent-3.2.2 [ami-0b25fd2fc6bd20788]: true
gravitational-teleport-ami-ent-3.2.4 [ami-03652fa0ac8ad3326]: true
gravitational-teleport-ami-ent-3.2.6 [ami-0bc7c3bdef639b4e8]: true
gravitational-teleport-ami-ent-4.0.0 [ami-00bf5e971654a0b95]: true
gravitational-teleport-ami-ent-4.0.1 [ami-07f097906091e002d]: true
gravitational-teleport-ami-ent-4.0.2 [ami-0b4a185f20187e059]: true
gravitational-teleport-ami-ent-4.0.3 [ami-09ed381679673520d]: true
gravitational-teleport-ami-ent-4.0.4 [ami-0e53cd757bc98e23b]: true
gravitational-teleport-ami-ent-4.0.9 [ami-0bff1e475f24ce5fc]: true
gravitational-teleport-ami-ent-4.0.9-fips [ami-041b7e973a9b22790]: true
gravitational-teleport-ami-ent-4.0.10 [ami-0ace87f9b158db08f]: true
gravitational-teleport-ami-ent-4.0.10-fips [ami-07a7d9f0779f21dcf]: true
gravitational-teleport-ami-ent-4.0.12 [ami-035eacb6aba9a1f9e]: true
gravitational-teleport-ami-ent-4.0.12-fips [ami-0f238975dc254eb1f]: true
gravitational-teleport-ami-ent-4.1.0 [ami-02bba5875c6283688]: true
gravitational-teleport-ami-ent-4.1.0-fips [ami-07189c34ce892b134]: true
gravitational-teleport-ami-ent-4.1.2 [ami-027f0627fca289fa4]: true
gravitational-teleport-ami-ent-4.1.2-fips [ami-04eb333af29638ca5]: true
gravitational-teleport-ami-ent-4.1.3 [ami-0e7c2fd0e12785caa]: true
gravitational-teleport-ami-ent-4.1.3-fips [ami-0ad800f81dececdee]: true
gravitational-teleport-ami-ent-4.1.4 [ami-0317fe6223c76fcde]: true
gravitational-teleport-ami-ent-4.1.4-fips [ami-0d58dadd41d9680ab]: true
gravitational-teleport-ami-ent-4.1.5 [ami-0a8bd5bed0d2f0985]: true
gravitational-teleport-ami-ent-4.1.5-fips [ami-08b381e373d0b6e21]: true
gravitational-teleport-ami-ent-4.1.6 [ami-0baf68aebcfc581f6]: true
gravitational-teleport-ami-ent-4.1.6-fips [ami-0dc48fd476b6ab06a]: true
gravitational-teleport-ami-ent-4.2.0 [ami-00e0e97a81db86960]: true
gravitational-teleport-ami-ent-4.2.0-fips [ami-01e32c305879f3f3a]: true
gravitational-teleport-ami-ent-4.2.1 [ami-0f89d94ceab674cda]: true
gravitational-teleport-ami-ent-4.2.1-fips [ami-038149c17f5815841]: true
gravitational-teleport-ami-ent-4.2.2 [ami-082a77c6da88c7d2c]: true
gravitational-teleport-ami-ent-4.2.2-alpha.1 [ami-089fb379b9224c85d]: true
gravitational-teleport-ami-ent-4.2.2-alpha.1-fips [ami-0cff82629d7e4a377]: true
gravitational-teleport-ami-ent-4.2.2-fips [ami-05db59337ca11a572]: true
gravitational-teleport-ami-ent-4.2.3 [ami-0be8f0e96c6819a1c]: true
gravitational-teleport-ami-ent-4.2.3-beta.1 [ami-08be6d48f69b1fc3a]: true
gravitational-teleport-ami-ent-4.2.3-beta.1-fips [ami-08cc9a219c88b87be]: true
gravitational-teleport-ami-ent-4.2.3-fips [ami-030aa43a4c383bfdf]: true
```

2) We also publish a private copy of the same image with the name format `gravitational-teleport-marketplace-ami-[oss|ent]-<version>`:

```
$ aws ec2 describe-images --owners 126027368216 --region us-east-1 --filters 'Name=name,Values=gravitational-teleport-marketplace-ami-ent*'| jq -r '.Images[] | .Name + " [" + .ImageId + "]: " + (.Public|tostring)' | sort -V
gravitational-teleport-marketplace-ami-ent-3.1.7 [ami-05cff101f517ef13e]: false
gravitational-teleport-marketplace-ami-ent-3.1.8 [ami-0838fd4bed193d768]: false
gravitational-teleport-marketplace-ami-ent-3.2.0 [ami-01bc14981961be3d6]: false
gravitational-teleport-marketplace-ami-ent-3.2.1 [ami-03e9c03caae15ecdc]: false
gravitational-teleport-marketplace-ami-ent-3.2.2 [ami-096c6bac97d0a28c6]: false
gravitational-teleport-marketplace-ami-ent-3.2.4 [ami-04cbff17bafb78e74]: false
gravitational-teleport-marketplace-ami-ent-3.2.6 [ami-0d0ad18db4c04ceeb]: false
gravitational-teleport-marketplace-ami-ent-4.0.0 [ami-03031b1a139827492]: false
gravitational-teleport-marketplace-ami-ent-4.0.1 [ami-05064204948d68f42]: false
gravitational-teleport-marketplace-ami-ent-4.0.2 [ami-021e502c97d21419c]: false
gravitational-teleport-marketplace-ami-ent-4.0.3 [ami-03a2d796d40eafddf]: false
gravitational-teleport-marketplace-ami-ent-4.0.4 [ami-06bf34d24f72fd33c]: false
gravitational-teleport-marketplace-ami-ent-4.0.9 [ami-0c62944b8bfdcc252]: false
gravitational-teleport-marketplace-ami-ent-4.0.10 [ami-006f329b0621b57fa]: false
gravitational-teleport-marketplace-ami-ent-4.0.12 [ami-06850fda631ec2eba]: false
gravitational-teleport-marketplace-ami-ent-4.1.0 [ami-08f18e5c8eb8008f7]: false
gravitational-teleport-marketplace-ami-ent-4.1.2 [ami-0138208abe7977f9c]: false
gravitational-teleport-marketplace-ami-ent-4.1.3 [ami-07c748ac4b7064951]: false
gravitational-teleport-marketplace-ami-ent-4.1.4 [ami-0345d0f9b37faedf7]: false
gravitational-teleport-marketplace-ami-ent-4.1.5 [ami-0e2c7359783d3615e]: false
gravitational-teleport-marketplace-ami-ent-4.1.6 [ami-075289929bedaffc9]: false
gravitational-teleport-marketplace-ami-ent-4.2.0 [ami-0eef755525a1c1758]: false
gravitational-teleport-marketplace-ami-ent-4.2.1 [ami-0f6194ec57f330465]: false
gravitational-teleport-marketplace-ami-ent-4.2.2 [ami-0cc5d71f92cee9f34]: false
gravitational-teleport-marketplace-ami-ent-4.2.2-alpha.1 [ami-095dec6212238b96b]: false
gravitational-teleport-marketplace-ami-ent-4.2.3 [ami-006e85f6592efdee9]: false
gravitational-teleport-marketplace-ami-ent-4.2.3-beta.1 [ami-08aef42618fb848c6]: false
```

Anyone who wants to use any of our AMIs for Teleport with Terraform can do it independently of the AWS Marketplace; the Marketplace is just another way that we offer AMIs to people. It's a manual publishing process via an AWS UI which has to be done every time we publish a new version, though, which is why it lags behind the current version somewhat.

The reason for having separate images is that when you publish to Marketplace, AWS 'consumes' the image by 1) adding the Marketplace account ID as an owner and 2) changing the image's visibility to private. We always want to keep a public image for each version available, so having two separate images is the easiest way to achieve this. The contents are identical between the two versions.

**Comment by webvictim** [comment]
@gravitational-jenkins retest this please

**Review by benarent — APPROVED** [review]
Thanks for the clarification Gus.

**Pull request merged**
