### PR TITLE
chore: Bump golang.org/x/crypto to v0.17.0

### PR DESCRIPTION
**Pull request by codingllama**
Update to latest release / security patch.

* https://groups.google.com/g/golang-announce/c/qA3XtxvMUyg/m/ZOwFpYq3AAAJ

Changelog: Bump golang.org/x/crypto to v0.17.0

### CODE REVIEW

**Comment by codingllama** [comment]
Tidied and added api/go.mod

**Review by zmb3 — APPROVED** [review]
changelog entry probably wouldn't hurt since this does resolve a CVE that may start to show up in scanners

**Comment by codingllama** [comment]
> changelog entry probably wouldn't hurt since this does resolve a CVE that may start to show up in scanners

I was planning on the changelog for the backports, as I assume new releases already have patched dependencies. I can add it here, though.

**Comment by codingllama** [comment]
Added Changelog, feel free to remove/edit/etc.

**Review by tigrato — APPROVED** [review]

**Pull request merged**
