### PR TITLE
Aggressive connection bookeeping for reverse tunnels

### LINKED ISSUE #556: Enforce idle timeout in proxy transport
## Description

We recently found a bug on a client side that affected this function:

https://github.com/gravitational/teleport/blob/master/lib/reversetunnel/agent.go#L225

In essense, clients to reverse tunnel were leaking connections never closing them. Techincally this is a fault of a client, however we should limit the number of client connections opened via this function and terminate the connections that are idle longer than some reasonable default, e.g. (10-15 minutes of inactivity), otherwise client bugs will lead to denial of service of the reverse tunnel.

### PR DESCRIPTION
**Pull request by kontsevoy**
Closes #556
### Changes

Two things:
1. Read/write timeouts are applied on both client & server.
2. Server now always closes its connection if there are any issues  communicating with the client.
### Misc

I see this PR as "medium" risk so we probably should be extra-careful merging it right in front of a stable gravity build

### CODE REVIEW

**Review by klizhentas — APPROVED** [review]
I did review the approach, and it looks good, let's merge this in. I had some concerns about `SetReadDeadline`, but after digging into runtime a bit, it looks quite secure to call in in concurrent mode as implemented by go runtime.

**Comment by kontsevoy** [comment]
I want to do one more round of corner case testing before merging.

**Comment by kontsevoy** [comment]
retest this

**Comment by kontsevoy** [comment]
retest this please

**Pull request merged**
