### PR TITLE
Add proxied databases to DatabaseService

### PR DESCRIPTION
**Pull request by marcoandredinis**
This PR changes the DatabaseService to also heartbeat the proxied databases.
This is useful to troubleshoot issues with database access.

This was done in a way that we can extend the properties of each database.
Eg, in the future we can also include the number of active connections to a given database.

Demo:
`tctl get db_service`
```yaml
kind: db_service
metadata:
  expires: "2024-08-27T15:19:40.15076Z"
  name: baad5779-603c-4fbd-8545-7878dd04d57a
  revision: 62f073c8-f4e9-4dde-9e86-7dfb162d06d6
spec:
  hostname: lenix
  proxied_databases:
  - name: dynamic-pg
  - name: static-database
  resources:
  - aws: {}
    labels:
      env: prod
version: v1
```

changelog: Proxied databases by a Database Service can now be queried using `tctl get db_service`.

### CODE REVIEW

**Review by greedy52 — COMMENTED** [review]
proxied databases already have their own heartbeats. what benefit this gives over listing `db_server`?

**Comment by marcoandredinis** [comment]
Having a clear view of what `db_servers` are being heartbeated by a given `database_service` is helpful when troubleshooting.
Otherwise, you have to compare labels with label matchers, and do RBAC checks manually.

Also, it might happen that a temporary failure makes the database not accessible in a given DatabaseService even though it passed the RBAC checks. I'm not sure about this one, but looking at the code it seems possible.

This issue can give more context
https://github.com/gravitational/teleport/issues/45804

Also, @stevenGravy , if you want to give more inputs on this.

**Comment by greedy52** [comment]
> Having a clear view of what `db_servers` are being heartbeated by a given `database_service` is helpful when troubleshooting. Otherwise, you have to compare labels with label matchers, and do RBAC checks manually.
> 
> Also, it might happen that a temporary failure makes the database not accessible in a given DatabaseService even though it passed the RBAC checks. I'm not sure about this one, but looking at the code it seems possible.
> 
> This issue can give more context #45804
> 
> Also, @stevenGravy , if you want to give more inputs on this.

It's a bit long but you can get search all db services for a particular dynamic db like this?
```bash
tctl get db_server/test-db-98 --format json | jq -r .[].spec.host_id | xargs -I {} bash -c "tctl get db_service/{} --format json | jq -r .[].metadata.name"
``` 

The proxied databases include both static, dynamic. so not sure it would be more confusing. Also the heartbeat is a snaphot so i think listing `db_server` directly is more accurate

**Comment by marcoandredinis** [comment]
Will that work if you have HA set up?
IIRC, there's deduplication of `db_server` when returning the servers in API calls.
So, extracting the host id from the `tctl get db_server/test-db-98` will not return all the database_service's names.

**Comment by greedy52** [comment]
> Will that work if you have HA set up? IIRC, there's deduplication of `db_server` when returning the servers in API calls. So, extracting the host id from the `tctl get db_server/test-db-98` will not return all the database_service's names.

`tsh/tctl db ls` deduplicates. `tctl get db_server` shouldn't.

Alternatively, maybe we can implement some cool helper commands like `tctl db dynamic-resource-test` or something

**Comment by stevenGravy** [comment]
Frequently customers and prospects want to have a top down view of their connected resources. Having list of databases helps to both confirm a database has been added and the current load on a db service.

**Comment by greedy52** [comment]
> Frequently customers and prospects want to have a top down view of their connected resources. Having list of databases helps to both confirm a database has been added and the current load on a db service.

sorry i was wrong about `tctl db ls`, which does NOT deduplicate. Is this view good enough?
```
$ tctl db ls "teleport.dev/origin=dynamic"
Host                                        Name                        Protocol URI                                        Labels                   Version    
------------------------------------------- --------------------------- -------- ------------------------------------------ ------------------------ ---------- 
STeves-MacBook-Pro.local                    mongo-atlas                 mongodb  mongodb+srv://stevexin.joeizhy.mongodb.net                          17.0.0-dev 
STeves-MacBook-Pro.local                    self-hosted-mysql           mysql    localhost:3306                                                      17.0.0-dev 
STeves-MacBook-Pro.local                    self-hosted-postgres        postgres localhost:15432                                                     17.0.0-dev 
STeves-MacBook-Pro.local                    self-hosted-postgres-drop   postgres localhost:15432                            db-auto-user-mode=drop   17.0.0-dev 
STeves-MacBook-Pro.local                    self-hosted-postgres-import postgres localhost:15432                            db-auto-user-mode=import 17.0.0-dev 
STeves-MacBook-Pro.local                    self-hosted-postgres-keep   postgres localhost:15432                            db-auto-user-mode=keep   17.0.0-dev 
STeves-MacBook-Pro.local                    self-hosted-redis           redis    localhost:6379                                                      17.0.0-dev 
ip-10-0-0-211.ca-central-1.compute.internal mongo-atlas                 mongodb  mongodb+srv://stevexin.joeizhy.mongodb.net                          17.0.0-dev 
ip-10-0-0-211.ca-central-1.compute.internal self-hosted-mysql           mysql    localhost:3306                                                      17.0.0-dev 
ip-10-0-0-211.ca-central-1.compute.internal self-hosted-postgres        postgres localhost:15432                                                     17.0.0-dev 
ip-10-0-0-211.ca-central-1.compute.internal self-hosted-postgres-drop   postgres localhost:15432                            db-auto-user-mode=drop   17.0.0-dev 
ip-10-0-0-211.ca-central-1.compute.internal self-hosted-postgres-import postgres localhost:15432                            db-auto-user-mode=import 17.0.0-dev 
ip-10-0-0-211.ca-central-1.compute.internal self-hosted-postgres-keep   postgres localhost:15432                            db-auto-user-mode=keep   17.0.0-dev 
ip-10-0-0-211.ca-central-1.compute.internal self-hosted-redis           redis    localhost:6379                                                      17.0.0-dev 
```

**Comment by stevenGravy** [comment]
> > Frequently customers and prospects want to have a top down view of their connected resources. Having list of databases helps to both confirm a database has been added and the current load on a db service.
> 
> 
> 
> sorry i was wrong about `tctl db ls`, which does NOT deduplicate. Is this view good enough?
> 
> ```
> 
> $ tctl db ls "teleport.dev/origin=dynamic"
> 
> Host                                        Name                        Protocol URI                                        Labels                   Version    
> 
> ------------------------------------------- --------------------------- -------- ------------------------------------------ ------------------------ ---------- 
> 
> STeves-MacBook-Pro.local                    mongo-atlas                 mongodb  mongodb+srv://stevexin.joeizhy.mongodb.net                          17.0.0-dev 
> 
> STeves-MacBook-Pro.local                    self-hosted-mysql           mysql    localhost:3306                                                      17.0.0-dev 
> 
> STeves-MacBook-Pro.local                    self-hosted-postgres        postgres localhost:15432                                                     17.0.0-dev 
> 
> STeves-MacBook-Pro.local                    self-hosted-postgres-drop   postgres localhost:15432                            db-auto-user-mode=drop   17.0.0-dev 
> 
> STeves-MacBook-Pro.local                    self-hosted-postgres-import postgres localhost:15432                            db-auto-user-mode=import 17.0.0-dev 
> 
> STeves-MacBook-Pro.local                    self-hosted-postgres-keep   postgres localhost:15432                            db-auto-user-mode=keep   17.0.0-dev 
> 
> STeves-MacBook-Pro.local                    self-hosted-redis           redis    localhost:6379                                                      17.0.0-dev 
> 
> ip-10-0-0-211.ca-central-1.compute.internal mongo-atlas                 mongodb  mongodb+srv://stevexin.joeizhy.mongodb.net                          17.0.0-dev 
> 
> ip-10-0-0-211.ca-central-1.compute.internal self-hosted-mysql           mysql    localhost:3306                                                      17.0.0-dev 
> 
> ip-10-0-0-211.ca-central-1.compute.internal self-hosted-postgres        postgres localhost:15432                                                     17.0.0-dev 
> 
> ip-10-0-0-211.ca-central-1.compute.internal self-hosted-postgres-drop   postgres localhost:15432                            db-auto-user-mode=drop   17.0.0-dev 
> 
> ip-10-0-0-211.ca-central-1.compute.internal self-hosted-postgres-import postgres localhost:15432                            db-auto-user-mode=import 17.0.0-dev 
> 
> ip-10-0-0-211.ca-central-1.compute.internal self-hosted-postgres-keep   postgres localhost:15432                            db-auto-user-mode=keep   17.0.0-dev 
> 
> ip-10-0-0-211.ca-central-1.compute.internal self-hosted-redis           redis    localhost:6379                                                      17.0.0-dev 
> 
> ```

That will only show for the DBs you have access to. I thought db services won't restrict the admins from viewing their list of services.

**Comment by marcoandredinis** [comment]
> Is it common for a kind of admin that has access to db_service but not the databases?

I don't think that would be a common set up.
If someone has access to the list of running services, I think it's expected for them to also have access to at least the database names.

But I agree, that it can lead to leaking information.
Given this, I'm re-thinking the usefulness of this feature vs the security implications.

**Comment by espadolini** [comment]
Practical implication: an individual backend item should not be bigger than 128KiB or so (and dynamodb writes cost _per kb written_), so with a large amount of databases you might hit a size limit on the heartbeat itself.

**Comment by marcoandredinis** [comment]
I was not aware of that limit, but I think we will face proxying issues before that is actually a problem.

Is that a hard limit or a recommendation?

Using back of a napkin calculations, I think we should be fine with 2700 databases (some assumptions were used on this calculation).

Anyway, the security question is the one that concerns me the most.
@zmb3 Do you have an opinion on this?

**Pull request closed without merging**
