### PR TITLE
kube: handle large number of trusted clusters in mTLS handshake

### PR DESCRIPTION
**Pull request by awly**
Same as https://github.com/gravitational/teleport/issues/3870 but for
k8s endpoints. There is a hard limit on how many CAs we can put into a
client CertPool, usually several hundred (depending on Subject length).

The solution here is to fall back to only using the current cluster's CA
for validation if the limit is reached. This is almost always the case
in root clusters. There, the client certificate will be signed by the
root cluster and validation will pass.

In the unlikely case that you have a leaf cluster which in turn has
hundreds of trusted leaf clusters itself, the validation will fail. The
client cert will still be signed by the root cluster (not the leaf).
However, that's better than a panic. And I'm not aware of any real
setups like that.

Also in this PR, add the wildcard `*.teleport.cluster.local` SAN to
proxy and k8s TLS certificates, which was missing before. This SAN is
used for clients to encode the cluster name and pass it in SNI. The
client (kubectl) is not updated to set this SNI yet, it would break
existing clusters without the SAN change.

Updates https://github.com/gravitational/teleport/issues/5001

### CODE REVIEW

**Review by Joerger — APPROVED** [review]

**Review by andrejtokarcik — APPROVED** [review]
It might be too cumbersome at this point, but in order not to disallow 2nd-order leaf clusters (leafs of leafs) outright, the truncated CA pool could be made to consist of the current/root cluster + any leaf cluster that reports to have its own leaf clusters registered...?

**Comment by andrejtokarcik** [comment]
Isn't this commit description a bit misleading?

> In the unlikely case that you have a leaf cluster which in turn has hundreds of trusted leaf clusters itself, the validation will fail.

It looks like it should say "In the unlikely case that you have a leaf cluster which in turn has a trusted leaf cluster itself, ...".

**Comment by awly** [comment]
> It might be too cumbersome at this point, but in order not to disallow 2nd-order leaf clusters (leafs of leafs) outright, the truncated CA pool could be made to consist of the current/root cluster + any leaf cluster that reports to have its own leaf clusters registered...?

I couldn't understand this. We don't want to disallow 2nd-order leaf clusters.

> It looks like it should say "In the unlikely case that you have a leaf cluster which in turn has a trusted leaf cluster itself, ...".

Nope, a leaf cluster with its own leaf clusters is not a problem (except our cluster routing logic doesn't really support it).
Only a leaf cluster which is forced to truncate the CA pool (per this PR) will hit an issue. The client cert it receives during mTLS handshake will be signed by the root cluster, but it will try to validate it using the leaf cluster CA.

But this multi-tier trusted cluster setup is not something that would work well anyway.

**Comment by andrejtokarcik** [comment]
@awly Don't worry about the first question, there was a misunderstanding on my part.

**Review by russjones — APPROVED** [review]
Bot approved, once test coverage is added.

**Pull request merged**
