### PR TITLE
Add in access list review posthog metrics.

### PR DESCRIPTION
**Pull request by mdwn**
Access list review posthog metrics have been added.

Corresponding cloud PR: https://github.com/gravitational/cloud/pull/6948

### CODE REVIEW

**Comment by zmb3** [comment]
Can you link to the corresponding cloud PR?

**Comment by mdwn** [comment]
> Can you link to the corresponding cloud PR?

Updated the description!

**Review by ibeckermayer — APPROVED** [review]

**Comment by zmb3** [comment]
Thanks for the link. What's the plan - keep this open until the cloud change is verified and deployed? Or merge this now and just hold off on the backport until the cloud change is deployed?

**Comment by mdwn** [comment]
> Thanks for the link. What's the plan - keep this open until the cloud change is verified and deployed? Or merge this now and just hold off on the backport until the cloud change is deployed?

We've got to wait until the cloud change is at least committed. It deploys pretty quickly IIRC, but I can't merge this until then. So basically option 3: hold off on merging this at all (plus any backports) until prehog is verified and deployed.

**Review by zmb3 — APPROVED** [review]

**Review by smallinsky — APPROVED** [review]

**Pull request merged**
