### PR TITLE
Remove pre-v7 device migration logic

### PR DESCRIPTION
**Pull request by codingllama**
Follows up on a few `// DELETE IN: 7` TODOs.

### CODE REVIEW

**Comment by codingllama** [comment]
FYI @awly.

**Review by awly — APPROVED** [review]
LGTM, assuming you tested that a cluster upgraded through that migration still works after removing all the compatibility hacks.

**Comment by codingllama** [comment]
> LGTM, assuming you tested that a cluster upgraded through that migration still works after removing all the compatibility hacks.

OK, so this is what I did:

1. Started a brand new install using Teleport 5.2, creating 2 users (branch/v5.2)
    * foo (using second_factor:u2f)
    * foo-otp (using second_factor:otp)
    (note, there is no second_factor:optional on Teleport 5.2)

2. Changed second_factor to "optional" and upgraded to Teleport 6.2 (branch/v6)
    * Logged with foo-otp and foo
    * Created user foo6, added otp and u2f devices, logged in, didn't restart server in-between (no v6 migration for foo6)

3. Upgraded to Teleport 7.2 (branch/v7)
    * Logged in with foo-otp, foo and foo6
    * Created user foo7, added otp and u2f devices, logged in, didn't restart server in-between(no v7 migration for foo7)

4. Upgraded to current Teleport (codingllama/u2f-cleanup)
    * Logged in with foo-otp, foo, foo6 and foo7, using all devices
    * Created user foo8, logged in

It all seems to work as intended. Let me know if you had something else in mind, @awly.

**Comment by codingllama** [comment]
Friendly ping @awly / reviewers? May I send this one to bots?

**Review by zmb3 — APPROVED** [review]
`+10 -247` 🎉

**Comment by awly** [comment]
LGTM

**Review by klizhentas — APPROVED** [review]

**Pull request merged**
