### PR TITLE
Refactor lib/kube/client

### PR DESCRIPTION
**Pull request by awly**
- rename package from `client` to `kubeconfig` and remove "kubeconfig"
  from function names
  (https://github.com/golang/go/wiki/CodeReviewComments#package-names)
- export `Update` and `UpdateWithClient` to allow updates without
  building a full `TeleportClient`
- accept an optional user-specified path to kubeconfig, to bind to CLI
  flags

Updates #2825

### CODE REVIEW

**Review by russjones — COMMENTED** [review]
What do you think about calling the methods on `kubeconfig` from a `TeleportClient`?

It's a Teleport Client not a SSH client, so in theory it should support all protocols that Teleport supports. That way in `tsh.go` we can go from:

```go
kubeconfig.UpdateWithClient("", tc) 
```

to

```go
tc.UpdateKubeconfig()
```

Ideally not even passing the `path` variable since it doesn't looks like it's ever set in production, only in tests where you could pass it into the private function that does the actual call.

**Comment by awly** [comment]
> What do you think about calling the methods on kubeconfig from a TeleportClient?

I'd like to avoid adding more logic to `TeleportClient`.
`lib/client` is already ~8k LOC. Parsing/wrinting configs feels like a concern separate from clients using those configs.

```
Ideally not even passing the path variable since it doesn't looks like it's ever set in production, only in tests where you could pass it into the private function that does the actual call.
```

This PR is a step towards implementing `tctl auth sign --format=kubernetes --user=ci-bot --out=/path/to/kubeconfig`. It will need to take a custom flag, to match how all other formatting options work.

**Review by russjones — APPROVED** [review]
@awly Makes sense, didn't know you planned to pass in paths outside of tests.

**Comment by awly** [comment]
retest this please

**Comment by awly** [comment]
retest this please

**Comment by awly** [comment]
retest this please

**Comment by awly** [comment]
retest this please

**Pull request merged**
