### PR TITLE
[v14] fix: Do not attempt relogin on remote BadParameter errors

### PR DESCRIPTION
**Pull request by codingllama**
Backport #36866 and #37647 to branch/v14.

Changelog: Fix tsh trying to relogin on fatal errors

#36749, #36850

### CODE REVIEW

**Comment by codingllama** [comment]
Clean backport - git got a bit confused with the assertions on api/utils/grpc/interceptors/errors_test.go but the final patch ended exactly the same.

**Comment by codingllama** [comment]
I'll hold merging until the end of v15 testplan, just in case.

**Review by tigrato — APPROVED** [review]

**Review by Joerger — APPROVED** [review]

**Review by rosstimothy — APPROVED** [review]

**Comment by codingllama** [comment]
FYI, I'm waiting until #37647 can be backported to merge this one.

**Comment by codingllama** [comment]
I've cherry-picked #37647 on top of this. PTAL.

**Review by Joerger — APPROVED** [review]

**Pull request merged**
