### PR TITLE
Fixes racy backend test suite

### PR DESCRIPTION
**Pull request by tcsc**
After routinely having CI builds fail in parts of the system unrelated to the change, I started to dig.

Many of these failures happened inside the backend compliance test suite, specifically in `BackendSuite.Locking()`. After a few more test failures it became apparent that the backend under test (`etcd`, `memory`, etc) didn't really matter; it was the test suite itself at fault.

It turns out that there are polling loops in helpers used by the test that require a `clockwork.Clock` to measure a polling interval. In the test case, this was implemented by a `clockwork.fakeClock` that requires manual advancing, or else the time the clock reports stays the same forever.

The working hypothersis is that, in almost all test runs, either
 1. AcquireLock() succeeds on the first try, meaning it never needs to enter the polling loop, or
 2. The one-off manual clock advance written into the test happened to occur during the wait, and so the polling loop was woken

In either case, all would be well and the test would pass. If neither of these cases happened then the test would lock up, waiting for a clock update that would never come and eventually the test would time out after 10 minutes.

This patchset:
1. Adds a 1-minute timeout to the `Lock()` test, so that it fails faster if the deadlock condition is hit
2. Adds a regular, asynchronous update to the `fakeClock` at 10x real-time to ensure that waiting code does not rely on hitting a one-of clock update, and
2. Refactors the polling loop in `backend.AcquireLock()` to honour context cancellation

### CODE REVIEW

**Review by xacrimon — APPROVED** [review]
LGTM

**Review by webvictim — APPROVED** [review]
LGTM. Thanks a ton for looking into this @tcsc

**Review by nklaassen — APPROVED** [review]

**Comment by tcsc** [comment]
No worries @webvictim - very few things annoy me more than flaky tests :-)

**Review by russjones — APPROVED** [review]
Bot.

**Pull request merged**
