### PR TITLE
add local windows users guide link to enrollment

### PR DESCRIPTION
**Pull request by stevenGravy**
Includes link to local windows users passwordless setup in discover

image

changelog: Include local windows users guide in discovery

### CODE REVIEW

**Review by zmb3 — COMMENTED** [review]
I don't think "local windows" is the right term for this.

**Comment by stevenGravy** [comment]
> I don't think "local windows" is the right term for this. 

I was also thinking
- Local Windows Users
- Local
- Standalone Windows
- Non-AD

**Comment by zmb3** [comment]
@ibeckermayer this is a Q4 goal that's tentatively assigned to you. Up to you whether you want to pick it up from here or start from scratch.

**Comment by ibeckermayer** [comment]
IIRC the decision was that we would get rid of the guided AD path entirely. To that end, I've changed it to

image

and added this [admonition](https://github.com/gravitational/teleport/pull/34010/commits/e36490fefb964743e648936bd55c9a64c70a718f#diff-28b87359ec16686b45ba4fc96d3521a4eff9eaa2be49283cd838dfe1fbe3953dR10-R14) in the docs to point AD users in the right direction.

**Comment by ibeckermayer** [comment]
The goal is actually to remove the AD scripts entirely, so I've updated the link in the admonition to point to `active-directory-manual.mdx` and created a follow on PR which finishes the job: https://github.com/gravitational/teleport/pull/34816

**Comment by ibeckermayer** [comment]
This needs to link to a non-AD discover flow. Converting this to a draft for now.

**Comment by ibeckermayer** [comment]
Closed in favor of https://github.com/gravitational/teleport/pull/35231

**Pull request closed without merging**
