### PR TITLE
IAM Node Join Method

### LINKED ISSUE #8659: IAM Method for Simplified Node Joining
### What
Teleport should support the IAM method for Simplified Node Joining. This will allow services running in AWS to join Teleport clusters without the need to distribute any tokens or secrets.

### How
The IAM method is described in RFD 41 https://github.com/gravitational/teleport/blob/master/rfd/0041-aws-node-join.md#iam-method

### Why
This will enable Cloud support for Simplified Node Joining, because no AWS credentials are needed on the teleport Auth or Proxy, only on the nodes.

### Workaround
Use the EC2 method for simplified node joining https://goteleport.com/docs/setup/guides/joining-nodes-aws/, but this does not work for Teleport Cloud

### PR DESCRIPTION
**Pull request by nklaassen**
This PR implements the IAM method for joining nodes in AWS, described in [RFD 41](https://github.com/gravitational/teleport/blob/master/rfd/0041-aws-node-join.md#iam-method). Further reading on the current join endpoints and methods can be found in [RFD 50](https://github.com/gravitational/teleport/pull/9871).

The join flow (included in RFD 41) is as follows:
1. The node initiates a `JoinService/RegisterUsingIAMMethod` gRPC request.
2. The auth server enforces that TLS is used for transport.
3. The auth server sends a base64 encoded 32 byte crypto-random challenge on the server stream.
4. The node creates the `sts:GetCallerIdentity` request, adds the challenge in
   a header, and signs it with its AWS credentials.
5. The node sends a types.RegisterUsingTokenRequest to the auth server on the client stream, including the signed
   `sts:GetCallerIdentity` request and other parameters currently in
   [RegisterUsingTokenRequest](
   https://github.com/gravitational/teleport/blob/d4247cb150d720be97521347b74bf9c526ae869f/lib/auth/auth.go#L1538-L1563)
6. The auth server checks that the signed request is valid:
   - it is a `POST` request to `sts.amazonaws.com`
   - the body is `Action=GetCallerIdentity&Version=2011-06-15`
   - the `X-Teleport-Challenge` header value equals the issued challenge
   - the Authorization header includes `x-teleport-challenge` as one of the signed headers
   - the Authorization header includes `AWS4-HMAC-SHA256` as the signing algorithm
7. The auth server sends the signed request to `sts.amazonaws.com` over TLS and gets the response.
8. The auth server checks for a provision token that matches the AWS account in
   the `sts:GetCallerIdentity` response and the teleport service role of the
   join request.
9. The auth server sends credentials to join the cluster.

The new gRPC `JoinService` is implemented on both Auth and Proxy, the server code is common and implemented in `lib/services/join.go`. This gRPC service does not use mTLS, as joining nodes do not yet have client certificates.

`lib/services.JoinService` provides an interface for `RegisterUsingIAMMethod` using channels instead of gRPC streams. This allows both `api/client.Client` and `lib/auth.Server(WithRoles)` to implement the method so it can be called on both Proxy and Auth.

Closes #8659

Docs are added in #8899

### CODE REVIEW

**Review by codingllama — COMMENTED** [review]
Hey @nklaassen, the PR looks massive, even considering pb.go changes. Would you mind splitting it into smaller, more focused parts, so it's easier to review and scope the changes?

**Comment by nklaassen** [comment]
@codingllama I must admit it is much bigger than I would like. I'll take a crack at splitting it up.

**Comment by codingllama** [comment]
Thanks!

**Comment by nklaassen** [comment]
> Hey @nklaassen, the PR looks massive, even considering pb.go changes. Would you mind splitting it into smaller, more focused parts, so it's easier to review and scope the changes?

I split this into https://github.com/gravitational/teleport/pull/10085 and https://github.com/gravitational/teleport/pull/10087

**Pull request closed without merging**
