### PR TITLE
Fix session leave + termination deadlock

### LINKED ISSUE #11600: After Moderated Session box doesn't upload session or let you access it again.
### Description

**What happened**:

At the end of a moderated SSH session, the session hangs and the resulting session recording isn't uploaded and you can't Teleport into the box again.

While recording Teleport 9 videos I ran into the bug. I started a SSH session that required moderation.  I was able to connect but when I left the session the session hung. I used my breakglass SSH key. This was the resulting logs

```
ubuntu@ip-10-0-0-99:~$ journalctl -fu teleport
-- Logs begin at Thu 2022-03-17 19:17:32 UTC. --
Mar 30 20:00:49 ip-10-0-0-99 teleport[469]: 2022-03-30T20:00:49Z INFO [SESSION:N] Party member 3289128f-2960-41bd-abb8-2bab515ca2b5 left session 4fea2c87-ac6b-4446-bfb3-d711ecb7971d. srv/sess.go:1526
Mar 30 20:00:49 ip-10-0-0-99 teleport[469]: 2022-03-30T20:00:49Z INFO [SESSION:N] Party member bbe3e0d6-654a-4e55-8faa-a6d69bebfbb4 left session 4fea2c87-ac6b-4446-bfb3-d711ecb7971d. srv/sess.go:1526
Mar 30 20:45:44 ip-10-0-0-99 teleport[469]: 2022-03-30T20:45:44Z INFO [SESSION:N] Closing party c8a1a2f6-43de-4e7a-91f0-2afa51fc23f5 srv/sess.go:1679
Mar 30 20:45:44 ip-10-0-0-99 teleport[469]: 2022-03-30T20:45:44Z INFO [SESSION:N] Party member c8a1a2f6-43de-4e7a-91f0-2afa51fc23f5 left session 2e223ad9-49dd-4389-b412-36e58b956f50. srv/sess.go:1526
Mar 30 21:01:47 ip-10-0-0-99 teleport[469]: 2022-03-30T21:01:47Z ERRO             Failed sending keepalive request: EOF sshutils/server.go:537
Mar 30 21:02:15 ip-10-0-0-99 teleport[469]: 2022-03-30T21:02:15Z ERRO             Failed sending keepalive request: EOF sshutils/server.go:537
Mar 30 21:02:35 ip-10-0-0-99 teleport[469]: 2022-03-30T21:02:35Z ERRO             Failed sending keepalive request: EOF sshutils/server.go:537
Mar 30 21:02:50 ip-10-0-0-99 teleport[469]: 2022-03-30T21:02:50Z ERRO             Failed sending keepalive request: EOF sshutils/server.go:537
Mar 30 21:02:58 ip-10-0-0-99 teleport[469]: 2022-03-30T21:02:58Z ERRO             Failed sending keepalive request: EOF sshutils/server.go:537
Mar 30 21:02:58 ip-10-0-0-99 teleport[469]: 2022-03-30T21:02:58Z ERRO             Failed sending keepalive request: read pipe: i/o timeout sshutils/server.go:537
```
If you try to SSH into the same box, the UI looks like this. 
ubuntu@ip-10-0-0-99

**What you expected to happen**:

### Reproduction Steps
As minimally and precisely as possible, describe step-by-step how to reproduce the problem.
1. Start a moderated session
2. Get party to join moderated ssh session
3. Kill Sessions
4. You'll no longer be able to access the box. 

### Server Details
- Teleport version (run `teleport version`): 9.0.1

### PR DESCRIPTION
**Pull request by Joerger**
This fixes a deadlock on `SessionRegistry.leaveSession(party)` and `SessionRegistry.ForceTermiante()`. This deadlock occurs when the party leaving forces the session to terminate, due to the new moderated session changes.

The lock on `leaveSession` was added in https://github.com/gravitational/teleport/pull/5365, but it doesn't look like this particular lock is doing anything.

I also wrapped in [this fix](https://github.com/gravitational/teleport/pull/11329) for `session.leave` event emitter.

Closes https://github.com/gravitational/teleport/issues/11600

Note: I ran into this while attempting to solve [the session freezing issue](https://github.com/gravitational/teleport/issues/10983), which could also result in this deadlock.

### CODE REVIEW

**Review by xacrimon — APPROVED** [review]
lgtm! make sure to backport to v9

**Review by smallinsky — APPROVED** [review]
LGTM, though wonder if we can add ut regression for this.

**Review by zmb3 — APPROVED** [review]
This _looks_ correct, but there's so many different locks and other concurrency primitives involved it's hard for me to know just by reading the code.

**Comment by Joerger** [comment]
> LGTM, though wonder if we can add ut regression for this.

Fair, I gave a try to adding a test to `sshserver_test.go`, but it looks like first we need to upgrade built in roles to v5, or else the moderated sessions changes won't even trigger in tests.

> This looks correct, but there's so many different locks and other concurrency primitives involved it's hard for me to know just by reading the code.

Agreed. Unfortunately the `session`, `sessionRegistry` and `sessionParty` code is heavily entertwined, meaning any one of their methods might call another's methods. Outside of a major refactor, the best we can do is make reasonable assumptions.

**Pull request merged**
