### PR TITLE
Remove the Upcoming Releases page

### PR DESCRIPTION
**Pull request by ptgott**
The intention is for this to exist only in v14 of the docs.

### CODE REVIEW

**Comment by ptgott** [comment]
@zmb3 At this point, the alternatives I see are:
1. Maintaining it on all four docs version branches, which has been untenable
2. Syncing it to all four docs version branches with each major release, which drifts quickly
3. Modifying the docs engine to support routing specific URL paths to one version of a page. We were doing some work on this in the spring (https://github.com/gravitational/docs/pull/279).

What do you think? (3) is the best approach in my opinion. 

@avatus, did you run into any roadblocks with getting this to work?

**Comment by zmb3** [comment]
Option 3 sounds fine.

In the meantime, can we work around this by adding a step to the deployment pipeline to copy this file from master to all of the `content/` subdirectories? Then we'd only have to maintain it in master.

**Comment by avatus** [comment]
Let me checkout that agnostic link branch again. I think it was "Ready" but missing the manual navigation part which shouldn't be too large of an issue right now as any manual links would be pointing where we want them to go anyway. I have to refresh my memory

**Comment by ptgott** [comment]
Closing since we're merging support for version-agnostic docs pages

**Pull request closed without merging**
