### PR TITLE
Add '+' to key sanitizer whitelist

### LINKED ISSUE #6632: Okta SAML issues with '+' in email address
### Description

**What happened**: Created a user in Okta (dev account) with a `+` in the email: `allenv+oktadev@goteleport.com`. Gmail supports the `+` character as a subaddressing filter and allows a user to use the same email address for unique logins.

When Okta attempts to login to Teleport Cloud using the default email address it will fail. You have to edit the user in Okta and change the username to something that Teleport supports (in my case changing user to `allenv-oktadev` worked vs using the email).

Teleport audit log info:

```
{
  "attributes": {
    "groups": [
      "Everyone",
      "okta-dev"
    ],
    "username": [
      "allenv+oktadev@goteleport.com"
    ]
  },
  "cluster_name": "skyward.teleport.sh",
  "code": "T1001W",
  "ei": 0,
  "error": "special characters are not allowed in resource names, please use name composed only from characters, hyphens and dots: \"/web/users/allenv+oktadev@goteleport.com/params\"",
  "event": "user.login",
  "message": "special characters are not allowed in resource names, please use name composed only from characters, hyphens and dots: \"/web/users/allenv+oktadev@goteleport.com/params\"",
  "method": "saml",
  "success": false,
  "time": "2021-04-28T14:10:13.862Z",
  "uid": "32044ab7-81bb-466a-b234-9c502892cbfe"
}

```

**What you expected to happen**:

Expected user to be able to login without any issue regardless on email formatting. RFC 5233 addresses subaddressing - https://tools.ietf.org/html/rfc5233

### Reproduction Steps
As minimally and precisely as possible, describe step-by-step how to reproduce the problem.
1. Create user in Okta with a subaddress email - `user+dev@domain.com`
2. Attempt to login to Teleport using Okta SAML with this users email
3. It will fail, but if you edit the user in Okta and assign a different username vs the email it will work.

### Server Details
- Teleport version (run `teleport version`): v6.1.2
- Server OS (e.g. from `/etc/os-release`): OSX
- Where are you running Teleport? (e.g. AWS, GCP, Dedicated Hardware): Teleport Cloud
- Additional details:

### Client Details
- Computer OS (e.g. Linux, macOS, Windows): macOS
- Browser version (for UI-related issues): Chrome

### PR DESCRIPTION
**Pull request by atburke**
Fixes #6632. Relies on gravitational/roundtrip#20.

### CODE REVIEW

**Review by nklaassen — APPROVED** [review]
Can you update `errorMessage` as well to indicate that `+` is allowed?

**Comment by russjones** [comment]
@atburke I think the original issue was trying to mitigate path traversal issues. So imagine you are trying to hit `http://example.com/user/atburke` and the user controls `atburke` then the attacker can change it to `../context` and hit the internal endpoint `http://example.com/context`.

I think `+` is probably safe, but please do some research on path traversal attacks to make sure we are not opening ourselves up to anything here.

**Comment by atburke** [comment]
> @atburke I think the original issue was trying to mitigate path traversal issues. So imagine you are trying to hit `http://example.com/user/atburke` and the user controls `atburke` then the attacker can change it to `../context` and hit the internal endpoint `http://example.com/context`.
> 
> I think `+` is probably safe, but please do some research on path traversal attacks to make sure we are not opening ourselves up to anything here.

I've done the research, and no source I found mentioned `+` as a problem character, so I think we're okay.

**Comment by atburke** [comment]
@russjones OK. I was leaving it in draft because gravitational/roundtrip#20 needs to be merged and vendored in before this can be merged.

**Review by russjones — APPROVED** [review]
Bot.

**Comment by russjones** [comment]
@atburke Can you backport this to `branch/v7`.

**Pull request merged**
