### PR TITLE
Fix inclusion of non-existent gcp-credentials secret and credentialsPath when gcp.credentialSecretName is empty

### PR DESCRIPTION
**Pull request by somethingnew2-0**
According to the [values.yaml](https://github.com/gravitational/teleport/blob/master/examples/chart/teleport-cluster/values.yaml#L121)
```
gcp:
  ...
  # You can override this to a blank value if the worker node running Teleport already has a service account which grants access.
  credentialSecretName: teleport-gcp-credentials
```

This PR fixes the helm template by removing the incorrect mounting of the non-existant `gcp-credentials` secret and removing the `credentialPath` from backend URIs so that the short-lived Google Application Default Credentials can be used via the GKE Metadata Service or GKE Workload Identity.

### CODE REVIEW

**Review by webvictim — APPROVED** [review]
LGTM.

@somethingnew2-0 Thanks for the PR!

**Comment by webvictim** [comment]
Backports required:
- `branch/v8`

**Comment by tcsc** [comment]
I'm having a look into the build failures now.

**Comment by tcsc** [comment]
Update on build issues: In the initial passes, github+GCB was not giving the build trigger a `_BASE_BRANCH` for some reason, I expect (but can't _prove_) that this is related to the PR coming from a fork, rather than a branch. A workaround seems to be to make sure the target branch is merged into the PR and them immediately run CI. I'll keep an eye on it.

**Review by russjones — APPROVED** [review]

**Comment by somethingnew2-0** [comment]
Anything I need to do to get this merged in?

**Comment by webvictim** [comment]
@somethingnew2-0 Nope, don't think so - just waiting for the tests to pass. I'll have to backport it to `branch/v8` after that and hopefully we can get it out with Teleport 8.1.1.

**Review by zmb3 — APPROVED** [review]

**Comment by russjones** [comment]
@somethingnew2-0 Will close this and merge your changes in https://github.com/gravitational/teleport/pull/9879.

**Pull request closed without merging**
