### PR TITLE
Bump integration test timeout

### PR DESCRIPTION
**Pull request by codingllama**
We've been hitting the 25m mark somewhat consistently, so applying a small bump in the hopes that it's enough to clear it.

### CODE REVIEW

**Review by greedy52 — APPROVED** [review]
seems it's already `30m` in makefile

**Comment by codingllama** [comment]
> seems it's already `30m` in makefile

I suppose the GCB timeout is the one taking effect, but we'd have to bump both if we wanted to go beyond 30m. Thanks for the reminder.

**Comment by r0mant** [comment]
@codingllama We think that timeouts were caused by some recent changes we made related to automatic AWS tags import which was fixed in https://github.com/gravitational/teleport/pull/13128. So this probably is no longer necessary. Let's monitor the situation for a bit and close this if we no longer see the timeouts?

**Comment by codingllama** [comment]
@r0mant thanks for the update. I'll go ahead and close now, but happy to reopen if we need it, it's a pretty small change.

**Pull request closed without merging**
