### PR TITLE
Add a global disable flag for Webauthn

### PR DESCRIPTION
**Pull request by codingllama**
Since #8176[1] landed, tsh login favors Webauthn challenges over U2F, a behavior
recommended to other clients as well (such as the Web UI). This creates a
problem: until the Webauthn implementation if proven in the wild, if there are
issues with it, then clients could consistently fail login.

This change introduces a fallback for disabling Webauthn regardless of the
cluster's second_factor:on or second_factor:optional setting. By stopping
challenge generation we automatically push clients over to U2F or TOTP as a
fallback, allowing breaking issues to be fixed without impact. (Note that using
second_factor:u2f as a fallback isn't always possible, since it disables OTP as
well.)

The added setting is meant as a safety switch - once Webauthn is proved in the
wild it is to be removed.

This affects both teleport.yaml and cloud resource configs.

teleport.yaml:

```yaml
auth_service:
  authentication:
    type: local
    second_factor: on # or "optional"
    u2f: {}           # omitted
    webauthn:
      disabled: true
```

Resource configuration:

```yaml
kind: cluster_auth_preference
version: v2
spec:
  type: local
  second_factor: on
  webauthn:
    disabled: true
```

[1] https://github.com/gravitational/teleport/pull/8176

### CODE REVIEW

**Comment by codingllama** [comment]
FYI @klizhentas and @russjones, this is me playing it safe. Let me know your thoughts about it.

**Comment by codingllama** [comment]
Note to reviewers: a good chunk of the line changes are .pb.go files.

**Review by zmb3 — APPROVED** [review]
Seems reasonable to me.

**Comment by codingllama** [comment]
Rebased on master and regenerated protos.

**Review by klizhentas — APPROVED** [review]

**Pull request merged**
