### PR TITLE
add value to let you annotate the service account

### PR DESCRIPTION
**Pull request by timothy-spencer**
For similar reasons to https://github.com/gravitational/teleport/pull/5271, I would like to be able to annotate the serviceaccount.

Let me know if you like this or have suggestions, whatever!  Thanks, and have fun!

### CODE REVIEW

**Comment by klizhentas** [comment]
@timothy-spencer thank you for your PR. We will review and get back to you! Have a great day 👋

**Comment by russjones** [comment]
@timothy-spencer Thank you for your contribution!

@webvictim You're reworking Helm charts in #6344, can you take a look at this and see if these changes make sense in the context of new Helm charts?

**Comment by webvictim** [comment]
@timothy-spencer I'll add support for serviceAccount annotations into #6344, as this PR is introducing a whole `annotations` section and it'll save refactoring it twice.

**Comment by webvictim** [comment]
https://github.com/gravitational/teleport/pull/6344/commits/d3eb086d07272e1ed49af06de0dd8da67e1d451d

**Comment by timothy-spencer** [comment]
Supercool.  That looks great to me!  Thank you!  This will make it much easier to integrate with EKS.

**Pull request closed without merging**
