### PR TITLE
Restructure `rdpdr.rs` into a multi file module

### PR DESCRIPTION
**Pull request by ibeckermayer**
The `rdpdr` module is going to get a lot bigger and more complex as we implement directory sharing. This PR prepares for that by beginning to split it up into multiple files.

### CODE REVIEW

**Review by zmb3 — APPROVED** [review]

**Review by espadolini — APPROVED** [review]
Why not leave `rdpdr.rs` where it was instead?

**Comment by ibeckermayer** [comment]
> Why not leave `rdpdr.rs` where it was instead?

This makes it a multi file module, so `rdpdr.rs` is now `rdpdr/mod.rs`, and `rdpdr/` houses files with other functionality relevant to the `rdpdr` virtual channel.

**Comment by espadolini** [comment]
Yeah but you can still have a `rdpdr.rs` as the module's entry point and sub modules in the `rdpdr/` directory - it's a matter of style, I'm not sure if we're following some standard in the codebase already.

**Comment by ibeckermayer** [comment]
> Yeah but you can still have a `rdpdr.rs` as the module's entry point and sub modules in the `rdpdr/` directory - it's a matter of style, I'm not sure if we're following some standard in the codebase already.

Is that true? My understanding was that Rust required me to use mod.rs.

**Pull request merged**
