### PR TITLE
Add audit_emit_event prometheus metric

### PR DESCRIPTION
**Pull request by rcanderson23**
Addition of this metric gives context to the metric `audit_failed_emit_events` allowing us to calculate percentage of audit events persisted to the storage backend, this is useful for SLO tracking. I added the metric to the `CheckingEmitter` as that seems to be the common code path for local and external storage audit event storage. 

During my investigation I also found that when using local storage where the audit partitioned was filled up the emit failure was incremented twice for each failure:
```
# HELP audit_emit_events Number of audit events emitted
# TYPE audit_emit_events counter
audit_emit_events 2
# HELP audit_failed_disk_monitoring Number of times disk monitoring failed.
# TYPE audit_failed_disk_monitoring counter
audit_failed_disk_monitoring 0
# HELP audit_failed_emit_events Number of times emitting audit event failed.
# TYPE audit_failed_emit_events counter
audit_failed_emit_events 4
```

This is due to `CheckingEmitter` and `AuditLog` both incrementing on failure. I removed the increment from `AuditLog` for consistency sake.

### CODE REVIEW

**Review by russjones — COMMENTED** [review]
@rcanderson23 Can you update the following page as well with the new event you added.


https://goteleport.com/docs/setup/reference/metrics/

**Comment by quinqu** [comment]
If you want to calculate the percentage, you can add an additional metric and do that in the code, right?

**Comment by rcanderson23** [comment]
> @rcanderson23 Can you update the following page as well with the new event you added.
> 
> https://goteleport.com/docs/setup/reference/metrics/

Added


> If you want to calculate the percentage, you can add an additional metric and do that in the code, right?

It is best to keep these kind of calculations out of the code base and do them on the Prometheus side with PromQL since the counters will be reset anytime Teleport instances are restarted.

**Review by quinqu — APPROVED** [review]

**Review by Joerger — APPROVED** [review]

**Review by russjones — APPROVED** [review]

**Review by russjones — APPROVED** [review]

**Comment by russjones** [comment]
@rcanderson23 Can you merge this PR?

**Pull request merged**
