### PR TITLE
Use modules instead of "is enterprise" flag

### PR DESCRIPTION
**Pull request by r0mant**
This PR does away with the "is enterprise" flag in teleport and uses pluggable modules mechanism to inject custom logic instead. There are 3 places where it was used:

* When creating an "admin" role, the default list of allowed logins is different.
* When creating a trusted cluster resource, the behavior in case of empty roles is different.
* When printing version, the output is a bit different.

Note: I've tried to unify this with the existing "web" plugin that injects additional handlers, but it doesn't seem to be possible without major refactoring due to cyclic imports between "web" and "services".

### CODE REVIEW

**Comment by r0mant** [comment]
retest this please

**Comment by r0mant** [comment]
retest this please

**Review by kontsevoy — CHANGES_REQUESTED** [review]
I can't comment on the details of this PR because I'm trying to step away from day-to-day involvement in Teleport code, but I have a general comment:

I think the name "plugin" is unfortunate here and the generic naming of modules/files is also unfortunate.

This will confuse future users, because we have planned to add support for user-supplied plugins for:

- audit loggers
- authentication back-ends

Those were thought to be implemented as dynamically loaded `.so`-modules using Golang's "plugin" mechanism (see, the name is already taken). 

What I see here is more like a "process trait"... not sure.

**Review by russjones — APPROVED** [review]

**Comment by r0mant** [comment]
@kontsevoy Good point. I'll think of a better name for it.

**Comment by r0mant** [comment]
retest this please

**Review by klizhentas — APPROVED** [review]

**Review by kontsevoy — APPROVED** [review]

**Comment by r0mant** [comment]
retest this please

**Comment by r0mant** [comment]
retest this please

**Pull request merged**
