### PR TITLE
Pin dind version and remove GOCACHE from push pipelines

### PR DESCRIPTION
**Pull request by nklaassen**

### CODE REVIEW

**Review by russjones — APPROVED** [review]
Bot.

**Comment by wadells** [comment]
Failures like this serve as motivation for looking into https://github.com/gravitational/teleport/issues/6895 (and deterministic/reproducible builds in general) further.

**Review by r0mant — APPROVED** [review]

**Comment by webvictim** [comment]
Why did we remove `GOCACHE` here?

**Comment by wadells** [comment]
> Why did we remove `GOCACHE` here?

Enabling gocache resulted in the following failures:

```
make: Entering directory '/go/src/github.com/gravitational/teleport/e'
failed to initialize build cache at /go/cache: mkdir /go/cache/00: permission denied
failed to initialize build cache at /go/cache: mkdir /go/cache/00: permission denied
```
As seen here:

https://drone.gravitational.io/gravitational/teleport/13000/2/4

We'd either needed to push through those (in which case reverting docker would have been moot) or revert the `GOCACHE` change.  In the moment, we figured it was better to roll back instead of push through -- as we didn't know if there would be further issues after the the permission ones were addressed.

**Comment by nklaassen** [comment]
Right, and just to be clear removing GOCACHE was just reverting the first attempted fix #7190 from minutes earlier

**Comment by webvictim** [comment]
Thanks - that makes a lot more sense now. Adding `GOCACHE` is actually the correct fix, but it also needs the volumes to be added/configured for the pipelines in `dronegen` for it to work as expected.

**Pull request merged**
