### PR TITLE
use the same static secret with the teleport-kube-agent chart

### PR DESCRIPTION
**Pull request by timothy-spencer**
This should allow the teleport-kube-agent helm chart to actually be able to join the teleport-cluster.

### CODE REVIEW

**Comment by russjones** [comment]
@timothy-spencer Thank you for your contribution!

@webvictim You're reworking Helm charts in https://github.com/gravitational/teleport/pull/6344, can you take a look at this and see if these changes make sense in the context of new Helm charts?

**Comment by webvictim** [comment]
@klizhentas @awly What do you think about this? IMO we shouldn't encourage setting static join tokens in the chart, but there isn't really a good alternative for using `teleport-kube-agent` until we fix https://github.com/gravitational/teleport/issues/4832.

**Comment by awly** [comment]
The list of static tokens should be opt-in, not added by default.
Otherwise, it's reasonable that `teleport-cluster` and `teleport-kube-agent` should be easy to set up with each other. I don't know what kind of refactoring @webvictim is doing and whether we'll keep both charts though.

**Comment by webvictim** [comment]
We're keeping both charts and I agree that until `teleport-kube-agent` can support dynamic tokens, we should make it easier to use both together. I'll wait to see what @klizhentas thinks though.

**Comment by timothy-spencer** [comment]
Any news on this?  I'd love to be using your helm chart and not my fork.  :-)

**Comment by webvictim** [comment]
@timothy-spencer We won't implement this exactly as-is, but after https://github.com/gravitational/teleport/pull/6344 is merged we'll take a look at a way to define a token which can be shared and used between the two charts. We're in the process of refactoring our Helm guides (`teleport-cluster` is written but `teleport-kube-agent` is still to be done) so it'll likely come along with that.

**Comment by timothy-spencer** [comment]
I definitely saw a lot of activity over there in https://github.com/gravitational/teleport/pull/6344, but until that lands, seems like this would be a quick fix for people who actually want to use `teleport-kube-agent`.  I will definitely be excited to use dynamic join tokens down the road, though!!

**Comment by webvictim** [comment]
https://github.com/gravitational/teleport/pull/7123 has been merged which adds support for running `teleport-kube-agent` as a `StatefulSet` and using persistent storage. This makes the use of dynamic join tokens possible, so I'm going to close this PR. Thanks!

**Pull request closed without merging**
