### PR TITLE
Fix make update-vendor on macOS

### PR DESCRIPTION
**Pull request by zmb3**
We were using switches specific to GNU coreutils for the api symlink.
These aren't supported on macOS with its BSD variants, so use a more
primitive syntax that will work on both platforms.

### CODE REVIEW

**Review by timothyb89 — APPROVED** [review]
This works for me on macOS, Linux, and Windows/MinGW.

**Comment by zmb3** [comment]
> This works for me on macOS, Linux, and Windows/MinGW.

Thanks for validating, especially on Windows!

**Review by codingllama — APPROVED** [review]
LGTM.

I have this exact same fix, was about to mail it.

**Review by russjones — APPROVED** [review]
Bot.

**Pull request merged**
