### PR TITLE
Update repo for Windows artifact build pipeline GHA migration

### PR DESCRIPTION
**Pull request by fheinecke**
This PR includes several changes, all required for moving the Windows build pipeline to GHA:
* All Windows build pipelines have been removed from .drone.yml, and dronegen (both Windows native, and Linux cross-compilation of tsh)
* Updated and added Powershell commandlets as required by the new GHA pipeline
* Updated `e` ref **\[PENDING `teleport.e` PR\]**

~~The actual Windows build workflows in the `teleport.e` repo are not quite ready for review, however they are very close and these changes are stable enough that I'd like to open this up for review.~~ This is now available [here](https://github.com/gravitational/teleport.e/pull/2598).

### Reviewers, we (Gravitational) have a week (total) to merge and backport this and at least two other PRs, test them all together, and cut at least one new full release. If all this is not completed by then, then we lose the ability to cut new releases. Please review this as soon as possible so that I can get fixes in quickly.

Changelog: Updated the code signing certificate for Windows artifacts

### CODE REVIEW

**Comment by fheinecke** [comment]
Added do-not-merge label until the pending teleport.e PR is merged, and the e ref is updated in this PR

**Comment by GavinFrazar** [comment]
I don't know enough about our build pipelines to provide a meaningful review

**Review by camscale — APPROVED** [review]
Looks good. Pretty standard stuff in my experience changing the pipelines over to GHA.

The powershell also seems fine, but I have little experience to know if there might be better ways to be doing things or if there are subtle bugs. But it is quite readable and looks straightforward enough.

**Review by tcsc — APPROVED** [review]

**Review by tigrato — APPROVED** [review]

**Review by r0mant — APPROVED** [review]

**Review by wadells — APPROVED** [review]
Love those red diffs!

**Pull request merged**
