### PR TITLE
[doc] allow either role name or full ARN for AWS IAM role db_users

### PR DESCRIPTION
**Pull request by greedy52**
Related change
- #20610

<s>May also want to update #19956</s>

### CODE REVIEW

**Review by smallinsky — APPROVED** [review]
Thanks for this alignment.

**Review by GavinFrazar — APPROVED** [review]

**Review by ptgott — APPROVED** [review]

**Comment by greedy52** [comment]
@alexfornuto let me know if you want to incorporate this in your backports of the guides or I can backport this separately after those.

**Review by alexfornuto — APPROVED** [review]

**Comment by alexfornuto** [comment]
> @alexfornuto let me know if you want to incorporate this in your backports of the guides or I can backport this separately after those.

Please go ahead and backport this on its own, as the guides this affects are already in various states of... backportiness?

**Comment by alexfornuto** [comment]
@greedy52 I can also do the manual backporting if you'd like.

**Comment by greedy52** [comment]
@alexfornuto I need to get in the backport of the code change first. I will backport this doc afterwards. Thanks!

**Pull request merged**
