### PR TITLE
Add check on apiserver upserUser to ensure all roles on user exist

### LINKED ISSUE #21500: Users can be granted non-existing roles through the UpsertUser() call
### Expected behaviour:

I try to upsert a user with an invalid role, the call returns the error "role X is not found".

### Current behaviour:

Using `UpsertUser()` allows the creation of a user with a non-existing role. The call succeeded and the user cannot log in.

### Bug details:

[A similar issue](https://github.com/gravitational/teleport/issues/14108) was fixed in https://github.com/gravitational/teleport/pull/14298 for the grpc calls `api/client.Client.CreateUser()` and `api/client.Client.UpdateUser()`. However, `lib/auth.Client.UpsertUser()` seems to call through a different API (the plain HTTP one on the `users` route) which does not perform such validation.

### Workaround:

Use the gRPC client and create/update calls.

### PR DESCRIPTION
**Pull request by EdwardDowling**
Closes #21500

### CODE REVIEW

**Review by fspmarshall — COMMENTED** [review]
As a general rule, checks should only live in `auth.APIServer`/`auth.GRPCServer` if they relate to some specific element of the protocol (e.g. extracting peer IP address).

Resource sanity-checks should live either in `auth.AuthWithRoles` or `auth.Server` level, since those are common across the http and grpc methods.


Regardless, I'm not sure about this check.  Having teleport be sensitive to resource creation order isn't ideal, especially when folks might be setting up users/roles in the context of automation.  Having the creation fail intermittently _even_ if the order was correct because the roles didn't propagate to the cache fast enough would be even more onerous (tho idk how likely that is).

I think a better way to go about this would be to add a client-side check and emitted `WARN` logs if an unknown roles were in use.

**Comment by EdwardDowling** [comment]
> As a general rule, checks should only live in `auth.APIServer`/`auth.GRPCServer` if they relate to some specific element of the protocol (e.g. extracting peer IP address).
> 
> Resource sanity-checks should live either in `auth.AuthWithRoles` or `auth.Server` level, since those are common across the http and grpc methods.
> 
> Regardless, I'm not sure about this check. Having teleport be sensitive to resource creation order isn't ideal, especially when folks might be setting up users/roles in the context of automation. Having the creation fail intermittently _even_ if the order was correct because the roles didn't propagate to the cache fast enough would be even more onerous (tho idk how likely that is).
> 
> I think a better way to go about this would be to add a client-side check and emitted `WARN` logs if an unknown roles were in use.
@fspmarshall 
Was something like this what you were thinking?

**Comment by fspmarshall** [comment]
> Was something like this what you were thinking?

@EdwardDowling Functionally, yes, except that I'd suggest moving the logic into `tool/tctl` rather than having it in `auth.Client`, so that it's only present in the command-line utils.  `auth.Client` may also be used by teleport servers.  I don't *think* `auth.Client.UpsertUser` is actually used by any teleport servers right now, but it's _allowed_ to be used, and loading a bunch of roles would be unexpected behavior in that case.

**Review by fspmarshall — APPROVED** [review]

**Review by gabrielcorado — APPROVED** [review]

**Comment by r0mant** [comment]
@EdwardDowling @fspmarshall Adding a warning here doesn't really do anything (nobody is ever going to see it), and it doesn't address the original issue as you can still create an invalid user. Moreover, "create" and "update" methods already do the role check so "upsert" is the outlier here and leads to inconsistency.

I do understand the concern about someone potentially using it with unsorted list of resources. I propose we do this:

- In master branch, restore the server side check in "upsert" to reject users without valid roles as was in original Edward's implementation. We will document this as potentially breaking change in release notes.
- We could backport the "warning" approach, but tbh I don't think it's worth it as like I mentioned I'm 100% it will go unnoticed.

WDYGT? 

We should also reopen the original ticket as the issue is not actually fixed.

**Pull request merged**
