### PR TITLE
[v15] AWS OIDC Service: bootstrap and ListDatabases

### PR DESCRIPTION
**Pull request by marcoandredinis**
Backport #37335 to branch/v15
Backport #37853 to branch/v15

### CODE REVIEW

**Review by espadolini — COMMENTED** [review]
Do we need the stubs backported in separate PRs? Couldn't we just backport the entire feature once complete?

**Comment by marcoandredinis** [comment]
Backporting as soon as the PR lands in `master` decreases the risk of merge conflicts.

What would be the advantages of backporting the entire feature?
Is it because we are delivering a new API that throws a `not implemented` error?

**Comment by espadolini** [comment]
Yeah, it seems kind of unnecessary to have in a release; especially because until the feature is actually implement we're liable to want to change things around.

**Review by EdwardDowling — APPROVED** [review]

**Comment by marcoandredinis** [comment]
@espadolini It contains the implementation now :+1:

**Review by espadolini — APPROVED** [review]

**Pull request merged**
