### PR TITLE
Serialize HSM tests

### LINKED ISSUE #13599: `TestHSMRotation` flakiness
### CI Logs
- https://console.cloud.google.com/cloud-build/builds/b8047da9-c5af-44e4-90ee-6493bd9aa5d2;step=0?project=ci-account
- https://console.cloud.google.com/cloud-build/builds/2e331f94-0ac7-45dd-b102-13d8e0d25794?project=ci-account
- https://console.cloud.google.com/cloud-build/builds/f32dce90-bbf6-4d98-b3a3-585eadc4d8bf?project=ci-account

### Relevant Snippet
```
=== CONT  TestHSMRotation
    hsm_test.go:405: 
        	Error Trace:	hsm_test.go:405
        	Error:      	Received unexpected error:
        	            	timed out waiting for proxy to be ready
        	            		context deadline exceeded
        	Test:       	TestHSMRotation
```

### LINKED ISSUE #13635: `TestHSMDualAuthRotation` flakiness
#### Link(s) to logs

- https://console.cloud.google.com/cloud-build/builds/bf5dc298-970e-468c-b739-11b47347036f?project=ci-account
- https://console.cloud.google.com/cloud-build/builds/d44b12f3-f37a-4835-a443-e3b5db10c712?project=ci-account
- https://console.cloud.google.com/cloud-build/builds/143a9e10-c336-4dc4-baa5-3846cd40d7d3?project=ci-account
- https://console.cloud.google.com/cloud-build/builds/1e717527-9d6e-482c-bce1-13182af4468d?project=ci-account
- 07.07.2022 -> https://console.cloud.google.com/cloud-build/builds;region=us-west1/e42873ae-6da5-4f76-a6f7-687771a0997f;step=0?project=ci-account
#### Relevant snippet

```
    hsm_test.go:76: 
        	Error Trace:	hsm_test.go:76
        	            				testing.go:1034
        	            				testing.go:1203
        	            				testing.go:1187
        	            				panic.go:500
        	            				testing.go:864
        	            				hsm_test.go:76
        	            				testing.go:1034
        	            				testing.go:1203
        	            				testing.go:1433
        	            				panic.go:500
        	            				testing.go:864
        	            				hsm_test.go:680
        	            				hsm_test.go:693
        	Error:      	Received unexpected error:
        	            	context canceled
        	Test:       	TestHSMDualAuthRotation
        	Messages:   	error while closing auth1 during test cleanup
--- FAIL: TestHSMDualAuthRotation (480.13s)
```

### PR DESCRIPTION
**Pull request by nklaassen**
I'm observing `libsofthsm2` becoming very slow and returning flaky results on certain APIs, especially when running these tests in parallel. Unfortunately `libsofthsm2` is extremely slow as soon as you have more than a very small number of keys at once (multiple seconds to generate a new keypair).

Parallelizing these tests seems to give us a modest speedup, but I'm worried it has made them all flakier. When running them in parallel with all other integration tests, I'm not sure the speedup actually makes a difference, so I'm considering serializing these again to improve stability.

Opening this draft PR to see if it affects overall runtime of our integration tests.

EDIT:
https://console.cloud.google.com/cloud-build/builds/bf368bfd-a788-4a6f-aaa2-bd6792e5bdd9?project=ci-account
Integration tests passed on this in 21:48, all other passing integration test runs right now seem to take 21:30-25 minutes, usually 23-24.

The total time for all HSM tests is 2:30. These DO still run in parallel with all other integration tests, because they are in their own package. They only run serially with each other.
```
pass (in 149.91s): github.com/gravitational/teleport/integration/hsm
```

Fixes https://github.com/gravitational/teleport/issues/13599
Fixes #13635

### CODE REVIEW

**Comment by ibeckermayer** [comment]
> The total time for all HSM tests is 2:30.

Can you provide further context? What was the typical time for these tests when parallelized with each other?

It would also be ideal if we could determine whether your hypothesis is true by looking at the failure rate on these tests before and after parallelization was added (which happened in https://github.com/gravitational/teleport/pull/12470). I know @russjones has some custom scripts that run against GCB, though I'm not sure how big of an additional project it would be to suss that out.

**Comment by nklaassen** [comment]
> > The total time for all HSM tests is 2:30.
> 
> Can you provide further context? What was the typical time for these tests when parallelized with each other?

Three random parallelized runs:
```
pass (in 93.77s): github.com/gravitational/teleport/integration/hsm
pass (in 96.03s): github.com/gravitational/teleport/integration/hsm
pass (in 107.38s): github.com/gravitational/teleport/integration/hsm
```

Three serialized runs:
```
pass (in 161.72s): github.com/gravitational/teleport/integration/hsm
pass (in 149.91s): github.com/gravitational/teleport/integration/hsm
pass (in 132.68s): github.com/gravitational/teleport/integration/hsm
```

So they take a bit longer, but since they will run in parallel with the entire `github.com/gravitational/teleport/integration` package, it doesn't seem to make a difference overall.

> 
> It would also be ideal if we could determine whether your hypothesis is true by looking at the failure rate on these tests before and after parallelization was added (which happened in #12470). I know @russjones has some custom scripts that run against GCB, though I'm not sure how big of an additional project it would be to suss that out.

I'm working on getting some log history

**Comment by ibeckermayer** [comment]
@nklaassen got it, and just to confirm -- you found that the parallelized version tends to fail?

**Review by ibeckermayer — APPROVED** [review]

**Comment by nklaassen** [comment]
> @nklaassen got it, and just to confirm -- you found that the parallelized version tends to fail?

Yeah I tried adding some more parallelism locally to repro with this snippet, and the test basically hangs and times out while trying to get `libsofthsm2` to generate some keypairs.
```go
func TestParallel(t *testing.T) {
    for i := 0; i < 5; i++ {
        t.Run(fmt.Sprintf("iteration %d", i), TestHSMRotation)
    }
}
```

**Review by zmb3 — APPROVED** [review]

**Pull request merged**
