### PR TITLE
Remove preview release page for non-maintained branches

### PR DESCRIPTION
**Pull request by stevenGravy**
Only the current active major version is maintained for preview releases content.  Removing this will remove non-maintained content.

### CODE REVIEW

**Comment by ptgott** [comment]
Should we be backporting changes to the Upcoming Releases page instead? I think this makes sense to do, since our roadmap will be the same regardless of which version of the docs a user is currently viewing.

If we remove the "Upcoming Releases" page from all but the current version of the docs, we'll need a reliable way to ensure that maintain this practice for future docs versions.

**Comment by stevenGravy** [comment]
> Should we be backporting changes to the Upcoming Releases page instead? I think this makes sense to do, since our roadmap will be the same regardless of which version of the docs a user is currently viewing.
> 
> If we remove the "Upcoming Releases" page from all but the current version of the docs, we'll need a reliable way to ensure that maintain this practice for future docs versions.

My understanding is they specifically did not want to have to backport this.  Which requires multiple approvals and PRs.

**Comment by ptgott** [comment]
@stevenGravy That makes sense—I'll approve this once we've confirmed that we're building this approach into our documentation test plan (#18179).

**Comment by zmb3** [comment]
If we remove this from master, when we cut `branch/v12` from master we'll no longer have an upcoming releases page. How do we plan to solve that?

**Comment by stevenGravy** [comment]
Then 12 will become the maintained version. That can be part of the checklist for a major version release like the testing.

**Comment by stevenGravy** [comment]
> If we remove this from master, when we cut `branch/v12` from master we'll no longer have an upcoming releases page. How do we plan to solve that?

Thoughts @zmb3 ?

**Comment by zmb3** [comment]
@stevenGravy I'm not convinced this is any better.

**Pull request closed without merging**
