### PR TITLE
Fix `tsh` env flags 

### PR DESCRIPTION
**Pull request by Joerger**
This PR updates `tsh` to check env flags after parsing CLI args and flags, rather than before.

This parsing order was originally broken by the introduction of tsh aliases - https://github.com/gravitational/teleport/pull/13305

This fixes https://github.com/gravitational/teleport/pull/27057, which did not work as expected.

### CODE REVIEW

**Comment by Joerger** [comment]
@Tener can you double check that this change will still work with `tsh` aliases?

**Comment by Tener** [comment]
@Joerger this is rather subtle stuff, made no easier by the quirks of the Kingpin library. Can you say the expected processing order of the various inputs, and why do you believe so?

We need a way to enable debug logging before parsing the arguments. Processing the env variables first feels like a reasonable option. Otherwise, there will be no way to debug aliases: by default, we silence the debug logs, and by the time `--debug` is parsed, the aliases have already been expanded.

If we expect certain order between env vars and flags, we should have a test for this; do you mind adding one so that we have an explicit way to check if this use case you have in mind is preserved?

Depending on the use case, it may be a good call to use `.Envar()` instead of custom processing:

https://github.com/gravitational/teleport/blob/19e36d6a67af736f446359bfe4929d223a13e906/tool/tsh/common/tsh.go#L611-L612

**Comment by Tener** [comment]
@Joerger 

Thanks for the reminder about `TELEPORT_DEBUG`, it slipped my mind that we already do special stuff here.

Sorry if I wasn't clear with my questions about use cases and precedence.

The use case I gather from the code is as follows: if the user requests headless login (in one of three ways:  `--headless`, `--auth=headless` or `TELEPORT_HEADLESS=1`), then we want to default `Proxy`, `Username` and `SiteName` to the values read from one of `SSH_*` vars. This choice creates a dependency: we must know the flags' value before applying those conditional defaults.

If you look at Kingpin's treatment of `Envar()`, it is clear that explicit flag value takes precedence:
```
TELEPORT_AUTH=bar tsh ls --auth=foo --proxy=boson.tener.io:3080
ERROR: invalid connector name: foo; valid options: google, okta-oidc
```

This works even for empty strings. Notice the difference:

```
TELEPORT_AUTH=bad-auth tsh ls --auth='' --proxy=boson.tener.io:3080
Enter password for Teleport user tener:

TELEPORT_AUTH=bad-auth tsh ls --proxy=boson.tener.io:3080
ERROR: invalid connector name: bad-auth; valid options: google, okta-oidc
```

Postponing the call to `setEnvFlags` causes it to override the empty string in `cf.SiteName` and `cf.KubernetesCluster`, which can be set by explicit arguments. This makes it a backward-incompatible change with respect to those two params in case someone wants to override the environment defaults. 

This changes the meaning of numerous commands, for example:

```
TELEPORT_CLUSTER=some-cluster tsh ls --cluster ""
```

Right now, this will cause the `cf.SiteName` to be `""` and default to the active cluster. After this PR is merged, it will ignore `--cluster=""` and `some-cluster` set via env var will take precedence over the explicit flag. 

I'm open to discussing whether this is preferable or not, but I feel this is simply an unintended consequence of fixing the bug with the `SSH_*` env vars.

**Comment by Joerger** [comment]
> This changes the meaning of numerous commands, for example:
> 
> ```
> TELEPORT_CLUSTER=some-cluster tsh ls --cluster ""
> ```
> 
> Right now, this will cause the `cf.SiteName` to be `""` and default to the active cluster. After this PR is merged, it will ignore `--cluster=""` and use `some-cluster` instead. This means that env var will take precedence over the explicit flag.
> 
> I'm open to discussing whether this is preferable or not, but I feel this minor breaking change is simply an unintended consequence of fixing the bug with the `SSH_*` env vars.

Interesting, I was not aware of this edge case. It looks like this is only possible after the changes made in https://github.com/gravitational/teleport/pull/13305, so older v10 versions will prioritize the env variable.

I'm not sure I see the benefit of keeping this, but if we think someone will use it we can prioritize preserving it. In this case I will just move the `SSH_*` env var logic out of `SetEnvFlags()`. Then in a follow up PR, I will remove `SetEnvFlags()` in favor of using `.Envar` to avoid this kind of problem in the future.

**Comment by Joerger** [comment]
Closing in favor of https://github.com/gravitational/teleport/pull/27970

**Pull request closed without merging**
