### PR TITLE
chore: Bump protoc and related dependencies

### PR DESCRIPTION
**Pull request by codingllama**
Updates Buf, protoc and protoc-gen-go.

* https://github.com/bufbuild/buf/releases/tag/v1.31.0
* https://github.com/protocolbuffers/protobuf/releases/tag/v26.1
* https://github.com/protocolbuffers/protobuf-go/releases/tag/v1.34.0

Our protoc version has rather outdated, so I moved us to the latest "double-numbered" release. See the [Version Support][1] protobuf page for details.

Minimal changes to generated files.

[1]: https://protobuf.dev/support/version-support/

### CODE REVIEW

**Comment by codingllama** [comment]
I was taking a look at editions and decide to put this together, as it ends up touching generated files.

Now I wonder if protoc is even necessary anymore?

**Review by espadolini — APPROVED** [review]

**Review by rosstimothy — APPROVED** [review]

**Comment by hugoShaka** [comment]
> Now I wonder if protoc is even necessary anymore?

Protoc is still used directly to generate the terraform schema and operator CRDs

**Comment by codingllama** [comment]
I've dropped protoc from grpcbox, but kept the buildbox one. It's not clear to me that we really need that one, or could move the remaining uses to buf too.

**Comment by codingllama** [comment]
`cd integrations/operator; make crdgen-test manifests` is coming up clean. (My local env has protoc 26.1 too.)

**Comment by codingllama** [comment]
PTAL @espadolini @rosstimothy? I just want to be sure you saw the last commit.

**Review by espadolini — APPROVED** [review]

**Pull request merged**
