### PR TITLE
Update Moderated Session Guide

### PR DESCRIPTION
**Pull request by russjones**
Updated Moderated Sessions documentation to mention it's only available in commercial Teleport. To be paired with https://github.com/gravitational/teleport/issues/11366.

* b7880d8e4f11e39aa24acea63dc8f86912b94b8a: Reformatting Moderated Session Guide
* 373adde8339622f25e6e54d96e9c57b960532a62: Added admonition for Moderated Sessions

### CODE REVIEW

**Review by xacrimon — APPROVED** [review]
Looks good, will be addressing the licensing today.

**Review by xacrimon — CHANGES_REQUESTED** [review]
I figure this may need some minor changes. Due to #11223 clarifying intent to remove the node checks. We'll need to rely on the join_session feature of moderated sessions for facilitating joining sessions which is allowed in OSS in v5 roles.

My current idea for license restriction is to disallow any sessions with require policies from starting (i.e requires moderation) but I think we still need to clarify that only those are enterprise only and that join_session is available in OSS. Does this seem reasonable?

**Comment by russjones** [comment]
@xacrimon I don't think we need to get that fine grained in the documentation. The fact that it's not supported is sufficient in my opinion.

**Review by xacrimon — APPROVED** [review]
👍

**Review by r0mant — APPROVED** [review]

**Pull request merged**
