### PR TITLE
Update CODEOWNERS

### PR DESCRIPTION
**Pull request by russjones**

### CODE REVIEW

**Comment by russjones** [comment]
@webvictim What else makes sense to update in `CODEOWNERS`?

**Comment by webvictim** [comment]
To be honest, my biggest issue is that I’m a code owner on the majority of the Teleport repo, but I can’t approve my own PRs. Where appropriate it’d be nice to have @awly there too as he’s very active on Github.

**Comment by russjones** [comment]
> I’m a code owner on the majority of the Teleport repo, but I can’t approve my own PRs

I don't think GitHub allows anyone to approve their own PRs?

**Comment by webvictim** [comment]
Yeah, it doesn’t, which is why more `CODEOWNERS` are good.

**Review by webvictim — APPROVED** [review]

**Review by benarent — APPROVED** [review]

**Pull request merged**
