### PR TITLE
Naji/force http2 kubernetes

### PR DESCRIPTION
**Pull request by NajiObeid**
https://github.com/gravitational/cloud/issues/1043

Force the kubernetes proxy to use http2

### CODE REVIEW

**Review by knisbet — APPROVED** [review]
Looks ok on my end, although I don't spend much time in the Teleport code. Were you able to test that a client is able to establish an H2 connection to the kubernetes proxy?

**Comment by NajiObeid** [comment]
@knisbet sorry I somehow missed your comment. yes I was able to test it

**Review by russjones — APPROVED** [review]
This looks reasonable. But please wait for two people from scale team to sign off.

Ping @fspmarshall @rosstimothy @espadolini.

**Review by fspmarshall — APPROVED** [review]
To my knowledge, we only care about the diff between http1/2 on web api ports (we use it to multiplex between grpc and standard http apis).  This seems fine.

**Review by espadolini — APPROVED** [review]

**Comment by NajiObeid** [comment]
@knisbet does this need to be backported to a specific version?

**Comment by russjones** [comment]
@NajiObeid Can you add test coverage?

**Comment by knisbet** [comment]
> @knisbet does this need to be backported to a specific version?

Teleport 8 please.

**Review by espadolini — APPROVED** [review]

**Review by rosstimothy — APPROVED** [review]

**Comment by russjones** [comment]
@NajiObeid You're good to go, please merge and then backport to a release branch.

**Comment by NajiObeid** [comment]
@russjones https://github.com/gravitational/teleport/runs/4820029278?check_suite_focus=true#step:4:82

**Review by russjones — APPROVED** [review]

**Comment by russjones** [comment]
@NajiObeid Feel free to ping reviewers anytime, you're not bothering us.

**Comment by benarent** [comment]
FYI, I was just updating my Kubernetes demo to 8.1.1 and ran into this error. Looks like it could be related to this 

```
$ kubectl exec --stdin --tty shell-demo -- /bin/bash
error: Internal error occurred: error executing command in container: error sending request: Post "https://kube.teleport.cluster.local/api/v1/namespaces/default/pods/shell-demo/exec?command=%!F(MISSING)bin%!F(MISSING)bash&container=nginx&stdin=true&stdout=true&tty=true": malformedHTTP response "\x00\x00\x18\x04\x00\x00\x00\x00\x00\x00\x05\x00\x10\x00\x00\x00\x03\x00\x00\x00\xfa\x00\x06\x00\x10\x01@\x00\x04\x00\x10\x00\x00"
```

**Pull request merged**
