### PR TITLE
Update docs structure for branch/4.4 to use with the new docs engine

### PR DESCRIPTION
**Pull request by iAdramelk**

### CODE REVIEW

**Review by klizhentas — APPROVED** [review]

**Comment by klizhentas** [comment]
@webvictim please approve

**Review by webvictim — APPROVED** [review]

**Comment by webvictim** [comment]
@klizhentas Please don't merge this yet

**Review by webvictim — CHANGES_REQUESTED** [review]
Do not merge yet

**Review by webvictim — APPROVED** [review]

**Comment by klizhentas** [comment]
@webvictim is this one good to merge after conflicts are resolved?

**Comment by webvictim** [comment]
@klizhentas Yes

**Pull request merged**
