### PR TITLE
updated HDR histogram vendor

### PR DESCRIPTION
**Pull request by quinqu**
## Purpose: 
Updated the package because there were some methods in their docs that weren't available with the version from 2015 and link was renamed from https://github.com/codahale/hdrhistogram to https://github.com/HdrHistogram/hdrhistogram-go. Tested and this update still works with `tsh bench`.

### CODE REVIEW

**Comment by awly** [comment]
If you `go get github.com/HdrHistogram/hdrhistogram-go@master`, we can drop the old import

**Comment by quinqu** [comment]
I ran that command to update and it changed a ton of files. The tests are not passing, is there something I am missing?

**Comment by webvictim** [comment]
Tests are passing in Drone :) The Jenkins failure is something etcd-related, likely just being flaky.

@gravitational-jenkins retest this please

**Comment by quinqu** [comment]
I just went back 2 commits, so it makes sense that it's passing now.

**Review by awly — APPROVED** [review]
All the extra dependency changes are because github.com/HdrHistogram/hdrhistogram-go depends on a newer version of go-cmp than we had.

@quinqu please remove the unrelated `lib/client/benchmark` changes from this PR before merging

**Pull request merged**
