### PR TITLE
Support running Teleport in a "hot reload" mode

### PR DESCRIPTION
**Pull request by bl-nero**
This change follows the example of our Cloud project which uses the same solution under the hood.

### CODE REVIEW

**Comment by strideynet** [comment]
Perhaps we should add `CompileDaemon` to the devbox ?

**Comment by bl-nero** [comment]
@strideynet Good idea, will do

**Review by ravicious — APPROVED** [review]

**Review by strideynet — APPROVED** [review]

**Comment by bl-nero** [comment]
Sorry, @strideynet , I'm too swamped with other things right now and I have no time to improve this, I'll just have to merge it as is. If someone needs this in devbox, they'll have to add it themselves. :)

**Comment by strideynet** [comment]
Sounds good to me!

**Pull request merged**
