### PR TITLE
types.proto: Bring back RecoveryAttemptLockExpires field as deprecated

### PR DESCRIPTION
**Pull request by jentfoo**
Raised from @codingllama [here](https://github.com/gravitational/teleport/pull/35325/files/4add256f08d2633beb7b8ba699269e15a51905a3#r1473524505):
> The removal of this field is making UpdateAndSwapUser fail.

> If the stored user had the "recovery_attempt_lock_expires" field set, then the comparison always fails. That is because when we read and unmarshal the user the unknown field gets dropped, but the actual CompareAndSwap operation compares using the storage blobs instead.

This PR does the short term fix by reverting this field change but marking the field as `deprecated`.

### CODE REVIEW

**Comment by jentfoo** [comment]
@codingllama and @zmb3 the [lint failure](https://github.com/gravitational/teleport/actions/runs/7733170001) makes it look like we can't simply bring this field back.  Will this be API compatible?

**Comment by codingllama** [comment]
> @codingllama and @zmb3 the [lint failure](https://github.com/gravitational/teleport/actions/runs/7733170001) makes it look like we can't simply bring this field back. Will this be API compatible?

I don't see why restoring the field would be a breaking change, neither for proto or JSON. @espadolini, any ideas?

**Comment by espadolini** [comment]
It's ok, it's just that the backwards compatibility checker can't know that it's ok, and we never added a way to bypass it for a given PR (and I'm not sure of how we could do that for the check in the merge queue, actually).

Couldn't we fix the function instead? The correct way to do compare-and-swap with object is to load the item, unmarshal it according to the current understanding of the type by the auth, compare the object with the expected object, then do a conditional update with the new item (in pre-condupdate days, compare-and-swap the new item with the one that was fetched). It's always been slightly wrong to assume that the marshaling would never change.

**Comment by espadolini** [comment]
Prior art: #10351

**Comment by codingllama** [comment]
Yeah, fixing the CAS was one of my suggestions. This is just a simpler/quicker fix while we get that done.

**Comment by jentfoo** [comment]
I am on PTO today and tomorrow, and next week the security team has a lot of ISO audit work ahead.  Given that, I was just trying to get a quick fix out

**Comment by codingllama** [comment]
> I am on PTO today and tomorrow, and next week the security team has a lot of ISO audit work ahead. Given that, I was just trying to get a quick fix out

Enjoy your PTO, Mike. I'll take a look at the CompareAndSwap changes.

**Pull request closed without merging**
