### PR TITLE
Add STS session tags support for DynamoDB access

### LINKED ISSUE #33131: Database Access - Add support for Session Tags in STS Assume Role API call
## What 

In case of handing many AWS DB Resource (like DynamoDB table) a separate IAM role needs to be created with proper hardcoded IAM permission. That lead to following problems: 

**IAM Role Management**: Separate IAM roles need to be created and managed for different AWS database resources (like various DynamoDB tables). Each role should ideally follow the principle of least privilege (POLP).
**Scalability Concern:** The creation and management of multiple IAM roles can lead to configuration overhead and might be perceived as not very scalable, especially in environments with numerous AWS resources.

### Proposed Solution:
Using Session Tags in STS Assume Role API:
https://docs.aws.amazon.com/IAM/latest/UserGuide/id_session-tags.html 
```json
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Effect": "Allow",
      "Action": "dynamodb:Scan",
      "Resource": "arn:aws:dynamodb:::table/$${aws:PrincipalTag/ddb_table_name}"
    }
  ]
}
```

The above policy allows the entity assuming the role to access the DynamoDB table specified by the TableID session tag dynamically, thus potentially reducing the number of IAM roles required.

Where AWS session Tags can be managed and defined  in Teleport  Role definition: 
```yaml
kind: role
metadata:

  id: 111
  name: dynamodb-dev-write
spec:
  allow:
    db_labels:
      env: dev
    db_names:
    - '*'
    db_users:
    - teleportDDBWriteRole
    - teleportDDBReadRole
    request: {}
    review_requests: {}
  deny: {}
  options:
    aws:
      session_tags: [ { 'ddb_table_name' : "{{internal.db_name}}" } ]
    cert_format: standard
```

 #### 
 **Example Code Snippet (in Go, using the AWS SDK):**
```go
awsConfig.Credentials = aws.NewCredentialsCache(
		stscreds.NewAssumeRoleProvider(sts.NewFromConfig(awsConfig), roleARN, func(options *stscreds.AssumeRoleOptions) {
			options.Tags = tags
		}),
	)
```

### PR DESCRIPTION
**Pull request by gabrielcorado**
Closes #33131.

This update adds support for specifying STS session tags on database configurations. The tags will be passed into the assume role call for DynamoDB database access, making them available on the IAM policies. This feature allows users to have one Teleport database configured per DynamoDB table (to have granular access) but share IAM roles used to connect.

changelog: Added support for STS session tags in the database configuration for granular DynamoDB access.

<details>
<summary>Usage example</summary>

1. Specify the tags on the database configuration.

```yaml
kind: db
version: v3
metadata:
  name: dynamo-table-a
  description: "DynamoDB Table A"
spec:
  protocol: "dynamodb"
  aws:
    region: "us-east-1"
    account_id: "123456789012"
    session_tags:
      ddb_table_name: "table-a"
```

2. Create/Update the IAM access role to include the [tag session permissions](https://docs.aws.amazon.com/IAM/latest/UserGuide/id_session-tags.html#id_session-tags_permissions-required) on the trust policy. For this example, we're naming this role as `DynamoScanTableRole`. Note: If the role used has a permission boundaries set, it will also need to get updated with the new STS permissions.

3. Update the IAM role policy to use the session tag. Here is an example of a policy that gives access to describe the table:

```yaml
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Sid": "VisualEditor0",
            "Effect": "Allow",
            "Action": [
                "dynamodb:DescribeTable"
            ],
            "Resource": "arn:aws:dynamodb:*:123456789012:table/${aws:PrincipalTag/ddb_table_name}"
        }
    ]
}
```

4. Include the database user on the Teleport user or role:

```yaml
kind: user
metadata:
  name: alice
spec:
  roles:
  - access
  - editor
  traits:
    db_names:
    - '*'
    db_users:
    - 'DynamoScanTableRole'
version: v2
```

4. Run proxy tunnel (same as regular DynamoDB access): `tsh proxy db --tunnel --port 8000 --db-user=DynamoScanTableRole dynamo-table-a`

5. Execute the DynamoDB queries:

```
$ aws --endpoint-url=http://localhost:8000 dynamodb describe-table --table-name table-a

{
    "Table": {
        ...
    }
}
```

Trying to describe any other table should return access denied error:

```
$ ❯ aws --endpoint-url=http://localhost:8000 dynamodb describe-table --table-name table-b

An error occurred (AccessDeniedException) when calling the DescribeTable operation: User: arn:aws:sts::123456789012:assumed-role/DynamoScanTableRole/alice is not authorized to perform: dynamodb:DescribeTable on resource: arn:aws:dynamodb:us-east-1:123456789012:table/table-b because no identity-based policy allows the dynamodb:DescribeTable action
```

</details>

### CODE REVIEW

**Review by GavinFrazar — APPROVED** [review]

**Review by greedy52 — COMMENTED** [review]
If agent's IAM role has a boundary policy, is `sts:TagSession` required in the boundary?

@smallinsky what are your thoughts on this appraoch? Thanks

**Comment by smallinsky** [comment]
> If agent's IAM role has a boundary policy, is sts:TagSession required in the boundary?
> @smallinsky what are your thoughts on this appraoch? Thanks

I might be wrong but this should not be needed and the only proper trust relation setup is required but I it work to check and test. 

One improvement is tempting: 

Namely in current implementation a custom will need to create N teleport database resouce for each DynamoDB table I if session_tags can support simple expressions so customer will be able to configure database using session_tags template:
````
kind: db
version: v3
metadata:
  name: dynamo-database
  description: "DynamoDB Table A"
spec:
  protocol: "dynamodb"
  aws:
    region: "us-east-1"
    account_id: "123456789012"
    session_tags:
      ddb_table_name: "{{db_name}}"
```` 

By that we will support table rback for dynamoDB: 

```
    db_names:
    - 'TableA'
    - 'TableB'
 ```

and a user will be able to dynamically  connect  to dynamo-database tables using `tsh db proxy --db-user=DynamoScanTableRole --db-name=TableA dynamo-database`

The cons is naming confusion db_name == DynamoDB table.

**Comment by gabrielcorado** [comment]
@greedy52 Yes, if the agent role has a boundary set, it needs to get updated with the `sts:TagSession`. (I've updated the example)

**Comment by greedy52** [comment]
> @greedy52 Yes, if the agent role has a boundary set, it needs to get updated with the `sts:TagSession`. (I've updated the example)

Could you update the AWS configurator as well?
https://github.com/gravitational/teleport/blob/f17ace0041fa35eefa544e037e321c86de4d7d8d/lib/configurators/aws/aws.go#L270-L273

Thanks!

**Review by greedy52 — APPROVED** [review]
LGTM 👍

**Comment by greedy52** [comment]
@smallinsky PTAL. thanks!

**Review by smallinsky — APPROVED** [review]

**Pull request merged**
