### PR TITLE
Add a timeout for device cancels

### PR DESCRIPTION
**Pull request by codingllama**
U2F devices, like Yubikey 4, don't seem to respect cancels, locking the program if a different security key is chosen.

There isn't a clean way to cancel when Cancel() doesn't work, so I've added a timeout to let the program complete. It's OK for the timeout to be short, it's not tied to user interaction and by the time we get to it all cancels were already issued.

### CODE REVIEW

**Comment by tobiaszheller** [comment]
> U2F devices, like Yubikey 4, don't seem to respect cancels, locking the program if a different security key is chosen.
> 
> There isn't a clean way to cancel when Cancel() doesn't work, so I've added a timeout to let the program complete. It's OK for the timeout to be short, it's not tied to user interaction and by the time we get to it all cancels were already issued.

@codingllama I have been trying to reproduce it with Yubikey 4 but wasn't able. I have registered 2 keys, yubi 4 and yubi 5. When I use yubi 5 for login program finish without any delays. Should it hang in that scenario?

**Comment by codingllama** [comment]
> @codingllama I have been trying to reproduce it with Yubikey 4 but wasn't able. I have registered 2 keys, yubi 4 and yubi 5. When I use yubi 5 for login program finish without any delays. Should it hang in that scenario?

@tobiaszheller, yep, that sounds like what I'm doing here, it definitely hangs without the fix.

**Review by tobiaszheller — APPROVED** [review]
lgtm although cannot reproduce locally

**Comment by codingllama** [comment]
Friendly ping @smallinsky @tigrato.

**Review by tigrato — APPROVED** [review]

**Review by smallinsky — APPROVED** [review]

**Pull request merged**
