### PR TITLE
Append web assets to `teleport` binary

### LINKED ISSUE #512: Pack web assets into executable
Teleport is a bit messy to deploy because of the need to carry around the web assets for serving the Web UI in a separate directory.

Consider serving them directly from the binary, this way Teleport's deployment becomes as easy as copying a single binary.

### PR DESCRIPTION
**Pull request by pdf**
Using the `append` method of https://github.com/GeertJohan/go.rice

Fixes #512

Worth noting that go.rice supports alternative embedding methods, the primary alternative to consider would be generating Go source files from the assets.  This removes the requirement for having the `zip` binary available at build time, however this will increase build time and memory requirements.  Happy to switch to that method though, if that would be preferable.

### CODE REVIEW

**Comment by kontsevoy** [comment]
@pdf Thank you for contributing this! We're actually in the middle of throwing out a ton of unneeded web assets, so merging this will take a bit more time.

**Comment by pdf** [comment]
Sure, in your own time.

Just so you're aware though - the only hard-coded asset is the `index.html` template, just like the previous code.  Whatever is in  the web root will get packed at build time, so it's no problem to make modifications to the web assets at will.  Accessing resources explicitly can be done via the box as easily as via the regular filesystem if required - they're actually proxied direct from the filesystem when using `go run` or similar during development.

**Comment by kontsevoy** [comment]
@pdf we're merging this in line-by-line right now, thanks! I'll close the PR when we're done.

**Comment by pdf** [comment]
Let me know if there's anything required from my end.

**Comment by kontsevoy** [comment]
Dupe of #601

**Pull request closed without merging**
