### PR TITLE
feat: Inform trusted device requirement to the frontend

### PR DESCRIPTION
**Pull request by codingllama**
Calculate the trusted device requirement when a web session is created and relay it to the frontend (through the CreateSessionResponse).

The presence (or lack) of a DeviceWebToken, whether the user went through device web authentication, and the current trusted device requirement can be used to inform the user that their access may be hindered by the lack of a trusted device:

* trusted device required and nil device web token -> access is likely hindered
* trusted device required and user skipped device web authentication -> access is likely hindered
* other scenarios -> unlikely impact to access

This PR makes the trusted device requirement field transient and sets it only in the initial session response. This may be revisit if we desire the information in other places / at different moments.

#43126

### CODE REVIEW

**Comment by codingllama** [comment]
Created as draft to gather feedback first.

@avatus, I think this could be used to draw an "yellow shield" in the Web UI, instead of the green shield, so we can warn users that they should likely enroll their device, install Connect, etc.

WDYT?

**Comment by avatus** [comment]
>"yellow shield" in the Web UI, instead of the green shield

Do you mean if they aren't enrolled and not upgraded? I'm guessing if they completed the ceremony we would still show the green shield yeah?

I think this would be a good solution. I don't think there would be a "non-shield" state anymore right? If they aren't enrolled (or are enrolled and skipped the ceremony) we show the yellow shiled/warning icon. and green if they blessed the session

**Comment by codingllama** [comment]
> > "yellow shield" in the Web UI, instead of the green shield
> 
> Do you mean if they aren't enrolled and not upgraded? I'm guessing if they completed the ceremony we would still show the green shield yeah?

Yes, green shield for a complete ceremony.

> I think this would be a good solution. I don't think there would be a "non-shield" state anymore right?

I was thinking non-shield still applies for OSS and for clusters that don't have any sort of trusted device enforcement.

> If they aren't enrolled (or are enrolled and skipped the ceremony) we show the yellow shiled/warning icon. and green if they blessed the session

Yep.

**Review by avatus — APPROVED** [review]
LGTM. Just to double check, this will still return it's value regardless of a user has a device enrolled or not, yes? 

Currently, the frontend only checks if `deviceWebToken` is received to do it's whole song and dance, but now we should always be doing _something_ since this value will be returned no matter what? 
edit: and by _something_ i mean, just checking for this value. if `NOT_REQUIRED` is returned, we can just continue about our merry way

**Review by tigrato — APPROVED** [review]

**Comment by codingllama** [comment]
FYI, pushed b96b74ef30af0e4afeadf1885ac7ab23c9d61481 in attempt to appease the FTD.

**Pull request merged**
