### PR TITLE
Fix typo in teleport-kube-agent Chart Reference

### PR DESCRIPTION
**Pull request by joehorsnell**
Not much more to say - fixing copy-paste error for link text on EC2 join method.

### CODE REVIEW

**Review by xinding33 — APPROVED** [review]

**Comment by joehorsnell** [comment]
Can we get another review on this one please @lsgunn-teleport / @ptgott / @r0mant / @zmb3 ?

**Review by lsgunn-teleport — APPROVED** [review]

**Comment by ptgott** [comment]
@joehorsnell Thanks for the fix! We need to cherry-pick your commit into a new branch so it can pass CI. I am doing this now.

**Comment by ptgott** [comment]
Closing so we can move this work over to https://github.com/gravitational/teleport/pull/31489

**Comment by joehorsnell** [comment]
> @joehorsnell Thanks for the fix! We need to cherry-pick your commit into a new branch so it can pass CI. I am doing this now.

@ptgott - for future reference, you could have just changed the base branch of this PR, or just rebased it, I think?

**Comment by ptgott** [comment]
@joehorsnell It would have been possible to rebase this PR against, say, an empty branch by a Teleport employee, though the end result would be pretty much the same. In general we need a Teleport-authored branch to be able to get a change past our CI tooling.

**Pull request closed without merging**
