### PR TITLE
Implement new inputs and select components

### LINKED ISSUE #46611: Implement the new inputs
[Figma](https://www.figma.com/file/Gpjs9vjhzUKF1GDbeG9JGE/Application-Design-System?type=design&node-id=8582-10113&mode=design&t=lfboeNMENiqaZygH-4) _**Size:**_ xs, sm, md, lg + **_Interaction states_**

### PR DESCRIPTION
**Pull request by bl-nero**
This change:
- Revamps the existing `Input` and `FieldInput` components
- Revamps the existing `Select*` and `FieldSelect*` family of components, including unifying the set of accepted properties and supported features between the components of the family
- Replaces the concept of "label tooltip" with "helper text" to better align with the UX dictionary and the actual placement of the helper text
- Tweaks the existing UI in necessary places.

Figma: [inputs](https://www.figma.com/design/Gpjs9vjhzUKF1GDbeG9JGE/Application-Design-System?node-id=8582-10113&node-type=frame&t=cpNraWuf7TyEr8AY-0), [dropdowns](https://www.figma.com/design/Gpjs9vjhzUKF1GDbeG9JGE/Application-Design-System?node-id=15326-653&node-type=canvas&t=3OsnVCwsP8xpY2Mu-0)

This is a large PR, so it's best to review it commit by commit. I decided to lump both input and select changes together, since they frequently appear together and testing these changes together saved a lot of time.

Screenshot 2024-09-20 at 18 28 59
Screenshot 2024-09-20 at 18 29 46
Screenshot 2024-09-20 at 18 30 25
Screenshot 2024-09-20 at 18 30 51
Screenshot 2024-09-20 at 18 31 50
Screenshot 2024-09-20 at 18 32 25

Caveats:
- I took liberty to implement a small size for the select control, even though it wasn't designed, for consistency with inputs (and there was at least one place that required it).
- There's still a separate implementation of `SelectCreatable` inside `teleport/Discover/Shared/SelectCreatable`, but I don't want to make this PR bigger than it already is.

Fixes https://github.com/gravitational/teleport/issues/46611
Needs to be merged together with https://github.com/gravitational/teleport.e/pull/5052.

Tested by inspecting all storybook entries and making sure that layouts are fine and don't break when they show validation errors. A couple of screens were also tested on the real Web and Connect UI.

Note: since this PR is the largest and latest of the highly-visible UI changes, it bears the changelog line; however, this has been gradually introduced to v17 across a multitude of PRs. To see the entire development history, see all subissues of https://github.com/gravitational/teleport/issues/37260.

Changelog: Refreshed the Web and Teleport Connect UI design.

### CODE REVIEW

**Review by kimlisa — APPROVED** [review]
this is pretty amazing stuff 🤩 

fyi i didn't try clicking around the connect app

unified resource dropdowns gap:

image

are we okay with how we typically use the circle info icon as a hover tooltip and using it as a non hover tooltip icon in the input?
 
image

**Comment by bl-nero** [comment]
@kimlisa The dropdowns gap is a separate issue that has been introduced before this PR. As for the non-hover icons, they were designed this way, so any feedback should go to Kenny and Rishi. :)

**Comment by bl-nero** [comment]
@kiosion @ravicious @avatus Friendly ping

**Comment by avatus** [comment]
> The dropdowns gap is a separate issue that has been introduced before this PR

do you know when it was introduced?

**Review by avatus — APPROVED** [review]
Looks really nice! Will this be backported?

**Comment by bl-nero** [comment]
> Looks really nice! Will this be backported?

@avatus I didn't intend to backport this, as it (1) changes the look of the login dialog, and I'd like to reserve that for a major version upgrade, and (2) we want to maintain consistency with other design updates. I may backport the API change, similarly to how I backported the typography API changes without the actual design change before. I think the only change here is addition of the size attribute and renaming the label tip field to helper text.

**Pull request merged**
