### PR TITLE
docs: include Enterprise in tctl version for ent, cloud prereq

### PR DESCRIPTION
**Pull request by stevenGravy**
Enterprise was not included in `tctl version` for enterprise, cloud versions.

### CODE REVIEW

**Review by ptgott — COMMENTED** [review]
Should we include `docs/pages/includes/tctl.mdx` in these new partials?

**Comment by stevenGravy** [comment]
> Should we include `docs/pages/includes/tctl.mdx` in these new partials?

You can't include partials in partials I thought.

**Comment by ptgott** [comment]
@stevenGravy It's not common but it is possible:

```
 $ grep -R '(!docs/pages/includes.*!)' docs/pages/includes

docs/pages/includes/plugins/editor-request-rbac.mdx:(!docs/pages/includes/add-role-to-user.mdx role="editor-reviewer"!)
docs/pages/includes/plugins/rbac.mdx:(!docs/pages/includes/add-role-to-user.mdx role="access-plugin-impersonator"!)
docs/pages/includes/kubernetes-access/rbac.mdx:(!docs/pages/includes/add-role-to-user.mdx role="kube-access"!)
docs/pages/includes/dns.mdx:(!docs/pages/includes/dns-app-access.mdx!)
docs/pages/includes/sso/loginerrortroubleshooting.mdx:(!docs/pages/includes/node-logins.mdx!)
docs/pages/includes/install-linux.mdx:  (!docs/pages/includes/compatibility.mdx!)
```

**Comment by stevenGravy** [comment]
> Should we include `docs/pages/includes/tctl.mdx` in these new partials?

The problem I see with include it is that has scope.  Then it would show the wrong view on the tabs.

**Review by ptgott — APPROVED** [review]

**Review by alexfornuto — CHANGES_REQUESTED** [review]
We should remove the bullet point from the partials, because the convention in the standard tctl partial is to provide the bullet when calling the partial.

**Review by alexfornuto — APPROVED** [review]
Approving as this PR adds value by creating/editing specific `tctl`/`tsh` partials for the three main types of Teleport offerings (self-hosted OSS, self-hosted Enterprise, and Cloud).

My concern is what these changes mean for the `docs/pages/includes/tctl.mdx` partial. It doesn't cover which version, but does include the important point of being logged in to the cluster. As discussed above, embedding that partial into these doesn't work because these partials are already used in a page-level Tabs set, creating nested Tabs.

I think we should follow up on this PR with some additional standardization to how we build prerequisites sections and/or these partials, such that we can include both version and login status into a single uniform item.

CC @ptgott for thoughts.

**Comment by ptgott** [comment]
@alexfornuto Since we've merged this PR, would you be okay creating another issue elaborating this idea?

> I think we should follow up on this PR with some additional standardization to how we build prerequisites sections and/or these partials, such that we can include both version and login status into a single uniform item.

**Pull request merged**
