### PR TITLE
small corrections and clarifications around ports.

### PR DESCRIPTION
**Pull request by programmerq**

### CODE REVIEW

**Review by ptgott — COMMENTED** [review]
Should we add a "Config Option" column and move the config option names there?

**Comment by programmerq** [comment]
> Should we add a "Config Option" column and move the config option names there?

I thought that might be a good idea. I liked having that information on the rows where it already was. I'll add them into a column and see how it looks!

**Comment by programmerq** [comment]
The wide configuration option is getting broken across lines in my browser. Not sure if there's a better way to keep that from happening?

image

**Comment by ptgott** [comment]
That might be outside the scope of this PR—I had suggested adding another column to make it more explicit that these were config options. Maybe change the "Description" header to "Description and Teleport Config Option," or add a note to the sentence before the table that the description includes config options?

**Review by ptgott — APPROVED** [review]

**Review by zmb3 — APPROVED** [review]
LGTM, we just need to rebase and include desktop (port 3028)

**Comment by ptgott** [comment]
@programmerq Checking whether there's any work you still want to do on this

**Comment by zmb3** [comment]
Closing due to inactivity.

**Pull request closed without merging**
