### PR TITLE
Use tmpfs instead of disk storage

### PR DESCRIPTION
**Pull request by webvictim**
We have lots of RAM on our CI servers, but the disks aren't super fast. As such, we can make test runs much quicker and subject to less contention by creating and using `tmpfs` as the backing store for our code and go cache.

I've been noticing that Drone gets really sluggish and operations take 3-5x their normal time with no obvious CPU/RAM contention when there are 4/5 test runs going on in parallel, or 2 test runs and a release build. I suspect the reason is that the disks are getting thrashed.

### CODE REVIEW

**Comment by knisbet** [comment]
Don't know if it applies or not, but one thing I do is use a tmpfs overlay mount ontop of a persistent directory, and then have a background rsync from the tmpfs overlay layer to the persistent underlay disk. Seems to work reasonably well where writes appear to be faster for go builds on cloud VMs, but will still survive a reboot with the exception of an unplanned poweroff.

**Comment by webvictim** [comment]
I think for our situation (where a full CI run is ~8 minutes) we would just restart the tests in a brand new pod with a fresh copy of the checkout if they failed.

**Comment by knisbet** [comment]
Sure, but for something like the gocache, having some sort of persistence might make a bigger impact than writing to a tmpfs.

**Comment by webvictim** [comment]
It's fair. We did try persisting the cache to S3 but it took longer to gzip/upload and vice versa than it saved on testing time, unfortunately.

**Review by klizhentas — APPROVED** [review]

**Comment by webvictim** [comment]
@awly @r0mant @russjones Need one of you for `CODEOWNERS` approval please.

**Review by awly — APPROVED** [review]

**Review by r0mant — APPROVED** [review]

**Pull request merged**
