### PR TITLE
[v11] helm: have proxy reload certificates daily

### PR DESCRIPTION
**Pull request by hugoShaka**
Manual backport of https://github.com/gravitational/teleport/pull/20115

### CODE REVIEW

**Review by tigrato — APPROVED** [review]

**Comment by webvictim** [comment]
@hugoShaka @tigrato Do we need a version gate in these backports? The reload functionality was only implemented in 11.2.1 and 10.3.12 - would anyone trying to set `teleportVersionOverride` to anything less than that with an up-to-date Helm chart (i.e. a pipeline pulling it regularly) get pods failing to start due to unknown configuration?

**Review by marcoandredinis — APPROVED** [review]

**Comment by hugoShaka** [comment]
> Do we need a version gate in these backports?

In my opinion, it depends on the kind of release we do. If this change is part of a bugfix release, it should be gated as users don't expect new stuff to be introduced. If this is part of a minor release I'm OK with not gating and sticking to our versioning scheme.

@r0mant and @zmb3 do you have info about the next release kind?

The version constraint should at least be documented in the reference, though. I'll update the backports before merging.

**Comment by webvictim** [comment]
Just for my own curiosity, I confirmed that it would be a breaking change:

```
$ teleport version
Teleport Enterprise v10.3.11 git:v10.3.11-0-gb9d89b8 go1.19.4

$ sudo teleport configure --test /etc/teleport.yaml
FAIL /etc/teleport.yaml
ERROR: failed parsing the config file: yaml: unmarshal errors:  line 31: field https_keypairs_reload_interval not found in type config.Proxy
```

**Comment by tigrato** [comment]
@hugoShaka @webvictim 

I think we should include the check here. 

Usually no one checks the helm chart version and they just care about the version installed. Currently, release `v11.2.2` breaks AWS access and users that rely on it must downgrade to older versions and we shouldn't break the deployment because of that.

We should check the version in `teleportVersionOverride` supports proxy reload certs.

**Comment by hugoShaka** [comment]
I added the version check constraints, could you take a look again @webvictim @tigrato ?

**Review by tigrato — APPROVED** [review]

**Review by webvictim — APPROVED** [review]

**Review by r0mant — APPROVED** [review]

**Pull request merged**
