### PR TITLE
Buddy PR for #30473

### PR DESCRIPTION
**Pull request by ibeckermayer**
This was reviewed in https://github.com/gravitational/teleport/pull/30473, should just be a rubber stamp (though open to further improvements if somebody is really motivated to dig in).

### CODE REVIEW

**Review by espadolini — COMMENTED** [review]
At least some resources (like Token) have a CreateFoo api that can be used without racy behavior. The solution for the other resources is not an additional racy roundtrip that pretends that everything is ok, it's to implement Create and Upsert rpcs, using the latter if -f is specified and the former if it's not.

**Comment by ibeckermayer** [comment]
I think we're talking past each other a bit here, my answer assumes that we don't have consistent e.g. `Create` semantics, between resources and between all backends. I inferred this from the fact that some of our oldest resources, such as `create user`, do it this janky way where we check with a `Get` first:

https://github.com/gravitational/teleport/blob/194dcc5d72317d25838740f0929cf5017bc828fe/tool/tctl/common/resource_command.go#L444-L480

Ideally `createUser` looks something like this

```go
// createUser implements `tctl create user.yaml` command.
func (rc *ResourceCommand) createUser(ctx context.Context, client auth.ClientI, raw services.UnknownResource) error {
	user, err := services.UnmarshalUser(raw.Raw)
	if err != nil {
		return trace.Wrap(err)
	}

	if rc.force {
		return client.UpsertUser(user)
	}
        
        // returns AlreadyExists error if it already exists, calling function can tell the user to use -f/--force if they want to overwrite
	return client.CreateUser(ctx, user)
}
```

However that adds additional problems, because now we don't know whether an `Upsert` should tell the user the resource was "created" vs "overwritten", it's not clear if `CreateUser` will always return `AlreadyExists` with every backend (I would assume so, but this is not documented and its a relatively involved project to check, particularly for every resource).

However it's a much more involved project to get that working and tested for all the various resources and backends. The idea here is a hack to fix the user-facing behavior, which is to say make the `-f` behavior and printed output consistent between resources. Then we can go through and fix the internals over time.

As I see it, without these changes, the internals are wrong and the user facing behavior is inconsistent vs with these changes, the internals are wrong but the user facing behavior is at least consistent.

I can see an argument that this just makes things so much worse internally that we should accept inconsistent user-facing behavior and fix things right the first time (which can be done iteratively, per-resource). Opinions?

**Comment by espadolini** [comment]
We should not incur a pessimization just to pretend to use the correct verb in the output message. To get that output correctly you need the resource to support condupdate (coming Soon™) and **a loop** that does "get resource, if resource exists then condupdate the resource i just got else create resource, if condupdate returns CompareFailed or create returns AlreadyExists, loop again". Is that really worth it, compared to "if force then upsert else create"? We considered having backend operations return the previous state of the world, but that would end up not being used very often at all, and it would be more expensive on the backend side (because then an upsert would also involve reading, which is sometimes completely avoided depending on the specifics of the backend).

**Comment by espadolini** [comment]
Also, this might be a somewhat silly objection, but in our permission model you don't need read permissions to write, and these changes all involve reading and hard exiting on any error other than notfound (including permission errors) right before writing.

**Review by justinas — APPROVED** [review]

**Comment by ibeckermayer** [comment]
@espadolini 

> To get that output correctly you need the resource to support condupdate

I'm not quite sure what condupdate means, I did some searching online but it doesn't seem to be commonly used. From context my educated guess is that it means "conditional update" where the condition is that the resource passed is indeed the latest version of a given resource (?). And this is in reference to the "optimistic locking" backend changes?

> Is that really worth it, compared to "if force then upsert else create"?

Being forced to give an answer -- I would say no, particularly for an admin tool which assumes a sort of "root access". Which is to say we assume the user knows what they're doing, we don't necessarily need to create some crazy rube-goldberg contraption to give them a slightly more specific output message.

> We considered having backend operations return the previous state of the world, but that would end up not being used very often at all, and it would be more expensive on the backend side (because then an upsert would also involve reading, which is sometimes completely avoided depending on the specifics of the backend).

Broadly it makes sense to me to expose an API that is maximally efficient, and if we want to return a previous state of the world too then we can expose a possibly-less-efficient version.

> in our permission model you don't need read permissions to write

Valid point, though isn't that a problem for an optimistic locking version of the system too? As I understand it, we would need to read first in order to upsert.

**Comment by espadolini** [comment]
> @espadolini
> 
> > To get that output correctly you need the resource to support condupdate
> 
> I'm not quite sure what condupdate means, I did some searching online but it doesn't seem to be commonly used. From context my educated guess is that it means "conditional update" where the condition is that the resource passed is indeed the latest version of a given resource (?). And this is in reference to the "optimistic locking" backend changes?

Yes, sorry for the confusion. "Conditional Update" (https://github.com/gravitational/teleport/blob/a26b6d88bfdeed2fd404a0165bc2c4a741005e87/lib/backend/backend.go#L88 as of current master) is a v15+ primitive backend operation that relies on revisions (also v15+) to guarantee that an update will go through if and only if the item revision matches what is expected - the revision changes on every write on the item, so if you've got the revision by reading the item (or by writing the item) you'll be sure that nothing else has modified it. It's not relevant for `tctl create` or `tctl create --force`, although we could expose it as some `tctl create --update` operation, and efforts are underway to use it for `tctl edit`.

> > Is that really worth it, compared to "if force then upsert else create"?
> 
> Being forced to give an answer -- I would say no, particularly for an admin tool which assumes a sort of "root access". Which is to say we assume the user knows what they're doing, we don't necessarily need to create some crazy rube-goldberg contraption to give them a slightly more specific output message.

Exactly.

> > We considered having backend operations return the previous state of the world, but that would end up not being used very often at all, and it would be more expensive on the backend side (because then an upsert would also involve reading, which is sometimes completely avoided depending on the specifics of the backend).
> 
> Broadly it makes sense to me to expose an API that is maximally efficient, and if we want to return a previous state of the world too then we can expose a possibly-less-efficient version.

Yeah, if you absolutely need the previous state you can get the previous state, then do the correct write operation depending on the previous state (create or conditional update for writing, conditional delete or... nothing? for deleting), and loop a few times in case the conditions have changed because of concurrent operations.

> > in our permission model you don't need read permissions to write
> 
> Valid point, though isn't that a problem for an optimistic locking version of the system too? As I understand it, we would need to read first in order to upsert.

It would be a problem for the optimistic locking version too, which is why I'm not suggesting it. My point is that even if we decided to accept this PR and do the extra work just to give out what we hope is the correct message at the end, we still have to implement a fall back to upsert and a more generic message in case the user is not allowed to read the current state.

**Pull request closed without merging**
