### PR TITLE
Emit node hostname as part of session.end event

### PR DESCRIPTION
**Pull request by kimlisa**
part of issue https://github.com/gravitational/teleport/issues/3537

#### Definition
- Add `server_hostname` to event fields

#### Manual Testing
Screenshot from 2020-04-14 19-26-45

#### Related PR
Display node hostname: https://github.com/gravitational/webapps/pull/75

### CODE REVIEW

**Review by awly — APPROVED** [review]
Add a unit test please

**Review by fspmarshall — APPROVED** [review]

**Review by alex-kovoy — APPROVED** [review]

**Comment by alex-kovoy** [comment]
@kimlisa  To verify that it populates this field you can add a check in here https://github.com/gravitational/teleport/blob/master/lib/web/apiserver_test.go#L1000

**Review by alex-kovoy — APPROVED** [review]

**Review by russjones — APPROVED** [review]

**Comment by kimlisa** [comment]
retest this please

**Comment by kimlisa** [comment]
retest this please

**Comment by kimlisa** [comment]
retest this please

**Comment by kimlisa** [comment]
retest this please

**Comment by kimlisa** [comment]
retest this please

**Comment by kimlisa** [comment]
retest this please

**Pull request merged**
