### PR TITLE
Better error message for IdP initated logins.

### LINKED ISSUE #2648: Provide better UX around unsupported IdP-initiated logins
**What happened**: Teleport administrators are contacted by end-users who see the generic error message `login unsuccessful, contact your system administrator` when they try to initiate a login directly into their Teleport installation via their IdP.

**What you expected to happen**: Give a clear message to the end-user that they must initiate login to that Teleport instance via Teleport itself rather than the IdP. Eg, surface the current admin-only error message:
```
ERRO [AUTH]      Teleport does not support initiating login from an SAML identity provider, login must be initiated from either the Teleport Web UI or CLI. auth/saml.go:249
WARN error while processing callback: identity provider initiated flows are not supported web/saml.go:109
```

Teleport version: <= 3.2

### PR DESCRIPTION
**Pull request by klizhentas**
Fixes #2648

Teleport does not support SAML identity provider
initiated logins, this commit gives a better
error message to the user instructing them
what to do.

### CODE REVIEW

**Review by russjones — APPROVED** [review]

**Review by webvictim — APPROVED** [review]
What's the logic behind changing the message not to start with a capital and then writing a whole function to capitalise it?

**Comment by klizhentas** [comment]
according to our golang code review guidelines errors should be lowercase https://github.com/golang/go/wiki/CodeReviewComments#error-strings

**Comment by klizhentas** [comment]
retest this please

**Comment by klizhentas** [comment]
retest this please

**Comment by klizhentas** [comment]
retest this please

**Comment by klizhentas** [comment]
retest this please

**Comment by klizhentas** [comment]
retest this please

**Comment by klizhentas** [comment]
retest this please

**Comment by klizhentas** [comment]
tests, like Seattle weather, are flaky today, so going to merge this as is.

**Pull request merged**
