### PR TITLE
[V6.2] Fix broken link

### PR DESCRIPTION
**Pull request by Erick-Reyes**
Backport: https://github.com/gravitational/teleport/pull/9825
Contributes to: https://github.com/gravitational/teleport/issues/8635

### CODE REVIEW

**Review by wadells — APPROVED** [review]

**Review by ptgott — APPROVED** [review]

**Comment by Erick-Reyes** [comment]
Fix GSuite naming on broken link: 3de1716

**Comment by russjones** [comment]
@Erick-Reyes Looks like this is approved, can we merge?

**Pull request merged**
