### PR TITLE
fix typo in image

### LINKED ISSUE #21215: Fix typo in X.509 certificate image
## Applies To
https://goteleport.com/docs/architecture/authentication/

This image in particular:

https://goteleport.com/docs/_next/static/media/x509-cert@2x.902f96d8.svg

image

## Details

The image needs to be re-done. There is a typo. 

Should say **device** but instead says **devcie** under the **Extensions** box.

### PR DESCRIPTION
**Pull request by adityakode**
Fix spelling mistake in x509 image

Closes #21215

### CODE REVIEW

**Review by zmb3 — APPROVED** [review]

**Review by alexfornuto — APPROVED** [review]
Thanks!

**Comment by adityakode** [comment]
Hi @alexfornuto !
I had a question . Why is my PR failing Check / Checking reviewers (pull_request_target) ?
PS answer if you can, as it would help me.

**Comment by zmb3** [comment]
@r0mant ca you stamp this one?

**Comment by alexfornuto** [comment]
@adityakode it's because external PRs need extra-special approvals and what-not. I'm not sure on the details, but we'll get there.

**Review by webvictim — DISMISSED** [review]
There is also a typo in "algorithm"
image

@adityakode Can you please fix this too?

**Comment by adityakode** [comment]
@webvictim Done :white_check_mark:

**Comment by zmb3** [comment]
Something looks wrong with `extiensions` too.

**Comment by webvictim** [comment]
Yep, I think the way the image is being edited is introducing artifacts. it may be easier to rebuild the entire thing from scratch.

**Comment by alexfornuto** [comment]
I found the original, editable format, commit incoming.

**Comment by alexfornuto** [comment]
@r0mant please 👍

**Review by r0mant — APPROVED** [review]

**Review by webvictim — APPROVED** [review]

**Pull request merged**
