### PR TITLE
Preserve backwards compatibility of teleport.lib.teleterm.v1.Gateway

### PR DESCRIPTION
**Pull request by ravicious**
#26441 introduced what is technically a breaking change in teleterm's protos by changing the type of a field while reusing its name and number. This tripped up the CI check that Edoardo is working on (https://github.com/gravitational/teleport/pull/26441#issuecomment-1557488902).

This PR corrects this by reserving the old field name and number and adding a new field with the new type.

### CODE REVIEW

**Comment by ravicious** [comment]
Oops, I forgot to change the Go code. 🤦

**Comment by ravicious** [comment]
For the Go code I changed only what's necessary to make the code compile. The Go code talks about "CLI command" much more, which kinda makes sense in that case since it operates on `os.exec.Cmd`. While "CLI command" as a name in general makes less sense (command-line interface command), I think I'll just leave it like that for now.

**Review by ibeckermayer — COMMENTED** [review]
Granted that I'm not up to speed on what's going on in this section of the code, but at first glance a `GatewayCLIClient` that only sends a single command makes less sense than a `GatewayCLICommand`. I typically think of a client as a thing that sends and receives messages repeatedly, whereas afaict this object represents just a single command sent once. 

I don't quite understand what you think doesn't make sense about "command-line interface command", to me that sounds like "a command that is sent to the command-line interface".

**Review by espadolini — APPROVED** [review]

**Comment by espadolini** [comment]
(not entering the merit of how to call the field and the message)

**Comment by ravicious** [comment]
I hear your concerns @ibeckermayer. It is a single command that's supposed to launch the client. I'm going to use Edoardo's suggestion, `gateway_cli_command`, which I think addresses your concerns and at the same time doesn't necessitate as many changes in the frontend code as `cli_client` does.

**Review by gzdunek — APPROVED** [review]

**Pull request merged**
