### PR TITLE
[v11] Update webassets in teleport/branch/v11 from webassets/master

### PR DESCRIPTION
**Pull request by smallinsky**
## What 

Update v11 webasset by `make update-webassets TELEPORT_BRANCH=branch/v11`

### CODE REVIEW

**Review by kimlisa — CHANGES_REQUESTED** [review]
> Update v11 webasset by `make update-webassets TELEPORT_BRANCH=branch/v11` 

thanks for this, if this was the exact command, then this is incorrect, webapps also has a v11 branch named `teleport-vXXX`, so [teleport-v11](https://github.com/gravitational/webapps/tree/teleport-v11). i'd double check that whatever you committed to master and needs to be in v11, that it is also backported in the webapps repo

new command:
`make update-webassets TELEPORT_BRANCH=branch/v11 WEBASSETS_BRANCH=teleport-v11`

**Comment by smallinsky** [comment]
@kimlisa 

Seems that `teleport-v11` is not yet cut off for `webassets` 

```
make update-webassets TELEPORT_BRANCH=branch/v11 WEBASSETS_BRANCH=teleport-v11
build.assets/webapps/update-teleport-webassets.sh -w teleport-v11 -t branch/v11
github.com
  ✓ Logged in to github.com as smallinsky (/Users/marek/.config/gh/hosts.yml)
  ✓ Git operations for github.com configured to use https protocol.
  ✓ Token: *******************

Cannot find teleport-v11 in the webassets repo.
```

Do you know if it can be done manually by just creation of a new `teleport-v11` branch or this operation needs to be done by some script ?

**Comment by kimlisa** [comment]
@smallinsky there should be a `teleport-v11` now and is good to go: https://github.com/gravitational/webassets/tree/teleport-v11

**Comment by smallinsky** [comment]
delete in favour of https://github.com/gravitational/teleport/pull/17245

**Pull request closed without merging**
