### PR TITLE
[docs] Change proxy_service ui_config to ui

### LINKED ISSUE #23667: Proxy service UI config documentation appears to be inaccurate.
## Applies To

https://goteleport.com/docs/reference/config/#proxy-service

## Details

The following block in the example config appears to be inaccurate:

```yml
    # Configuration options for the Web UI served by the Proxy Service.
    ui_config:
      # The amount of scrollback in the terminal. Scrollback is the amount of
      # rows that are retained when lines are scrolled beyond the initial
      # viewport. Does not apply to session recording view.
      scrollback_length: 1000
```

This fails config tests with `teleport configure --test test-teleport.yaml`

```bash
labelakb01:~ # teleport configure --test test-teleport.yaml 
FAIL test-teleport.yaml
ERROR: failed parsing the config file: yaml: unmarshal errors:  line 53: field ui_config not found in type config.Proxy
```

Example `test-teleport.yml` file:

```yml
---
# /etc/teleport.yaml

version: v3
teleport:
  nodename: labelakb01
  data_dir: /var/lib/teleport
  join_params:
    method: token
    token_name: <redacted>
  diag_addr: ""
  log:
    output: stderr
    severity: INFO
    format:
      output: text
auth_service:
  enabled: "yes"
  cluster_name: labeltel01.nimbl.lab
  authentication:
    type: local
    second_factor: otp
    connector_name: local
  listen_addr: 0.0.0.0:3025
  session_recording: node
  client_idle_timeout: 4h
  client_idle_timeout_message: "Your Teleport session has timed out due to inactivity and you've been disconnected."
  web_idle_timeout: 15m
  proxy_listener_mode: multiplex
  tunnel_strategy:
    type: agent_mesh
ssh_service:
  enabled: "yes"
  listen_addr: 0.0.0.0:3022
  commands:
    - name: hostname
      command: [hostname]
      period: 1m0s
  permit_user_env: false
  disable_create_host_user: false
  port_forwarding: true
  ssh_file_copy: true
proxy_service:
  enabled: "yes"
  web_listen_addr: 0.0.0.0:443
  public_addr: labeltel01.nimbl.lab:443
  https_keypairs:
    - key_file: /var/lib/teleport/labeltel01.key
      cert_file: /var/lib/teleport/labeltel01.cert
  https_keypairs_reload_interval: 0s
  ui_config:
    scrollback_length: 10000
```

Review of the [source code](https://github.com/gravitational/teleport/blob/master/lib/config/fileconf.go) revealed that the following config is correct:

```yml
  ui:
    scrollback_lines: 10000
```

If this change is made in the `test-teleport.yaml` above example it passes:

```bash
labelakb01:~ # teleport configure --test test-teleport.yaml 
OK test-teleport.yaml
```

So either the documentation needs to be updated, or perhaps this is a bug in the code if it really is supposed to be as the docs say. 

## Related Issues

I wasn't able to find any related issues.

### PR DESCRIPTION
**Pull request by avatus**
Fixes: https://github.com/gravitational/teleport/issues/23667

### CODE REVIEW

**Review by ptgott — APPROVED** [review]

**Comment by ptgott** [comment]
@avatus Does this one need backporting?

**Comment by avatus** [comment]
> @avatus Does this one need backporting?

Back to 12, yes! (now that I see these docs werent backported to 12 originally, we can get the _good_ version in first try.). Thanks for the reminder.

**Review by zmb3 — APPROVED** [review]

**Comment by zmb3** [comment]
You might as well remove the backport label for v12. If you didn't backport the original it's not goign to work.

**Comment by avatus** [comment]
I'll manually add the docs to v12 and skip the "backport" process. Will get a PR up for that shortly.

**Comment by avatus** [comment]
I was wrong above. I _did_ backport it (maybe I was looking in the wrong spot earlier?). Anyway, backport is live https://github.com/gravitational/teleport/pull/23672

**Pull request merged**
