### PR TITLE
Docs: cluster_name and public_addr do not need to match

### PR DESCRIPTION
**Pull request by sclevine**
Docs currently state:
> When using ACME, the cluster name must match the 'public_addr' of Teleport

I tested a configuration where `cluster_name` and the proxy's `public_addr` were not matched and found no issues. 

@r0mant confirmed that this bit of documentation is incorrect.

### CODE REVIEW

**Review by r0mant — APPROVED** [review]
Might wanna remove some [dead code](https://github.com/gravitational/teleport/blob/v10.1.5/lib/service/acme.go#L39-L40) as well while you're at it (doesn't look like this `clusterName` field is used anywhere).

**Review by ptgott — APPROVED** [review]

**Comment by zmb3** [comment]
Should this go to v9 and v8 as well?

**Comment by ptgott** [comment]
@sclevine Following up to see if you still want to merge this one

**Comment by sclevine** [comment]
Yep, but it's still blocked on approvals (CC: @zmb3)

**Comment by sclevine** [comment]
Oh, missed the question re: v8 and v9 -- will check those versions today.

**Comment by sclevine** [comment]
Looks good to backport to v8 and v9.
The original commit that added the dependency on `clusterName` never actually used the value: https://github.com/gravitational/teleport/commit/c0bb7325453e1694273719d67e80dd3ad79a4f7e

**Review by zmb3 — APPROVED** [review]

**Pull request merged**
