### PR TITLE
Create KeyStore library to wrap HSMs

### PR DESCRIPTION
**Pull request by nklaassen**
This PR adds a KeyStore library that transparently wraps actions on raw or HSM private keys in `lib/keystore`.

Access to private keys is provided through the `crypto.Signer` interface. The library support creating new keys, retrieving keys by their identifier, and selecting the local SSH, TLS, or JWT keys from a given CA.

the `keystore.KeyStore` interface has two implementations:
- `hsmKeyStore` handles real PKCS11 HSMs
- `rawKeyStore` only handles raw in-memory RSA keys, and is used to provide a consistent interface to the key source when no HSM is connected or configured.

This PR implements the keystore and updates `lib/auth/init.go` and `lib/auth/rotate.go` to use the HSM client interface to create keys for new CAs. Signers are also retrieved from the CA using the keystore instead of using the raw keys directly.

As the `rawKeyStore` is currently the only `KeyStore` implementation used, this should not cause any functional change.

I'm adding `softhsm2` to the docker buildbox here for testing purposes.

Future work:
- multi-auth clusters should have an HSM keypair per auth server (where HSMs are configured)
- CA rotation should work with per-auth keypairs
- user configuration

Reference: [RFD 25](https://github.com/gravitational/teleport/blob/master/rfd/0025-hsm.md)

### CODE REVIEW

**Comment by tcsc** [comment]
Looks OK in general - but I've been meaning to ask: how does the HSM support interact with the selection of ciphers. suites, etc. configured in the Teleport config file? Does there have to be some soft of feature selection happen on startup, or do they have such separate concerns that this is not an issue?

**Comment by klizhentas** [comment]
I've checked new vendored software licenses and they are OK.

**Comment by nklaassen** [comment]
> Looks OK in general, but I've only skimmed it so far. I've been meaning to ask, though: how does the HSM support interact with the selection of ciphers, algorithms, etc. configured in the Teleport config file? Does there have to be some sort of feature selection happen on startup, or do they have such separate concerns that this is not an issue?

@tcsc So `SigningAlg` is an attribute on the CA, and we wrap the ssh signer with an `AlgSigner` to make sure we use that algorithm [here](https://github.com/gravitational/teleport/blob/5af92559a7ae290e2ce331cb990467698ed5c55f/lib/hsm/hsm.go#L301). Everything else I *believe* occurs at a higher level simply using the `crypto.Signer`/`ssh.Signer` that you get from the hsm client.

**Comment by nklaassen** [comment]
Closing this as I have split it up into https://github.com/gravitational/teleport/pull/7612, https://github.com/gravitational/teleport/pull/7613, https://github.com/gravitational/teleport/pull/7614, and https://github.com/gravitational/teleport/pull/7615

**Pull request closed without merging**
