### PR TITLE
fix: Issue DeviceWebToken during Github authn

### PR DESCRIPTION
**Pull request by codingllama**
Issue a device web token during GitHub authn.

I've taken the opportunity to also calculate the "trusted device requirement" when a new session is created via CreateWebSessionFromReq (which should address regular and SSO logins too).

Partly addresses GitHub for issue #44598 (missing the frontend hooks).

### CODE REVIEW

**Comment by codingllama** [comment]
Requires https://github.com/gravitational/teleport.e/pull/4753 to work properly (otherwise web tokens are only issued to newly-enrolled devices).

- https://github.com/gravitational/teleport.e/pull/4753

**Comment by codingllama** [comment]
FYI @avatus.

**Comment by codingllama** [comment]
I've moved some of the logic around in a9f0fd7942fa7224d0dac29f774ded679db7dcf3 so we create tokens as part of CreateWebSessionFromReq - this works much better with upcoming SAML/OIDC changes.

Commit 3f619a3320bb7fedf64eb9bf3a00ed67c3651719 only moves some funcs around, no changes.

**Comment by codingllama** [comment]
Rebased onto latest master and solved protogen conflicts.

**Comment by codingllama** [comment]
Friendly ping @r0mant @rosstimothy @atburke ?

**Review by rosstimothy — APPROVED** [review]

**Review by r0mant — APPROVED** [review]

**Pull request merged**
