### PR TITLE
Wire FIDO2 into tsh login and registration

### PR DESCRIPTION
**Pull request by codingllama**
Seamlessly change the public API of lib/auth/webauthncli to use the libfido2-backed implementation, as long as the binary was compiled with the `libfido2` build tag.

A few adjustments are necessary to "wancli" methods to allow users to provide prompt callbacks and to return the credential user (not applicable here, but will be in following PRs).

Additional changes are made to `tsh mfa add` in order to avoid stdin hijacking by ContextReader, since we now may require PIN reads for authenticators.

#9160

### CODE REVIEW

**Comment by codingllama** [comment]
Branched from #11166, merge target automatically changes once it lands. Picked same reviewers as before for simplicity; it should be far simpler to review this one.

**Comment by codingllama** [comment]
Btw, the first few commits mostly rename/move code around. Feel free to review commit-by-commit.

**Review by zmb3 — APPROVED** [review]
LGTM

**Comment by codingllama** [comment]
Friendly ping @rosstimothy @Tener ?

**Comment by Tener** [comment]
Sorry for the delay @codingllama , I'll review on Monday.

**Comment by codingllama** [comment]
@Tener no worries, thanks for the reply.

**Review by rosstimothy — APPROVED** [review]

**Comment by Tener** [comment]
Hah, I just came back from reading the RFDs and looking at the files to see the branch merged 😄  But not to worry, the code looks good. 

One general thought I have is we have multiple places (`prompt.Stdin()`, `prompt.StdinSync()`, `term.ReadPassword()`) reading stdin in incompatible ways, stepping on each other toes. Ideally, we shouldn't need to introduce `prompt.StdinSync()` at all, but rather ensure the other two play along nicely, or...

Maybe we should actually scrap `prompt.StdinSync()` and `prompt.Stdin()` or implement them both with the help of `term` package for proper cross-platform support, buffering awareness etc. (we assume line-buffered input, but that isn't only option; see: https://gist.github.com/mrnugget/9582788).

The matter of reading input from stdin is not truly the meat of this PR though, so I think we can leave it for now.

**Comment by Tener** [comment]
@codingllama 
Thanks for the info!

If you want to take a look at the `term` vs. `prompt` issue, I'd expect the latter to break in the scenarios where `term` is doing extra cross-platform stuff, like for Windows: https://cs.opensource.google/go/x/term/+/03fcf44c:term_windows.go

Still, I think it is more important to get #9160 right, so thank you for your efforts in that direction 😄

**Pull request merged**
