### PR TITLE
Update `gosaml2` so it supports AES256GCM

### LINKED ISSUE #10019: Stale DynamoDB Auth Service Items
A customer has a need to frequently restart auth/proxy pods that are deployed by the `teleport-cluster` Helm chart. This results in stale DynamoDB auth service items that persist for a time period typically not exceeding one hour. All issues are resolved when the stale DynamoDB auth service items are deleted manually or the DynamoDB auth service items expire.

The following are logs that are observed when the issue is occurring:

Error from client:
```
ERROR REPORT:
Original Error: *trace.TraceErr connection error: desc = &#34;transport: authentication handshake failed: read tcp 192.168.248.193:65080-&gt;172.31.150.10:443: i/o timeout&#34;
Stack Trace:
        /tmp/build-darwin-amd64/go/src/github.com/gravitational/teleport/vendor/github.com/gravitational/teleport/api/client/client.go:2340 github.com/gravitational/teleport/api/client.(*Client).GetResources
        /tmp/build-darwin-amd64/go/src/github.com/gravitational/teleport/vendor/github.com/gravitational/teleport/api/client/client.go:1095 github.com/gravitational/teleport/api/client.(*Client).GetDatabaseServers
        /tmp/build-darwin-amd64/go/src/github.com/gravitational/teleport/lib/auth/clt.go:1589 github.com/gravitational/teleport/lib/auth.(*Client).GetDatabaseServers
        /tmp/build-darwin-amd64/go/src/github.com/gravitational/teleport/lib/client/client.go:617 github.com/gravitational/teleport/lib/client.(*ProxyClient).GetDatabaseServers
        /tmp/build-darwin-amd64/go/src/github.com/gravitational/teleport/lib/client/api.go:1925 github.com/gravitational/teleport/lib/client.(*TeleportClient).ListDatabaseServers
        /tmp/build-darwin-amd64/go/src/github.com/gravitational/teleport/lib/client/api.go:1930 github.com/gravitational/teleport/lib/client.(*TeleportClient).ListDatabases
        /tmp/build-darwin-amd64/go/src/github.com/gravitational/teleport/tool/tsh/db.go:50 main.onListDatabases.func1
        /tmp/build-darwin-amd64/go/src/github.com/gravitational/teleport/lib/client/api.go:504 github.com/gravitational/teleport/lib/client.RetryWithRelogin
        /tmp/build-darwin-amd64/go/src/github.com/gravitational/teleport/tool/tsh/db.go:49 main.onListDatabases
        /tmp/build-darwin-amd64/go/src/github.com/gravitational/teleport/tool/tsh/tsh.go:659 main.Run
        /tmp/build-darwin-amd64/go/src/github.com/gravitational/teleport/tool/tsh/tsh.go:285 main.main
        /var/folders/ys/8czjjsys38x504kj8172pd_m0000gp/T/drone-c5rOl7CA9nUzyqDD/home/drone/build-9935-1643075385-toolchains/go/src/runtime/proc.go:255 runtime.main
        /var/folders/ys/8czjjsys38x504kj8172pd_m0000gp/T/drone-c5rOl7CA9nUzyqDD/home/drone/build-9935-1643075385-toolchains/go/src/runtime/asm_amd64.s:1581 runtime.goexit
User Message: connection error: desc = &#34;transport: authentication handshake failed: read tcp 192.168.248.193:65080-&gt;172.31.150.10:443: i/o timeout&#34;
```

error from kube-agent:

```
teleport-kube-agent-9bc9d67f9-8gg5g teleport 2022-01-27T14:49:18Z WARN [DB:SERVIC] Failed to create remote tunnel: failed to dial: all auth methods failed, conn: <nil>. leaseID:900 target:redacted.com:443 reversetunnel/agent.go:384

```

gz#4346

gz#3996

### LINKED ISSUE #10909: Unable to decrypt SAML assertion
### Description

**What happened**:
As part of the RA findings, one of the Digital Identity Guidelines (FedRAMP Federal Mandate) is to use both signed and encrypted bearer (SAML) assertions for SSO to Okta-managed resources/applications.
It was noted that the Teleport <-> Okta SAML wasn't in compliance.

~~~
failed to retrieve SAML assertion info from response: error validating response: unable to decrypt encrypted assertion: unknown symmetric encryption method "http://www.w3.org/2009/xmlenc11#aes256-gcm"
~~~

However, it does seem from the https://github.com/golang/go/blob/dev.boringcrypto/README.boringcrypto.md repo that AES 256 GCM is approved (see section 9.1, second row): https://csrc.nist.gov/CSRC/media/projects/cryptographic-module-validation-program/documents/security-policies/140sp3678.pdf 

Teleport is running in FIPS mode.

**What you expected to happen**:
SAML assertation will not fail due to AES 256 GCM encryption method, even with FIPS.

Any indication of if this is truly not a supported algorithm or if there is some other error here is appreciated

### Reproduction Steps
As minimally and precisely as possible, describe step-by-step how to reproduce the problem.
1. Configure Teleport to use FIPS
2. Configure SSO with Okta using the specified encryption method

### PR DESCRIPTION
**Pull request by probakowski**
This change updates `gosaml2` to our fork with added support for AES256GCM and AES192GCM for encrypted assertions. 
I also run `go mod tidy` to cleanup `go.mod` file

Closes #10909 

Note to reviewers: I'd ask for review of 2 things, this change and https://github.com/gravitational/gosaml2/pull/4. 
I moved `master` in fork to the commit we used before in `go.mod` (https://github.com/gravitational/gosaml2/commit/757d23f1bc281bbf2bcdcf6a4a795edee8fa152a) and started from there, you can check history at https://github.com/gravitational/gosaml2/commits/master

### CODE REVIEW

**Comment by Tener** [comment]
The change looks fine on its own, but I have questions:
- why do we need support for AES256GCM and AES192GCM? This PR "closes https://github.com/gravitational/teleport/issues/10019", but it is already closed and doesn't mention either of the two...?
- our fork of gosaml2 is behind several commits from the original. perhaps we want to move it to the tip of the main branch?

**Review by Tener — APPROVED** [review]
Thanks to @zmb3 for clarification regarding the original issue.

Nit: as mentioned, perhaps worth moving our fork to include latest additions to https://github.com/russellhaering/gosaml2.

Other than that, LGTM.

**Review by zmb3 — APPROVED** [review]
LGTM.

If we want to update gosaml2 to the latest upstream commit, let's do that as a separate PR in case something breaks and we need to roll it back.

**Comment by probakowski** [comment]
@Tener @zmb3 thanks for review! 
I'll merge it as is and test updating fork to upstream in separate PR.

**Pull request merged**
