### PR TITLE
Introduce barrier for read deadline propagation of websocket alpn upgraded connection

### PR DESCRIPTION
**Pull request by AntonAM**
This PR adds a barrier to connection read deadline propagation, when it's set in the past.  
This fixes kubectl exec not working properly over L7 load balancer, because in that case connection was upgraded and hijacked twice. And golang http server during hijacking aborts its own pending read by setting read deadline to a past value. But since during second hijack we already have established underlying upgraded connection in cases of L7 load balancer, when http server calls `SetReadDeadline()` it goes to the very bottom and disrupts the chain.
This barrier now only cancels topmost read, it is done by decoupling `Read()` in our websocket wrapper from underlying connection read.

Changelog: Fix "kubectl exec" functionality when Teleport is running behind L7 load balancer.

Fixes #41014

### CODE REVIEW

**Review by jakule — COMMENTED** [review]
This looks like an important change that should have some test coverage.

**Comment by AntonAM** [comment]
@jakule yep, I'm working on adding tests.

**Comment by AntonAM** [comment]
Added test https://github.com/gravitational/teleport/pull/41946/commits/29e41304b62002b92e5d1dd274337d28ad48a100

**Review by greedy52 — COMMENTED** [review]
As discussed offline, I think the approach is reasonable but the implementation is complex and a little bit hacky. Let me know what you think about this alternative approach to use the raw `ws` library instead of the gorilla websocket conn:
https://github.com/gravitational/teleport/compare/master...STeve/try_fix_kube_exec

This more aligns with our client implementation which uses `ws`:
https://github.com/gravitational/teleport/blob/dd8071333edb787948b426533563dd96212c536b/api/client/alpn_websocket.go#L112-L129
And less code than original impl....

I can certainly review the current approach (this PR) if we decide to go with it.

**Comment by AntonAM** [comment]
@greedy52 yeah, we could use your version of the fix 👍 Will you open a PR?

**Comment by greedy52** [comment]
> @greedy52 yeah, we could use your version of the fix 👍 Will you open a PR?

yes i will do that. may steal your UT though. Thanks

**Comment by AntonAM** [comment]
Closed in favor of https://github.com/gravitational/teleport/pull/42091

**Pull request closed without merging**
