### PR TITLE
Update dockerized build to Go 1.14

### LINKED ISSUE #4001: Upgrade to Go 1.14
Go 1.14 was released in February and is stable by now.
I've been using it for local development for a while with no problems.

Changes relevant for us:
- modules improvements (for https://github.com/gravitational/teleport/issues/3541)
- performance improvements (esp. defers and timers)

### PR DESCRIPTION
**Pull request by awly**
Fixes https://github.com/gravitational/teleport/issues/4001

### CODE REVIEW

**Comment by webvictim** [comment]
This will only update anything that you build for local use with `make docker` - not sure if that's the intention.

- To update the Go runtime globally, you'd want to `s/1.13.2/1.14.4/g` on everything under `build.assets`
- To get Drone to pick it up, you need to `s/1.13.2/1.14.4/g` in `.drone.yml`
- To get Jenkins to pick it up, you need to `s/1.13.2/1.14.4/g` in https://github.com/gravitational/ops/blob/master/xcloud/release-teleport.sh#L31

**Comment by awly** [comment]
> To update the Go runtime globally, you'd want to s/1.13.2/1.14.4/g on everything under build.assets

Everything under `build.assets` uses the `RUNTIME` var in the makefile. At least my grepping doesn't find anything.

> To get Drone to pick it up, you need to s/1.13.2/1.14.4/g in .drone.yml

Done, missed it because `ag` ignores hidden files by default.

> To get Jenkins to pick it up, you need to s/1.13.2/1.14.4/g in https://github.com/gravitational/ops/blob/master/xcloud/release-teleport.sh#L31

Do we still need to maintain jenkins configs? Are we planning to keep it running side-by-side for a while with Drone?

**Comment by webvictim** [comment]
I think we're probably going to try and cut over to Drone fully as of Teleport 4.4 so for now, we should still keep Jenkins up to date. The question is partly whether we release Teleport 4.3.1 using Go 1.14.4, or whether we keep `branch/4.3` at 1.13.2 and then cut over to 1.14.4 with Teleport 4.4

The Jenkins build code isn't tied to the teleport repo sadly (it just builds from `ops` master) so any updates there would affect any release on the 4.3 branch too. As such, maybe we leave Jenkins be for now and just have Drone handle all the 1.14.4 builds.

**Comment by awly** [comment]
I don't think we should backport anything into 4.3 unless necessary.
In case of Go, that would be vuln mitigation or some other critical bug.

So sounds good, let's leave Jenkins as is and have Go 1.14 for releases starting 4.4

**Comment by webvictim** [comment]
```
FAIL: password_test.go:104: PasswordSuite.TestTiming

password_test.go:132:
    c.Assert(elapsedDifference.Seconds() < 0.040, Equals, true, comment)
... obtained bool = false
... expected bool = true
... elapsed difference (40.377358ms) greater than 40 ms
```

So close.

retest this please

**Review by webvictim — APPROVED** [review]

**Pull request merged**
