### PR TITLE
Allow setting diagnostics address via config file

### LINKED ISSUE #3841: Allow setting diagnostics address via config file
### Feature Request

Today, `teleport` has a `--diag-addr` flag to expose a diagnostics HTTP endpoint.
This address should also be configurable via the config file for consistency. 

### Who's it for?
OSS User, Pro, Enterprise

### PR DESCRIPTION
**Pull request by quinqu**
### Purpose 

Allow users to add diagnostic address via the config file 

Fixes https://github.com/gravitational/teleport/issues/3841

### CODE REVIEW

**Comment by xacrimon** [comment]
Changes seem good but I'm confused on how it works. This adds a parameter to the file configuration but doesn't read it anywhere. I assume that currently the actual address is hardcoded somewhere and this needs to be used in place of it?

**Comment by quinqu** [comment]
The current address is passed through as a flag. What this change does is it sets the `service` config (config used to start Teleport, where it is read) diagnostic address to whatever the user passed in from the file config. @xacrimon

**Review by xacrimon — APPROVED** [review]

**Review by russjones — COMMENTED** [review]
@quinqu Please add test coverage then this looks good to me.

**Review by russjones — APPROVED** [review]
Bot.

**Pull request merged**
