### PR TITLE
correct `tctl get db_server` command

### PR DESCRIPTION
**Pull request by ArunNadda**
`tctl get db` option is not present, it should be `tctl get db_server`.

### CODE REVIEW

**Comment by tigrato** [comment]
@ArunNadda `tctl get db` should work and should return the dynamic dbs registered in the cluster.

The `db_server` resource type identifies the different databases being served and by which agent.

**Review by zmb3 — APPROVED** [review]
Thanks Arun!

**Review by ptgott — APPROVED** [review]

**Review by r0mant — CHANGES_REQUESTED** [review]
Like @tigrato said, `db` resource represents a dynamically registered Database resource, `db_server` represents an instance of a Database proxied by a Database Service. So the current reference is correct. Users are almost never expected to have to remove db_server's manually.

**Comment by ptgott** [comment]
@ArunNadda given **r0mant's** review, is there any further work you would like to do on this branch, or should we close the PR?

**Pull request closed without merging**
