### PR TITLE
Fix setting pending request TTL pass the access expiry time

### PR DESCRIPTION
**Pull request by kimlisa**
part of https://github.com/gravitational/teleport/issues/35436

recommend reviewing by commit

There's two commits to this PR:

1) Mostly about preventing users from setting a pending request TTL pass the access expiry time. This led to the access request being in the list pass its access expiry time, and it disappears from the list right after approving. 

2) When a `role max_duration` isn't set it means `max_duration: 0`. Before, if a user sent a request with a max duration, this max duration got silently ignored and got set to the `session TTL` instead. So if my sessionTTL is 12 hours, and user requested a duration of `1hr`, it got overwrote to `12 hours`. This PR allows requested max duration less than the sessionTTL to be respected.

### CODE REVIEW

**Comment by zmb3** [comment]
Recommend replacing "pass" with "beyond" in the changelog entry.

**Comment by kimlisa** [comment]
> Recommend replacing "pass" with "beyond" in the changelog entry.

@zmb3 actually, do i need a changelog? i think this bug got introduced with this [PR](https://github.com/gravitational/teleport/pull/35799) but it didn't get backported yet

**Comment by kimlisa** [comment]
friendly ping @jakule @fspmarshall

**Review by fspmarshall — APPROVED** [review]

**Review by jakule — APPROVED** [review]
LGTM, I think we're only missing a test that covers session TTL, max duration and pending expiry.

**Pull request merged**
