### PR TITLE
RFD 24: DynamoDB Audit Event Overflow Handling

### PR DESCRIPTION
**Pull request by xacrimon**
This PR contains RFD 24 which contains a proposal for a scheme for dealing with the maximum size limit of DynamoDB partitions with LSI.

### CODE REVIEW

**Comment by xacrimon** [comment]
Please review @russjones @klizhentas. Who else is relevant for this?

**Review by russjones — COMMENTED** [review]
@fspmarshall Can you take a look?

**Comment by fspmarshall** [comment]
Full disclosure: I'm a dynamo newbie, and I've never done any work on the internals of our event system, so I'm probably missing something here... but don't we already spread out events across multiple partitions?

https://github.com/gravitational/teleport/blob/0ea35df10c80c95da1feb9a5bc2ddae55e80dd3d/lib/events/dynamoevents/dynamoevents.go#L324-L328 

Looks to me like audit events get partitioned by session ID, or randomly for global events.

**Comment by xacrimon** [comment]
> Full disclosure: I'm a dynamo newbie, and I've never done any work on the internals of our event system, so I'm probably missing something here... but don't we already spread out events across multiple partitions?
> 
> https://github.com/gravitational/teleport/blob/0ea35df10c80c95da1feb9a5bc2ddae55e80dd3d/lib/events/dynamoevents/dynamoevents.go#L324-L328
> 
> Looks to me like audit events get partitioned by session ID, or randomly for global events.

I will have to double check and run this against Dynamo to confirm myself but this leaves me a bit confused as it wasn’t what I heard that the implementation was so I assumed it was just defaulting fo something plus the session ID in the SDK threw me off. If that’s the case this issue is far less dire than I understood.

**Comment by fspmarshall** [comment]
For what its worth, I know that "backend" state (nodes, cas, etc) definitely *are* stored under a single partition.  I don't think thats an issue though.  We'd probably need to overhaul the caching system well before dynamo ever became the bottleneck for that stuff.

**Comment by xacrimon** [comment]
@fspmarshall Have a look at https://github.com/gravitational/teleport/blob/master/lib/events/dynamoevents/dynamoevents.go#L672

Here we create a new GSI which essentially acts like a second table, this partitions by namespace which is hardcoded as `default` and this is the table causing trouble.

**Comment by fspmarshall** [comment]
@xacrimon I see.  Solution as described won't work then, yeah?  Sounds like we need to change how we handle indexing rather than moving the events themselves around.

**Comment by xacrimon** [comment]
> @xacrimon I see. Solution as described won't work then, yeah? Sounds like we need to change how we handle indexing rather than moving the events themselves around.

Yeah, after reading the re-reading documentation that seems to be the case. From my point of view this leaves us with two options
- a) We figure out another way to structure the global secondary index (I have no idea if this is actually feasible to do and I would have to sink a lot more time into Dynamo to figure this out)
- b) We move old events not just to a separate partition, but use a separate archival table without a global secondary index entirely.

**Comment by xacrimon** [comment]
Or wait, would it perhaps work with this scheme? The issue is that the secondary view blows up because it partitions on the namespace right. If we make that attribute in the form of `namespace-yyyy-mm-dd` that would solve the problem without needing another table.

**Comment by fspmarshall** [comment]
@xacrimon looks like GSIs can be [added or removed](https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/GSI.OnlineOps.html), so modification is possible if we can come up with an improved model.

I wonder if we could get away with just creating an index that was partitioned by month (`yyyy-mm`), or by ten day blocks (`yyyy-mm-d`) and only query the past couple partitions by default?  No need for background process, and pretty simple to reason about.  Plus, it would work well with our existing API that queries events by time range since computing the keys for all partitions within the range would be trivial.

**Comment by xacrimon** [comment]
That could work, I quite like that. Is namespace information something we should retain and include in these keys as well?

**Comment by fspmarshall** [comment]
If it's hardcoded I don't see the point, but maybe @klizhentas or @russjones could weigh in on that?

**Comment by klizhentas** [comment]
> I wonder if we could get away with just creating an index that was partitioned by month (yyyy-mm), or by ten day blocks (yyyy-mm-d) and only query the past couple partitions by default? No need for background process, and pretty simple to reason about. Plus, it would work well with our existing API that queries events by time range since computing the keys for all partitions within the range would be trivial.

I agree, this idea could work, we should give it a try. Namespaces are not currently used so all events have `default` namespace.

**Comment by xacrimon** [comment]
Should we go back and retroactively move events on first start?

**Comment by fspmarshall** [comment]
I don't think we need to move them, just add an additional field that the new GSI uses as it's partition. Adding the new key should be safe to do asynchronously in the background (to not block auth init).  IMO it's okay if it takes a few seconds for audit events to re-appear in the UI after upgrade.

Removing the old GSI might affect folks, but to my knowledge we don't promise back compact for stuff like that, and we can phase in the new GSI scheme before removing the old one, so if someone is directly accessing the old GSI they can have a window of overlap to transition over to calling the new one (though fresh deployments should just create the new one).

**Review by klizhentas — APPROVED** [review]

**Review by fspmarshall — APPROVED** [review]

**Comment by webvictim** [comment]
This RFD was implemented in https://github.com/gravitational/teleport/pull/6583 (for future searchers)

**Pull request merged**
