### PR TITLE
Skip cache during CreateBot RPC

### LINKED ISSUE #14883: Bot deletion is not consistant when cache is enabled
Expected behavior:

- Run teleport with cache
- Delete a bot using `DeleteBot`
- quickly create the bot back using `CreateBot`
- The bot is created

Current behavior:

Bot creation fails because the bot's role still lives in cache. Retrying later works.

Bug details:
- Teleport version
v11.0.0-dev
- Recreation steps

```go
    name := "mybot"
    role := "access"

    // Delete the bot
    if err := authClient.DeleteBot(ctx, name); err != nil {
        return "", trace.Wrap(err)
    }

    // Delete the bot's role
    roleName := fmt.Sprintf("bot-%s", name)
    if err := authClient.DeleteRole(ctx, roleName); err != nil {
        // This raises an error saying the role doesn't exist, it makes sense and we continue
    }

    // We create the bot and it fails saying the role already exists
    response, err := authClient.CreateBot(ctx, &proto.CreateBotRequest{
        Name:  name,
        Roles: []string{role},
    })

    time.Sleep(5*time.Second)

    // Here the bot creation works
    response, err := authClient.CreateBot(ctx, &proto.CreateBotRequest{
        Name:  name,
        Roles: []string{role},
    })
```

See slack thread: https://gravitational.slack.com/archives/C01TYKHFVTQ/p1658519346840079?thread_ts=1658518996.952949&cid=C01TYKHFVTQ

### PR DESCRIPTION
**Pull request by strideynet**
Closes #14883

Adjusts CreateBot RPC to skip the cache when checking if the role and user already exist. This fixes an issue whereby rapidly deleting and recreating a bot would throw an error, as is currently happening in the Teleport operator. 

This will of course reduce performance of this endpoint a little, but this is probably insignificant given the rest of the endpoint makes a few writes to the backend anyway. We also don't expect for this endpoint to be called too much.

### CODE REVIEW

**Review by zmb3 — APPROVED** [review]
I wonder if we should put `s.Services` behind a field called `NoCache` so that these types of opt-out scenarios would be more explicit.

`s.NoCache.GetRole(ctx, resourceName)`

**Comment by strideynet** [comment]
> I wonder if we should put `s.Services` behind a field called `NoCache` so that these types of opt-out scenarios would be more explicit.
> 
> `s.NoCache.GetRole(ctx, resourceName)`

I do find myself agreeing with you. I did notice that in @espadolini 's recent PR, he did originally name the field `Uncached`, but this was changed during review to `Services`. It certainly feels like this is going to come up in review a lot, and that mistakes made with this are going to be largely unnoticed until we have performance issues or unexpected behaviour caused by caching when someone intended to not cache.

**Comment by espadolini** [comment]
Can't this be done by creating the role and then the user, instead? Create will atomically check that no previous resource with the same name existed before.

**Comment by strideynet** [comment]
> Can't this be done by creating the role and then the user, instead? Create will atomically check that no previous resource with the same name existed before.

Hmm, I think that risks further aggravating an inconsistent state. For example, some situation where a deletion of a bot had partially succeeded, by then causing this creation of a bot to partially succeed, giving a situation where an old user exists with a new role. Even though we don't use transactions, it feels important to me that we at least try to detect an inconsistent state and prompt it to be manually rectified rather than potentially worsening it.

**Comment by espadolini** [comment]
You should still swap the `UpsertRole` for a `CreateRole` in `createBotRole` IMO - sadly there's not much to do for role and user deletion unless we add some atomic "delete item with certain key if value equals expected value" operation.

**Review by espadolini — APPROVED** [review]

**Pull request merged**
