### PR TITLE
`handle_server_announce` tests

### PR DESCRIPTION
**Pull request by ibeckermayer**
## key structural change for testing

The primary idea behind this change is to make `rdpdr::Client` easier to test. Currently, `rdpdr::Client` is called by `RdpClient` with the raw `tpkt::Payload` given to us by `rdp-rs`:
https://github.com/gravitational/teleport/blob/a67f5c3eb458065cceb1bcbe65399ff364ac700c/lib/srv/desktop/rdp/rdpclient/src/lib.rs#L634
`rdpdr.read_and_reply`  in the above version of the code handles sending the replies itself internally by calling `write()` on the passed `&mut self.mcs`. With these new changes, the `rdpdr.read_and_reply` function in that line is renamed to `rdpdr.read_and_create_reply`, which now returns an `RdpResult<Vec<Vec<u8>>>` (and it's `RdpClient` that's responsible for sending those raw response payloads via the `self.mcs`):
https://github.com/gravitational/teleport/blob/08df0d47a4230ceb1787fc2eb48890c094ff3df2/lib/srv/desktop/rdp/rdpclient/src/lib.rs#L634-L641

With this new structure, we can now create tests that call `rdpdr.read_and_create_reply` with a given input payload, and check that we get the expected output payload. This sets us up to test all of the different common server-request --> client-response scenarios for the `rdpdr::Client`, from raw input to raw response.

See `test_server_announce` for the first example:
https://github.com/gravitational/teleport/blob/08df0d47a4230ceb1787fc2eb48890c094ff3df2/lib/srv/desktop/rdp/rdpclient/src/rdpdr.rs#L4237-L4263

## Notes to self
- [x] Need to create PR and update rdp-rs ref
- [x] change base branch to `master` before merging

### CODE REVIEW

**Comment by zmb3** [comment]
The approach looks good to me and is similar to how I tested the cliprdr channel.

I have always wondered if `RdpResult<Vec<Vec<u8>>>` is hard to work with and if we should typedef it for readability. Maybe something like:

```
type Message = Vec<u8>
type Messages = Vec<Message>
```

and then return `RdpResult<Messages>`

**Comment by ibeckermayer** [comment]
> The approach looks good to me and is similar to how I tested the cliprdr channel.
> 
> I have always wondered if `RdpResult<Vec<Vec<u8>>>` is hard to work with and if we should typedef it for readability. Maybe something like:
> 
> ```
> type Message = Vec<u8>
> type Messages = Vec<Message>
> ```
> 
> and then return `RdpResult<Messages>`

I went with

```rust
/// PayloadIn represents raw incoming RDP messages for parsing.
pub(crate) type PayloadIn = Cursor<Vec<u8>>;
/// Message represents a raw outgoing RDP message to send to the RDP server.
pub(crate) type MessageOut = Vec<u8>;
pub(crate) type PayloadOut = Vec<MessageOut>;
```

to add some logical symmetry to the names.

ab1359ee65ff006009b30dc80f6d231069710334

**Comment by zmb3** [comment]
I'm not sure I like `PayloadOut = Vec<MessageOut>` over `Messages`, but your call.

**Comment by ibeckermayer** [comment]
> I'm not sure I like `PayloadOut = Vec<MessageOut>` over `Messages`, but your call.

Yeah you're right it's worse, I changed it to your suggestion 6dfc69d30918583486762debb054bd2f4ad38d61

**Comment by ibeckermayer** [comment]
closed in favor of https://github.com/gravitational/teleport/pull/16299

**Pull request closed without merging**
