### PR TITLE
Update CHANGELOG

### PR DESCRIPTION
**Pull request by fspmarshall**
Updates CHANGELOG to cover release 4.2.0.

### CODE REVIEW

**Comment by wadells** [comment]
LGTM.

**Review by wadells — APPROVED** [review]

**Comment by wadells** [comment]
We should we also pull forward the version number changes.  I don't think it practically matters, but having 4.0.2-dev.4 in master doesn't really make sense anymore.

**Comment by fspmarshall** [comment]
> We should we also pull forward the version number changes. I don't think it practically matters, but having 4.0.2-dev.4 in master doesn't really make sense anymore.

We don't want to pull the version bumps from `branch/4.2` since we started adding `4.3` related commits to `master` already.  Version on `master` needs to be updated to `4.3.0-dev.1`.  I'll deal with that once we've finished getting the `4.2` related stuff squared away.

**Comment by wadells** [comment]
> We don't want to pull the version bumps from `branch/4.2` since we started adding `4.3` related commits to `master` already. Version on `master` needs to be updated to `4.3.0-dev.1`. I'll deal with that once we've finished getting the `4.2` related stuff squared away.

That makes sense.  Thanks for explaining!

**Pull request merged**
