### PR TITLE
Add Ping method to auth server (#3298)

### PR DESCRIPTION
**Pull request by fspmarshall**
Makes the Auth Server's `Version` available to GRPC clients via a new `Ping` method.  This method currently *only* returns `Version`, but may be expanded to cover more information in the future (similar to the [proxy's `Ping` method](https://github.com/gravitational/teleport/blob/dbe6202a4a014ad52abd38fe9905658a342b9675/lib/client/weblogin.go#L126-L135)).

*EDIT*: Method has been updated to return `ClusterName` as well.

### CODE REVIEW

**Comment by russjones** [comment]
@alex-kovoy Check this out.

**Review by russjones — APPROVED** [review]

**Comment by alex-kovoy** [comment]
@benarent is working on finalizing of what else needs to be sent in addition to version number (like node count) for V5 version, but since this is for 4.3 perhaps we dont need to wait for Ben (?)

**Comment by alex-kovoy** [comment]
related
https://github.com/gravitational/teleport/issues/2460
https://github.com/gravitational/teleport/issues/2925
https://github.com/gravitational/teleport/issues/2924

**Review by klizhentas — APPROVED** [review]

**Comment by fspmarshall** [comment]
retest this please

**Comment by russjones** [comment]
@gravitational-jenkins retest this please

**Comment by russjones** [comment]
@gravitational-jenkins retest this please

**Comment by russjones** [comment]
@gravitational-jenkins retest this please

**Comment by russjones** [comment]
@gravitational-jenkins retest this please

**Pull request merged**
