### PR TITLE
Split Docker/AMI jobs into separate build and publish steps

### PR DESCRIPTION
**Pull request by webvictim**
Relevant to #3936 

Currently in Drone:
- Docker images are built when a Git tag is pushed, but they're not published (as this would make the images available for public consumption - we haven't cut over to Drone fully yet, so Jenkins is still responsible for building Docker images)
- AMIs are built and made public when a Git tag is pushed, which is in conflict with what Jenkins is doing.

This PR makes the following changes to the jobs that run on a `tag` event:
- Build and push Docker images to a separate private CI repo, so they can be tested before publishing.
- Build AMIs, but don't make them public.

It also makes the following changes to the job that runs on a `promote` event:
- Download Docker images from the private CI repo, retag them to the production version and push them to the production repo for use
- Make the AMIs built as part of the `tag` event public.

This also removes the dependency on the `test` pipeline for all `tag` jobs - essentially, we don't re-run the linter and unit/integration tests on the tag, as the commit will already have been tested.

### CODE REVIEW

**Comment by webvictim** [comment]
Tested this by:
- pushing the `4.4.0-dev.11` tag to the Teleport repo: https://drone.gravitational.io/gravitational/teleport/1632
- running the promotion step: https://drone.gravitational.io/gravitational/teleport/1634

**Comment by webvictim** [comment]
@awly @russjones ping for approval please.

It's been tested with several dev tags so should work fine.

**Review by awly — APPROVED** [review]

**Comment by webvictim** [comment]
Just realised I need approval on https://github.com/gravitational/teleport.e/pull/159 for the `e` changes as well please - then I'll merge that and update the e ref here.

**Comment by webvictim** [comment]
@russjones @klizhentas Need one of you to approve the e ref bump please.

**Review by russjones — APPROVED** [review]

**Pull request merged**
