### PR TITLE
Add a user watcher.

### PR DESCRIPTION
**Pull request by mdwn**
A user watcher has been added to allow for the enterprise Okta service to monitor users for reconciliation.

### CODE REVIEW

**Review by nklaassen — APPROVED** [review]

**Review by r0mant — COMMENTED** [review]
How is Okta service going to use the user watcher?

**Comment by mdwn** [comment]
> How is Okta service going to use the user watcher?

The idea here is to watch for users to log in/be created/updated, and then attempt to reconcile Okta access from it. So for example, a user has been created that has access to a certain subset of Okta applications, so we then monitor that within the Okta service and create a corresponding Okta assignment to match that within Okta.

Also, since IdP/Okta users are emphemeral, something like this will likely be needed in order to indicate that a user can be checked within the Teleport Okta reconciler.

**Comment by r0mant** [comment]
Can't we create appropriate OktaAssignment's (which Okta service already watches), say, when the user logs in? I'm just a bit concerned with Okta service becoming pretty complex with multiple watchers running, etc. It doesn't feel like Okta service should be concerned about what users there are in the cluster tbh.

**Comment by mdwn** [comment]
> Can't we create appropriate OktaAssignment's (which Okta service already watches), say, when the user logs in? I'm just a bit concerned with Okta service becoming pretty complex with multiple watchers running, etc. It doesn't feel like Okta service should be concerned about what users there are in the cluster tbh.

That seems reasonable. I'll sync with you on that.

**Comment by mdwn** [comment]
Going to do this on user login as opposed to using a monitor.

**Pull request closed without merging**
