### PR TITLE
Updating dependencies for etcd v3.3.15

### LINKED ISSUE #2762: Single node failure of etcd brings Teleport 3.1.8 down.
Running Teleport 3.1.8 with etcd 3.3.10.

When connecting to etcd, Teleport connects to the first endpoint int he list of peers and if that node goes down, Teleport goes down with it (no tsh or web login). 

Does this problem still reproduce on 4.0 and 4.1?

### PR DESCRIPTION
**Pull request by klizhentas**
Fixes #2762

This commit vendors etcd v3.3.15 client taht has fixes for the problem reported
in etcd-io/etcd#9949

### CODE REVIEW

**Comment by klizhentas** [comment]
@russjones @fspmarshall please take a look, this fixes problematic behavior of teleport with etcd node going down and bringing the whole cluster down, so I thought it's useful to add to 4.1

**Review by r0mant — APPROVED** [review]
Looks good to me...

**Review by fspmarshall — COMMENTED** [review]
Is there any conflict with the ability to produce `go1.9` builds (see #2960)?  A quick glance at the etcd CHANGELOG indicates that `3.3.15` targets `go1.12+`, but I don't know enough about golang's compilation/compatibility to know if this is a hard limitation.

**Review by russjones — APPROVED** [review]

**Comment by klizhentas** [comment]
going to close this in favor of a simplified PR with less dependencies

**Pull request closed without merging**
