### PR TITLE
Fix race condition in PipeNetCon

### PR DESCRIPTION
**Pull request by tcsc**
The race condition detector is being triped by a concurrent `Write` and `Close` in the `PipeNetCon` in several integration tests. 

Example race detector report:
```
==================
WARNING: DATA RACE
Read at 0x00c00307e060 by goroutine 318:
  golang.org/x/crypto/ssh.(*channel).WriteExtended()
      /workspace/vendor/golang.org/x/crypto/ssh/channel.go:233 +0x5b
  golang.org/x/crypto/ssh.(*channel).Write()
      /workspace/vendor/golang.org/x/crypto/ssh/channel.go:535 +0x88
  golang.org/x/crypto/ssh.(*sessionStdin).Write()
      <autogenerated>:1 +0x87
  github.com/gravitational/teleport/lib/utils.(*PipeNetConn).Write()
      /workspace/lib/utils/pipenetconn.go:56 +0x79
  github.com/gravitational/teleport/lib/client.(*NodeSession).pipeInOut.func2()
      /workspace/lib/client/session.go:618 +0x20d

Previous write at 0x00c00307e060 by goroutine 678:
  ??()
      -:0 +0xffffffffffffffff
  internal/poll.ignoringEINTRIO()
      /opt/go/src/internal/poll/fd_unix.go:581 +0x16e
  internal/poll.(*FD).Write()
      /opt/go/src/internal/poll/fd_unix.go:274 +0x294
  net.(*netFD).Write()
      /opt/go/src/net/fd_posix.go:73 +0x68
  net.(*conn).Write()
      /opt/go/src/net/net.go:195 +0xeb
  net.(*TCPConn).Write()
      <autogenerated>:1 +0x69
  bufio.(*Writer).Flush()
      /opt/go/src/bufio/bufio.go:607 +0x141
  golang.org/x/crypto/ssh.(*connectionState).writePacket()
      /workspace/vendor/golang.org/x/crypto/ssh/transport.go:182 +0x148
  golang.org/x/crypto/ssh.(*transport).writePacket()
      /workspace/vendor/golang.org/x/crypto/ssh/transport.go:172 +0xbe
  golang.org/x/crypto/ssh.(*handshakeTransport).pushPacket()
      /workspace/vendor/golang.org/x/crypto/ssh/handshake.go:223 +0x52a
  golang.org/x/crypto/ssh.(*handshakeTransport).writePacket()
      /workspace/vendor/golang.org/x/crypto/ssh/handshake.go:516 +0x535
  golang.org/x/crypto/ssh.(*channel).writePacket()
      /workspace/vendor/golang.org/x/crypto/ssh/channel.go:215 +0x12c
  golang.org/x/crypto/ssh.(*channel).WriteExtended()
      /workspace/vendor/golang.org/x/crypto/ssh/channel.go:271 +0x644
  golang.org/x/crypto/ssh.(*channel).Write()
      /workspace/vendor/golang.org/x/crypto/ssh/channel.go:535 +0x88
  golang.org/x/crypto/ssh.(*sessionStdin).Write()
      <autogenerated>:1 +0x87
  github.com/gravitational/teleport/lib/utils.(*PipeNetConn).Write()
      /workspace/lib/utils/pipenetconn.go:56 +0x79
  bufio.(*Writer).Flush()
      /opt/go/src/bufio/bufio.go:607 +0x141
  golang.org/x/crypto/ssh.(*connectionState).writePacket()
      /workspace/vendor/golang.org/x/crypto/ssh/transport.go:182 +0x148
  golang.org/x/crypto/ssh.(*transport).writePacket()
      /workspace/vendor/golang.org/x/crypto/ssh/transport.go:172 +0xbe
  golang.org/x/crypto/ssh.(*handshakeTransport).pushPacket()
      /workspace/vendor/golang.org/x/crypto/ssh/handshake.go:223 +0x52a
  golang.org/x/crypto/ssh.(*handshakeTransport).writePacket()
      /workspace/vendor/golang.org/x/crypto/ssh/handshake.go:516 +0x535
  golang.org/x/crypto/ssh.(*channel).writePacket()
      /workspace/vendor/golang.org/x/crypto/ssh/channel.go:215 +0x12c
  golang.org/x/crypto/ssh.(*channel).sendMessage()
      /workspace/vendor/golang.org/x/crypto/ssh/channel.go:227 +0x211
  golang.org/x/crypto/ssh.(*channel).SendRequest()
      /workspace/vendor/golang.org/x/crypto/ssh/channel.go:586 +0x1bc
  golang.org/x/crypto/ssh.(*Session).RequestPty()
      /workspace/vendor/golang.org/x/crypto/ssh/session.go:209 +0x4f9
  github.com/gravitational/teleport/lib/client.(*NodeSession).allocateTerminal()
      /workspace/lib/client/session.go:299 +0x13a
  github.com/gravitational/teleport/lib/client.(*NodeSession).interactiveSession()
      /workspace/lib/client/session.go:248 +0xf7
  github.com/gravitational/teleport/lib/client.(*NodeSession).runShell()
      /workspace/lib/client/session.go:441 +0x72
  github.com/gravitational/teleport/lib/client.(*TeleportClient).runShell()
      /workspace/lib/client/api.go:1956 +0x24f
  github.com/gravitational/teleport/lib/client.(*TeleportClient).SSH()
      /workspace/lib/client/api.go:1397 +0x5ec
  github.com/gravitational/teleport/integration.testPAM.func1.2()
      /workspace/integration/integration_test.go:3388 +0x34a

Goroutine 318 (running) created at:
  github.com/gravitational/teleport/lib/client.(*NodeSession).pipeInOut()
      /workspace/lib/client/session.go:592 +0x9a
  github.com/gravitational/teleport/lib/client.(*NodeSession).interactiveSession()
      /workspace/lib/client/session.go:271 +0x210
  github.com/gravitational/teleport/lib/client.(*NodeSession).runShell()
      /workspace/lib/client/session.go:441 +0x72
  github.com/gravitational/teleport/lib/client.(*TeleportClient).runShell()
      /workspace/lib/client/api.go:1956 +0x24f
  github.com/gravitational/teleport/lib/client.(*TeleportClient).SSH()
      /workspace/lib/client/api.go:1397 +0x5ec
  github.com/gravitational/teleport/integration.testPAM.func1.2()
      /workspace/integration/integration_test.go:3388 +0x34a
==================
```
This is a naive fix to serialise the write and close operations to resolve the race condition.

The affected tests were also not handling asynchronous error reporting correctly (i.e. it's not legal to call `require.XYZ()` from a goroutine other than the one executing the test function.). This patch introduces some plumbing to marshal asynchronous errors back into the main test routine before failing the test.

This is an incredibly naive way to address the race condition, an i hope that the review process will help bring out a better solution.

### CODE REVIEW

**Review by zmb3 — COMMENTED** [review]
Any thoughts about changing to a `RWMutex` and acquiring a read lock for the `Read` call? Feels odd to synchronize Close/Write and not Read.

**Review by codingllama — COMMENTED** [review]
Hey Trent, sorry for the delay, I meant to get to this one yesterday. Thanks for once again fixing our tests.

I agree with Zac on the RWMutex for PipeNetConn - guarding all operations seems easier to reason about.

In regards to the assertions, I think we can do away with asyncError and asyncAssertion and use plain `error` to communicate what we need - see the suggestions and let me know your thoughts. Ideally we would "simply" run the assertions in the proper goroutine, but I'm assuming that is fairly difficult to achieve.

**Review by tcsc — COMMENTED** [review]
>  Ideally we would "simply" run the assertions in the proper goroutine, but I'm assuming that is fairly difficult to achieve.

In a perfect world, yes. Unfortunately, the go testing package doesn't help us. From [the docs for `testing.T`](https://pkg.go.dev/testing#T):

>> A test ends when its Test function returns or calls any of the methods FailNow, Fatal, Fatalf, SkipNow, Skip, or Skipf. Those methods, as well as the Parallel method, must be called only from the goroutine running the Test function. 

Given that [`testify`](https://github.com/stretchr/testify) is a pretty thin layer over these functions, it doesn't help in this case either.

**Review by codingllama — APPROVED** [review]

**Review by zmb3 — APPROVED** [review]

**Review by russjones — APPROVED** [review]
Bot.

**Pull request merged**
