### PR TITLE
Update READMEs to correct Telekube URL

### PR DESCRIPTION
**Pull request by aberoham**
Google Webmaster Tools on gravitational.com is complaining about being unable to index these dead URLs

### CODE REVIEW

**Comment by russjones** [comment]
@gravitational-jenkins okay to test

**Comment by russjones** [comment]
ok to test

**Review by alex-kovoy — APPROVED** [review]

**Comment by aberoham** [comment]
retest this please

**Comment by aberoham** [comment]
@gravitational-jenkins retest this please

**Comment by klizhentas** [comment]
merged in a separate PR

**Pull request closed without merging**
