### PR TITLE
Preserve roles from user cert when forwarding k8s requests

### LINKED ISSUE #3593: Leaf Cluster not Mapping Approved Roles
### Description
After a user is approved for another role the new role is not mapped when connecting to the leaf cluster. In case of Kubernetes the user then cannot use the approved role on the leaf cluster for their k8s access.

**What happened**:
A user has a limited role in the k8s groups binding with their default roles.  They request and receive approval for a role that maps to a group with k8s exec privilege in a namespace.  Within the cluster they requested the role with the exec privilege works.  After getting approval they have additional privileges within k8s in the cluster.

  When they login to a leaf cluster they only have access to their original default roles. Attempts to use the exec function return errors matching to their role before received approval.

**What you expected to happen**:
When a user logins to a another cluster after receiving approved roles they receive the mapping from those approved roles, not just their default roles.

**How to reproduce it (as minimally and precisely as possible)**:
1. Create a teleport configuration with a leaf cluster
2. Define two k8s roles, role bindings to groups that have different access (ex: one get only list pods and the other can exec sessions)
3. Create two roles in each cluster each matching to the different k8s groups.  One role can request the other role with more privileges.  The roles should map to the leaf cluster with the same privileges.
4. Create a user with the less privileged role and a user with the more privileged role.
5.  Confirm both users have the access expected and denied access with their k8s groups on the trusted and leaf cluster.
6. Have the user request the more privileged role (tsh login --request-roles=<rolename>) on the trusted cluster.
7. Approve the request through tctl
8. Confirm the user now has more k8s access with the approved role session
9. Login to the leaf cluster
10. Attempt the same access

### Environment
- Teleport version (use `teleport version`): Teleport Enterprise v4.2.8git:v4.2.8-0-ga9015b33 go1.13.2

- Tsh version (use `tsh version`): Teleport v4.2.8 git:v4.2.8-0-ga9015b33 go1.13.2
- OS (e.g. from `/etc/os-release`): Ubuntu 18.04.4 LTS

- Where are you running Teleport? (e.g. AWS, GCP, Dedicated Hardware): GKE

**Relevant Debug Logs If Applicable**

These logs show a user not getting the mapped role they were approved after getting approved from the trusted cluster.  A user that has the devadminrole was confirmed to work on the leaf cluster through the trusted cluster mapping.

Original tsh status after logging into the trusted cluster:
```
 Profile URL:  https://mdem428-dev
  Logged in as: stevendev
  Cluster:      mdem428-dev
  Roles:        devrole*
  Logins:       devuser
  Valid until:  2020-04-16 11:32:40 -0400 EDT [valid for 12h0m0s]
  Extensions:   permit-agent-forwarding, permit-pty
```

 tsh status after getting approved for devadminrole and logging into leaf cluster
```
> Profile URL:  https://mdem428-dev
  Logged in as: stevendev
  Cluster:      mdem428-test
  Roles:        devadminrole, devrole*
  Logins:       devuser, devadminuser, root2
  Valid until:  2020-04-16 11:32:40 -0400 EDT [valid for 11h53m0s]
  Extensions:   permit-agent-forwarding, permit-pty
```

- Leaf cluster when a k8s exec is attempted.  The testadminrole (mapped from devadminrole) is missing.
```
DEBU [AUTH]      Mapped roles [devrole] of remote user "stevendev" to local roles [testrole] and traits map[kubernetes_groups:[developer-oncall] kubernetes_users:[] logins:[]]. auth/permissions.go:161
DEBU [PROXY:KUB] Exec /api/v1/namespaces/prd/pods/nginx-65f88748fd-2v7hn/exec?command=bash&container=nginx&stdin=true&stdout=true&tty=true. proxy/forwarder.go:443
```

Error received through leaf cluster after attempting exec:
`error: Internal error occurred: error executing command in container: Internal error occurred: error executing command in container: pods "nginx-65f88748fd-2v7hn" is forbidden: User "remote-stevendevl.com-mdem428-dev.gravitational.co" cannot create resource "pods/exec" in API group "" in the namespace "prd"`

### PR DESCRIPTION
**Pull request by awly**
When a proxy forwards a k8s request to another proxy in a trusted leaf
cluster, it dynamically generates a new client key/cert to impersonate
the user. This key/cert is presented to the leaf proxy as if a user was
directly making a request to it.

Auth server, when processing the CSR, would load user identity from the
backend. If this user had temporary role grants via workflow API, they
would **not** be loaded from the backend.

This means that if a user accesses k8s through:
```
kubectl -1-> root proxy -2-> leaf proxy -3-> k8s
```
the 2nd hop would drop their temporary role grants.

To fix this, preserve full user identity from the original client cert
presented to root proxy, as encoded in CSR Subject. The auth server
_implicitly_ trusts the CSR Subject that the proxy presents.
This also requires fixing the Subject encoding on the proxy side, which
was inconsistent with how auth server does it.

One possible downside here is: a compromised proxy can mint k8s client certs for
arbitrary users with arbitrary (but existing) roles.

Fixes #3593

### CODE REVIEW

**Review by webvictim — APPROVED** [review]
This is great. Please wait for others before merging though.

**Comment by russjones** [comment]
@awly I don't suppose `kubeconfig` supports configuration which would allow us to use SNI to solve this problem? If it did, we could just connect the client and target proxy directly instead of going through certificate re-issue.

**Comment by awly** [comment]
@russjones interesting idea!
I believe `kubectl` uses the standard `crypto/tls` under the hood. `crypto/tls` always sends SNI unless `InsecureSkipVerify` is set or if `ServerName` contains an IP.

If we used SNI, it wouldn't work with:
- proxies sharing the same hostname (using different ports)
- root proxies that only have a public IP and not a hostname

which could be fine, but it's an awkward caveat to document

**Comment by webvictim** [comment]
A lot of people's Teleport PoCs/trials don't use domains set up with proper TLS at all, they're using IP addresses and `--insecure`. It would almost certainly make that sort of use case harder.

**Comment by fspmarshall** [comment]
Since this fix relies on updated proxy behavior, version compatibility is a concern.  The auth server should fallback to the old strategy if it doesn't receive any roles from the proxy.  You can add a `// DELETE IN: 5.0` directive to the fallback logic.

> One possible downside here is: a compromised proxy can mint k8s client certs for
> arbitrary users with arbitrary (but existing) roles.

If a certificate was constructed in part based on access requests, the request IDs _are_ preserved under the [`teleport-active-requests`](https://github.com/gravitational/teleport/blob/c8c49d4721b14069db71631fa89e2f73233e218e/lib/auth/native/native.go#L299) extension.  The extension is currently only used by `tsh`, but it exists and could technically be used to solve this problem. Doesn't prevent a malicious proxy from deciding to impersonate a _different_ user though, so its an open question whether the extra complexity is worth it.  Also, keeping the user's cert as the source of truth is more consistent with how teleport operates everywhere else.

**Comment by awly** [comment]
> A lot of people's Teleport PoCs/trials don't use domains set up with proper TLS at all, they're using IP addresses and --insecure. It would almost certainly make that sort of use case harder.

@webvictim  _would_ or _wouldn't_ make it harder? I imagine we want to make trying the product easy but ensure that prod setups use good security practices.

> Since this fix relies on updated proxy behavior, version compatibility is a concern. The auth server should fallback to the old strategy if it doesn't receive any roles from the proxy.

@fspmarshall ahh, good catch. I'll add some heuristic in auth server to detect a CSR from older proxy and fall back to manually producing the Subject. Stand by.

**Comment by webvictim** [comment]
> @webvictim _would_ or _wouldn't_ make it harder? I imagine we want to make trying the product easy but ensure that prod setups use good security practices.

I suppose it wouldn't really make it harder. I agree with your overall assessment - an easyish trial but great production setup is exactly we want to do. Trialling the product without using DNS and valid TLS certs is already a tricky experience so it's unlikely to make a lot of difference.

**Comment by awly** [comment]
@klizhentas @russjones added `UsageKubeOnly` enforcement as we discussed.

**Review by russjones — APPROVED** [review]

**Pull request merged**
