### PR TITLE
Sasha/bench

### PR DESCRIPTION
**Pull request by klizhentas**
## Purpose

add benchmark tool and fix concurrent DeleteBucket

## Details

* Add bench tool and library functions
* Fix concurrent DeleteBucket problem refs #931

```bash
# generate requests at 100 requests per second
# for 30 seconds
# using pool of 10 concurrent threads
tsh bench --rate=100 --duration=30s --threads=10 127.0.0.1 ls -l /
```

### CODE REVIEW

**Comment by klizhentas** [comment]
retest this please

**Comment by kontsevoy** [comment]
love the bench. no questions about the code. one ask: can we please make `bench` command hidden/undocumented. it competes with core commands like `ssh` and `scp` for user attention when tsh help runs. thx.

**Comment by klizhentas** [comment]
retest this please

**Review by russjones — APPROVED** [review]

**Comment by russjones** [comment]
@gravitational-jenkins test this please

**Comment by russjones** [comment]
@gravitational-jenkins retest this please

**Pull request merged**
