### PR TITLE
Implement new typography (H3, H4 header levels; paragraphs, body styles)

### LINKED ISSUE #44052: Implement new typography
[Typography](https://www.figma.com/file/Gpjs9vjhzUKF1GDbeG9JGE/Application-Design-System?type=design&node-id=6868-38183&mode=design&t=lfboeNMENiqaZygH-4): Requires a complete overhaul of text throughout the product to unify sizes and styles and to improve accessibility.

Additional scope: remove horizontal bars below the feature headers.

### PR DESCRIPTION
**Pull request by bl-nero**
This PR finalizes the implementation of new typography. It sets the new default typography, but doesn't refactor all of our UI; I limited myself to:
- places that previously specified affected typography classes explicitly
- the Discovery features, which were revamped comprehensively, as they are content-heavy and could benefit from internal consistency.

Since there seems to be no consensus on heading margins, I skipped that part, focusing mostly on font sizes and consistent usage of various classes.

Along with standardizing the new typography, this PR adds new tools that should make it easier to consistently apply it throughout the UI in future:
- semantic heading components for `H3` and `H4` headings
- semantic `P` component with support for intra-paragraph spacing (but only for scenarios where it's unambiguously needed)
- `P1`-`P3` convenience wrappers for applying `bodyN` classes to paragraph text
- `Subheading1`-`Subheading3` convenience wrappers for applying `subheadingN` classes.

There's a [living document in Notion](https://www.notion.so/goteleport/Typography-5c39e8571ca9447f9354043beb2cb7e8) that contains my guidelines for the new components and typography; I'll subsequently move it to this repo.

A couple of random screenshots:

Screenshot 2024-07-22 at 14 20 09

Screenshot 2024-07-23 at 09 57 49

Screenshot 2024-07-23 at 10 42 37

Screenshot 2024-07-22 at 14 17 38

Screenshot 2024-07-22 at 14 21 00

This PR needs to be merged together with https://github.com/gravitational/teleport.e/pull/4729.

Closes https://github.com/gravitational/teleport/issues/44052

### CODE REVIEW

**Comment by bl-nero** [comment]
Note for reviewers: for your convenience, the PR is split into 2 separate commits: one for code, one for snapshots.

**Comment by bl-nero** [comment]
In response to feedback from @roraback, I changed the resource enrollment workflow headings and updated the screenshots.

**Review by zmb3 — APPROVED** [review]

**Review by ryanclark — APPROVED** [review]

**Comment by gzdunek** [comment]
My early feedback is that I feel we are overusing light font weight. I'm clicking through Connect and most of the places seem to use now `font-weight: 300` (the difference is better visible if you zoom in):
| font-weight: 300  | font-weight: 400 |
| ------------- | ------------- |
| image  | image |
| image  | image |
| image | image  |

In my opinion we should by default use 400 because:
- it's considered a ["normal" font weight](https://developer.mozilla.org/en-US/docs/Web/CSS/@font-face/font-weight#norma)
- [it improves readability](https://ux.stackexchange.com/a/52972)
- does not cause too much constrast when used next to 700 (it's especially visible in the Connect My Computer screen)

**Comment by bl-nero** [comment]
@roraback What do you think about what Grzegorz wrote above?

**Comment by roraback** [comment]
I see a few things happening here:
1. We intended anything <14px to be 400 weight, but I'm seeing some 12px text with 300 weight, particularly in some of the form labels
2. (My fault) We reduced the line-height of the Body 2 text from 24px to 20px. This has a significant impact on readability - Let's bump it back up to 24px.
3. As for legibility of lightweight fonts, that's more of a mixed bag. Yes, excessively lightweight fonts are less legible when rendered poorly, but that doesn't mean that a "light" font is inherently less legible than a "normal" font. It [depends on how well the font is rendered,](https://jdobr.es/pdf/Dobres-etal-2016-Auto-UI.pdf) and rendering (for web) is largely a function of the size of the font and the pixel density of the display. In fact, some research has indicated that lightweight fonts are _more_ legible when well rendered (see link above)—the key detail being the quality of the rendering. It is my intention that anything below 14px is at least 400 weight, because below 14px the stroke of the 300 weight falls below 1px wide, which starts to significantly decrease legibility on standard density monitors.

   * _That said,_ there is some gray area as far as knowing where font weights become more/less legible on standard-density monitors. I'm open to bumping our 14px font (Body 2) up to 400 weight if the line height adjustments feel insufficient.

5. Ubuntu is naturally heavier than many fonts used for body copy. For example, note how much darker/heavier the text looks in the final paragraph of this webpage about typography, where I've substituted Ubuntu and made no other changes.
image

**Comment by gzdunek** [comment]
>Ubuntu is naturally heavier than many fonts used for body copy. For example, note how much darker/heavier the text looks in the final paragraph of this webpage about typography, where I've substituted Ubuntu and made no other changes.

Yeah I can see that, although for body text, 400 doesn't look bad to me.

And there is one more thing: in Connect we use `font-family: system-ui`. This means using San Francisco on macOS, Segoe UI on Windows and Ubuntu on Ubuntu (this aligns the app better with the system, vscode also does this). 
From my testing, after changing Body 2 to 400 the text looks better in Connect and still good in Web UI.
So if you use a more “standard” font weight, there is a better chance that it will look good when rendered in a different font.

**Comment by bl-nero** [comment]
What @gzdunek wrote sounds rational, but I can't deny that the more I'm looking at the lighter version, the more I like it, both on web and Connect. @roraback, will you break this tie? I'll send you a Connect binary.

**Comment by bl-nero** [comment]
Since I haven't heard back, I'm merging this PR as is; we can switch to 400 afterwards, if that's needed. (This should be a simple change, though it requires changing the table and navigation styles.)

**Pull request merged**
