### PR TITLE
[v7] Backport add ExactKey function to create absolute storage paths

### PR DESCRIPTION
**Pull request by capnspacehook**
Backport of #12464.

### CODE REVIEW

**Review by Tener — COMMENTED** [review]
Only 3 files changed, and looks like linter is unhappy (rightfully?).

**Comment by capnspacehook** [comment]
Yeah think I messed up fixing merge conflicts

**Review by rosstimothy — APPROVED** [review]

**Review by Tener — CHANGES_REQUESTED** [review]
Would it be possible to backport at least the affected test in `lib/services/local/users_test.go` ? 

More importantly: looks like `lib/services/local/usertoken.go` *does* exist on v7 as `lib/services/local/resetpasswordtoken.go`. Please check if we shouldn't be changing that one instead.

**Comment by zmb3** [comment]
@capnspacehook are we still planning on addressing this one?

**Comment by capnspacehook** [comment]
I don't think so, Teleport 7 isn't supported now that 10 is out, and this was backported to 8 and 9 so I think it's safe to close this.

**Pull request closed without merging**
