### PR TITLE
Fixed domain_name concatenation on cluster.tf

### PR DESCRIPTION
**Pull request by Valien**
In the current `starter-cluster` folder there is a `cluster.tf` file and if run as it is, it will not concatenate the FQDN of the cluster. I added some additional Terraform formatting options so that the FQDN gets built properly.

### CODE REVIEW

**Comment by russjones** [comment]
@webvictim Can you review?

**Review by webvictim — CHANGES_REQUESTED** [review]
If you look at https://github.com/gravitational/teleport/blame/master/examples/aws/terraform/starter-cluster/README.md#L96 the intention appears to be that the `route53_domain_name` variable should be specified as an FQDN already - i.e. `cluster.example.com`.

This PR would change this to concatenate that twice, so the variable would become `cluster.example.com.example.com` (as I understand it)

What prompted this change?

**Comment by Valien** [comment]
Hey @webvictim  - So when I ran the starter-cluster it was only putting in my subdomain in the build and Teleport configuration files. When I tried to add the FQDN in both places it made it similar to your example above. 

So I added the concatenation logic and it solved my problem. I thought I tested all the edge cases but might have missed something. I'll tear down my cluster tomorrow and test it again and see what my results look like and will update this issue.

**Comment by webvictim** [comment]
This may also be an issue with the mapping from the Terraform variables through to the [`teleport-generate-config`](https://github.com/gravitational/teleport/blob/master/assets/aws/files/bin/teleport-generate-config) script.

Some other things that would be helpful for debugging this:
- the output of `journalctl -u teleport-generate-config`
- the contents of `/etc/teleport.yaml`
- the contents of `/etc/teleport.d/conf`
- `ls -l /etc/teleport.d`

Thanks!

**Comment by Valien** [comment]
Ok @webvictim - did some more testing and the `starter-cluster` works as intended. Going to close this PR. I must have messed something up when I was building it out the other day and made changes in other areas of my `Makefile` and then didn't revert them. I think I had misread the `TF_VAR_router53_domain` and only put in my subdomain vs the FQDN of the cluster.

Thanks for getting a 2nd set of eyes on this issue though! If I encounter anything else down the road I'll reopen/comment on this PR.

One thing, if a user does only put in the subdomain instead of the FQDN then the Terraform logic will concatenate it together, but you are right in that if a user puts in the FQDN for the subdomain it will make it `subdomain.aaa.com.aaa.com`.

**Pull request closed without merging**
