### PR TITLE
Update Connect icons

### PR DESCRIPTION
**Pull request by gzdunek**
The new icons were prepared with Kenny's help. We decided to move away from using (almost) the same icon for Windows and macOS, but to adapt it more to the platform guidelines. As a result, now we have a circle icon for Windows and Linux.

macOS
image

Windows
image

Linux
image

Should be backported just before 16.1.

@zmb3 if I'm correct, the only other icon to update is the one for `teleport-windows-auth` in e, right?

### CODE REVIEW

**Review by zmb3 — APPROVED** [review]
That's correct.

**Comment by gzdunek** [comment]
>the only other icon to update is the one for teleport-windows-auth in e, right?

Actually, there's also `icon.bmp` there, I will update it too.

**Comment by zmb3** [comment]
> Actually, there's also icon.bmp there, I will update it too.

Oh yeah, we do need a new icon for that, but it needs to be gray and white like the existing icon.

**Comment by zmb3** [comment]
I imagine we will backport this to 14 and 15 as well, with the same caveat - don't merge backports until we're ready to release 16.1.

**Review by ravicious — APPROVED** [review]
Looks cool! I ran them through ImageOptim to reduce the image size even further.

**Comment by gzdunek** [comment]
>I ran them through ImageOptim to reduce the image size even further.

Thank you!

**Pull request merged**
