### PR TITLE
modify naming scheme to be compatible with ssh-add

### PR DESCRIPTION
**Pull request by klizhentas**
**Purpose**

Change key and certificate file names to match what OpenSSH generates for interoperability.

**Implementation**

```
<identity>.cert -> <identity>-cert.pub
<identity>.key  -> <identity>
<identity>.pub  -> <identity>.pub
```

### CODE REVIEW

**Comment by russjones** [comment]
lgtm, only one issue, the extensions need to be updated here as well: https://github.com/gravitational/teleport/blob/master/lib/client/keystore.go#L41-L43

**Comment by klizhentas** [comment]
I this is out of the scope of this PR, but generally good point, can you create a separate issue about this?

**Comment by russjones** [comment]
@klizhentas Sure.

**Review by russjones — APPROVED** [review]

**Review by kontsevoy — APPROVED** [review]

**Comment by klizhentas** [comment]
retest this please

**Comment by klizhentas** [comment]
retest this please

**Comment by klizhentas** [comment]
retest this please

**Pull request merged**
