### PR TITLE
revendor golang ssh lib

### PR DESCRIPTION
**Pull request by aberoham**
Per request of Cove

### CODE REVIEW

**Comment by russjones** [comment]
@gravitational-jenkins okay to test

**Comment by russjones** [comment]
ok to test

**Review by russjones — APPROVED** [review]

**Comment by klizhentas** [comment]
@russjones when mergin gmake sure the merge commit is gone and you rebased (spotted merge commit added a recently)

**Comment by russjones** [comment]
@aberoham :tada:

**Pull request merged**
