### PR TITLE
add support for dynamodb backups in helm chart

### PR DESCRIPTION
**Pull request by timothy-spencer**

### CODE REVIEW

**Comment by russjones** [comment]
@webvictim Can you review?

**Comment by webvictim** [comment]
Looks OK to me.

@timothy-spencer Two things:
1) Please add this value to the Helm chart reference at https://github.com/gravitational/teleport/blob/master/docs/pages/kubernetes-access/helm/reference.mdx so it's kept up to date.

2) Please add the value into https://github.com/gravitational/teleport/blob/master/examples/chart/teleport-cluster/values.schema.json so it can be validated by Helm.

Thanks for the PR!

**Review by webvictim — CHANGES_REQUESTED** [review]
General idea looks fine to me.

@timothy-spencer Two things:
1) Please add this value to the Helm chart reference at https://github.com/gravitational/teleport/blob/master/docs/pages/kubernetes-access/helm/reference.mdx so it's kept up to date.

2) Please add the value into https://github.com/gravitational/teleport/blob/master/examples/chart/teleport-cluster/values.schema.json so it can be validated by Helm.

Thanks for the PR!

**Comment by timothy-spencer** [comment]
@webvictim, I plugged in the changes you requested.  Thanks for catching that, and let me know how it looks!

**Review by webvictim — APPROVED** [review]

**Review by klizhentas — APPROVED** [review]

**Pull request merged**
