### PR TITLE
Lint markdown files syntax for master with the new linter

### PR DESCRIPTION
**Pull request by iAdramelk**
Upd: Added Microsoft link to whitelist and remove releases table

### CODE REVIEW

**Comment by klizhentas** [comment]
Please escape:

http://schemas.microsoft.com/ws/2008/06/identity/claims/windowsaccountname"

and remove the obsolete downloads table

**Comment by iAdramelk** [comment]
Upd: Added Microsoft link to whitelist and remove releases table. Please check: https://github.com/gravitational/teleport/commit/3db556c1f946abe420ae66dd6073d2deb211a9b5

**Review by klizhentas — APPROVED** [review]

**Comment by klizhentas** [comment]
@iAdramelk please rebase and let's merge

**Comment by iAdramelk** [comment]
@klizhentas done

**Pull request merged**
