### PR TITLE
Fix inventory controller tests after adding additional ping

### PR DESCRIPTION
**Pull request by vapopov**
Fix for the inventory controller tests identified by flaky tests detector https://github.com/gravitational/teleport.e/actions/runs/12116931575/job/33778324175

After adding additional ping for time reconciliation, many tests which don't have downstream consumer, or consumers expecting only one ping request start failing

Tested with
```bash
inventory % go test . -v -count 500 -race -timeout 0 -failfast
...
ok  	github.com/gravitational/teleport/lib/inventory	1534.162s
```

Related: https://github.com/gravitational/teleport/pull/44489

### CODE REVIEW

**Comment by vapopov** [comment]
@rosstimothy fixed, interesting that I wasn't able to reproduce in darwin platform

```bash
root@3e255c82fc04:/go/teleport/lib/inventory# go test . -v -count 1000 -race -timeout 0 -failfast -run "TestTimeReconciliation"
PASS
ok  	github.com/gravitational/teleport/lib/inventory	110.439s
```
Took a while to debug, there were two issues, one was related to test only in this line:  https://github.com/gravitational/teleport/pull/49663/files#diff-0559b6dbb369be5e2e76ed5a7248e6d882b7229d9a6eb4128b350ddddc6d207eL1491

Since we have variable timer, and when value of the first duration is very small like 2ms or less might happen that heartbeat executed before ping request and this `return` actually stops receiving messages by downstream, as result next ping request blocks inventory controller stream.

Second one test event signals about time reconciliation is done, but we only send ping request and didn't wait response

**Comment by vapopov** [comment]
@rosstimothy could you please ensure that it was last commit, because it more looks like error of previous version, current line 1543 https://github.com/gravitational/teleport/blob/4a723251432abb3ee66e68d5c878353e4620cf32/lib/inventory/controller_test.go#L1543

**Comment by vapopov** [comment]
Results from linux container
```bash
root@3e255c82fc04:/go/teleport/lib/inventory# go test . -v -count 1000 -race -timeout 0 -failfast
ok  	github.com/gravitational/teleport/lib/inventory	3078.046s
```

**Review by rosstimothy — APPROVED** [review]
After rebuilding the test binary I've not seen a failure in over an hour.

**Review by zmb3 — APPROVED** [review]

**Pull request merged**
