### PR TITLE
Fixed anti-pattern use of /var/run as the PID dir

### PR DESCRIPTION
**Pull request by eldios**
Fixed anti-pattern use of /var/run as the PID dir

### CODE REVIEW

**Comment by benarent** [comment]
Hey @eldios,  Can you explain a bit more about how this is an anti-pattern? Just for my own reference.

**Comment by webvictim** [comment]
Most modern distros link /var/run to /run anyway so the actual effect of this is quite minimal, but it's definitely nice to be correct!

```
$ ls -ld /var/run
lrwxrwxrwx. 1 root root 6 Nov  5  2017 /var/run -> ../run
```

**Comment by webvictim** [comment]
ok to test

**Comment by eldios** [comment]
https://lwn.net/Articles/436012/

**Comment by eldios** [comment]
@benarent it's all explained in there and now latest version of systemd raise an alert every time you start a unit which uses /var/run

**Comment by benarent** [comment]
@eldios Thank you.

**Review by benarent — APPROVED** [review]

**Pull request merged**
