### PR TITLE
charts/teleport-cluster: configurable podSecurityContext

### LINKED ISSUE #38138: charts/teleport-cluster: configurable podSecurityContext
I'd like to be able to configure the pod security context for the auth and proxy deployments. In restrictive environments this could be helpful where for example the container user does not have write permissions on pod volumes by default and requires to set the `fsGroup` parameter in the pod security context.

### PR DESCRIPTION
**Pull request by AuditeMarlow**
Changelog: Make the podSecurityPolicy configurable in the `teleport-cluster` chart.

In some setups like OpenShift, the Kubernetes distribution has constraints on the UID/GID ranges of the container. To run in such setups, the user might have to change/unset the `fsGroup`.

Resolves #38138.

### CODE REVIEW

**Review by hugoShaka — CHANGES_REQUESTED** [review]
Thank you for your contribution,

To ensure backward compatibility and avoid bugs we require every Helm chart feature to be tested and documented.
The contribution guidelines describe how to add tests and documentation: https://github.com/gravitational/teleport/blob/master/examples/chart/CONTRIBUTING.md

Once the PR has tests and docs, please ping us for a second review.

**Comment by hugoShaka** [comment]
Thank you for adding the tests, this looks good :)

The chart reference lives in `docs/pages/reference/helm-reference/teleport-cluster.mdx`. It is not yet generated from the values.yaml so you still have to manually edit the file to add a section with your new value and paste the same description as the one you put in the `values.yaml`.

**Comment by AuditeMarlow** [comment]
Thank you so much @hugoShaka! I was able to add the required documentation. I think that completes the PR as per the contributing guidelines unless there's something I'm still missing, which I'll be happy to add.

**Comment by hugoShaka** [comment]
Thanks for your contribution. We are currently unable to run our tests on external contributions. As such, I'll be helping you validate and merge your pull request. I've created an internal PR here: https://github.com/gravitational/teleport/pull/40945

Please wait and I'll get your code merged and backported. You will retain authorship of your commits.

**Comment by hugoShaka** [comment]
Merged in https://github.com/gravitational/teleport/pull/40945

**Pull request closed without merging**
