### PR TITLE
Add `GetEmitter()` to allow proper emitter wrapping for PreHog

### PR DESCRIPTION
**Pull request by timothyb89**
This is part of a fix for the PreHog usage reporter to resolve a bug where an improper emitter implementation was wrapped, potentially replacing a valid set of emitters. A new `GetEmitter` function is added to `Server` to allow fetching of the correct implementation so it can be wrapped overwritten sensibly.

Additionally, this changes the signature of `UsageLogger.New()` to require just an `events.Emitter` interface rather than an `IAuditLog` specifically.

Finally, this fixes a small bug in the PreHog submitter where failed events were accidentally dropped too early.

Co-authored-by: Roman Tkachenko <roman@goteleport.com>

### CODE REVIEW

**Review by r0mant — APPROVED** [review]

**Review by zmb3 — COMMENTED** [review]
Are you submitting the other half of the fix that uses this in a separate PR?

Edit: I see the e PR now. Just want to make sure this doesn't trigger a data race. The get/set have no synchronization so they can only safely be used by the main goroutine.

**Comment by timothyb89** [comment]
> Are you submitting the other half of the fix that uses this in a separate PR?

Yup: https://github.com/gravitational/teleport.e/pull/660

**Comment by timothyb89** [comment]
Just want to make sure this doesn't trigger a data race. The get/set have no synchronization so they can only safely be used by the main goroutine.

Hrm. It's definitely naughty. 

I'm not sure what the best solution is for that. We have some 200 accesses directly to `.emitter` since all audit log writes just reference it directly. Time to find and replace with `GetEmitter()`?

**Comment by zmb3** [comment]
For now I’m happy if you just build with -race and verify that noting
trips.

**Comment by timothyb89** [comment]
> For now I’m happy if you just build with -race and verify that noting trips.

It runs fine with `-race`, though I'm still pretty sure it's evil (if nothing else someone will eventually want to call `SetEmitter()` later under less safe-ish conditions).

**Review by espadolini — APPROVED** [review]
We should add some extra warning to `SetEmitter` but the same concerns apply to `SetAuditLog`, `SetEnforcer` and `SetUsageReporter`, which are all used by enterprise in the various flavors of `NewTeleport`, _before_ the process is `Start`ed. From what I can tell, nothing accesses the emitter before the process starts.

**Pull request merged**
