### PR TITLE
fix: incorrectly placed provision token name

### PR DESCRIPTION
**Pull request by gardar**
name is part of metadata not spec

### CODE REVIEW

**Review by zmb3 — APPROVED** [review]

**Review by hugoShaka — APPROVED** [review]

**Comment by zmb3** [comment]
@gardar looks like this does not pass linter due to white space formatting

**Comment by hugoShaka** [comment]
You can run `terraform fmt examples/agent-pool-terraform/teleport/token.tf` to automatically format the file

**Comment by gardar** [comment]
> @gardar looks like this does not pass linter due to white space formatting

Oh! Looks like good ol' trusty vim `dd` + `p` didn't suffice this time :)

> You can run `terraform fmt examples/agent-pool-terraform/teleport/token.tf` to automatically format the file.

Good tip, thanks!

**Review by russjones — APPROVED** [review]

**Comment by zmb3** [comment]
I've created a buddy PR over at #39415 to get this through CI. You will retain authorship of the commit.

**Pull request closed without merging**
