### PR TITLE
Fix an issue DB rotation event get send to older remote cluster

### LINKED ISSUE #13793: v9 leaf clusters with a v10 root are malfunctioning because of `db` authority
Expected behavior:
Adding a v9 leaf to a v10 cluster (or rather, adding a v10 root to a v9 cluster) works without errors.

Current behavior:
The root proxy logs errors like 
```
{"caller":"cache/cache.go:772","component":"reverse:child9.wet-dry.world:1:cache","level":"warning","message":"Re-init the cache on error: 'db' authority type is not supported.","timestamp":"2022-06-23T14:55:39+02:00"}
{"caller":"cache/cache.go:772","component":"reverse:child9.wet-dry.world:1:cache","level":"warning","message":"Re-init the cache on error: 'db' authority type is not supported.","timestamp":"2022-06-23T14:55:49+02:00"}
{"caller":"reversetunnel/remotesite.go:550","component":null,"error":"'db' authority type is not supported","level":"warning","message":"Failed to rotate external ca","timestamp":"2022-06-23T14:56:14+02:00"}
{"caller":"reversetunnel/remotesite.go:475","component":"proxy:server","level":"warning","message":"Could not perform cert authorities update: \nERROR REPORT:\nOriginal Error: *trace.BadParameterError \u0026#39;db\u0026#39; authority type is not supported\nStack Trace:\n\nCaught:\n\t/Users/espadolini/teleport/lib/httplib/httplib.go:167 github.com/gravitational/teleport/lib/httplib.ConvertResponse\n\t/Users/espadolini/teleport/lib/auth/clt.go:247 github.com/gravitational/teleport/lib/auth.(*Client).PostJSON\n\t/Users/espadolini/teleport/lib/auth/clt.go:382 github.com/gravitational/teleport/lib/auth.(*Client).RotateExternalCertAuthority\n\t/Users/espadolini/teleport/lib/reversetunnel/remotesite.go:549 github.com/gravitational/teleport/lib/reversetunnel.(*remoteSite).watchCertAuthorities\n\t/Users/espadolini/teleport/lib/reversetunnel/remotesite.go:463 github.com/gravitational/teleport/lib/reversetunnel.(*remoteSite).updateCertAuthorities\n\t/Users/espadolini/teleport/lib/reversetunnel/srv.go:1165 github.com/gravitational/teleport/lib/reversetunnel.newRemoteSite.func2\n\t/usr/local/go/src/runtime/asm_arm64.s:1263 runtime.goexit\nUser Message: \u0026#39;db\u0026#39; authority type is not supported\n.","timestamp":"2022-06-23T14:56:14+02:00","trace.fields":{"cluster":"child9.wet-dry.world"}}
{"caller":"cache/cache.go:772","component":"reverse:child9.wet-dry.world:1:cache","level":"warning","message":"Re-init the cache on error: 'db' authority type is not supported.","timestamp":"2022-06-23T14:56:16+02:00"}
{"caller":"cache/cache.go:772","component":"reverse:child9.wet-dry.world:1:cache","level":"warning","message":"Re-init the cache on error: 'db' authority type is not supported.","timestamp":"2022-06-23T14:56:51+02:00"}
```

Bug details:
- Teleport version: v10.0.0-alpha.2 (b58c843dd986336b70bd8bc07ca9cd96401d3363) root and v9.3.7 leaf
- Recreation steps: try to join a v9 leaf to a v10 root

### PR DESCRIPTION
**Pull request by greedy52**
Fixes #13793
- #13793 

Regression of https://github.com/gravitational/teleport/pull/12040

Setup:
- v10 root cluster
- v9 remote cluster

What happened:
- At root cluster
  - v9 remote cluster is identified
  - [Subscribing/Watching](https://github.com/gravitational/teleport/blob/8cb7522aabaa4fdae996269f73a0fe51b59f73de/lib/reversetunnel/remotesite.go#L496) **local** `types.KindCertAuthority` with subkind `host` and `user` events for this remote cluster. Note we are NOT subscribing subkind `db` events as we know the remote is old.
  - Unfortunately, `CertAuthorityWatcher` currently does NOT filter by `SubKind`. Local `db` event is emitted by the watcher, then it eventually reaches the remote cluster.

This PR now uses the new CertAuthorityFilter for filtering by CA types.

## testing
Tested this PR together with https://github.com/gravitational/teleport/pull/13871
Verified db access through root cluster working at standby, after remote cluster rotation, and after root cluster rotation.
Verified original error no long occurred.

### CODE REVIEW

**Comment by espadolini** [comment]
There's already "smart" filtering in place for `CertAuthority` which is available in 9.0.0 and later (which are the only two versions we have to deal with, for the purpose of the database CA); I'd rather make it so that we start using that in `CertAuthorityWatcher` without using `SubKind` (which is already abused for app/web/snowflake websessions, and would imply having to send multiple `WatchKind`s to watch multiple types of CA which in turn has other effects in the cache fanout mechanism).

**Comment by greedy52** [comment]
@espadolini thanks! switched to the "smart" filter.

**Comment by hugoShaka** [comment]
I encountered the same issue during v9/v10 migration tests and tested this branch against the broken setup.

After updating both auth and proxy nodes (keeping their state from v10.0.0-alpha2) I still get the error in proxy's logs.

```
Jun 28 20:48:50 proxy teleport[6473]: 2022-06-28T20:48:50Z INFO [PROXY:SER] Connection <- 192.168.56.50:58955, clusters: 1. cluster:kube reversetunnel/srv.go:926
Jun 28 20:48:53 proxy teleport[6473]: 2022-06-28T20:48:53Z WARN [REVERSE:K] Re-init the cache on error: 'db' authority type is not supported. cache/cache.go:772
Jun 28 20:49:01 proxy teleport[6473]: 2022-06-28T20:49:01Z WARN [REVERSE:K] Re-init the cache on error: 'db' authority type is not supported. cache/cache.go:772
^C
root@proxy:~# teleport version
Teleport v11.0.0-dev git:v10.0.0-dev.david.1-70-g57fd048de go1.18.1
```

Is this behaviour expected? Should I flush the proxy state and re-join the cluster?

**Comment by greedy52** [comment]
> #13871

@hugoShaka see https://github.com/gravitational/teleport/pull/13871

**Review by smallinsky — APPROVED** [review]

**Review by espadolini — COMMENTED** [review]
Can't we just have `(*caCollector).Subscribe` take a `types.CertAuthorityFilter` instead? All of our uses of `Subscribe` on `CertAuthorityWatcher` would be compatible with just zero or one of those (`nil` is a valid catch-all `CertAuthorityFilter`), and with that change you can just use `(CertAuthorityFilter).IntoMap` to configure a `WatchKind`'s filter.

**Comment by greedy52** [comment]
> Can't we just have `(*caCollector).Subscribe` take a `types.CertAuthorityFilter` instead? All of our uses of `Subscribe` on `CertAuthorityWatcher` would be compatible with just zero or one of those (`nil` is a valid catch-all `CertAuthorityFilter`), and with that change you can just use `(CertAuthorityFilter).IntoMap` to configure a `WatchKind`'s filter.

@espadolini `types.CertAuthorityFilter` only applies for `OpPut`. Without the cluster name in the watch, other types can get through. What do you think?

**Review by espadolini — APPROVED** [review]

**Pull request merged**
