### PR TITLE
Add support for multi-arch Docker images

### LINKED ISSUE #3384: Request: ARM container builds
This is a request to provide ARM container builds on quay.io.  Quay now supports multi-arch container manifests (anouncement [here](https://www.redhat.com/en/blog/introducing-red-hat-quay-3-registry-your-linux-and-windows-containers)).

NOTE: This is related to my personal use of Teleport Community Edition, not my employer's use of Teleport Enterprise.

### PR DESCRIPTION
**Pull request by webvictim**
Fixes #3384 

This PR:
- adds support for building `arm` and `arm64` Docker images using processors with `amd64` architecture
  - this is done using the `binfmt_misc` kernel extension which automatically detects the ELF 'magic' for binaries from other architectures and uses [`qemu-user-static`](https://github.com/multiarch/qemu-user-static) to emulate the correct CPU and run them
- adds support for multi-arch Docker manifests
  - essentially this means there is one image/tag name which has 3 different images behind it (`amd64`, `arm` and `arm64`)
  - the correct image for the host architecture will be picked by the Docker daemon when the image is pulled
- tidies up buildbox and image `Dockerfiles` by sorting them more logically\
- removes the separate FIPS `Dockerfiles` in favour of a multi-stage Docker build which optionally overrides the `ENTRYPOINT` for FIPS images (we were already using this for `teleport-docker-cron`)
- removes separate `release-arm` and `release-arm64` steps in favour of automatically deducing the correct arch from the supplied `ARCH` variable
  - this will cut down on boilerplate and make it a little easier to add support for more architectures in future

Still to come:
- a separate PR for updating the nightly `teleport-docker-cron` images which are produced by Drone
  - the logic changes are quite complicated and I didn't want to overcomplicate this PR

### CODE REVIEW

**Comment by benarent** [comment]
This PR will be really helpful for a project I'm working on. Commenting with enthusiasm and to watch this PR

**Comment by benarent** [comment]
Another thing I found out, when we publish the different version Quay provides this handy UI feature. 

image

**Comment by webvictim** [comment]
I'll try and have another look at this tomorrow.

**Comment by russjones** [comment]
@webvictim We have not had a lot of progress on this, so I am going to close it for now. Please re-open if you want to work on this issue again.

**Pull request closed without merging**
