### PR TITLE
DynamoDB backend

### PR DESCRIPTION
**Pull request by kontsevoy**
### Description

This backend can be enabled by optionally adding a new build flag.
See lib/backend/dynamo/README.md for details.
### Important

It should not affect default Teleport builds.

### CODE REVIEW

**Comment by kontsevoy** [comment]
Lets deal with this PR next week (after Gravity LTS is released)

**Review by klizhentas — CHANGES_REQUESTED** [review]
There's missing vendoring here, so this won't build even with the build tag

**Comment by kontsevoy** [comment]
"with" or "without"? part of the reason I added build flags is because I did not want to vendor this extra dependencies in (and deal with licenses).

**Comment by kontsevoy** [comment]
@klizhentas requested: #600

**Pull request merged**
