### PR TITLE
Set auth client field of session registry

### LINKED ISSUE #10659: starting a session with `require_session_mfa` closes session in few seconds
### Description

**What happened**:
In the web UI, i started a session, and in a few seconds, my session closes (as shown in image below) and hangs. Because it hangs, I am unable to ssh into the same node anymore even as a different user or when I try to ssh with `tsh`. I also get the same behavior in `tsh` where it closes session and hangs. I could not escape the hanging, so I had to restart teleport.

image

This is the logs:
```
2022-02-28T03:20:28Z DEBU             Will join session 9c8a21dd-85e4-43c3-98e7-0fc48607aa92 for SSH connection 174.127.243.201:47324. srv/ctx.go:514
2022-02-28T03:20:28Z DEBU [SESSION:N] Starting poll and sync of terminal size to all parties. srv/sess.go:1391
2022-02-28T03:20:28Z DEBU [SESSION:N] Launching session 9c8a21dd-85e4-43c3-98e7-0fc48607aa92. srv/sess.go:803
2022-02-28T03:20:28Z INFO [AUDIT]     session.start addr.local:127.0.0.1:3022 addr.remote:174.127.243.201:47324 cluster_name:cfg-auth-service-cluster-name-ALL-svc code:T2000I ei:0 event:session.start login:root namespace:default server_addr:127.0.0.1:3022 server_hostname:cfg-teleport-nodename-ALL-svc server_id:3b3cd3b0-663c-4b3e-8321-198eea7b57c0 server_labels:map[environment:test] session_recording:node sid:9c8a21dd-85e4-43c3-98e7-0fc48607aa92 size:80:25 time:2022-02-28T03:20:28.249Z uid:b506ee62-4ca3-4a42-b359-24bfcfd0c0e1 user:lisa events/emitter.go:325
2022-02-28T03:20:28Z DEBU [NODE]      Handling request window-change, want reply false. id:6 local:127.0.0.1:3022 login:root remote:174.127.243.201:47324 teleportUser:lisa regular/sshserver.go:1398
2022-02-28T03:20:28Z DEBU             Will join session 9c8a21dd-85e4-43c3-98e7-0fc48607aa92 for SSH connection 174.127.243.201:47324. srv/ctx.go:514
2022-02-28T03:20:39Z DEBU [AUTH]      ClientCertPool -> cert(cfg-auth-service-cluster-name-ALL-svc issued by cfg-auth-service-cluster-name-ALL-svc:216377719071506119846396333477626861121) auth/middleware.go:609
2022-02-28T03:20:39Z DEBU [AUTH]      ClientCertPool -> cert(cfg-auth-service-cluster-name-ALL-svc issued by cfg-auth-service-cluster-name-ALL-svc:9751102761758653151994458698299553566) auth/middleware.go:609
2022-02-28T03:20:39Z DEBU [AUTH]      ClientCertPool -> cert(cfg-auth-service-cluster-name-ALL-svc issued by cfg-auth-service-cluster-name-ALL-svc:216377719071506119846396333477626861121) auth/middleware.go:609
2022-02-28T03:20:39Z DEBU [AUTH]      ClientCertPool -> cert(cfg-auth-service-cluster-name-ALL-svc issued by cfg-auth-service-cluster-name-ALL-svc:9751102761758653151994458698299553566) auth/middleware.go:609
2022-02-28T03:20:39Z DEBU [AUTH:1]    Server certificate cert(3b3cd3b0-663c-4b3e-8321-198eea7b57c0.cfg-auth-service-cluster-name-ALL-svc issued by cfg-auth-service-cluster-name-ALL-svc:216377719071506119846396333477626861121). auth/middleware.go:293
2022-02-28T03:20:43Z ERRO [SESSION:N] Failed to check presence, closing session as a security measure error:[
ERROR REPORT:
Original Error: *trace.BadParameterError cannot fetch session without auth service
Stack Trace:
  /go/src/github.com/gravitational/teleport/lib/srv/sess.go:1669 github.com/gravitational/teleport/lib/srv.(*session).trackerGet
  /go/src/github.com/gravitational/teleport/lib/srv/sess.go:1421 github.com/gravitational/teleport/lib/srv.(*session).checkPresence
  /go/src/github.com/gravitational/teleport/lib/srv/sess.go:827 github.com/gravitational/teleport/lib/srv.(*session).launch.func1
  /opt/go/src/runtime/asm_amd64.s:1581 runtime.goexit
User Message: cannot fetch session without auth service] srv/sess.go:829
2022-02-28T03:20:43Z INFO [SESSION:N] Closing session 9c8a21dd-85e4-43c3-98e7-0fc48607aa92. srv/sess.go:734
2022-02-28T03:20:43Z INFO [SESSION:N] Closing party 8bf4484e-c82a-477e-810f-51f9ad945b27 srv/sess.go:1656
2022-02-28T03:20:43Z DEBU [SESSION:N] Stopping poll and sync of terminal size to all parties. srv/sess.go:1412
2022-02-28T03:20:43Z DEBU [SESSION:N] Copying from PTY to writer completed with error read /dev/ptmx: input/output error. srv/sess.go:851
```

I turned off the `require_session_mfa` flag, restarted my teleport, and I do not get the same problem. I also switched my teleport version from `9.0.0-beta.1` to `v8.0.0.rc.1` (sorry, that was the latest v8 i had at the moment) and i do not get the same problem in both `tsh` and in the web UI with the flag on.

### Reproduction Steps
As minimally and precisely as possible, describe step-by-step how to reproduce the problem.
1. run teleport `9.0.0-beta.1`
2. login with a user with a role with `require_session_mfa` set to true
3. in the web UI and tsh, try ssh into a node, wait for a few seconds, and the message `closing session...` will appear

### Server Details
- Teleport version (run `teleport version`): Teleport Enterprise v9.0.0-beta.1 git:v9.0.0-beta.1-0-g5696e0b8e go1.17.2
- Server OS (e.g. from `/etc/os-release`):
```
NAME="Ubuntu"
VERSION="20.04.1 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.1 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
```
- Where are you running Teleport? (e.g. AWS, GCP, Dedicated Hardware): aws

### Client Details
- Tsh version (`tsh version`): Teleport v9.0.0-beta.1 git:v8.0.0-alpha.1-663-g051da5e0f go1.17.3
- Computer OS (e.g. Linux, macOS, Windows): linux
- Additional details:
config:
```
teleport:
  nodename: cfg-teleport-nodename-ALL-svc

auth_service:
  enabled: yes
  cluster_name: cfg-auth-service-cluster-name-ALL-svc

  authentication:
    type: local
    second_factor: webauthn
    u2f:
      app_id: https://kimlisa.dev:3080
      facets:
      - https://kimlisa.dev:3080
    require_session_mfa: no
  tokens: 
       - "node,auth,proxy:hello"
  license_file: /home/ubuntu/license.pem

ssh_service:
  enabled: yes
  labels:
    environment: test

```

### PR DESCRIPTION
**Pull request by xacrimon**
This PR fixes a one-off error likely introduced when rebasing moderated sessions before merging. This prevent the auth client field from being set which caused sessions to fail MFA checks and resulted in termination 15 seconds after start.

A fix for sometimes spurious hanging will be addressed in a separate PR.

Fixes #10659

### CODE REVIEW

**Comment by zmb3** [comment]
I am surprised that we don't have a single test that fails if you forget to pass the auth client. Can we get some test coverage for this?

**Comment by xacrimon** [comment]
The reason we don't have a test that checks this is that the only thing that needs it is Moderated Sessions MFA presence. Everything else is independent of having a stable connection to auth. Since this has been the assumption, this field is also optional and many places such as tests pass a nil value here, that is also the reason there is a nil check that generated the error in the origin issue in the first place.

Restructuring this to require that an auth client is passed would make dozens of tests significantly slower since an auth service now needs to be started without any real benefit. I don't think there's a good way to test that auth is passed since it's so situational (only done in one place) and a simple check for it wouldn't contribute to confidence that we do pass it. @zmb3

**Comment by xacrimon** [comment]
@zmb3 Added test that verifies that a tracker is created now. It fails without the patch in the first commit.

**Comment by xacrimon** [comment]
rolling this in with some other fixes in another pr

**Pull request closed without merging**
