### PR TITLE
YAML formatting

### PR DESCRIPTION
**Pull request by benarent**
Formatting / nesting issue reported by a customer.

### CODE REVIEW

**Comment by klizhentas** [comment]
@benarent can you please rebase?

**Comment by benarent** [comment]
Rebased PTAL @klizhentas

**Comment by russjones** [comment]
@benarent Do you mind fixing conflicts?

**Comment by benarent** [comment]
@russjones I've fixed the formatting issue.

**Comment by russjones** [comment]
@inertial-frame Can you review/approve this PR?

**Comment by inertial-frame** [comment]
Surprised that made it through the linters on the Next repo. @benarent may be worth checking into - I'd think it's preferable to catch these during the build process too?

**Review by inertial-frame — APPROVED** [review]

**Comment by inertial-frame** [comment]
@benarent - Nit: should we use array notation (like we're presently doing) or multi-line (which I've seen many other places)? https://stackoverflow.com/questions/23657086/yaml-multi-line-arrays

**Comment by benarent** [comment]
> does the Teleport config for any reason prefer one over the other?

Teleport will lint YAML once its setup. I try to follow that output as closely as possible.  It looks like we do multi-line, but the only downside is it can be very verbose.

**Comment by inertial-frame** [comment]
I'll try to stick to array format especially for Tutorials and How To's where readers are copying or perusing the config.

**Pull request merged**
