### PR TITLE
Connect: Provide prehog address for prod env

### PR DESCRIPTION
**Pull request by gzdunek**
~DO NOT MERGE~
Merge and backport to v12 when the prod env is ready.

### CODE REVIEW

**Comment by strideynet** [comment]
@espadolini Do we want to make the same suggestion here re: creating a Connect specific endpoint ?

**Comment by gzdunek** [comment]
Like here https://github.com/gravitational/cloud-terraform/pull/1542? IMO we should do it.

**Comment by strideynet** [comment]
> Like here [gravitational/cloud-terraform#1542](https://github.com/gravitational/cloud-terraform/pull/1542)? IMO we should do it.

Yup, as shown in that PR. I can think of a few benefits, and barely any negatives of the approach and we've already done it for `tbot` so probably makes sense to do the same for connect just for consistency.

**Review by ravicious — APPROVED** [review]

**Comment by gzdunek** [comment]
PR for the Connect specific endpoint https://github.com/gravitational/cloud-terraform/pull/1563

**Review by strideynet — APPROVED** [review]

**Review by espadolini — APPROVED** [review]

**Comment by gzdunek** [comment]
Prod is ready, so let's merge.

**Pull request merged**
