### PR TITLE
Fixed an error in the documentation of audit log mirror output

### PR DESCRIPTION
**Pull request by emuesuenu**
Modify parameter names to match our definition.
https://github.com/gravitational/teleport/blob/master/examples/chart/teleport-cluster/values.yaml#L90

### CODE REVIEW

**Comment by zmb3** [comment]
There's another related error here:

https://github.com/gravitational/teleport/blob/edb5fa1daff2a2994add893c62e779efae7b95d8/examples/chart/teleport-cluster/values.schema.json#L167-L171

That should be `properties/gcp/...`

**Review by ptgott — APPROVED** [review]

**Review by zmb3 — APPROVED** [review]

**Comment by zmb3** [comment]
Looks like this was fixed by a separate PR.

**Pull request closed without merging**
