### PR TITLE
Fix nindent of `service.spec` in teleport-cluster chart

### LINKED ISSUE #9644: Fail to render teleport-cluster helm chart with `--set service.spec=...` argument
### Description

**What happened**:

Fail to render [teleport-cluster](https://github.com/gravitational/teleport/tree/master/examples/chart/teleport-cluster) helm chart with `--set service.spec=...` argument.

**What you expected to happen**:

Success to render [teleport-cluster](https://github.com/gravitational/teleport/tree/master/examples/chart/teleport-cluster) helm chart with `--set service.spec=...` argument.

### Reproduction Steps
As minimally and precisely as possible, describe step-by-step how to reproduce the problem.

1. Create `values.yaml` as follow.

```yaml
clusterName: MY_CLUSTER_NAME
chartMode: aws
aws:
  region: ap-northeast-1
  backendTable: teleport-backend
  auditLogTable: teleport-events
  sessionRecordingBucket: teleport-sessions
highAvailability:
  replicaCount: 2
  certManager:
    enabled: true
    issuerName: letsencrypt
service:
  spec:
    loadBalancerSourceRanges:
      - "0.0.0.0/0"
```

2. Run `helm template` command as follow. Then it returns error.

```bash
$ helm template teleport teleport/teleport-cluster --version 8.0.7 --namespace teleport --values values.yaml
Error: YAML parse error on teleport-cluster/templates/service.yaml: error converting YAML to JSON: yaml: line 14: mapping values are not allowed in this context

Use --debug flag to render out invalid YAML
```

### Server Details
None

### Client Details
- Computer OS (e.g. Linux, macOS, Windows): Linux
- Helm: v3.7.2
- [teleport-cluster](https://github.com/gravitational/teleport/tree/master/examples/chart/teleport-cluster) helm chart: v8.0.7

### Debug Logs
I uploaded output of following command to [teleport-cluster-helm-chart-error-log.txt](https://gist.github.com/shibataka000/00c51332d7636043d345f9779e894746).

```bash
$ helm template teleport teleport/teleport-cluster --version 8.0.7 --namespace teleport --values values.yaml --debug
```

### PR DESCRIPTION
**Pull request by shibataka000**
Close #9644

### CODE REVIEW

**Comment by r0mant** [comment]
@webvictim This too please. Thanks man!

**Review by webvictim — APPROVED** [review]
@shibataka000 Thanks for the PR!

**Comment by webvictim** [comment]
@r0mant This one is good to go!

**Comment by webvictim** [comment]
@r0mant @russjones Please review

**Review by zmb3 — APPROVED** [review]

**Review by somethingnew2-0 — APPROVED** [review]

**Review by r0mant — APPROVED** [review]

**Pull request merged**
