### PR TITLE
tool/tsh: fix dropped error in TestMakeClient()

### PR DESCRIPTION
**Pull request by alrs**
This picks up a dropped test error in the `tool/tsh` package.

### CODE REVIEW

**Comment by webvictim** [comment]
ok to test

**Comment by webvictim** [comment]
The build failure wasn't caused by your change.

**Comment by alrs** [comment]
> The build failure wasn't caused by your change.

Good to know, thanks. Are you guys open for PRs right now, or would you rather I hold back until CI is fixed?

**Comment by webvictim** [comment]
Feel free to PR whatever you like. FIxing CI is an ongoing process :)

**Review by klizhentas — APPROVED** [review]

**Review by fspmarshall — APPROVED** [review]

**Pull request merged**
