### PR TITLE
Run shellcheck during "make lint"

### PR DESCRIPTION
**Pull request by awly**
Shellcheck is a linter for shell scripts. Since we have quite a few of
those for release packaging and examples, we'll benefit from an extra
set of (robot) eyes.

Note: I disabled https://github.com/koalaman/shellcheck/wiki/Sc2086 to
make this PR smaller. That specific check is for the most frequent
mistake in our scripts - not quoting env var expansions. I'll do a
separate PR cleaning those up.

Updates https://github.com/gravitational/teleport/issues/4229

### CODE REVIEW

**Comment by webvictim** [comment]
We'll need to install `shellcheck` in the buildbox as well for this to work. I realise this is still a draft, but just wanted to highlight that.

Some of these scripts are also pretty old. I would delete the whole `build.assets/pkg` directory - we don't use it at all for our own packaging and red diffs are good.

**Comment by awly** [comment]
@webvictim thanks for taking an early look!
Installed `shellcheck` in the buildbox container and removed `build.asset/pkg`

**Review by webvictim — APPROVED** [review]
:+1:

**Review by benarent — APPROVED** [review]
Nice! I always need extra help with a spellcheck.

**Pull request merged**
