### PR TITLE
Add a conceptual guide to Moderated Sessions

### PR DESCRIPTION
**Pull request by ptgott**
The tutorial-style guide created in previous commits did not
provide enough context into how the feature works and which
configuration options are available. Since the instructions in
the guide are mostly example configurations anyway, I thought it
would make sense to combine the guide and the reference while
removing the tutorial instructions and adding more detailed
guidance on available configuration options.

This guide now lives in docs/pages/access-controls. I thought
keeping it in docs/pages/setup/reference would not be appropriate,
since the references there are for broad approaches to interacting
with Teleport (configuration, dynamic resources, metrics, etc.),
rather than specific features.

We can plan to edit the dynamic resource reference to include
the config options mentioned in this guide.

### CODE REVIEW

**Comment by ptgott** [comment]
cc @xacrimon and @klizhentas What do you think of turning the Moderated Sessions docs into a single [conceptual guide](https://goteleport.com/docs/docs/#admin-and-user-guides) per this PR? (There's still a bit of work to be done on the PR itself, as you can see by the TODOs)

**Comment by xacrimon** [comment]
Sounds like a good idea, I'm for it. What do you think? @klizhentas

**Review by klizhentas — APPROVED** [review]
@ptgott @xacrimon looks good, but we also need to update RBAC reference with all new fields if we haven't yet.

**Comment by xacrimon** [comment]
Yep, I will merge this into my branch and fill out all technical RBAC details.

**Pull request merged**
