### PR TITLE
fix: removing new line convergance

### PR DESCRIPTION
**Pull request by moabu**
Upon leaving it as is the `-` removes the new line combining the `audit_sessions_uri` key and value to the end of the `audit_events_uri` key and value causing the following error : 

```
kubectl logs -f teleport-7f446d5848-7lj9b -n teleport
ERROR: failed parsing the config file: yaml: line 13: mapping values are not allowed in this context
```

line 13 in `config.yaml`

```yaml
        credentials_path: /etc/teleport-secrets/gcp-credentials.jsonaudit_events_uri: ['firestore://teleport-helm-events?projectID=x-x-x-x&credentialsPath=/etc/teleport-secrets/gcp-credentials.json']audit_sessions_uri: "gs://teleport-helm-sessions?projectID=x-x-x-x&credentialsPath=/etc/teleport-secrets/gcp-credentials.json"
```

### CODE REVIEW

**Review by webvictim — APPROVED** [review]
Good catch, looks like an oversight or copy/paste failure as the AWS settings are correct.

**Comment by webvictim** [comment]
Same as #9628

**Review by r0mant — APPROVED** [review]

**Comment by webvictim** [comment]
Backports required:
- `branch/v8`

**Review by russjones — APPROVED** [review]

**Comment by russjones** [comment]
@tcsc Can you take a look at this next week, GCB says the following.

```
2022/01/15 03:41:10 FAILED: target branch must be set
```

**Pull request merged**
