### PR TITLE
Web: add a tooltip summary for aws oidc configure step

### PR DESCRIPTION
**Pull request by kimlisa**
this is for enrolling aws oidc integration flow

checkout story: https://localhost:9003/?path=/story/teleport-integrations-enroll-awsoidc--flow

image

### CODE REVIEW

**Comment by zmb3** [comment]
Is there a better way to display the IAM role? The editor feels too big for a tooltip, and having two scrollbars show up feels like a poor UX.

**Comment by GavinFrazar** [comment]
The script will provide specifics like the trust policy. I think the UI tooltip should just summarize in plain sentences

**Comment by thedevelopnik** [comment]
> Is there a better way to display the IAM role? The editor feels too big for a tooltip, and having two scrollbars show up feels like a poor UX.

Yeah, I think it could just be something like "configures an IAM role called `iam-role-name` that allows it to assume a role."

**Comment by r0mant** [comment]
I think showing the IAM policy here would be helpful too, for user reference. Can we borrow the "sliding out side panel" UX trick from TAG and show it in the panel that slides off of the right edge to view the full policy?

**Comment by kimlisa** [comment]
i discussed this with kenny, xin, and dave:

we agreed to keep the tooltip for now (with wider width, to get rideof horizontal scrolling), until we finalize how we want to better represent these type of information eg: side bar. there are other places in discover where we use same tooltip for similar info.

**Comment by zmb3** [comment]
Sounds good to me.

(Some day we really should get the ACE editor to use a light syntax theme when Teleport is in light mode).

**Review by zmb3 — APPROVED** [review]

**Review by avatus — APPROVED** [review]

**Pull request merged**
