### PR TITLE
[v9] Add Session tracker to DB, App, and Windows Desktop Sessions

### PR DESCRIPTION
**Pull request by Joerger**
Backports https://github.com/gravitational/teleport/pull/12304
Backports https://github.com/gravitational/teleport/pull/10478 (`make grpc` fix)

### CODE REVIEW

**Review by codingllama — COMMENTED** [review]
Did you have to do any noteworthy adaptations or did it backport cleanly?

**Comment by Joerger** [comment]
> Did you have to do any noteworthy adaptations or did it backport cleanly?

It should have backported cleanly, but I had to run `make grpc`, and it looks like running `make grpc` currently breaks `branch/v9`.

**Comment by Joerger** [comment]
> Did you have to do any noteworthy adaptations or did it backport cleanly?

It should have backported cleanly, but I had to run `make grpc`, and it looks like running `make grpc` currently breaks `branch/v9`.

**Comment by Joerger** [comment]
@codingllama I just had to include the fix for `make grpc` that you made a while back. So no other adaptations from the original PR were needed.

**Review by xacrimon — APPROVED** [review]

**Review by codingllama — APPROVED** [review]

**Comment by codingllama** [comment]
> @codingllama I just had to include the fix for `make grpc` that you made a while back. So no other adaptations from the original PR were needed.

Right, completely forgot about that. Thanks for pulling it in.

**Review by zmb3 — APPROVED** [review]

**Pull request merged**
