### PR TITLE
[helm] Restart teleport-kube-agent if it can't join the cluster

### PR DESCRIPTION
**Pull request by nml11c**
Sometimes `teleport-kube-agent` halt his connection to the main `teleport-proxy` and the only way to fix it is to restart it.

Liveness probe seems like a perfect way to do that.

### CODE REVIEW

**Review by webvictim — CHANGES_REQUESTED** [review]
Personally, I think this PR is likely to cause more problems than it solves. Restarting the pod is a pretty blunt weapon; if an agent isn't using persistent storage (i.e. it's running a `Deployment` rather than a `StatefulSet`) and its join token has expired, the restart would mean it loses all connectivity to Teleport until a new token is provisioned and the chart is redeployed. I would prefer this restart to be an explicit decision which the administrator makes, rather than it being forced upon them. It could also permanently disconnect an agent from a cluster which has a temporary networking issue that is naturally resolved a few minutes later, forcing another redeployment.

I would approve a PR which changes this to `/readyz` for the `StatefulSet` only (https://github.com/gravitational/teleport/blob/master/examples/chart/teleport-kube-agent/templates/statefulset.yaml#L132), as in that situation the agent is guaranteed to have persistent storage and will be able to rejoin the cluster using its mutual TLS certs.

**Comment by nml11c** [comment]
Thank you for a detailed explanation. Sounds reasonable. Changed liveness probe in `StatefulSet` instead.

**Review by webvictim — APPROVED** [review]
I think this is good assuming that the linter passes (no reason it shouldn't). Thanks @nml11c

**Comment by russjones** [comment]
https://github.com/gravitational/teleport/pull/9484

**Pull request closed without merging**
