### PR TITLE
build: Build webassets for CentOS 7 with buildbox-connect

### PR DESCRIPTION
**Pull request by camscale**
Build the webassets for the CentOS 7 binaries using the buildbox-connect
container prior to building the binaries. This allows us to use a later
version of node.js to build the UI than what is available on CentOS 7.

The `release-unix` and `clean` targets need to be rejigged a little as
`release-unix` first cleans any pre-build webassets. So we add a new
target `release-unix-preserving-webassets` that only cleans the build
and not the webassets and update the Makefile in `build.assets` to call
this new target when building CentOS 7 binaries.

### CODE REVIEW

**Comment by gzdunek** [comment]
At first I thought we would have to use GHA artifacts to share webassets between steps, but I think the idea of pre-building them in the Makefile is better than that.

On top of your branch, I tried to upgrade the Node version, it went smoothly, except Linux ARM64 where it tried to build enterprise webassets but only the OSS repo was checked out:
```
find: ‘/go/src/github.com/gravitational/teleport/e/web’: No such file or directory
make: *** [Makefile:1385: ensure-webassets-e] Error 1
```

I guess we should have some condition to prevent building enterprise webassets if `e` does not exist?

**Comment by jakule** [comment]
As we talked earlier, I think we should use the Node.js/Connect buildbox instead of the Ubuntu CI image. WebUI and Connect should be built with the same version of Node in my opinion.

**Comment by camscale** [comment]
> I guess we should have some condition to prevent building enterprise webassets if e does not exist?

Done. It now only builds the enterprise webassets if the enterprise Makefile exists (which is the usual test for that submodule being present).

> At first I thought we would have to use GHA artifacts to share webassets between steps, but I think the idea of pre-building them in the Makefile is better than that.

I first thought I would be changing the workflows but I realised to ensure the build.assets/Makefile still works for local dev and testing, it would need to be done there and ended up being better that way.

**Comment by camscale** [comment]
> I think we should use the Node.js/Connect buildbox instead of the Ubuntu CI image.

Done.

**Comment by camscale** [comment]
@gzdunek @jakule This is now ready for review if you wouldn't mind giving it another look over.

**Comment by gzdunek** [comment]
In logs I saw a few `/bin/bash: go: command not found`, but the build succeeded. 
Do you know where they come from?
```
 > importing cache manifest from public.ecr.aws/gravitational/teleport-buildbox-connect:teleport14:
------
docker run --rm=true -v "$(pwd)/../":/go/src/github.com/gravitational/teleport -v /tmp:/tmp -w /go/src/github.com/gravitational/teleport -h buildbox -e GOMODCACHE=/tmp/gomodcache -e HELM_PLUGINS=/home/ci/.local/share/helm/plugins-new -v /go/cache:/go/cache -e GOCACHE=/go/cache -u 1000:1000 public.ecr.aws/gravitational/teleport-buildbox-connect:teleport14 \
	/usr/bin/make ensure-webassets ensure-webassets-e
/bin/bash: go: command not found
/bin/bash: go: command not found
/bin/bash: go: command not found
/bin/bash: go: command not found
/bin/bash: go: command not found
make[1]: Entering directory '/go/src/github.com/gravitational/teleport'
/bin/bash: go: command not found
/bin/bash: go: command not found
yarn install v1.22.19
[1/4] Resolving packages...
[2/4] Fetching packages...
```

**Comment by camscale** [comment]
I think they are from the top-level Makefile: https://github.com/gravitational/teleport/blob/master/Makefile#L52 - that and a few other places that run `go` to get info for vars. The Makefile really needs a bit of a clean-up to fix this and other things, but it is generally benign. If you are only running make targets that do not need Go, then no harm done. If you do need Go for a target, then it will fail for that target.

**Comment by gzdunek** [comment]
Should we also add webassets pre-building to `build-binaries-fips` target (line 109) and `release-fips` (line 430)?

**Review by gzdunek — APPROVED** [review]
Looks good to me, I only left one question.

**Comment by camscale** [comment]
@gzdunek I've added the `webassets` dependency to those two targets too. Thanks. `release-fips` is not actually used anywhere and currently doesn't work. I'll look to clean that up when I simplify some of this stuff after getting it all running on GHA.

**Review by jakule — APPROVED** [review]
Looks good.

> Build the webassets for the CentOS 7 binaries using the standard Ubuntu
buildbox prior to building the binaries.

PR description needs to be updated. This build doesn't use the Ubuntu box anymore.

**Comment by gzdunek** [comment]
>PR description needs to be updated. This build doesn't use the Ubuntu box anymore.

Done in the description and in the PR.

**Pull request merged**
