### PR TITLE
[v13] Update e

### PR DESCRIPTION
**Pull request by wadells**
Includes changes from https://github.com/gravitational/teleport.e/pull/2978 / backports.

I'll be removing the `staging` enviroment (replaced by `build-stage` / `publish-stage`) and builds will no longer work without this change.

### CODE REVIEW

**Review by fheinecke — APPROVED** [review]

**Review by tcsc — APPROVED** [review]

**Comment by wadells** [comment]
Someone got to this before me.

**Comment by wadells** [comment]
Someone got to this before me.

**Review by r0mant — APPROVED** [review]

**Comment by wadells** [comment]
Looks like https://github.com/gravitational/teleport/pull/37877 broke Lint (Go) in v13 which will prevent anything from merging.  I'll take a look at it tomorrow if @codingllama doesn't beat me to it.

**Comment by codingllama** [comment]
o.O

```shell
$ cd integrations/kube-agent-updater

$ pwd
(...)/teleport/integrations/kube-agent-updater

$ golangci-lint run -c ../../.golangci.yml .
# exit code: 0
# so far so good

$ golangci-lint run -c ../../.golangci.yml ./...
ERRO Running error: context loading failed: no go files to analyze
# exit code: 5
# what?

$ find . -name '*.go'
./cmd/teleport-kube-agent-updater/constants.go
./cmd/teleport-kube-agent-updater/main.go
./version.go
./hack/cosign-fixtures.go
./pkg/basichttp/servermock.go
./pkg/basichttp/client.go
./pkg/cache/error.go
./pkg/cache/cache_test.go
./pkg/cache/cache.go
./pkg/constants/constants.go
./pkg/podutils/filter_test.go
./pkg/podutils/filter.go
./pkg/podutils/utils.go
./pkg/controller/deployment.go
./pkg/controller/utils_test.go
./pkg/controller/statefulset.go
./pkg/controller/updater.go
./pkg/controller/constants.go
./pkg/controller/updater_test.go
./pkg/controller/utils.go
./pkg/controller/statefulset_test.go
./pkg/controller/suite_test.go
./pkg/controller/errors.go
./pkg/img/insecure.go
./pkg/img/validator.go
./pkg/img/cosign_test.go
./pkg/img/cosign_fixtures_test.go
./pkg/img/doc.go
./pkg/img/cosign.go
./pkg/img/nop.go
./pkg/img/nop_test.go
./pkg/img/mock.go
./pkg/img/errors.go
./pkg/version/basichttp.go
./pkg/version/versionget_test.go
./pkg/version/basichttp_test.go
./pkg/version/mock.go
./pkg/version/versionget.go
./pkg/version/errors.go
./pkg/maintenance/window.go
./pkg/maintenance/basichttp.go
./pkg/maintenance/basichttp_test.go
./pkg/maintenance/unhealthy.go
./pkg/maintenance/unhealthy_test.go
./pkg/maintenance/mock.go
./pkg/maintenance/trigger.go
./pkg/maintenance/window_test.go
```

**Comment by codingllama** [comment]
The linter is failing because kube-agent-updater/go.mod is actually incorrect / untidy. Since #34462 the min Go version required for the module is 1.21 due to github.com/sigstore/cosign/v2 v2.2.1. I'll push a PR shortly.

**Comment by codingllama** [comment]
- https://github.com/gravitational/teleport/pull/38009

**Pull request merged**
