### PR TITLE
Update ent.yaml

### PR DESCRIPTION
**Pull request by jon-can**
Bump AMIs to 4.3.2

### CODE REVIEW

**Review by webvictim — COMMENTED** [review]
As we’re making the updates, could you do the same for `oss.yaml` too please?

I’ve added a note in https://github.com/gravitational/teleport/issues/4031 to look at automating these updates in future.

**Comment by awly** [comment]
LGTM, after `oss.yaml` is updated

**Comment by benarent** [comment]
@webvictim Did your other PR fix this? If so, should we close this.

**Comment by webvictim** [comment]
Yeah, it fixes it for 4.3.5 so we can close it. We'll need to make sure we run it again after we do every release - don't think we have a "post-release" checklist currently but I'll make one and add it.

**Pull request closed without merging**
