### PR TITLE
helm: Don't package/update old teleport chart

### LINKED ISSUE #5582: Helm charts improvements
### What

* [x] Add tests of helm charts to our CI/CD pipeline to avoid regressions
* [x] Release `teleport-kube-agent` and `teleport-cluster` to be our official charts
* [x] Extend `teleport-cluster` to support custom configuration, GKE and EKS scenarios
* [x] Provide migration guide from `teleport` to `teleport-cluster` and update the docs
* [x] Helm chart version should match Teleport version

## Strategy of Teleport Cluster

Keep amount of configuration parameters to a recommended minimum subset. Promote 3 major use cases:

* Standalone chart with ACME and PVC for getting started
* HA AWS chart with DynamoDB and S3
* HA GCP chart with Firebase and GCS

For every other scenario, provide escape hatch - ability for folks to mount their config files and give a couple of examples

## Strategy for Teleport Kube Agent

Teleport Kube Agent should support multiple roles and apps, provide ways to add apps to existing Database agent for example.

Add respective guides to documentation sections

### PR DESCRIPTION
**Pull request by webvictim**
Also updates the teleport-cluster chart README and chart repo index page with links to the new Helm guides. These links won't be valid until 6.2 is released and the docs are updated, so we can wait to merge this until then if needed.

Fixes #5582

### CODE REVIEW

**Review by wadells — APPROVED** [review]
LGTM -- pending docs release.

**Review by awly — APPROVED** [review]

**Review by russjones — APPROVED** [review]
Bot.

**Comment by awly** [comment]
@webvictim please merge this when you're ready so we can close out https://github.com/gravitational/teleport/issues/5582

**Comment by webvictim** [comment]
This is waiting for https://github.com/gravitational/next/pull/269 which will make 6.2 docs latest. Once that's merged and the 6.2 docs are live I will update/merge.

**Pull request merged**
