### PR TITLE
Remove underscores from documentation URLs

### PR DESCRIPTION
**Pull request by kontsevoy**
This enormous pull request closes our final SEO issue: **URLs with underscores**!!!
Only documentation is affected. 

Old URLs are redirected to new ones, basically anything under `/teleport/docs/any_path/to_page` becomes `/teleport/docs/any-path/to-page`

This is already deployed into production.

### CODE REVIEW

**Comment by webvictim** [comment]
`milv` is failing on `docs/4.1/quickstart--archive.md`:

```
---> Running milv on docs/4.1:
#################################################
#                     SUMMARY                   #
#################################################
| +--------------------------+----------------------------------------------+--------------------------------+
| \|           FILE           \|                     LINK                     \|          DESCRIPTION           \|
| +--------------------------+----------------------------------------------+--------------------------------+
| \| ./quickstart--archive.md \| /img/login.png?style=grv-image-center-md     \| The specified file doesn't     \|
| \|                          \|                                              \| exist                          \|
| +                          +----------------------------------------------+                                +
| \|                          \| /img/firstpage.png?style=grv-image-center-md \|                                \|
| \|                          \|                                              \|                                \|
| +                          +----------------------------------------------+                                +
| \|                          \| /trustedclusters                             \|                                \|
| \|                          \|                                              \|                                \|
| +                          +----------------------------------------------+                                +
| \|                          \| /quickstart/#adding-nodes-to-cluster         \|                                \|
| \|                          \|                                              \|                                \|
| +--------------------------+----------------------------------------------+--------------------------------+

```

**Comment by kontsevoy** [comment]
@benarent this `mil`v error makes no sense to me and I will need your help to resolve this.

**Comment by webvictim** [comment]
Ah - I suspect that it's because the old filename for that page was whitelisted in the `milv` config so it wasn't being checked (https://github.com/gravitational/teleport/blob/master/docs/4.1/milv.config.yaml#L30) 

@benarent Should we delete `docs/4.1/quickstart--archive.md` or update the `milv` config? I'm not sure why we have a page with broken links committed.

**Comment by kontsevoy** [comment]
Also, what's the latest on your `milv` decision? I really like it for internal markdown checking (mkdocs itself does this too, BTW) but for external links we have SEMRush send us alerts now. `milv` takes minutes to complete the build.

**Comment by webvictim** [comment]
The `milv` checks in Drone have been separated into two separate jobs now:
- the internal check (which took 27 seconds to run on this PR) and must pass
- the external check, which is ignored for the purposes of PR approval

We can remove the external check at any time - we still run all unit/integration tests on every docs PR which means a ~10 minute feedback cycle anyway.

**Review by benarent — APPROVED** [review]
I've a last few fixes. 

Re: milv. Since @webvictim has already put work into splitting it out, how about we turn it off for local dev to speed up flow and only run it externally as part of CI.

**Comment by webvictim** [comment]
Yeah, I forgot that we had it enabled in the `Makefile`. I can create a PR to switch it off.

**Pull request merged**
