### PR TITLE
Advertise a minimum version for clients.

### PR DESCRIPTION
**Pull request by russjones**
**Purpose**

Make `tsh` version checking less infuriating.

**Implementation**

* Servers return a minimum client version at the `/webapi/ping` endpoint.
* Clients check that their own version is greater than or equal to the minimum client version advertised by the server.
* Expose the `--skip-version-check` flag.

**Related Issues**

Fixes https://github.com/gravitational/teleport/issues/2344

### CODE REVIEW

**Comment by klizhentas** [comment]
I believe this PR needs a 3.0.<patch> counterpart that considers the version if it's present to make this feature operational in 3.1, don't you think?

**Review by kontsevoy — APPROVED** [review]
I am assuming that future versions of `tsh` will work with 3.0 servers (unless we introduce a breaking feature), right?

**Comment by russjones** [comment]
@klizhentas https://github.com/gravitational/teleport/pull/2352

**Comment by russjones** [comment]
@kontsevoy Yes, exactly.

**Review by klizhentas — APPROVED** [review]

**Pull request merged**
