### PR TITLE
Hide SSH banner #970

### PR DESCRIPTION
**Pull request by suedadam**
Hiding the SSH banner information as per Issue #970 to prevent people from finding bugs/vulnerabilities.

### CODE REVIEW

**Comment by klizhentas** [comment]
let's just always set banner to SSH2.0 without any extra config params, can't imagine the case when someone will want the banner with teleport really.

**Comment by suedadam** [comment]
True

**Review by klizhentas — APPROVED** [review]
ok to test

**Comment by klizhentas** [comment]
retest this please

**Comment by klizhentas** [comment]
retest this please

**Comment by suedadam** [comment]
@klizhentas It won't let me read the build error, could you paste it? It works fine for me on my local comp (or maybe I'm compiling it wrong)

`-:teleport suedadam$ make
go build -o build/tsh -i  -ldflags '-w -s' ./tool/tsh
go build -o build/teleport -i  -ldflags '-w -s' ./tool/teleport
go build -o build/tctl -i  -ldflags '-w -s' ./tool/tctl
-:teleport suedadam$ `

**Comment by klizhentas** [comment]
these are flaky tests, unrelated

**Comment by klizhentas** [comment]
retest this please

**Comment by kontsevoy** [comment]
This PR breaks Teleport behavior of accurately __recording client IP__ for audit purposes, i.e. one of the major Teleport features.

Teleport looks at the VersionString (and this is well documented in the code) and Teleport proxy passes the "true client IP" back to the server. Without this, every session will be recorded like it was initiated by the proxy IP. Original bug: #735

**Pull request closed without merging**
