### PR TITLE
RFD 0110 - usage reporting developer guidelines

### PR DESCRIPTION
**Pull request by espadolini**

### CODE REVIEW

**Comment by espadolini** [comment]
cc @strideynet for future tbot usage events

**Comment by espadolini** [comment]
The actual RFD is coming soon

Following the changes commit by commit should give a clear idea of what happened, but the short version is that `lib/usagereporting` contains both the generic reporter and the dedicated implementations (for Teleport and for Connect, for now, in subpackages) including event conversion.

The audit log emitter is still in `lib/events/usageevents` (but the event conversion is in `lib/usagereporter/teleport`), and the web UI side of things hasn't been moved.

@michellescripts and @marcoandredinis: how would you feel about moving some or most of the `/webapi/precapture` and `/webapi/capture`-related code in `lib/usagereporter`, considering that the frontend side would still have to live somewhere else?

**Comment by marcoandredinis** [comment]
> how would you feel about moving some or most of the /webapi/precapture and /webapi/capture-related code in lib/usagereporter, considering that the frontend side would still have to live somewhere else?

Moving the `convertUserEventRequestToUsageEvent` function?
Looks good to me

**Comment by espadolini** [comment]
Split off the refactor and the RFD, the refactor is at #22460.

**Comment by espadolini** [comment]
moved to gravitational/cloud#4407

**Pull request closed without merging**
