### PR TITLE
[v13] fix: Tidy integrations/kube-agent-updater/go.mod

### PR DESCRIPTION
**Pull request by codingllama**
The go.mod file is untidy and causing problems for the lint checks.

Since #34462 (or maybe even earlier than that) the min Go version for the module, as required by its dependencies (namely github.com/sigstore/cosign/v2 v2.2.1), is Go 1.21.

### CODE REVIEW

**Review by wadells — APPROVED** [review]

**Comment by wadells** [comment]
Do you understand why lint didn't fail on https://github.com/gravitational/teleport/pull/34462?  What were we missing?

**Comment by codingllama** [comment]
Fixes the issues spotted by #37679, #37875 and possibly others.

I'm not sure why this wasn't a problem until now, but I suspect it's related to our recent Go toolchain update (ie #37561).

I've checked the other go.mod files and they all seem to be tidy.

**Comment by codingllama** [comment]
I've checked the go.mods of all other active branches, for good measure. Everything seems to be OK.

Fish snippet:

```fish
find . -name go.mod | while read f
    echo $f
    pushd (dirname $f)
    go mod tidy
    popd
end
```

**Review by hugoShaka — APPROVED** [review]

**Review by strideynet — APPROVED** [review]

**Comment by codingllama** [comment]
It looks like this ain't passing the Rotation tests, which is another can of worms. Sadly I won't have time to purse this right now.

**Comment by wadells** [comment]
AFAICT, these test failures are unrelated to the changes herein. As someone relatively unfamiliar, I don't see what kube-agent-updater would have to do with the rotation tests. Do you have reason to believe otherwise?

**Comment by codingllama** [comment]
I don't think they have to do with this PR, but I suspect they might be more prevalent since the go update too.

**Comment by wadells** [comment]
I'm going to turn of the requirement for `Unit Tests (Go)` to merge for a couple minutes to get this in.

https://github.com/gravitational/github-terraform/pull/799

At least this way linting won't block that fix when we get there.

**Comment by codingllama** [comment]
Thanks! I'll see if I can figure something out before my day ends.

**Pull request merged**
