### PR TITLE
Fix a bug in socks5 when rendering remote address

### PR DESCRIPTION
**Pull request by jieyu**
When the remote address is an IP address, we cannot directly convert
byte array to string. Otherwise, we will see hex strings like
"\xac\x11\x01\xc8:443".
    
See more details about the bug in:
https://community.gravitational.com/t/ssh-dynamic-port-forwarding-not-working/432
    
The above reported issue is resolved after applying the patch.

### CODE REVIEW

**Comment by webvictim** [comment]
ok to test

**Comment by jieyu** [comment]
hum, I cannot see test logs. Can someone check for me?

**Comment by webvictim** [comment]
Our Jenkins tests are flaky so it probably means nothing. We'll need a review before it goes anywhere anyway.

**Comment by webvictim** [comment]
@jieyu 

```
FAIL: socks_test.go:48: SOCKSSuite.TestHandshake

socks_test.go:69:
    c.Assert(string(buf), check.Equals, remoteAddr)
... obtained string = "?6578616d706c65"
... expected string = "example.com:443"

OOPS: 0 passed, 1 FAILED
--- FAIL: TestSocks (0.01s)
```

**Comment by jieyu** [comment]
OK, i'll fix. I think we should distinguish between DNS name and IP addresses.

**Comment by jieyu** [comment]
@webvictim can you take another look? I updated the code and the test.

**Comment by jieyu** [comment]
ping @klizhentas @russjones

**Comment by webvictim** [comment]
Looks like the test passes now @jieyu - the integration test is failing but that's probably unrelated.

**Comment by jieyu** [comment]
@webvictim how can I get this bug fix reviewed and merged? This is blocking our progress

**Comment by klizhentas** [comment]
Thanks for your patience. We are currently overloaded with requests. We will get to this issue in the context of 4.2 milestone in a couple of weeks from now.

**Comment by webvictim** [comment]
@jieyu You can always build Teleport yourself from source with your patch included if you like.

**Comment by jieyu** [comment]
@webvictim we could, but that means our customers will have to use a forked version of teleport, which I am trying to avoid. This is clearly a bug, so I expect not too much trouble merging this.

**Review by klizhentas — APPROVED** [review]
@russjones can you please review sometime this week?

**Comment by klizhentas** [comment]
@jieyu the fix looks quite straightforward to me, we will try to wrap up the review this week. What version are you using?

**Comment by jieyu** [comment]
@klizhentas thanks for the review! we're using the latest. So if this can be included in the upcoming release, that'll be sufficient.

**Comment by klizhentas** [comment]
sounds good to me, thank you for the patch.

**Review by russjones — APPROVED** [review]

**Pull request merged**
