### PR TITLE
drone: Replace linux tag build pipelines with GitHub Actions

### PR DESCRIPTION
**Pull request by camscale**
Replace most of the linux tag build pipelines with a call to GitHub
actions to do build instead. The workflow handles all the linux tag
builds except for ARM64 builds which was previously done. This ARM64
pipeline will be consolidated with the new generic pipeline. Also not
yet migrated is the Windows build that is performed on Linux. That will
follow shortly as it follows the same structure as these builds.

This has resulted in the removal of the `-deb` and `-rpm` pipelines as
they are built as part of a single workflow. They are reasonably quick
so there is little gain from parallelising them, but that can still be
looked at later if it turns out to help enough.

Also removed are the `-centos7` pipelines. That and the non-centos AMD64
pipelines were calling the same build target, so work was being
duplicated. All AMD64 builds are centos7 builds. As life and
distributions advance, the AMD64 build will be updated in the Makefile
to build on the next minimum supported Linux/glibc and nothing needs to
be done to the workflow. Note that currently the target in the Makefile
still has the `-centos7` naming. That name will be removed shortly as we
never build a non-centos7 AMD64 release.

The following pipelines are updated:

    build-linux-amd64
    build-linux-amd64-fips
    build-linux-386
    build-linux-arm

The following pipelines are removed:

    build-linux-amd64-deb
    build-linux-amd64-fips-deb
    build-linux-amd64-centos7-rpm
    build-linux-amd64-centos7-fips-rpm
    build-linux-amd64-centos7
    build-linux-amd64-centos7-fips
    build-linux-386-deb
    build-linux-386-rpm
    build-linux-arm-deb
    build-linux-arm-rpm

---

NOTE: This supersedes https://github.com/gravitational/teleport/pull/29893
which did not migrate the FIPS pipelines and mucked up some
centos7/deb/rpm stuff. This PR is reasonably similar but has enough
changes that it did not feel right reusing the old one with the existing
approvals.

NOTE: The e ref update in this PR points to a commit on the PR
https://github.com/gravitational/teleport.e/pull/2302. This PR will be
merged after that teleport.e PR but not before updating the e ref in
this PR to point at a master commit.

NOTE: I am still testing this - it does all appear to work correctly but
due to unrelated breakage on master, I am currently unable to get a
clean tag build which I can then promote. The fix for that is
https://github.com/gravitational/teleport.e/pull/2339.

### CODE REVIEW

**Comment by camscale** [comment]
@jakule @tcsc @r0mant Apologies for respinning a PR you've already approved (https://github.com/gravitational/teleport/pull/29893). I was originally going to do the fips stuff later, but got it done while waiting for some other fixes to land. I also discovered some mistakes in the earlier PR with regard to centos7, deb, rpm, fips and teleport connect that required some revision.

**Review by r0mant — APPROVED** [review]

**Review by jakule — APPROVED** [review]
Linter is failing, but apart from that LGTM

**Comment by camscale** [comment]
> Linter is failing, but apart from that LGTM

Thanks. Fixed. Some now unused functions having converted all the linux tag build pipelines to call GHA.

**Comment by camscale** [comment]
This was superseded by https://github.com/gravitational/teleport/pull/35235

**Pull request closed without merging**
