### PR TITLE
Utilize IMDS v2 endpoints for instance metadata.

### LINKED ISSUE #4310: Update and provide docs for EC2 Instance Metadata Service V2 (IMDSv2)
### Feature Request
A customer mentioned that we use V1 of the Instance Metadata service for AWS. https://github.com/gravitational/teleport/blob/master/assets/aws/files/bin/teleport-lock#L19  We should upgrade this to V2 to follow security best practice. We should do the same for our example labels https://aws.amazon.com/blogs/security/defense-in-depth-open-firewalls-reverse-proxies-ssrf-vulnerabilities-ec2-instance-metadata-service/ 

We should also add signature check https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/verify-signature.html 

### Motivation
Customer comment / Security best practice

### Who's it for?
OSS User, Pro, Enterprise

### PR DESCRIPTION
**Pull request by travelton**
Updates the AWS AMI scripts to utilize [IMDS v2](https://aws.amazon.com/blogs/security/defense-in-depth-open-firewalls-reverse-proxies-ssrf-vulnerabilities-ec2-instance-metadata-service/) for improved security.

Test Plan:
- [x] Build `teleport-debug-ami-oss-4.4.1`.
- [x] Spin up ec2 from `teleport-debug-ami-oss-4.4.1` AMI.
- [x] Verify `teleport-generate-config` executes successfully with zero config. 
- [x] Run `teleport-generate-config` in debug mode and verify output reports no errors.
- [x] Give ec2 instance IAM role for test Dynamo DB table.
- [x] Run `teleport-lock` in debug mode and verify output reports no errors.
- [x] Check Dynamo DB table to verify `process` object contains correct local hostname.

### CODE REVIEW

**Comment by travelton** [comment]
@webvictim I was trying to DRY this out a bit, but was having issues with the following. Any advice? 

```sh
IMDS_TOKEN=$(curl -X PUT "http://169.254.169.254/latest/api/token" -H "X-aws-ec2-metadata-token-ttl-seconds: 300")
IMDS_TOKEN_HEADER="-H \"X-aws-ec2-metadata-token: ${IMDS_TOKEN}\""
LOCAL_HOSTNAME=$(curl -sS ${IMDS_TOKEN_HEADER} http://169.254.169.254/latest/meta-data/local-hostname)
```

**Comment by webvictim** [comment]
Think this should work? What isn't it doing?

```sh
IMDS_TOKEN=$(curl -X PUT -H "X-aws-ec2-metadata-token-ttl-seconds: 300" http://169.254.169.254/latest/api/token)
IMDS_TOKEN_HEADER='-H "X-aws-ec2-metadata-token: ${IMDS_TOKEN}"'
LOCAL_HOSTNAME=$(curl -sS ${IMDS_TOKEN_HEADER} http://169.254.169.254/latest/meta-data/local-hostname)
```

**Comment by travelton** [comment]
@webvictim The interpretation of `${IMDS_TOKEN_HEADER}` doesn't seem to work out:
```
IMDS_TOKEN=$(curl -X PUT "http://169.254.169.254/latest/api/token" -H "X-aws-ec2-metadata-token-ttl-seconds: 300")
IMDS_TOKEN_HEADER="-H \"X-aws-ec2-metadata-token: ${IMDS_TOKEN}\""
LOCAL_HOSTNAME=$(curl -sS ${IMDS_TOKEN_HEADER} http://169.254.169.254/latest/meta-data/local-hostname)
curl: (6) Could not resolve host: AQAAADygm-JHZRaPtDnrtKW4tl4keasdfasdfasdfasdfasdfasdffjMpw=="
```

I believe I found the solution though... Wrap `${IMDS_TOKEN_HEADER}` in quotes. 
```
IMDS_TOKEN=$(curl -X PUT "http://169.254.169.254/latest/api/token" -H "X-aws-ec2-metadata-token-ttl-seconds: 300")
IMDS_TOKEN_HEADER="-H \"X-aws-ec2-metadata-token: ${IMDS_TOKEN}\""
LOCAL_HOSTNAME=$(curl -sS "${IMDS_TOKEN_HEADER}" http://169.254.169.254/latest/meta-data/local-hostname)
echo $LOCAL_HOSTNAME
ip-172-31-1-203.ec2.internal
```

**Comment by webvictim** [comment]
Excellent. Is this still a WIP or ready for review?

**Comment by travelton** [comment]
@webvictim WIP, need to test. Will convert to PR after building a test AMI and running through the various paths. Will finish up tomorrow morning.

**Review by webvictim — APPROVED** [review]
LGTM, thanks @travelton!

**Pull request merged**
