### PR TITLE
[v10]  Desktop Access simplify configuration of Active Directory

### PR DESCRIPTION
**Pull request by LKozlowski**
Backports: #15842

### CODE REVIEW

**Comment by LKozlowski** [comment]
Some checks are failing right now as I just realized that my changes depends on the other changes that are yet to be backported: https://github.com/gravitational/teleport/pull/16009 I think I have to wait until these changes gets merged into v10 branch.

**Review by zmb3 — APPROVED** [review]

**Comment by zmb3** [comment]
Looks like we have some conflicts to resolve.

**Comment by alexfornuto** [comment]
Should https://goteleport.com/docs/desktop-access/getting-started/#step-57-export-your-ldap-ca-certificate be updated to export the certificate in PEM format instead of DER?

**Comment by zmb3** [comment]
@alexfornuto not necessary, the old format still works for now, and we'll be doing a major rewrite of that guide when this feature lands.

**Review by alexfornuto — APPROVED** [review]

**Pull request merged**
