### PR TITLE
Remove unused SVG icons

### PR DESCRIPTION
**Pull request by bl-nero**
Contributes to https://github.com/gravitational/teleport/issues/44542.

### CODE REVIEW

**Comment by bl-nero** [comment]
Tested by verifying a handful of random views in web UI and Teleterm.

**Review by zmb3 — APPROVED** [review]
Awesome.

**Review by gzdunek — APPROVED** [review]
I was afraid that we could remove some icons by accident when backporting this PR, but if I'm correct, this would fail the TS check, no?

**Comment by bl-nero** [comment]
> I was afraid that we could remove some icons by accident when backporting this PR, but if I'm correct, this would fail the TS check, no?

Yes, the UI won't compile, and tests won't pass. I verified that.

**Pull request merged**
