### PR TITLE
Make Hardware Key unit test interactive

### PR DESCRIPTION
**Pull request by Joerger**
This PR updates some Hardware Key unit tests tests to also cover `hardware_key_touch`. This makes the test interactive as we don't currently have a way to mock PIV touch.

These tests aren't run by CI, but I use them when developing new PIV features like https://github.com/gravitational/teleport/pull/31743. In the future we can adapt these tests to mock touch (if possible) or replace it with a tool similar to `tsh bench` to troubleshoot PIV issues.

### CODE REVIEW

**Review by jakule — COMMENTED** [review]
I don't think that having an "interactive test' as a part of our test suite helps testing and I think it will be more confusing when you run the test suite, and something fails without any explanation.
IMO the benefitial would be:
1. Fully automate the test by simulating the touch (if possible)
2. create something similar to `tsh bench` that is part of `tsh` and allows you to test this feature manually. We could even ask our users to run this test when they have some issues with PIV.

**Comment by Joerger** [comment]
@jakule Fair enough, I've removed it from the test plan and updated the PR description. Right now I just to merge this PR as a prerequisite for https://github.com/gravitational/teleport/pull/31743 and https://github.com/gravitational/teleport/pull/31732

**Review by jakule — APPROVED** [review]
LGTM :see_no_evil:

**Comment by Joerger** [comment]
@rudream should be a quick review when you get a chance, thanks!

**Review by rudream — APPROVED** [review]

**Pull request merged**
