### PR TITLE
Add missing audit log fields for k8s sessions

### LINKED ISSUE #4055: Unable to Replay Interactive k8s Sessions, Web UI due to missing event field
### Description

**What happened**:
When running an interactive k8s session through Teleport w/ k8s support enabled, the session is labeled as non-interactive, and you are unable to replay through the Teleport web UI. If you downgrade the cluster to 4.2.10, the session is playable in the web UI. If you use tsh (4.2.10 and 4.3), the session is playable. 

**What you expected to happen**:
Interactive k8s sessions are recorded and accessible via Teleport web UI. 

**How to reproduce it (as minimally and precisely as possible)**:
1. Configure Teleport w/ k8s proxy
2. Launch an interactive session `kubectl run -i --tty --rm debug2 --image=busybox --restart=Never -- sh`.
3. Observe that the Teleport web UI does not show this as an active session. There is no option to join the session. 
4. End the interactive session. 
5. Observe that the session is listed in the audit log, but it shows as non-interactive and there's no way to replay the session. 
6. Using tsh, run `tsh play <session-id>`. 
7. Observe that it's possible to replay the interactive session from tsh. 

Selection_084_clean

Selection_083

### Environment
- Teleport version (use `teleport version`): 4.3.0 Enterprise
- Tsh version (use `tsh version`): 4.3.0 
- OS (e.g. from `/etc/os-release`): Ubuntu 18.04.4 LTS

- Where are you running Teleport? (e.g. AWS, GCP, Dedicated Hardware): GCP + Azure AKS

**Browser environment**

- Browser Version (for UI-related issues): Chrome 84.0.4147.89

**Relevant Debug Logs If Applicable**

- `tsh --debug`
- `teleport --debug`

session.end event:
```
{
  "code": "T2004I",
  "ei": 12,
  "event": "session.end",
  "namespace": "default",
  "proto": "kube",
  "sid": "e1b00ab4-99c5-4e02-a75f-f2829e9860ea",
  "time": "2020-07-15T16:59:02.497Z",
  "uid": "b9e283de-2d28-4f7c-88c1-89474c2770dd",
  "user": "travelton"
}
```

### PR DESCRIPTION
**Pull request by awly**
Added `interactive` as needed.
Added `server_hostname` and `server_addr` referring to the k8s endpoint.

Screenshot_2020-07-15 a local • Audit Log

Fixes https://github.com/gravitational/teleport/issues/4055

### CODE REVIEW

**Comment by alex-kovoy** [comment]
@awly  I just realized that it misses below fields as well.

```js
session_start: string;
session_stop: string;
participants?: string[];
```

**Comment by awly** [comment]
@alex-kovoy thanks for catching this, added.
`participants` will only have 1 entry, since today you can't join k8s exec sessions.

**Review by russjones — APPROVED** [review]

**Comment by awly** [comment]
retest this please

**Comment by awly** [comment]
retest this please

**Comment by awly** [comment]
retest this please

**Comment by awly** [comment]
retest this please

**Pull request merged**
