### PR TITLE
Fix TDP/RDP termination

### PR DESCRIPTION
**Pull request by ibeckermayer**
In https://github.com/gravitational/teleport/pull/13479 I cleaned up the Client's API and centralized the connection and memory cleanup, but I also [removed a deferred `c.Close()` from the streaming goroutines](https://github.com/gravitational/teleport/pull/13479/files#diff-27da86cebdfa8870a5999b5cb051103a7cfc23e41131139feab9b26e935a5915L243-L263). This change meant that in the most common case of the TDP input streaming goroutine erroring due to the browser tab being closed:
https://github.com/gravitational/teleport/blob/7c8da82ac05d6f01a4809bac03cc3550775173d7/lib/srv/desktop/rdp/rdpclient/client.go#L285-L287
the RDP streaming goroutine was no longer being terminated immediately, causing it to awkwardly hang around failing calls until the idle timeout (possibly relates to https://github.com/gravitational/teleport/issues/13723).

This change reintroduces the deferred `c.close()` to streaming goroutines and also adds insurance that the TDP connection is closed in `c.close()`, so that whenever one goroutine terminates, the other one isn't left far behind.

### CODE REVIEW

**Review by zmb3 — COMMENTED** [review]
I'm also curious how this behaves if windows terminates the connection - do we see any confusing warnings or errors in the console?

(test by killing/rebooting a windows VM during a session)

**Comment by ibeckermayer** [comment]
> I'm also curious how this behaves if windows terminates the connection - do we see any confusing warnings or errors in the console?
> 
> (test by killing/rebooting a windows VM during a session)

Good question -- the screen just freezes for a while (which is sorta confusing), until the rust rdp client times out here
https://github.com/gravitational/teleport/blob/6f93378199440f0265d49588dba56629094312eb/lib/srv/desktop/rdp/rdpclient/src/lib.rs#L619 (takes about 20sec or so).

Nothing too crazy looking in the logs:
```
2022-06-27T16:58:05-04:00 DEBU [PROC:1]    Broadcasting event. event:TeleportDegraded pid:11293.1 service/supervisor.go:376
[2022-06-27T20:58:07Z ERROR rdp_client] RDP read failed: Io(Os { code: 60, kind: TimedOut, message: "Operation timed out" })
2022-06-27T16:58:07-04:00 WARN [WINDOWS_D] Failed reading RDP output frame: 1 client-ip:::1 desktop-addr:172.16.97.147:3389 desktop-name:WIN-1E6JDI6PHQA-teleport-dev pid:11293.1 rdp-addr:172.16.97.147:3389 rdpclient/client.go:265
2022-06-27T16:58:07-04:00 WARN [WINDOWS_D] Failed reading TDP input message: read tcp [::1]:3028->[::1]:56465: use of closed network connection client-ip:::1 desktop-addr:172.16.97.147:3389 desktop-name:WIN-1E6JDI6PHQA-teleport-dev pid:11293.1 rdp-addr:172.16.97.147:3389 rdpclient/client.go:289
2022-06-27T16:58:07-04:00 INFO [WINDOWS_D] TDP input streaming finished client-ip:::1 desktop-addr:172.16.97.147:3389 desktop-name:WIN-1E6JDI6PHQA-teleport-dev pid:11293.1 rdp-addr:172.16.97.147:3389 rdpclient/client.go:290
[2022-06-27T20:58:07Z DEBUG rustls::conn] Sending warning alert CloseNotify
[2022-06-27T20:58:07Z ERROR rdp_client] failed writing RDP keyboard event: Io(Os { code: 32, kind: BrokenPipe, message: "Broken pipe" })
2022-06-27T16:58:07-04:00 DEBU [SSH:PROXY] Closed connection [::1]:56466. sshutils/server.go:449
2022-06-27T16:58:07-04:00 INFO [WINDOWS_D] RDP output streaming finished client-ip:::1 desktop-addr:172.16.97.147:3389 desktop-name:WIN-1E6JDI6PHQA-teleport-dev pid:11293.1 rdp-addr:172.16.97.147:3389 rdpclient/client.go:273
2022-06-27T16:58:07-04:00 WARN [WINDOWS_D] error closing the RDP connection client-ip:::1 desktop-addr:172.16.97.147:3389 desktop-name:WIN-1E6JDI6PHQA-teleport-dev pid:11293.1 rdp-addr:172.16.97.147:3389 rdpclient/client.go:529
2022-06-27T16:58:07-04:00 DEBU [WINDOWS_D] Windows desktop disconnected client-ip:::1 desktop-addr:172.16.97.147:3389 desktop-name:WIN-1E6JDI6PHQA-teleport-dev pid:11293.1 desktop/windows_server.go:758
2022-06-27T16:58:07-04:00 DEBU [WINDOWS_D] Releasing associated resources - context has been closed. client-ip:::1 desktop-addr:172.16.97.147:3389 desktop-name:WIN-1E6JDI6PHQA-teleport-dev pid:11293.1 srv/monitor.go:253
```


@zmb3

**Review by zmb3 — APPROVED** [review]

**Comment by ibeckermayer** [comment]
@nklaassen @LKozlowski PTAL when you next have a chance

**Comment by nklaassen** [comment]
sorry, misclicked on mobile.. will review

**Review by nklaassen — APPROVED** [review]
LGTM

**Pull request merged**
