### PR TITLE
Remove DEBUG env var from Connect macOS dronegen

### PR DESCRIPTION
**Pull request by ravicious**
It was added in an effort to debug flaky Connect builds (#15836).

However, we discovered that the v11.1.0 macOS version of Connect stopped working. This was likely due to upgrade of electron-builder which recently updated its process of building native deps
(electron-userland/electron-builder#7196).

In the Node.js ecosystem, the DEBUG env var is typically used to control which packages emit debug messages [1]. However, after the update of electron-builder, the env var also changed the behavior of one of the packages responsible for building the apps.

This was confirmed by inspecting file tree between different app bundles and running the build locally with DEBUG set to electron-*.

[1] https://www.npmjs.com/package/debug

---

Although we did run a CI build after upgrading electron-builder to test if everything is working, we didn't actually execute the artifact built by drone, so we missed the fact that the build was broken.

### CODE REVIEW

**Comment by ravicious** [comment]
@gzdunek @avatus I'm not backporting this to v10 because the electron-builder version used by v10 is not affected.

**Review by gzdunek — APPROVED** [review]

**Review by avatus — APPROVED** [review]

**Review by strideynet — APPROVED** [review]

**Comment by ravicious** [comment]
Running a v11 drone build with this change included to be double sure that it fixes the problem.

https://drone.platform.teleport.sh/gravitational/teleport/18072/26/1

**Comment by ravicious** [comment]
idk if it's our macOS builder or Apple servers but notarizing the app bundles is super slow today. I'm yet to make a dev build because the notarization jobs time out after 1 hour.

Since we're fairly confident that this is going to fix the problem and we reproduced the issue locally, I'm thinking of merging this straight away. Thoughts? @gzdunek @avatus

**Comment by avatus** [comment]
I say ship it!

**Comment by ravicious** [comment]
I downloaded 11.1.1-dev.ravicious.3 and I can confirm that it works.

**Pull request merged**
