### PR TITLE
[v15] Cache remote clients in Connect

### PR DESCRIPTION
**Pull request by gzdunek**
Backport https://github.com/gravitational/teleport/pull/38201 to branch/v15

Changelog: Significantly reduced latency of network calls in Teleport Connect.

### CODE REVIEW

**Review by ravicious — APPROVED** [review]
Let's not sell ourselves short, the changelog can say "Significantly reduced latency of network calls in Teleport Connect" for sure. ;)

Also, I think all PRs related to caching could be included in a single backport, couldn't they?

**Comment by gzdunek** [comment]
>Let's not sell ourselves short, the changelog can say "Significantly reduced latency of network calls in Teleport Connect" for sure. ;)

Done! :D 

>Also, I think all PRs related to caching could be included in a single backport, couldn't they?

All PRs are already included, https://github.com/gravitational/teleport/pull/38202 has been merged into https://github.com/gravitational/teleport/pull/38201 before merging to master.

Or you mean https://github.com/gravitational/teleport/pull/38955?

**Comment by ravicious** [comment]
Oh I forgot that #38955 is not yet merged. It probably doesn't make sense to wait for #38955 before backporting.

It's good that #38202 and #38201 are already included here.

**Review by espadolini — APPROVED** [review]

**Review by rosstimothy — APPROVED** [review]

**Comment by gzdunek** [comment]
Added https://github.com/gravitational/teleport/pull/38955.

**Pull request merged**
