### PR TITLE
Fix Suggested Role Spec for Enrolling New Resources

### PR DESCRIPTION
**Pull request by evanfreed**
I went to `Enroll New Resource` and for both `EC2 Instance` and `RDS PostgresSQL` I was given a suggested role:

```
# EC2 example
kind: role
spec:
  allow:
    rules:
    - resources:
      - integration
      verbs:
      - list
      - create
      - use
    - resources:
      - node
      verbs:
      - create
      - update
      - list
      - read
```

I copied this to my role but I got:

Screenshot 2023-11-21 at 4 28 04 PM

After review it looks like it's missing the `read` verb in the suggestion.  Feel free to let me know if this is the correct place to change this.

changelog: Add read verb to suggested role spec when enrolling new resources.

### CODE REVIEW

**Comment by ibeckermayer** [comment]
Tagging @rudream in on this, is there any particular reason `read` wasn't added in the first place. Do you or @kimlisa recall running into this during testing?

**Review by kimlisa — APPROVED** [review]
wow... this was a major oversight on my part, thanks for the fix!

**Comment by kimlisa** [comment]
@evanfreed could you also add `integrations.read` on this [line](https://github.com/gravitational/teleport/blob/18ddc39019c07f19c24949a6c54182e493991023/web/packages/teleport/src/Discover/Shared/AwsAccount/AwsAccount.tsx#L76) 

like this:

```ts
integrationAccess.create && integrationAccess.list && integrationAccess.use && integrationAccess.read;
```

**Comment by rudream** [comment]
> is there any particular reason read wasn't added in the first place.

@ibeckermayer not aware of any reason, seems to have just been an oversight.

**Review by rudream — APPROVED** [review]
LGTM once @kimlisa's comment is addressed

**Comment by evanfreed** [comment]
Should I backport this change? @rudream @kimlisa

**Comment by kimlisa** [comment]
@evanfreed yes it needs to be backported to branch/v13

**Pull request merged**
