### PR TITLE
Add CA rotation flows to the test plan

### PR DESCRIPTION
**Pull request by espadolini**
`tbot` testing is not addressed here, pending #13231.

### CODE REVIEW

**Comment by espadolini** [comment]
@jakule Does DB access look ok? Should we have something more specific?

@zmb3 Is the intended behavior for desktop access essentially the same as DB access, with manual cert exports? What should we add to the testplan?

@strideynet Could you add the tests that you think are appropriate for `tbot` and CA rotations? Feel free to append to this branch.

**Comment by strideynet** [comment]
[In my current PR to support CA rotation in `tbot`, I've added an entry to the test plan.](https://github.com/gravitational/teleport/pull/13231/files#diff-21a9eed06f7bde81542684f9dae173dfed4779616db7ed8a80236a95a3a6638a) but perhaps I ought to move that under this CA rotation section you've introduced.

**Comment by zmb3** [comment]
@espadolini yes, user CA rotations will require a new cert to be export and pushed out to AD. I'm not sure if we need a dedicated test plan section yet, as it's basically the same as connecting a brand new cluster.

For Teleport 11 I'd like to have a separate desktop CA. When this work happens I'll make sure the dev also updates the test plan and docs with guidance on how to do a rotation without breaking connectivity.

**Comment by jakule** [comment]
@espadolini Yes, but don't forget that v9 still uses HostCA to sign database certificates. Because of that there are a few edge cases when migrating from v9 to v10. I'm not sure if we want to add it the the test plan or just double check before v10 release.

**Comment by espadolini** [comment]
@jakule should that be part of the "CA rotation" section? Perhaps the migration check should be added to the DB access checklist - and perhaps even for just this version, not in the general testplan.

**Review by r0mant — APPROVED** [review]

**Comment by smallinsky** [comment]
> Yes, but don't forget that v9 still uses HostCA to sign database certificates. Because of that there are a few edge cases when migrating from v9 to v10. I'm not sure if we want to add it the the test plan or just double check before v10 release.

This is the case only for v9 v10 migration. For v11 release this point will be invalid so I'm not sure if we should add it to generic test plan regression.

**Review by smallinsky — APPROVED** [review]

**Pull request merged**
