### PR TITLE
Update configuration.go to use all auth_servers

### PR DESCRIPTION
**Pull request by nmaki**
Only the last provided auth_server was being used.
#593

### CODE REVIEW

**Comment by ErikThoreson** [comment]
+1

**Comment by klizhentas** [comment]
ok to test

**Review by klizhentas — APPROVED** [review]

**Comment by nmaki** [comment]
Any chance of seeing this fix in the next release?

**Comment by kontsevoy** [comment]
@nmaki yes!

**Comment by nmaki** [comment]
@kontsevoy awesome! thanks

**Comment by kontsevoy** [comment]
@nmaki does this fix solve the problem described in #593?

**Comment by nmaki** [comment]
@kontsevoy Yep.

**Pull request merged**
