### PR TITLE
Bump golang.org/x/crypto

### PR DESCRIPTION
**Pull request by codingllama**
See https://groups.google.com/g/golang-announce/c/-cp44ypCT5s/m/wmegxkLiAQAJ.

### CODE REVIEW

**Comment by russjones** [comment]
@codingllama Thanks for doing this. We did a few hacks to support SHA 2, let's double check to make sure this change and those don't conflict. I'll share some more details a bit later.

**Comment by russjones** [comment]
@codingllama This was the original PR were we added partial support for SHA2, can you investigate if there are any issues with upgrading?

https://github.com/gravitational/teleport/pull/3777

**Comment by codingllama** [comment]
Hey @russjones, regarding #3777 and related work, this is what I found so far:

* The relevant /x/crypto commit is https://github.com/golang/crypto/commit/b4de73f9ece8163b492578e101e4ef8923ac2c5c, which landed on 2021-Nov-15
* That commit got pulled to master on https://github.com/gravitational/teleport/pull/9205 - 2021-Dec-2

* Teleport versions without #9205 need both `HostKeyAlgorithms +ssh-rsa-cert-v01@openssh.com
` and `PubkeyAcceptedKeyTypes +ssh-rsa-cert-v01@openssh.com
` in their `~/.ssh/config` for ssh to interop with them
* Teleport versions after #9205 need only `PubkeyAcceptedKeyTypes` to interop, as that PR "fixes" SSH signature/kex (our certificates still use ssh-rsa-cert-v01@openssh.com, even though signing uses rsa-sha2-512-cert-v01@openssh.com)

I seem to consistently get `debug1: kex: host key algorithm: rsa-sha2-512-cert-v01@openssh.com` for versions after #9205 and `debug1: kex: host key algorithm: ssh-rsa-cert-v01@openssh.com` for versions before it (from `ssh user@host -v`)

My main takeaways are:

1. `tsh config` does not give me a config that works out of the box (missing `PubkeyAcceptedKeyTypes`)
1. I'm not sure if we ever addressed https://github.com/gravitational/teleport/issues/3742, or if it got a regression
1. It is likely possible to delete [AlgSigner](https://github.com/gravitational/teleport/blob/3f507dfd06d1e3f6ccc30ecae7704a163d77b55d/lib/sshutils/signer.go#L42)
1. None of the items above seems to be affected by the present PR, either negatively or positively, so it seems we should handle them separately.

Let me know if you find otherwise. Also, pinging @r0mant, in case he has something to add here.

**Comment by timothyb89** [comment]
> 1. `tsh config` does not give me a config that works out of the box (missing `PubkeyAcceptedKeyTypes`)

I added SSH client version checking to tbot in https://github.com/gravitational/teleport/pull/10833/files#diff-09af045b16fe645414d52afd3c02045be058196f42a5cf97de2c58509d50ba35, we can take advantage of that in tsh if needed. 

Anyway, I'm glad to see we've eliminated one necessary workaround with #9205 but it's a shame this doesn't help with `PubKeyAcceptedAlgorithms`. Looks like our server is still advertising `ssh-rsa-cert-v01@openssh.com` host certs even though key algorithms are sane:
```
debug1: Server host certificate: ssh-rsa-cert-v01@openssh.com SHA256:A6eToiM0COlZJkye0CdD5KbC0Qf5VTDrx2s9z8f1yNw, serial 0 ID "" CA ssh-rsa SHA256:Xo1GJ1wGD0ppgLaIbOpUjTsRDAfy0MdzytuRbBRUXCg valid after 2022-01-19T18:43:08
debug2: Server host certificate hostname: fe6806fa-4b96-4c34-903e-1bdeb1a39940.foo.example.com
debug2: Server host certificate hostname: fe6806fa-4b96-4c34-903e-1bdeb1a39940
```

**Comment by r0mant** [comment]
@marcoandredinis Can you please take over this PR and verify the following things:

- [ ] Upgrade to this branch from latest stable release (e.g. 9.1.3) and verify connectivity within cluster with `tsh` (with both 9.1.3 tsh and from this branch). I would suggest upgrading step-by-step, e.g.
  - [ ] Upgrade auth, verify connectivity.
  - [ ] Upgrade proxy, verify connectivity.
  - [ ] Upgrade SSH agent, verify connectivity.
- [ ] Verify connecting to Teleport cluster running this branch with different versions of OpenSSH client:
  - [ ] Pre 8.2 which supported SHA1.
  - [ ] 8.2 which deprecated SHA1.
  - [ ] 8.8 which removed SHA1 support.

We basically want to make sure that upgrading crypto/ssh here plays nicely with the workarounds implemented in https://github.com/gravitational/teleport/pull/3777 a while back.

**Comment by codingllama** [comment]
Sorry folks, I did mean to take this forward but got caught up in other work.

@marcoandredinis, feel free to close this one and open a PR of your own if that's simpler for you. Last I checked this one was still broken, but tbh I don't exactly remember what the problem was (just that the test failures are legit).

**Comment by marcoandredinis** [comment]
Closing as we already merged the lib bump

**Pull request closed without merging**
