### PR TITLE
RFD 20: Automatic rotation of about-to-expire CAs

### PR DESCRIPTION
**Pull request by andrejtokarcik**

### CODE REVIEW

**Comment by klizhentas** [comment]
@andrejtokarcik I really like where this is going. My ideal is to have a teleport setup that rotates CAs nightly by default. Can we come up with a setup that sets default ttl period for CAs? I think the more frequently we rotate CAs the better - the system will be tested. 

For example, we can combine your proposal with clusterconfig setting of CA ttl, and secuirty minded users can set it to 72h. Then your logic will kick in to rotate user and host CAs every 24h. What do you think?

**Comment by webvictim** [comment]
IMO our defaults should still be high to preserve the existing behaviour which many customers are used to. I know some customers add nodes to their clusters and then only bring them online when they're needed, so a 24 or even 72 hour default rotation period would be too low for them. Something like 3 months (similar to LetsEncrypt cert validity time) or one year would be a more sane default, also exposing a setting for this so that customers can override it themselves if desired. Then we also add the logic detailed in the RFD to automatically rotate CAs in advance of their expiry time.

**Comment by r0mant** [comment]
Another thing to keep in mind is database access. Right now we use host CA to sign certificates that users use to configure their self-hosted Postgres/MySQL instances. If we rotate the CA every few days, they would have to regenerate key/cert every few days and update their db servers as well since we don't have any control over those and can't do it automatically.

So we might also need to decouple "db access" CA from host CA in the context of this (https://github.com/gravitational/teleport/issues/5029).

**Comment by andrejtokarcik** [comment]
@klizhentas I've been thinking about such very short-lived CAs as well, however in its current form the RFD is pretty conservative w.r.t. our current defaults so it still uses the rotation grace period of 30 hours and it wouldn't work well with CA TTLs <= 15 days, as noted in the very last paragraph.

To account for your use case, the rotation grace period (as well as max cert duration) would have to be inferred from CA TTL as well. For example:
```
TTL = 72h [configured by user]

[rest inferred:]
AboutToExpirePeriod = max(TTL / 12, 24h) = 24h
MaxCertDuration = min(TTL / 72, 30h) = 1h
default CertDuration = MaxCertDuration / 2 = 30min
RotationGracePeriod = MaxCertDuration = 1h
``` 

BTW, as far as I can tell, we currently don't support having more than two CAs at a single time -- yet with increased rotation periodicity, having 3+ simultaneously active CAs could become a common occurrence.

**Comment by webvictim** [comment]
@r0mant raises a very good point - all the constraints mentioned for database access also apply to long-lived SSH/k8s certs generated via `tctl auth sign` and would require those certs to be regenerated whenever a CA was rotated. This would also change:
- the user CA fingerprint generated by `tctl auth export --type=user` which many people have installed on their OpenSSH servers to trust Teleport user certs
- the host CA fingerprint generated by `tctl auth export --type=host` which people use in their local `~/.ssh/known_hosts` files to trust Teleport hosts

Naturally good scripting and automation could reduce the impact of any such changes for customers who integrate Teleport with OpenSSH, but it's a substantial increase in friction plus more moving parts which could fail. Every rotation gives the potential for a node somewhere to miss an update and get out of sync.

**Comment by klizhentas** [comment]
Agree with your points folks. This shows that our CA rotation system needs more development. The secret to success is to support frequent CA rotation without breaking the system. Whether it's one month or 1 day, it should work on a regular basis.

Now, the tricky parts is to figure out what is a reasonable default, and how not to break backwards compatibility. When choosing our approach, we should use the most secure as the promoted default. 

So ideally we would promote Teleport to rotate CAs on the entire fleet on a regular basis, while letting users to opt out. DB access should not break when CA rotates, this needs to be fixed. 

@andrejtokarcik I like the automatic defaults too. Can we come up with a design, that's lets say will set a 3 month period by default for new clusters, and let people set a longer TTL, that will be also set for all existing clusters?

**Comment by andrejtokarcik** [comment]
> Can we come up with a design, that's lets say will set a 3 month period by default for new clusters, and let people set a longer TTL, that will be also set for all existing clusters?

This could be an agreeable approach:

* Introduce `auth_service` options for configuring CA TTLs (whether a common value or per CA type, doesn't matter).
* These options would belong to a dynamically configurable resource so that Teleport Cloud users could tinker with these as well.
   * NB: Should this dynamically configurable resource be `cluster_config` itself, some of its current fields like `audit` and `cluster_id` should be moved to another resource since these shouldn't be modifiable via `tctl`.
* This resource would come with two sets of defaults, let's call them `DefaultSafe` [CA TTL = 3 months] and `DefaultConservative` [CA TTL = 1 year; this change already discussed in the RFD should be OK even for existing customers].
  * `DefaultSafe` would be used inside `service.MakeDefaultConfig`.
  * `DefaultConservative` would *not* have the `origin: defaults` label.
* In case the data dir is found not to exist (i.e. it's a fresh Teleport cluster) and the merged configuration (defaults -> file-based conf -> CLI conf) ends up with `DefaultSafe`, this `DefaultSafe` would be replaced with `DefaultConservative` (in the course of `service.NewTeleport` or similar) so `DefaultConservative` would ultimately be stored in the backend.
* Since `DefaultConservative` doesn't have `origin: defaults`, when it gets fetched from the backend during a consecutive startup, it would be seen as explicit dynamic configuration and wouldn't get overwritten with `DefaultSafe` during the next auth server initialization.

However, this goes beyond the humble scope of the present RFD. Of course, I can extend it in this direction if that's deemed desirable.

**Comment by klizhentas** [comment]
> However, this goes beyond the humble scope of the present RFD. Of course, I can extend it in this direction if that's deemed desirable.

I would extend the definition of this RFD, and may be planned for it as a part of our Certificate authority work with @awly

**Comment by awly** [comment]
A few thoughts:
- let's avoid a layer of indirection with named TTLs (Default/Hardened); expose the actual duration values to the user to tweak
- the defaults should consider an "average" user, in my mind that's:
  - 10-500 nodes, always online, using ssh/k8s/db/app and/or trusted clusters
  - not using OpenSSH servers or nodes that go offline for hours
  - config knobs should be available for those less common cases
- we need a good answer for automation creds (e.g. databases, CI bots using `tctl auth sign`-generated certs, etc)
  - this could be as simple as a daemon that rotates certs stored in a directory and sends a signal to another PID on change
- rotation-related periods should be inferred from CA TTL
  - except for user cert duration; our current user cert duration should be a natural lower bound for CA TTL
- user CA and host CA can be treated separately
  - user CA is more dynamic and can be rotated as fast as user certs are
  - host CA (+DB CA and JWT signer) can move more slowly to reduce risk and traffic overhead

**Comment by russjones** [comment]
Converting this to draft, until we have time to actively work on this.

**Comment by codingllama** [comment]
Closing PR for now, if we elect to pick this up again in the future we can reopen.

**Pull request closed without merging**
