### PR TITLE
Refactor admin action test suite

### PR DESCRIPTION
**Pull request by Joerger**
Refactor admin action tctl tests to use testify/suite for shared setup/teardown.

This should unblock my open PRs (ex: https://github.com/gravitational/teleport/pull/35464)  where the flaky test detector is timing out trying to diff all test cases.

### CODE REVIEW

**Review by zmb3 — COMMENTED** [review]
Why exactly do we need this? It looks like we now have 3 or 4 levels of nested subtests which seems a bit much.

**Comment by Joerger** [comment]
@zmb3 Without this refactor, the flaky test detector is timing out on my PRs trying to run all test subcases of `TestAdminActionMFA`. The flaky test detector has a condition for `testify/suite`s where it only runs the changed subcases instead of all of them.

As for the deeper sub cases, I could remove a couple layers if we think it's too confusing and not worth the shared code.

**Comment by zmb3** [comment]
> The flaky test detector has a condition for testify/suites where it only runs the changed subcases instead of all of them.

Got it - that's the piece I was missing. Thanks for clarifying.

**Review by zmb3 — APPROVED** [review]

**Review by tigrato — APPROVED** [review]

**Comment by Joerger** [comment]
@r0mant @zmb3 Can I get a flaky test skip?

**Pull request merged**
