### PR TITLE
bot: require admin approval for large PRs

### LINKED ISSUE #11861: Leave a comment on PRs that are too large
Leave a nice comment nudging the PR author to reduce the size of PR to make it easier to get a high quality review. Ignore `_test.go` and generated protobuf code.

### PR DESCRIPTION
**Pull request by zmb3**
This check requires that PRs which add > 1500 lines of new code
require an admin approval in order to be merged. Autogenerated files are excluded from this metric.

The majority of regressions and security issues recently can be traced back to a large PR. This change will encourage smaller PRs that are easier to review and reason about, while still making it possible to merge larger changes with an admin approval.

Closes #11861

### CODE REVIEW

**Comment by ravicious** [comment]
It'd be best if this was communicated to the PR author before the PR is made, like "This PR is over _X_ lines of code, so it'll require admin approval", or at least after the fact by the bot as a comment under the PR or in some other way.

I haven't checked the code, but it'd also be nice if it was possible to get rid of the requirement if the PR is reduced in size. But I guess the workaround here would be to close the PR and open a new one.

**Comment by russjones** [comment]
Might want to leave a comment on the PR explaining it's blocked until approved by an admin due to size. Will improve the UX. See https://github.com/gravitational/teleport/blob/master/.github/workflows/robot/internal/bot/backport.go#L197-L213

**Comment by ravicious** [comment]
Oh, one more thing: should we exclude automatically generated files in this check?

#13476 has 1316 changed lines total and 1090 of them are due to regenerating protobuf files for Go and JavaScript. 735 from those 1090 are additions.

**Comment by zmb3** [comment]
@ravicious this is why I'm looking at additions - deletions.

#13476 would have gone through without any approvals, as additions - deletions is only about 500 lines, well below the 1500-line threshold.

Happy to tweak the parameters if we see evidence of multiple PRs held up that shouldn't have been, but I don't see any issue with this particular example.

**Review by r0mant — APPROVED** [review]

**Review by russjones — APPROVED** [review]

**Comment by capnspacehook** [comment]
@zmb3 #13491 would fail this check due to 4525-2737=1788 changed lines, where as 3809-2706=1103 of those lines are from generated protobuf files. I believe the PR is small, as only 685 changed lines are directly from me. What would be the potential downside of ignoring generated files?

**Comment by zmb3** [comment]
@capnspacehook on first glance that looks like a PR that while technically may be smaller than it appears, it's still pretty intimidating as a reviewer. If I were to open that I would probably set it aside for later as soon as I see +4500 lines rather than reviewing it on the spot.

There are a number of ways you could have broken this up into more manageable pieces. For example, committing the protobuf changes separately, or adding the audit events in a separate PR after you got the core functionality working.

(I have also reviewed this PR several times, so you would have had my approval anyway if this were being enforced)

**Comment by capnspacehook** [comment]
@zmb3 thanks for the feedback, I'll try to make future PRs smaller and more manageable.

**Pull request merged**
