### PR TITLE
chore: Bump gci and golangci-lint

### PR DESCRIPTION
**Pull request by codingllama**
Update gci to v0.9.1 and golangci-lint to v1.51.2.

* https://github.com/daixiang0/gci/releases/tag/v0.9.1
* https://github.com/golangci/golangci-lint/releases/tag/v1.51.2

### CODE REVIEW

**Comment by codingllama** [comment]
I do get a diff when running `make fix-imports`, but that's already present on master, so it's not a regression. See the snippet below:

```diff
gci diff -s standard -s default -s 'prefix(github.com/gravitational/teleport)' --skip-generated ./integrations/operator/


--- integrations/operator/main.go
+++ integrations/operator/main.go
@@ -41,7 +41,6 @@
 	resourcesv5 "github.com/gravitational/teleport/integrations/operator/apis/resources/v5"
 	"github.com/gravitational/teleport/integrations/operator/controllers/resources"
 	sidecar2 "github.com/gravitational/teleport/integrations/operator/sidecar"
-	//+kubebuilder:scaffold:imports
 )

 var (
--- integrations/operator/controllers/resources/suite_test.go
+++ integrations/operator/controllers/resources/suite_test.go
@@ -51,7 +51,6 @@
 	"github.com/gravitational/teleport/lib/modules"
 	"github.com/gravitational/teleport/lib/service/servicecfg"
 	"github.com/gravitational/teleport/lib/utils"
-	//+kubebuilder:scaffold:imports
 )

 func fastEventually(t *testing.T, condition func() bool) {
```

There's already a `//nolint:goimports,gci` in those files, so it doesn't impact CI. Still, it would be nice if we could figure out a way to make `gci` ignore them when formatting.

FYI @hugoShaka.

**Comment by codingllama** [comment]
FYI @jakule

**Comment by jakule** [comment]
@codingllama I don't mind updating to the latest, but I also think that maybe we should keep `gci` and `golanglint-ci` "in-sync". The latest release notes mention 0.9.1 https://github.com/golangci/golangci-lint/releases/tag/v1.51.2

Looks also like the fix for that particular issue is reported in gci https://github.com/daixiang0/gci/issues/135 and should be fixed in https://github.com/daixiang0/gci/pull/136 which was released as v0.9.1 https://github.com/daixiang0/gci/compare/v0.9.0...v0.9.1

**Review by jakule — APPROVED** [review]

**Comment by codingllama** [comment]
Both 0.9.1 and 0.10.0 drop the `//+kubebuilder:scaffold:imports` comment for me.

Keeping in sync with golangci-lint seems reasonable, or at least keeping in the same minor. Let me do that here.

**Comment by codingllama** [comment]
PTAL - updated golangci-lint to the latest patch and gci to the same version it uses.

**Comment by codingllama** [comment]
Note that `gci --version` prints `0.9.0`, even though it's really `0.9.1`:

```shell

$ make enter
$ gci --version
> gci version 0.9.0
```

**Review by greedy52 — APPROVED** [review]

**Review by jakule — APPROVED** [review]

**Pull request merged**
