### PR TITLE
Merging webapps into teleport 

### PR DESCRIPTION
**Pull request by hatched**
In order to reduce development and deployment complexity this merges the `webapps` repository into `teleport`.

RFD: https://github.com/gravitational/teleport/blob/master/rfd/0089-merge-webapps.md

### CODE REVIEW

**Comment by ravicious** [comment]
I assumed that we're going to keep the commit hashes, wouldn't that be possible with multiple remotes and the `--allow-unrelated-histories` approach? https://stackoverflow.com/a/20974621/742872

We'd have a remote that has all of webapps history up until today and then a separate commit which moves everything into `web`. From what I see, the commits in this PR are reapplied to the same files but under `web` so naturally the commit hash has to change.

**Comment by ravicious** [comment]
Maybe it's not that important after all, I did `git log --grep="[a-f0-9]\{3,\}\b"` and there's like only one commit that's not a revert and intentionally mentions another commit by hash. I was just excited to see the commits untouched since I've learned that it's a thing that's possible. ;f

**Comment by codingllama** [comment]
@hatched, this is naturally to much to review with a naked eye, my browser is throwing a slight fit just by trying to view the files.

I see that there is the web/ folder and that there are changes outside of it. Could we:

1. Pull in web/, and do just that, in a PR; then
2. Do whatever changes to build scripts in another PRs, so those can be reviewed.

For (1), since it's a boatload of code, could you include the commands you did to create the PR, so we can at least sanity check those?

**Review by codingllama — CHANGES_REQUESTED** [review]
(See previous comment.)

**Comment by hatched** [comment]
@codingllama the `web` stuff has been pulled in in a single commit and the build changes are in the others so you can view those changes separately. The commands run to perform this merge contain some proprietary information so I'll send it to you separately.

**Pull request closed without merging**
