### PR TITLE
Update wasm-pack to 0.13.1

### PR DESCRIPTION
**Pull request by zmb3**

### CODE REVIEW

**Comment by zmb3** [comment]
In draft until I can complete a tag build.

**Review by jakule — APPROVED** [review]
LGTM, assuming that the tag build works.

**Comment by zmb3** [comment]
Tag build has some failures, some seem related but others look transient: https://github.com/gravitational/teleport.e/actions/runs/10001732513/job/27645901952

I'll let this sit for a while and revisit after Cam's new cross-compiling buildbox lands.

**Comment by zmb3** [comment]
Running a new tag build: https://github.com/gravitational/teleport.e/actions/workflows/tag-build.yaml

**Comment by camscale** [comment]
> Looks like this one fails too. @camscale any ideas?

@zmb3 I'll look into this in the coming week - I'm back to migrating the build to the new buildbox so I'll see how it goes with the new version of wasm-pack.

**Comment by zmb3** [comment]
Looks like wasm-pack 0.13 now requires cmake to be installed on the host due to a new transitive dependency.

A [PR to fix this](https://github.com/rustwasm/wasm-pack/pull/1407/) was merged months ago, but wasm-pack hasn't made a new release including the change.

**Review by rosstimothy — APPROVED** [review]

**Review by jakule — APPROVED** [review]
LGTM

**Review by r0mant — APPROVED** [review]

**Pull request merged**
