### PR TITLE
Implement #1456: ansible dynamic inventory for tsh

### PR DESCRIPTION
**Pull request by halfa**
> **NOTE**
> This is a retake of PR #1564 but rebased against `branch/2.4.0` and targeting  `teleport/tsh-ansible` instead of the `2.3.x` frozen branch

This pull request is a rough implementation of the feature described in #1456. It allows the `tsh` client to output the node list in a format compatible with `ansible` dynamic inventory as described on [the ansible doc](http://docs.ansible.com/ansible/latest/dev_guide/developing_inventory.html). It also implements the `--list` and `--host` flags.

#### How you can test it

Create a script with your `tsh` configuration (here `inventory.sh`):
```
#!/bin/bash
tsh --proxy=<url>:<port> --user=<user> --login=<login> ls --format=json "$@"
```
Then we can pass this file as a dynamic inventory provider to `ansible`. Don't forget to `tsh login` beforehand!
```
ansible -i inventory.sh -m ping -e ansible_ssh_user=<user> -e ansible_ssh_port=<teleport_node_port> all
```
There is also a second flag, `format=ansible-static`, which output a static inventory if necessary as described in #1456, and some tests for JSON marshaling stability.

As of why I choose to implement groups based on labels and not to populate `_meta`, that's because it was easier for writing playbooks, but I'll be happy to change this behavior if needed.

### CODE REVIEW

**Comment by halfa** [comment]
> From @stanchan in #1564
> I've been testing this on branch/2.4 and it works great! Thanks for implementing this @halfa. Just wanted to suggest a change in how the label works. It doesn't seem practical to create groups for every label in teleport. This is especially true if you have commands associated with some of them. Maybe having any label with Ansible as the value be assigned to that given group or a comma delimited set of groups for each node, like ansible_groups, be a more useful feature?

Basically from my POV we got two options:

- implement labels as `ansible_vars` values, meaning that you have to run your playbook against all the nodes and test the values in the task with `when: <label> is defined` and `when: <label> == <value>`
- the current group : `label-value` hack, that can _still_ be tested as a value with something like `when: inventory_hostname in groups['<label>-<value>']` in your playbook.

Can you provide an example for your third solution ?

**Comment by klizhentas** [comment]
@halfa keep in mind that you will have to address PR comments from previous PR first.

**Comment by stanchan** [comment]
The most common scenarios that I've seen Ansible users, both CLI and AWX/Tower, utilize are inventory directories separated by environments (e.g. development, staging, production) with host_vars and group_vars organized between them. Most playbooks would be written with host targets defined by type and each environment would have a separate dynamic inventory to populate hosts. In Teleport, I would imagine most users would utilize a label (e.g. environment) to filter on specific hosts and provide the correct output from the servers that belong to that environment. If we follow that pattern, we can provide a dynamic inventory that can return an inventory specific to an environment and use roles in playbooks to target appropriate servers within that environment.

`{
    "databases": {
        "hosts": ["host1.example.com", "host2.example.com"],
        "vars": {
        }
    },
    "webservers": {
        "hosts": ["host2.example.com", "host3.example.com", "host4.example.com"],
        "vars": {
        },
    "all": {
        "children": ["webservers", "databases"]
        "vars": {
        },
    },
    "_meta": {
        "hostvars": {
            "host1.example.com": {
                "environment" : "production"
            },
            "host2.example.com": {
                "environment": "production"
            }
        }
    }
}`

http://docs.ansible.com/ansible/latest/playbooks_best_practices.html

**Comment by halfa** [comment]
@klizhentas I believe your comments have been addressed by the latest set of commit (pushed in previous PR). Did I miss something?

**Comment by halfa** [comment]
@stanchan I agree this model is nice on paper, but how do you differentiate between labels targeting groups and labels targeting vars ? To give you some food for though, here is a sample of the data gathered by labels on our cluster:
```
apache=absent,elasticsearch=absent,haproxy=absent,hostname=<hostname>,kernel=4.4.0-109-generic,mysql=absent,os=ubuntu16.04,teleport=v2.3.5,varnish=absent
```
We proceed by deploying on all nodes a set of discovery scripts that return status and version if needed, and then use this data in the inventory and in AWX to run playbooks. IMHO, this data is much more relevant as a group than abstract labels that needs to be managed (like `staging` or `production`). You can still nonetheless fill your use-case by pushing a label named `group` with different values for each environment.

**Comment by kontsevoy** [comment]
I am now leaning towards implementing a vendor-neutral JSON output which a user can pipe into their own provder-specific filter to generate inventories of any desired format, i.e.

```
$ tsh ls --format=json | tsh-to-ansible > inventory.json
```

**Comment by halfa** [comment]
@kontsevoy 
> offers great points about the fact that teleport data model does not fit into Ansible directly. A "proper" implementation of flexible Ansible-compatible output looks almost like a SQL query to me with a GROUP BY clause

I respectively disagree with you, the Ansible data model is flexible for a reason, and while there _are_ recommended way to proceed when building an inventory system from scratch, I don't think that's what `teleport` was made for. So I don't see any wrongdoing in fitting the inventory format to the data when applied to a foreign API, especially when the resulting inventory format _still_ allows you to run Ansible Galaxy playbooks against it.

> A generic, well-documented JSON output looks like a better way to go.

Implementing a vendor neutral JSON output should be as simple as marshaling the node API struct IMHO, but the `ths-to-ansible` will be a pain to write. In fact, that's the main reason I started to patch `teleport` in the first place: I would rather patch a well-documented Go software than implement a parser/filter for the output to meet my need.

I've spend too much time on this one already. I'm still open for questions, but I won't advocate any further. If nobody's for merging it, I'll maintain a patch on my side and that's it. Glad the `teleport` code is well written and well documented, it's a breeze to work with.

**Comment by stanchan** [comment]
@halfa I completely agree with your position. I don't think there is anything wrong you implementation. I was just bringing up the possibility of supporting any other tool that might use Teleport as a 'source of truth' using the feature that you've worked on. The question would be if we want to support many different formats on a per implementation basis (like a plugin system in teleport) or if we could use a more generic format to possible enable a simple integration path to many different inventory systems. Examples of this would be Puppet External Node Classifiers [https://puppet.com/docs/puppet/5.3/nodes_external.html](https://puppet.com/docs/puppet/5.3/nodes_external.html) or Salt Master Tops Modules [https://docs.saltstack.com/en/latest/topics/master_tops](https://docs.saltstack.com/en/latest/topics/master_tops) which use YAML as input. Either way, I don't see how it would result in a lot of code that would need to be maintained to integrate to a target system (Ansible, Puppet, Salt...). I'll also be happy to maintain the Ansible side of the dynamic inventory scripts for this.

**Comment by klizhentas** [comment]
I spent some time thinking about this. I'm leaning towards using `jsonnet` library support in teleport. Here's how it will work:

```
tctl export --format=json --transform=ansible.jsonnet
```

Where ansible.jsonnet will be officially supported transformation of json output to the ansible format.

That should not be too hard to implement, especially because there is native jsonnet library now managed by Google folks.

This will solve the problems of outputing it in too specific format and will allow everyone to modify ansible.jssonnet and write new ones for other software products with different formats.

**Comment by kontsevoy** [comment]
Moving it to #1696 for now
@halfa thanks for the PR, we'll find a way to incorporate your changes soon!

**Pull request closed without merging**
