### PR TITLE
Update protoc to v3.20.1

### PR DESCRIPTION
**Pull request by jakule**
Update protoc to v3.20.1 and re-generate all protobufs as this is the latest version that works with Teleport Connect build.

There is no particular bug that this update will fix for us. Last week I realized that we hadn't updated our protoc for about 2 years and I'm unaware of why we shouldn't.

### CODE REVIEW

**Review by capnspacehook — APPROVED** [review]

**Review by espadolini — APPROVED** [review]

**Review by hatched — APPROVED** [review]

**Comment by zmb3** [comment]
Should we include the Teleport Connect protobufs in scope here as well?

cc @ravicious

**Review by ravicious — CHANGES_REQUESTED** [review]
3.21 seems to have removed the ability to generate JS files and breaks `make grpc-teleterm`.

Here's an issue about it in https://github.com/protocolbuffers/protobuf-javascript/issues/105 And here's a PR that removed JS support https://github.com/protocolbuffers/protobuf/pull/9874

The author of that issue says:

> I actually found \<the PR that removes JS support\> before I ran into this problem. I decided to follow the GitHub repos, leading me to this repo, where the documentation provides instructions for how to use Protobuf with JavaScript. I created this issue because when I followed those instructions, it didn't work.

I'm checking if downgrading to 3.20.1 helps, I'll follow up in a sec.

**Review by ravicious — APPROVED** [review]
I suppose this will be merged to master only so before backporting any protobuf changes to v10 and earlier we'll need to regenerate the files, right?

**Comment by ravicious** [comment]
This was added to [protobuf-javascript's README](https://github.com/protocolbuffers/protobuf-javascript#project-status-as-of-july-2022) two weeks ago:

> Project Status as of July 2022
>
> This project is currently in a somewhat broken state that we are working to rectify. We expect to have updated releases by the end of July 2022.
> 
> Support Status
>
> Protobuf JavaScript is widely used and well maintained internally at Google but does not currently have staffing for more than minimal support for this open source project.

**Pull request merged**
