### PR TITLE
[v10] Filter out internal teleport defined logins (#23400)

### PR DESCRIPTION
**Pull request by kimlisa**
backport #23400 on to branch/v10

cc @Erick-Reyes

### CODE REVIEW

**Review by ryanclark — APPROVED** [review]

**Review by zmb3 — APPROVED** [review]

**Comment by kimlisa** [comment]
closing, re-opening to re-trigger ci

**Comment by Erick-Reyes** [comment]
Is there an ETA for the next v10 release? @kimlisa

**Comment by zmb3** [comment]
It should be in 10.3.15, what makes you think it's not?

**Comment by Erick-Reyes** [comment]
Hey, @zmb3. I didn't see it in the changelog for `v10.3.15` release. However, just confirm this is part of that release. Ty.

**Pull request merged**
