### PR TITLE
Fix tsh cloud app role issue

### LINKED ISSUE #43842: 16.0.3: `tsh aws` fails demanding that `--aws-role flag is required`
Expected behavior:

tsh aws commands do not ask for `--aws-role` 

Current behavior:
1. Login to the app:
```
tsh apps login security-it-prod --aws-role teleport-administrator-role
Logged into AWS app "security-it-prod".

Your IAM role:
  arn:aws:iam::XXXXXXX:role/pipeline-roles/teleport-administrator-role

Example AWS CLI command:
  tsh aws s3 ls

Or start a local proxy:
  tsh proxy aws --app security-it-prod
```

2. Try a tsh aws command:
```
tsh aws s3 ls
Available AWS roles:
Role Name                   Role ARN
--------------------------- -------------------------------------------------------------------------
teleport-administrator-role arn:aws:iam::XXXXXXX:role/pipeline-roles/teleport-administrator-role
teleport-readonly-role      arn:aws:iam::XXXXXXX:role/pipeline-roles/teleport-readonly-role

ERROR: --aws-role flag is required
The tsh aws command does not need --aws-role  it also doesn't understand it.
tsh aws --aws-role teleport-administrator-role s3 ls
tsh: error: unknown long flag '--aws-role'
usage: tsh aws [<flags>] [<command>...]

Access AWS API.

Flags:
  -l, --login                    Remote host login
      --proxy                    Teleport proxy address
      --user                     Teleport user, defaults to current local user
      --ttl                      Minutes to live for a session
  -i, --identity                 Identity file
      --cert-format              SSH certificate format
      --[no-]insecure            Do not verify server's certificate and host name. Use only in test environments
      --auth                     Specify the name of authentication connector to use.
      --[no-]skip-version-check  Skip version checking between server and client.
  -d, --[no-]debug               Verbose logging to stdout
  -k, --add-keys-to-agent        Controls how keys are handled. Valid values are [auto no yes only].
      --[no-]enable-escape-sequences
                                 Enable support for SSH escape sequences. Type '~?' during an SSH session to list supported sequences. Default is enabled.
      --bind-addr                Override host:port used when opening a browser for cluster logins
      --callback                 Override the base URL (host:port) of the link shown when opening a browser for cluster logins. Must be used with --bind-addr.
      --mfa-mode                 Preferred mode for MFA and Passwordless assertions (auto, cross-platform, platform, otp)
      --[no-]headless            Use headless login. Shorthand for --auth=headless.
      --mlock                    Determines whether process memory will be locked and whether failure to do so will be accepted (off, auto, best_effort, strict).
      --piv-slot                 Specify a PIV slot key to use for Hardware Key support instead of the default. Ex: "9d"
  -J, --jumphost                 SSH jumphost
      --app                      Optional Name of the AWS application to use if logged into multiple.
      --exec                     Execute different commands (e.g. terraform) under Teleport credentials

Args:
  [<command>]  AWS command and subcommands arguments that are going to be forwarded to AWS CLI.

Aliases:

ERROR: unknown long flag '--aws-role'
```

Bug details:
- Teleport version: 16.0.3
- Recreation steps: See above
- Debug logs: See above

### PR DESCRIPTION
**Pull request by Joerger**
Active app logins were having their cloud role overwritten by `appInfo.checkAndSetDefaults`, which was added in https://github.com/gravitational/teleport/pull/40985.

Also adds the cloud role flags to `tsh aws/azure/gcloud/gsutil` to support first login through these commands.

Fixes https://github.com/gravitational/teleport/issues/43842

Changelog: Fix an issue where `tsh aws`, `tsh azure`, and `tsh gcloud` would fail for users with more than one AWS, Azure, or GCP service role available.

### CODE REVIEW

**Review by flyinghermit — APPROVED** [review]
LGTM, but I haven't tested `tsh aws ...` command build with this patch.

**Review by zmb3 — APPROVED** [review]

**Comment by Joerger** [comment]
@zmb3 Can I get a flaky test skip? Both `TestAzure` and `TestAws` take ~7s

**Comment by Joerger** [comment]
@rosstimothy Can I get a flaky test skip?

**Comment by RomuloGatto** [comment]
Still happening on 16.1.0

**Pull request merged**
