### PR TITLE
[branch/5] web UI disconnects

### PR DESCRIPTION
**Pull request by a-palchikov**
Backport of https://github.com/gravitational/teleport/pull/5276.

Updates https://github.com/gravitational/teleport/issues/5265.

### CODE REVIEW

**Review by webvictim — APPROVED** [review]
Backport rubberstamp

**Review by alex-kovoy — APPROVED** [review]

**Comment by alex-kovoy** [comment]
@kimlisa could you verify if this change does not break Access Requests?

**Review by kimlisa — APPROVED** [review]
tested ui for access request and waiting room, against this branch and 5.0 branches checked out for other repos

**Comment by alex-kovoy** [comment]
@a-palchikov can we merge it?

**Pull request merged**
