### PR TITLE
Bump UI Role version to `v7`

### PR DESCRIPTION
**Pull request by tigrato**
This PR bumps the default Role version to `v7`.
The version is controlled by a fixed asset in web package as was never updated

### CODE REVIEW

**Review by rosstimothy — APPROVED** [review]
Maybe we should add a comment somewhere closer to the role that links here so that if/when we bump the version again we don't forget this?

**Review by zmb3 — APPROVED** [review]

**Comment by zmb3** [comment]
Was role v7 backported all the way to Teleport 12?

**Comment by tigrato** [comment]
> Was role v7 backported all the way to Teleport 12?

No. The backport for v12/v13 will be for v6

**Comment by zmb3** [comment]
So we might as well remove the v12 and v13 backport labels, right?

**Comment by tigrato** [comment]
> So we might as well remove the v12 and v13 backport labels, right?

I prefer to keep the history of this backport - I need to update v12 and v13 to v6 anw -   but since that even the title will change, I will remove them

**Comment by tigrato** [comment]
- v13: https://github.com/gravitational/teleport/pull/32335
- v12: https://github.com/gravitational/teleport/pull/32336

**Pull request merged**
