### PR TITLE
Clean up AWS EKS Guide

### PR DESCRIPTION
**Pull request by benarent**
This PR cleans up our EKS guide and redirects users to our Getting started with Kubernetes guide.

### CODE REVIEW

**Comment by benarent** [comment]
PTAL @klizhentas I removed this content as it was out of date when using the new helm chart.

**Comment by benarent** [comment]
@webvictim PTAL, as this removes old EKS guide which will be replaced by your new chart

**Review by webvictim — APPROVED** [review]
LGTM. We can replace this link with a direct link to the new EKS guide once it's live.

**Review by klizhentas — CHANGES_REQUESTED** [review]
Why not remove this file altogether and set up a redirect in config.json?

**Comment by klizhentas** [comment]
@benarent ping

**Comment by benarent** [comment]
> Why not remove this file altogether and set up a redirect in config.json?

This content was embedded in https://goteleport.com/docs/aws-oss-guide/ . Which outlines a few other AWS specific setup concerns, such as IAM setup and DynamoDB Setup.  There wasn't a standalone page to redirect to.

**Comment by inertial-frame** [comment]
Are we planning on merging all of the Infrastructure content? https://github.com/gravitational/teleport/issues/6391 - I don't see the Section in there. 

I'd think we can remove the EKS stuff and keep the rest per @benarent's plan since the rest of the AWS items don't appear listed anywhere else presently.

We can probably "cannibalize" (yes, scare-quotes) and move these Infrastructure guides into the new Setup Section?

By the way, a more detailed layout is available here: https://github.com/gravitational/teleport/blob/01e364875dc78cd906087d4aa2049636ffe364cb/docs/layout.md

**Comment by klizhentas** [comment]
Yes, I'd move all those to 'Setup' section. Not sure what @benarent do you mean by parts of the guide being referenced elsewhere, there is no content remained after changes. I'd simply remove this section altogether.

**Comment by benarent** [comment]
Sorry I was confused with all of the rebasing and docs in flight. I can see how it's empty of content now.

 I'll update this to remove this section.

**Review by klizhentas — APPROVED** [review]

**Comment by benarent** [comment]
_fixing the merge conflict_

**Pull request merged**
