### PR TITLE
remove db name checkers for protocols

### PR DESCRIPTION
**Pull request by GavinFrazar**
This PR removes db name checkers for snowflake and Oracle.

## Why

We do not intend to enforce db name RBAC for these protocols, and we do not document it.
Our docs state:
> Database names are only enforced for PostgreSQL and MongoDB databases.

Currently, we enforce RBAC checks for Snowflake and Oracle at connection time.
However we do not enforce RBAC if an already connected user switches db name.

If a user tries e.g. `tsh db connect snowflakedb --db-user=alice --db-name=prod` and they get an access denied error message about connecting to the "prod" db name, this may give a user the false impression that our docs are simply out of date; they may think they can rely on Teleport RBAC to enforce db name access control.

Snowflake: `--db-name` is the snowflake db warehouse. A user can issue `USE WAREHOUSE <some-warehouse>` command after connecting. They could, for example, do `tsh db connect snowflakedb --db-user=alice --db-name=dev`, pass RBAC checks for `dev` warehouse, and then switch to the `prod` warehouse.

Oracle: Same idea, except `--db-name` corresponds to an "Oracle RAC database":
https://github.com/gravitational/teleport/blob/f1ab6cc8a27984c6ffb0e9b123fd01844c23f8ee/lib/client/db/dbcmd/dbcmd.go#L696-L698

(oracle docs): https://docs.oracle.com/middleware/12211/bip/BIPAD/GUID-FB2AEC3B-2178-48DF-8B9F-76ED2D6B5194.htm#BIPAD289

> Oracle RAC database
> 
> To connect to an Oracle RAC database, use the following format:
> 
> jdbc:oracle:thin:@//<host>[:<port>]/<service_name>
> 
> For example: jdbc:oracle:thin:@//myhost.example.com:1521/my_service

@smallinsky I have found mixed results while investigating whether it is possible to switch services during an Oracle connection, and I'm not familiar with Oracle. Could you take a look at that to make sure? If we decide to keep the Oracle DB name matcher, then we'll need to update this PR and update our docs to say:
> Database names are only enforced for PostgreSQL, MongoDB, and Oracle databases.

~Leaving this PR in draft so we can decide on the oracle question.~

### CODE REVIEW

**Comment by smallinsky** [comment]
> I have found mixed results while investigating whether it is possible to switch services during an Oracle connection, and I'm not familiar with Oracle. Could you take a look at that to make sure? If we decide to keep the Oracle DB name matcher, then we'll need to update this PR and update our docs to say:

> Database names are only enforced for PostgreSQL, MongoDB, and Oracle databases.

> Leaving this PR in draft so we can decide on the oracle question.


I think that we should remove Oracle db_name matcher.  The Oracle protocol is private and not documented and there is always a risk that we miss something. At initial implementation I was not intended to support db_name In Oracle Protocol. 

Thanks for finding this issue.

**Review by smallinsky — COMMENTED** [review]
LGMT but let me test this change. 

In meantime could you take a look at failing UT ? 

`TestAccessSnowflake/no_access_to_databases`

**Comment by GavinFrazar** [comment]
yeah, the UT probably just tries to deny access by db name for snowflake, i'll take a look

**Review by mdwn — APPROVED** [review]
This LGTM. I know there's some extra testing to do here, but wanted to give my approval so I'm not holding anything up.

**Comment by GavinFrazar** [comment]
fixed the UT. opened a PR in `e` to update oracle tests as well - those oracle tests actually were not broken by this change because we forgot to set the db session protocol in the oracle test setup, so I fixed that as well.

**Review by jakule — APPROVED** [review]
Thanks for fixing this

**Pull request merged**
