### PR TITLE
[master] Add support for building `fdpass-teleport` (#42731)

### PR DESCRIPTION
**Pull request by fheinecke**
Forward ports https://github.com/gravitational/teleport/pull/42731

This will need an e ref bump just prior to merge

### CODE REVIEW

**Review by marcoandredinis — APPROVED** [review]
You should drop the `[master] ` from the PR title

**Comment by fheinecke** [comment]
> You should drop the [master]  from the PR title

Even though this is a forward port?

**Comment by marcoandredinis** [comment]
> > You should drop the [master]  from the PR title
> 
> Even though this is a forward port?

I think this is the first (well, 2nd 😅 ) forward port I see.
Is adding the `[master]` a good practice defined somewhere? Or is it personal preference?

I'm fine with it, but I wasn't expecting to see this tag for PR against `master`.
Up to you 👍

**Comment by fheinecke** [comment]
> Is adding the [master] a good practice defined somewhere? Or is it personal preference?

Honestly, no idea. I _think_ I've seen this once or twice before, but forward ports are so infrequent that I may just be misremembering. Apparently GH search doesn't work properly with `[ ... ] in:title` so I don't have a great way of looking for other PRs with this pattern.

> I wasn't expecting to see this tag for PR against master.

Yea I completely understand. This work needed to be done against v15 first on a very short timeline so I ended up forward-porting instead of backporting. This won't become a trend (I hope).

**Review by r0mant — APPROVED** [review]

**Pull request merged**
