### PR TITLE
Add device trust to testplan

### PR DESCRIPTION
**Pull request by codingllama**
Add device trust items to testplan.

For the "device authorization" section, I suggest assigning Database and K8s for the folks already doing those items, otherwise this requires a lot of setup. The person covering the bulk of device trust can take SSH and Trusted Clusters.

https://github.com/gravitational/teleport.e/issues/514

### CODE REVIEW

**Comment by codingllama** [comment]
FYI @rosstimothy @russjones @r0mant, in particular this comment:

> For the "device authorization" section, I suggest assigning Database and K8s for the folks already doing those items, otherwise this requires a lot of setup. The person covering the bulk of device trust can take SSH and Trusted Clusters.

I also thought of adding a comment to the testplan, but I wasn't sure if that's helpful. WDYT?

**Review by AntonAM — APPROVED** [review]

**Comment by zmb3** [comment]
@codingllama would you mind changing this to target branch `zmb3/test-plan-updates` and I'll merge it with mine?

Additionally, the test plan issues for v12 have already been created so these new items will need to be manually added to those.

**Comment by codingllama** [comment]
@zmb3 sure, let me rebase.

I'll port the changes to the ongoing testplan, I was just looking for the approvals first.

**Comment by codingllama** [comment]
Done, PTAL @zmb3 ?

**Review by zmb3 — APPROVED** [review]

**Pull request merged**
