### PR TITLE
docs: add homebrew version compatibility note

### PR DESCRIPTION
**Pull request by awly**

### CODE REVIEW

**Comment by klizhentas** [comment]
@awly let's hold off all docs PRs until we merge #5603

**Comment by webvictim** [comment]
Maybe our versioning strategy should be that your `tsh` major version always needs to match your cluster's major version.

It'd be even more awesome if we could just prompt people to auto update their outdated version of `tsh` if it doesn't match and serve the binary from the server.

**Comment by awly** [comment]
@webvictim that was our strategy before https://github.com/gravitational/teleport/pull/5293
The problem is during updates - when parts of your cluster run `vX` and `vX+1`.

**Review by webvictim — APPROVED** [review]
LGTM, will be a conflict after #5603 is merged though

**Comment by awly** [comment]
Updated to the `mdx` format.

**Review by klizhentas — APPROVED** [review]
good to go assuming rebase against `branch/v6`

**Pull request merged**
