### PR TITLE
Install script changes and sudo command updates for Teleport install and configure

### PR DESCRIPTION
**Pull request by stevenGravy**
Modified to use `sudo` in a manner that will work without requiring to be root.

### CODE REVIEW

**Review by zmb3 — COMMENTED** [review]
Let's hold off for a second. The $ should work and os likely a regression with the docs repo migration.

**Comment by stevenGravy** [comment]
> Let's hold off for a second. The $ should work and os likely a regression with the docs repo migration.

The copy/paste works cleanly when `code` is in the page.  it seems specific to includes perhaps.  

The original commands were failing though in a typical ubuntu environment with sudo rights with permission denied.

**Comment by stevenGravy** [comment]
example error with the ubuntu part

```code
cat<<EOF>/etc/apt/sources.list.d/teleport.list
> deb [signed-by=/usr/share/keyrings/teleport-archive-keyring.asc] https://deb.releases.teleport.dev/ stable main
> EOF
-bash: /etc/apt/sources.list.d/teleport.list: Permission denied
```

**Review by klizhentas — CHANGES_REQUESTED** [review]
Let's hold this change, I'd rather fix https://github.com/gravitational/docs/issues/25 instead. I will ask our web team to prioritize the fix

**Review by zmb3 — APPROVED** [review]

**Review by ptgott — APPROVED** [review]

**Review by klizhentas — APPROVED** [review]

**Pull request merged**
