### PR TITLE
fix: Update terraform docs

### PR DESCRIPTION
**Pull request by codingllama**
`make -C integrations/terraform docs`

### CODE REVIEW

**Comment by codingllama** [comment]
This is causing other PRs to fail CI, for example #45473.

**Review by benarent — APPROVED** [review]
This Link is correct in V17 docs https://github.com/gravitational/teleport/pull/45495 but not v16. I Think it's ok as this is part of our planned reorg

**Review by tigrato — APPROVED** [review]

**Review by rosstimothy — APPROVED** [review]

**Comment by codingllama** [comment]
I think the template was incorrect, links should match now. PTAL.

**Comment by codingllama** [comment]
Added also d8d78ff so CI catches problems in the offending PRs in the future. We could trigger on `docs/**` but that feels a bit heavy-handed. Let's see if this keeps causing problems.

**Pull request merged**
