### PR TITLE
adding additional parameter documentation for etcd backend

### PR DESCRIPTION
**Pull request by jeremyd**
Noticed this was required.

### CODE REVIEW

**Review by klizhentas — COMMENTED** [review]
let's set a reasonable value in examples, as many people will copy-paste

**Comment by jeremyd** [comment]
I wasn't actually sure what to set, suggestions?

**Comment by kontsevoy** [comment]
perhaps `/teleport/data` or `teleport/data`? @klizhentas : which one will work?

**Comment by kontsevoy** [comment]
maybe we should also rename the config setting to `key_prefix` too?

**Comment by kontsevoy** [comment]
Actually I would add that our `etcd` back-end in general needs more comprehensive documentation. And it's not limited to `teleport.yaml`, we also need to add a paragraph or two to the clustering section. Lets push this into 1.5 release.

**Pull request closed without merging**
