### PR TITLE
Updates AWS SDK to 1.28.11

### LINKED ISSUE #3210: Bump aws-sdk-go version dependency
Please bump the aws-sdk-go version dependency to at least v1.21.0 https://github.com/aws/aws-sdk-go/blob/master/CHANGELOG.md#release-v1210-2019-07-18

AWS added support in EKS for kubernetes service accounts to be associated to IAM roles to allow granular, pod-level permissions to be inherited by containers. This release of the SDK is required in order to support the `AWS_WEB_IDENTITY_TOKEN_FILE` and `AWS_ROLE_ARN` environment variables.

### PR DESCRIPTION
**Pull request by klizhentas**
This commit updates AWS Go SDK and fixes #3210

Tested with a sanity test using AWS Dynamo and S3 for sessions, events and tables.

### CODE REVIEW

**Review by russjones — APPROVED** [review]

**Review by fspmarshall — APPROVED** [review]

**Comment by klizhentas** [comment]
retest this please

**Comment by klizhentas** [comment]
retest this please

**Comment by russjones** [comment]
@gravitational-jenkins retest this please

**Comment by klizhentas** [comment]
retest this please

**Comment by klizhentas** [comment]
retest this please

**Comment by klizhentas** [comment]
retest this please

**Comment by klizhentas** [comment]
retest this please

**Comment by russjones** [comment]
@gravitational-jenkins retest this please

**Comment by russjones** [comment]
@gravitational-jenkins retest this please

**Comment by russjones** [comment]
@gravitational-jenkins retest this please

**Comment by robcoward** [comment]
Any chance of this getting merged into the `branch/4.2` branch so that is can be included in the `4.2.3` release please ?

**Comment by robcoward** [comment]
Is this going to be released in 4.2 (its missed out on the 4.2.3 and 4.2.4 releases already...) or are we having to wait for 4.3.x ? If so, what is your roadmap for releasing 4.3 please ? I am reliant on this functionality to allocated IAM permissions to k8s pods and dont want to be building my own containers any longer than I have to. Thanks.

**Pull request merged**
