### PR TITLE
Fix docs markup errors for v16

### PR DESCRIPTION
**Pull request by iAdramelk**
Some fixes for the docs to fix validation errors and warnings in Docusaurus:

- Remove duplicate redirects.
- Remove redirects form existing pages.
- Update redirects leading to non-existing pages.
- Fix damaged svg image (can't read width and height).
- Add `.mdx` extension to links to make possible to validate links.
- Fixed typo in `docs/pages/access-controls/access-request-plugins/servicenow.mdx` inline code.
- Fixed typo in `docs/pages/reference/terraform-provider.mdx` that was causing mdx failing. (But this is an auto-generated file, so it's better to fix it in the original location too).
- Fixed `dbname` key for `tctl-auth-sign-3-files.mdx` includes to make them work.

Didn't fix, but should be fixed separately:

- Link to `includes/dynamodb-iam-policy.mdx` in `CHANGELOG.md` – files in includes folder does not build to full pages in docs.
- Three images are used in docs, but are missing in the filesystem: 
  - `/docs/img/database-access/guides/cloudsql/instance-id@2x.png`
  - `/docs/img/database-access/guides/cloudsql/instance-public-ip@2x.png`
  - `/docs/img/desktop-access/install-active-directory.png`

### CODE REVIEW

**Comment by zmb3** [comment]
Should this be targeting `branch/v16` or `master`?

**Comment by iAdramelk** [comment]
> Should this be targeting branch/v16 or master?

Docs for v16 are pointing to `master` right now https://github.com/gravitational/docs/blob/main/.gitmodules#L9, so I'm also referencing `master` here.

**Comment by zmb3** [comment]
> Docs for v16 are pointing to master right now

Right, but they will soon be updated for branch/v16, so if you do this PR to v13, v14, v15, and master you're going to miss v16.

**Comment by iAdramelk** [comment]
Can't switch it to v16 without conflicts, will close and recreate it.

**Comment by iAdramelk** [comment]
Done https://github.com/gravitational/teleport/pull/42603

**Comment by zmb3** [comment]
@iAdramelk I would keep this one open too, we don't want the release branches to diverge from master, otherwise we'll have this problem again when we cut v17.

**Pull request closed without merging**
