### PR TITLE
`IRP_MJ_QUERY_INFORMATION`

### PR DESCRIPTION
**Pull request by ibeckermayer**
Adds handler for `IRP_MJ_QUERY_INFORMATION` based on the FreeRDP implementation, which starts [here](https://github.com/FreeRDP/FreeRDP/blob/511444a65e7aa2f537c5e531fa68157a50c1bd4d/channels/drive/client/drive_main.c#L373)

### CODE REVIEW

**Comment by xacrimon** [comment]
@ibeckermayer Was the teleport.e submodule update intentional?

**Review by xacrimon — APPROVED** [review]

**Comment by xacrimon** [comment]
Same goes for the webassets update.

**Comment by ibeckermayer** [comment]
> @ibeckermayer Was the teleport.e submodule update intentional?

'Twas not, good catch.

**Review by LKozlowski — APPROVED** [review]

**Review by zmb3 — APPROVED** [review]
I would love to see a restructure so that rdpdr/mod.rs is not so big.

**Comment by ibeckermayer** [comment]
> I would love to see a restructure so that rdpdr/mod.rs is not so big.

https://github.com/gravitational/teleport/issues/13499

**Pull request merged**
