### PR TITLE
[v10] Fix database role fetch for `tsh db ls --all`

### PR DESCRIPTION
**Pull request by atburke**
Backport #13617 to branch/v10

### CODE REVIEW

**Review by rosstimothy — APPROVED** [review]

**Review by ravicious — APPROVED** [review]

**Comment by ravicious** [comment]
Oops, I re-ran the integration tests, sorry!

**Comment by ravicious** [comment]
I want to merge #13877 to v10 too but I'll wait for this one to be merged first.

**Comment by ravicious** [comment]
@atburke I'm so sorry, literally one gaffe at the start of my day and then another one at the end. I was so excited to see CI pass on my PR that I just clicked "Merge" without realizing I set your branch as the base of mine. 🤦‍♂️

Feel free to remove my commit from your branch if it causes any problems. We could try merging it in with rebase though.

**Comment by atburke** [comment]
@ravicious No worries! I'm not doing anything else with that branch, so there shouldn't be any problems.

**Comment by ravicious** [comment]
@atburke Do you plan to merge this PR before the v10 release?

**Comment by atburke** [comment]
@ravicious Yep. I'll merge it now.

**Pull request merged**
