### PR TITLE
Fix non-JSON text handling in test reporter

### PR DESCRIPTION
**Pull request by tcsc**
A non-json line in a test log caused the test reporter to enter an
infinite loop. This is caused by the JSON fragment reader attempting to
pick itself up after a failure, when instead it really should just
signal en error and exit.

Unfortunately, `go test -json` does not report build failures in the JSON
format as all of its other messages, but dumps a plain text logline into
the output.

This patch makes the test renderer exit on a parse failure, rather than
try to carry on.

Output looks like: 
```
 43.9% pass: github.com/gravitational/teleport/lib/services
 47.4% pass: github.com/gravitational/teleport/lib/services/local
 55.5% pass: github.com/gravitational/teleport/lib/cache
 47.8% pass: github.com/gravitational/teleport/lib/auth
------ skip: github.com/gravitational/teleport/lib/auth/mocku2f
------ skip: github.com/gravitational/teleport/lib/auth/test
------ skip: github.com/gravitational/teleport/lib/auth/testauthority
------ skip: github.com/gravitational/teleport/lib/auth/u2f
------ skip: github.com/gravitational/teleport/lib/auth/webauthn/httpserver
------ skip: github.com/gravitational/teleport/lib/backend/test
ERROR: failed parsing JSON record: FAIL github.com/gravitational/teleport/lib/client [build failed]
exit status 2
```

### CODE REVIEW

**Comment by rosstimothy** [comment]
`go test -c` does not work on multiple packages at the moment, the [proposal](https://github.com/golang/go/issues/15513) seems likely to be implemented in the near future. Can we merge this in until then?

**Comment by codingllama** [comment]
> `go test -c` does not work on multiple packages at the moment, the [proposal](https://github.com/golang/go/issues/15513) seems likely to be implemented in the near future. Can we merge this in until then?

That doesn't stop us from compiling them individually. It's a bit more work, but could be done.

**Comment by rosstimothy** [comment]
> > `go test -c` does not work on multiple packages at the moment, the [proposal](https://github.com/golang/go/issues/15513) seems likely to be implemented in the near future. Can we merge this in until then?
> 
> That doesn't stop us from compiling them individually. It's a bit more work, but could be done.

Sure, but how would that impact the time it takes to run all tests?

**Comment by codingllama** [comment]
> > > `go test -c` does not work on multiple packages at the moment, the [proposal](https://github.com/golang/go/issues/15513) seems likely to be implemented in the near future. Can we merge this in until then?
> > 
> > 
> > That doesn't stop us from compiling them individually. It's a bit more work, but could be done.
> 
> Sure, but how would that impact the time it takes to run all tests?

I think it could be done to be fast (maybe as fast or better if we parallelize correctly), but kind of a pain to manage. What about trying `go test -c` on parse failures so we can disambiguate and extract errors?

To be clear, I'm not holding the PR on the need to `go test -c`, it was just parked waiting for a reply.

**Comment by rosstimothy** [comment]
> > > > `go test -c` does not work on multiple packages at the moment, the [proposal](https://github.com/golang/go/issues/15513) seems likely to be implemented in the near future. Can we merge this in until then?
> > > 
> > > 
> > > That doesn't stop us from compiling them individually. It's a bit more work, but could be done.
> > 
> > 
> > Sure, but how would that impact the time it takes to run all tests?
> 
> I think it could be done to be fast (maybe as fast or better if we parallelize correctly), but kind of a pain to manage. What about trying `go test -c` on parse failures so we can disambiguate and extract errors?
> 
> To be clear, I'm not holding the PR on the need to `go test -c`, it was just parked waiting for a reply.

Ack. I totally agree it makes more sense to utilize `go test -c` than to add more logic to the test renderer. In it's present state this PR would at least point you to the failure and prevent infinite spam of 

```
Error parsing JSON test record: invalid character 'F' looking for beginning of value
Error parsing JSON test record: invalid character 'F' looking for beginning of value
Error parsing JSON test record: invalid character 'F' looking for beginning of value
Error parsing JSON test record: invalid character 'F' looking for beginning of value
```

**Comment by rosstimothy** [comment]
Thoughts on replacing `render-tests` with https://github.com/gotestyourself/gotestsum?

**Comment by tcsc** [comment]
Closed in favour of #9626

**Comment by tcsc** [comment]
> Thoughts on replacing `render-tests` with https://github.com/gotestyourself/gotestsum?

@russjones wasn't keen, but I'm definitely keeping an eye on it - at the very least as an inspiration for our own builds.

**Pull request closed without merging**
