### PR TITLE
Add endpoint for restarting gateways in Teleport Connect

### PR DESCRIPTION
**Pull request by ravicious**
# The problem

gravitational/webapps.e#282 is the umbrella issue for making the app handle expired certs. One of the remaining issues to tackle is that if you have active gateways (database proxies) and re-login to get a set of fresh certs, those gateways still use old certs.

At the moment it's not possible to refresh certs used by a proxy, but we asked the database access team to implement such feature and we'll address that in the future (gravitational/webapps.e#299).

# The solution

In the meantime, we want to apply this temporary band-aid in the form of restarting active gateways on re-login. To achieve this, we add an endpoint which the Electron app can call in order to restart a gateway.

After logging in again in Connect, the app will call this endpoint for each active gateway. Initially we wanted to restart all active gateways within a single request. However, it soon became clear that we need to do it on an individual basis. Between the cert expiring and the user refreshing the certs, the user may lose access to one of the databases. We didn't want this to interrupt the process of getting fresh certs for other dbs, so we're going to send this request for each db instead.

This will also let us communicate potential errors better.

# The drawbacks

As I said, this is just a temporary solution, ideally we'd just make the proxies use new certs. This solution here also won't work if you refresh your certs with `tsh login` rather than through Connect, since Connect will not know that a re-login through tsh took place. This might get addressed in gravitational/teleport.e#850.

### CODE REVIEW

**Review by marcoandredinis — COMMENTED** [review]
Overall looks good
Can we please add a test?

**Comment by ravicious** [comment]
> Can we please add a test?

Yeah, I'll try to at least add a test for `daemon.Service.RestartGateway`. `lib/teleterm` has almost no tests other than just a single one that boots up the daemon service and stops it.

I spent about an hour today trying to make them work (they're on the branch `ravicious/restart-gateways-test`), mostly copying code from tsh tests for now. I couldn't get `MockSSOLogin` to work, the daemon still tries to connect to the connector. I'll make another attempt at this tomorrow.

**Review by zmb3 — APPROVED** [review]
Seems fine to me.

Should we add a comment to mark the `RestartGateway` RPC as a temporary workaround that will eventually be removed?

**Comment by ravicious** [comment]
@marcoandredinis Is it okay if I merge this PR without tests?

It's my fault that I didn't plan for adding some test coverage to the tsh daemon in advance. Yesterday I tried to imitate what the tsh tests are doing (spinning up a Teleport server, mocking a connector and so on). After talking with Zac I realized that I don't really want to do it and instead, it'd be better to write smaller tests. Our unit test suite is already slow and flaky.

So I went back to the drawing board again, but I quickly realized that the current structure of lib/teleterm doesn't really mesh well with small tests. After some discussion on Slack, I wrote up a plan on how to approach this in the future (gravitational/teleport#13278). Unfortunately, working on this right now would mean that I wouldn't have time for other stuff that we need to implement for the upcoming release.

After the GA release I'll allocate some time so that when writing some of the new features related to k8s, we'll think about testing from the start.

**Review by marcoandredinis — APPROVED** [review]
Yes, it makes sense
Thank you for the explanation 🙏

**Pull request merged**
