### PR TITLE
chore: Bump golangci-lint to v1.51.0

### PR DESCRIPTION
**Pull request by codingllama**
Update golangci-lint to v1.51.0 and do a few configuration tweaks.

### CODE REVIEW

**Comment by codingllama** [comment]
Backporting to v12 an v11 - v10 is running a rather outdated version, so it's likely to run into all sorts of problems. For some reason I'm having a hard time running the linter locally, so I'm letting CI pick up the slack for now.

**Review by timothyb89 — APPROVED** [review]
Looks like 1.51.1 is out already?

**Review by jakule — APPROVED** [review]

**Comment by codingllama** [comment]
This likely needs a closer look than I've been able to give it. Also, it looks like 1.51.1 is out, so I'd rather wait for it to land on brew and then upgrade straight to it.

I'll move this to draft for now.

**Comment by codingllama** [comment]
Closing in favor of #21440 (1.51.1) and #21460 (tweaks).

**Pull request closed without merging**
