### PR TITLE
allow overrides of the AWS config for the service in the helm chart

### PR DESCRIPTION
**Pull request by timothy-spencer**
If you do it this way, you can override the annotations that are set for AWS so that you can do things like set the backend protocol to ssl and so on.

### CODE REVIEW

**Comment by russjones** [comment]
@webvictim Can you review?

**Review by webvictim — APPROVED** [review]
I'm not super keen on this as it's basically abusing YAML's preference for the latest defined item, but it's certainly better than exposing each of those values individually.

**Comment by timothy-spencer** [comment]
I totally agree.  It's not great, but it's simple and it works.  Thanks for the approval!

**Comment by timothy-spencer** [comment]
Hey, your CI system seems to have a problem with the firestore tests, if I am interpreting it correctly.  I cannot imagine that these changes could affect them, so I am suspecting that it's some sort of transient failure.  I cannot click on the "Restart" button.  Would it be possible for one of you folks to do that?

**Comment by timothy-spencer** [comment]
Nevermind.  I put in an extra space to trigger the build.

**Comment by webvictim** [comment]
Approved the build, we'll see what the feedback is. As you say it's unlikely that anything with Firestore is failing due to your changes!

**Comment by timothy-spencer** [comment]
Looks like it worked this time.  This and https://github.com/gravitational/teleport/pull/7288 are available for you to rub some approval on so that we can merge this stuff!  :-)

**Review by webvictim — APPROVED** [review]

**Review by klizhentas — APPROVED** [review]

**Pull request merged**
