### PR TITLE
Add SFTP subsystem fails note to server access FAQ

### PR DESCRIPTION
**Pull request by jakule**
In many cases, we see people trying to use `tsh` v11 with Teleport Node v9. In this combination, `ssh: subsystem request failed`, which is very confusing for users. As we're not able to make sure that all Teleport installations are up-to-date, we at least can we mention the most common solution in our FAQ.

Updates https://github.com/gravitational/teleport/issues/22456

### CODE REVIEW

**Review by zmb3 — APPROVED** [review]

**Review by alexfornuto — APPROVED** [review]
If there was a specific page on SFTP I'd like to see this added there, but I don't think we have such a page, or even section. Maybe [here](https://goteleport.com/docs/connect-your-client/tsh/)?

In any case, looks ok but with a couple edits.

**Comment by alexfornuto** [comment]
@jakule does this not apply to Teleport 10?

**Comment by zmb3** [comment]
No. SFTP was added in Teleport 11.

**Comment by jakule** [comment]
> No. SFTP was added in Teleport 11.

To be specific. SFTP on the server side was added in 10.1, but the client side was added in v11. Because of that, there is no way that you can get this error in v10.

**Pull request merged**
