### PR TITLE
Convert integration_test.go to testify.Suite

### PR DESCRIPTION
**Pull request by gzigzigzeo**
This is required to make difftest work with integration tests.

### CODE REVIEW

**Comment by tcsc** [comment]
I'm only partway through so far, and while it's looking good - can I suggest that next time we do something like this that we separate the functional changes into one PR and have a separate one for the re-arrangement? I agree that both changes are necessary and good, it's just a bit harder to review when they're mingled like this.

**Comment by jakule** [comment]
@gzigzigzeo Why did we go back to using `testify/suite` for testing? We migrated away from it a few months ago. Another thing, as Trent mentioned, it's hard to review 5k changed lines in one PR.

**Comment by tcsc** [comment]
> @gzigzigzeo Why did we go back to using `testify/suite` for testing? 

I moved a whole heap of stuff away from `GoCheck` suites months ago, but I don't think we've ever used `testify` suites before. I have no objections about using a predefined suite library - the whole integration test setup is using a de-facto suite anyway, so it probably _should_ use a common pattern rather than my ad-hoc dependency injection approach. 

But yeah - I should also ask: how _does_ using a testify suite make this more amenable to using the flaky test detector?

**Comment by tcsc** [comment]
> how does using a testify suite make this more amenable to using the flaky test detector?

Spoke with @r0mant, and apparently the tooling for the flaky test detector natively works with the way `testify/suite` reports its tests, where it would need to have some special handling to interpret the test output from the inline subtests.

**Review by tcsc — APPROVED** [review]
I don't think its feasible to do a full, line-by-line review of 5k lines. 

I have managed to reconstruct a minimal diff for about a quarter of the integration tests by re-arranging the new tests in the order they appeared in the old file, and the pattern of changes looks to be pretty consistent, and the right thing to do.

Assuming that the same pattern continues, and as long as everything compiles and runs, I'm happy to approve and move on. It's just impossible to review architectural changes in these tests due to the scale.

**Review by tcsc — APPROVED** [review]

**Pull request closed without merging**
