### PR TITLE
[v10] Remove Parallel call in TestAppServersHA test

### PR DESCRIPTION
**Pull request by smallinsky**

### CODE REVIEW

**Review by ibeckermayer — APPROVED** [review]

**Review by gabrielcorado — APPROVED** [review]

**Comment by zmb3** [comment]
Should we merge this or backport @r0mant's PR instead?

**Comment by nklaassen** [comment]
we're already hitting 25 min timeouts a lot, how much higher will this push us?

**Comment by r0mant** [comment]
Yeah we gotta backport the full https://github.com/gravitational/teleport/pull/13867, that will result in faster tests even without t.Parallel in the HA test.

That said, I only removed t.Parallel in my PR as a test to see if it improves the situation on the CI. It has never failed once for me even with t.Parallel locally so I'm not entirely sure that was the problem.

I'll try to backport my PR later today.

**Comment by r0mant** [comment]
Can probably close this now as it's included in that backport.

**Pull request closed without merging**
