### PR TITLE
Fail `app_service` start on invalid configuration

### PR DESCRIPTION
**Pull request by Tener**
`app_service` supports two modes: one in which the single process runs `app_service`, `auth` and `proxy`, and the second in which the connection to auth server is done via proxy: it must be able to create a reverse tunnel.

Currently, if we cannot create a reverse tunnel, the `singleProcessModeResolver` is used, but we are not checking the configuration before waiting for all components to come online. If the configuration is invalid, they never will.

This change calls `singleProcessModeResolver` to force the (already existing) check before entering the wait.

Parent: #13969.

### CODE REVIEW

**Review by alistanis — APPROVED** [review]
@Tener Thanks for the background on this. I took a look at the surrounding code and this change seems perfectly reasonable to me.

Is it ever possible that the resolver in question wouldn't be ready either? Should there be a blocking context for the resolver function itself? (I'm still very new so apologies if that's irrelevant)

**Review by strideynet — APPROVED** [review]
Looks good. I assume we need to do similar for the other services ??

**Comment by Tener** [comment]
> Looks good. I assume we need to do similar for the other services ??

Yes: https://github.com/gravitational/teleport/issues/13969#issuecomment-1180727492

I'll be looking at `kubernetes_service` and `db_service` next, but since this is self-contained already I'll be doing that in different PR.

Thanks for the review!

**Comment by strideynet** [comment]
> > Looks good. I assume we need to do similar for the other services ??
> 
> Yes: [#13969 (comment)](https://github.com/gravitational/teleport/issues/13969#issuecomment-1180727492)
> 
> I'll be looking at `kubernetes_service` and `db_service` next, but since this is self-contained already I'll be doing that in different PR.
> 
> Thanks for the review!

Perfect

**Pull request merged**
