### PR TITLE
[v12] Allow Okta origin for new apps.

### PR DESCRIPTION
**Pull request by mdwn**
Backport #23550 to branch/v12

### CODE REVIEW

**Review by r0mant — APPROVED** [review]

**Review by probakowski — APPROVED** [review]

**Review by r0mant — CHANGES_REQUESTED** [review]
@mdwn So I've been looking at this PR in conjunction with https://github.com/gravitational/teleport/pull/23603 and have a concern that there may be a slight security risk with this approach.

Specifically, with these 2 changes anyone who can register apps in the cluster now can create an app with "okta" origin and with the changes in https://github.com/gravitational/teleport/pull/23603 the app service will just happily redirect you to the app's URI. So I wonder if there's a risk that a malicious user can register a `VeryInnocentApplication` with Okta origin and basically get an arbitrary redirect for anyone who clicks it.

I would consider changing the approach a bit, let me know if you think it makes sense:

- First, we don't allow okta origin in apps passed via the API. Auth server should know the identity of the service that's making an API request, right? So it should be able to set the origin to "okta" automatically if it sees the request is coming from the okta_service,
- For the https://github.com/gravitational/teleport/pull/23603, I wonder if instead of adding this to app service, can we have Okta service do the redirect? Then it can do extra verification like is this really an Okta app instead of just doing a blind redirect to whatever's in the URI.

Let me know what you think. Requesting changes until we figure it out.

**Comment by mdwn** [comment]
> @mdwn So I've been looking at this PR in conjunction with #23603 and have a concern that there may be a slight security risk with this approach.
> 
> Specifically, with these 2 changes anyone who can register apps in the cluster now can create an app with "okta" origin and with the changes in #23603 the app service will just happily redirect you to the app's URI. So I wonder if there's a risk that a malicious user can register a `VeryInnocentApplication` with Okta origin and basically get an arbitrary redirect for anyone who clicks it.
> 
> I would consider changing the approach a bit, let me know if you think it makes sense:
> 
> * First, we don't allow okta origin in apps passed via the API. Auth server should know the identity of the service that's making an API request, right? So it should be able to set the origin to "okta" automatically if it sees the request is coming from the okta_service,
> * For the #23603, I wonder if instead of adding this to app service, can we have Okta service do the redirect? Then it can do extra verification like is this really an Okta app instead of just doing a blind redirect to whatever's in the URI.
> 
> Let me know what you think. Requesting changes until we figure it out.

I think having the auth server know the identity of the caller indicating the origin makes a lot of sense and will be pretty trivial to do.

I'm slightly leery of having the Okta service do the redirect because it's a pretty big can of worms I think -- to add it to the Okta service will likely involve re-implementing, to a degree, the app service within the Okta service so that the proxy is able to redirect there. The Okta service goes from a backend only service to a service that can handle HTTP communication. It's definitely doable, but I feel like having the auth server use the caller identity to set the origin effectively does this verification during app creation rather than during actual redirect.

**Comment by tigrato** [comment]
> > @mdwn So I've been looking at this PR in conjunction with #23603 and have a concern that there may be a slight security risk with this approach.
> > Specifically, with these 2 changes anyone who can register apps in the cluster now can create an app with "okta" origin and with the changes in #23603 the app service will just happily redirect you to the app's URI. So I wonder if there's a risk that a malicious user can register a `VeryInnocentApplication` with Okta origin and basically get an arbitrary redirect for anyone who clicks it.
> > I would consider changing the approach a bit, let me know if you think it makes sense:
> > 
> > * First, we don't allow okta origin in apps passed via the API. Auth server should know the identity of the service that's making an API request, right? So it should be able to set the origin to "okta" automatically if it sees the request is coming from the okta_service,
> > * For the [[v12] App service handles Okta apps. #23603](https://github.com/gravitational/teleport/pull/23603), I wonder if instead of adding this to app service, can we have Okta service do the redirect? Then it can do extra verification like is this really an Okta app instead of just doing a blind redirect to whatever's in the URI.
> > 
> > Let me know what you think. Requesting changes until we figure it out.
> 
> I think having the auth server know the identity of the caller indicating the origin makes a lot of sense and will be pretty trivial to do.
> 
> I'm slightly leery of having the Okta service do the redirect because it's a pretty big can of worms I think -- to add it to the Okta service will likely involve re-implementing, to a degree, the app service within the Okta service so that the proxy is able to redirect there. The Okta service goes from a backend only service to a service that can handle HTTP communication. It's definitely doable, but I feel like having the auth server use the caller identity to set the origin effectively does this verification during app creation rather than during actual redirect.

Not being very familiar with Okta approach, I tend to prefer the second option that @r0mant mentioned for several reasons:
- Okta catalog can be in memory and we don't even need to touch Auth server except for announcing the server using heartbeats. This means we don't need the App RW permission - reduces possible attack surfaces.
- I assume redirection is a trivial operation so we won't have huge troubles implementing just a subset of app service. The code can be shared with the app service.
- Configuring an Okta service does not require any other service to be operational, i.e. we won't need to configure the dynamic resource watcher in the App service - from a UX perspective it's great.

This also fixes possible security scenarios where users with RW to Apps (stolen okta creds) might hijack the redirection URL and simplify bug fixes/adding new features.

**Comment by r0mant** [comment]
@tigrato @mdwn I think we should do both tbh: set labels based on identity and handle redirect in Okta service.

@tigrato Okta service will still need r/w on apps, I don't think we want to keep catalog in memory of the service. We will mention that Okta service has to be protected in the docs as it will also possess Okta API key.

@mdwn Moving redirect logic to the Okta service should be really easy. Since it already establishes reverse tunnel to the cluster (does it?), you will just need to extract a very small subset of app_service. You'll need to update proxy transport to dial okta agent instead of app agent: https://github.com/gravitational/teleport/blob/master/lib/web/app/transport.go#L281. And on the Okta service side have a very lightweight version of app's Server that receives a request, validates it is Okta application and does redirect: https://github.com/gravitational/teleport/blob/master/lib/srv/app/server.go#L257.

**Comment by mdwn** [comment]
Closing this as it's superseded by the approach in https://github.com/gravitational/teleport/pull/23688

**Pull request closed without merging**
