### PR TITLE
Implement device data collection for Linux

### PR DESCRIPTION
**Pull request by codingllama**
Add the capability to collect device data for Linux devices. This is an important step in enabling device trust for linux.

Commands such as `tsh device collect` and `tsh device asset-tag` now work. If the current user does not have the necessary permissions, tsh will elevate itself (via `sudo tsh device dmi-read`) to collect the information. A DMI local cache is also implemented in order to avoid the constant need for sudo in routine operations.

See the Linux TPM RFD for details: https://github.com/gravitational/teleport.e/blob/rfd/0017e-linux-tpm/rfd/0017e-device-trust-linux-tpm.md#details

https://github.com/gravitational/teleport.e/issues/827

### CODE REVIEW

**Comment by codingllama** [comment]
Branched from #34458. Reviewing commit-by-commit may be easier, as it's clearer what is copied/moved (like ec2d5ee and 5f1c0f4) vs actual code changes. I've also tried to add "features" in their own isolated commits.

The split between tpm_common.go and tpm_device.go is in part to avoid the unused linter from going crazy. Eventually all of tpm_device.go is going to be used by Linux builds too.

**Review by lxea — APPROVED** [review]

**Comment by codingllama** [comment]
Friendly ping @ryanclark?

**Review by ryanclark — APPROVED** [review]
Was on PTO/travelling to Poland, sorry!

**Comment by codingllama** [comment]
No worries! Thanks for the quick review!

**Pull request merged**
