### PR TITLE
Adds prerequisites check to kube integration tests

### PR DESCRIPTION
**Pull request by tcsc**
After losing a heap of time trying to diagnose kubernetes integration test failures only to find that they were caused by an un-primed minikube cluster, I have added some hopefully-helpful checks to the kubernetes integration test to assert that the target cluster is ready to have test run against it.

The test failure messages point the user to a document that describes how to initialise the cluster.

It also moves some of the cluster setup forward in the  test initialisation, so kube errors don't get buried in the teleport logs.

In a perfect world, the tests would inject the appropriate config into the cluster themselves. I _did_ start down that track, but it  ended up being a bit more complex than I'd hoped - so we now have the simple version that at least points you in the right direction.

### CODE REVIEW

**Review by nklaassen — APPROVED** [review]
I like it

**Comment by tcsc** [comment]
*sigh*. It looks like the CI runner does not have the permissions required to perform these queries. @webvictim - your name is on the latest commit to the doc I used as a reference. Do you have any suggestions?

**Review by russjones — APPROVED** [review]
Bot.

**Comment by webvictim** [comment]
@tcsc I think you're correct - you'd need to modify https://github.com/gravitational/teleport/blob/master/fixtures/ci-teleport-rbac/ci-teleport.yaml#L13-L19  and ad something like:
```yaml
- apiGroups: [""]
  resources: ["serviceaccounts"]
  verbs: ["get"]
```

You'd then also have to apply the updated `ci-teleport.yaml` to the Drone cluster so that the pods have permission to query the list of `ServiceAccounts`. You'd likely also need other permissions to allow your other checks to work.

**Comment by tcsc** [comment]
> You'd then also have to apply the updated `ci-teleport.yaml` to the Drone cluster so that the pods have permission to query the list of `ServiceAccounts`. You'd likely also need other permissions to allow your other checks to work.

That sounds a bit more invasive than I was hoping for. Can anyone thing of a better approach to check that the cluster is primed for testing that doesn't mean fiddling with the whole drone cluster?

**Comment by nklaassen** [comment]
> > You'd then also have to apply the updated `ci-teleport.yaml` to the Drone cluster so that the pods have permission to query the list of `ServiceAccounts`. You'd likely also need other permissions to allow your other checks to work.
> 
> That sounds a bit more invasive than I was hoping for. Can anyone thing of a better approach to check that the test-target cluster is primed for testing that doesn't mean fiddling with the whole drone cluster?

Rather than checking that the correct roles are set up, could you check if we have the right permissions by attempting to call the APIs that teleport actually hits and seeing if they work?

**Comment by tcsc** [comment]
OK, this was supposed to be a minor developer affordance, but looks like it's going to take more work than I'm happy doing. Closing for now, and will re-open if/when it becomes relevant again.

**Pull request closed without merging**
