### PR TITLE
Various AMI fixes

### LINKED ISSUE #4680: Teleport AMIs deployed via our Terraform templates have their teleport.yaml reset on reboot
### Description

**What happened**:
Rebooting an EC2 instance that has been launched via our Terraform causes the instance's teleport.yaml to be replaced with the original default teleport.yaml.

**What you expected to happen**:
The teleport.yaml should not be replaced on reboot.

**How to reproduce it (as minimally and precisely as possible)**:
Launch a cluster using our Terraform template. Edit the teleport.yaml, reboot the the instance.

### Environment
- Teleport version (use `teleport version`): This has been seen in several versions, but most recently in 4.3.7
- OS (e.g. from `/etc/os-release`): AMIs

- Where are you running Teleport? (e.g. AWS, GCP, Dedicated Hardware): AWS

**Relevant Debug Logs If Applicable**

- `tsh --debug`
- `teleport --debug`

### PR DESCRIPTION
**Pull request by webvictim**
- Changes path for Teleport and installed AMI scripts from `/usr/bin` to `/usr/local/bin`
  - This was an inconsistency pointed out by a customer.
- Uses a t2.medium as a build instance instead of t2.micro for a little more speed
- Adds AMI script checking to `make lint-sh`
  - Also fixes various `shellcheck` complaints found as a result
- Changes `teleport-generate-config` to exit with error when `/etc/teleport.yaml` already exists
  - Fixes #4680 
- Adds the `TeleportRole: monitor` tag to monitor ASG instances
- Modifies the `make oss` and `make ent` targets which build debug AMIs to only build the AMI in the region specified in the `Makefile` (`AWS_REGION`)
  - This speeds up the debug build process a lot as the AMIs don't need to be copied elsewhere, with the limitation that you'll only be able to launch the debug AMI in that particular region.

Tested by building and launching a cluster using the 4.4.4 debug AMI. Tested user creation, logging in, rebooting an instance and making sure the config didn't get overwritten. Also made sure Teleport processes were running at the new path automatically on every instance.

### CODE REVIEW

**Comment by webvictim** [comment]
This is a draft PR, pending a full test of the AMI.

**Comment by webvictim** [comment]
Ping @reviewers

**Comment by benarent** [comment]
Can I request a bump for Grafana to 6.7.4 https://github.com/gravitational/teleport/blob/324098e670c10f78d4a4ff4415dfbb9331801e5e/assets/aws/Makefile#L44  to fix https://github.com/gravitational/teleport/issues/4218

**Review by russjones — APPROVED** [review]

**Comment by webvictim** [comment]
@benarent There have been too many changes to Grafana to bump that many versions at once, I tried before and the build process failed. I'll try and do it in my next wave of updates.

**Review by benarent — APPROVED** [review]

**Pull request merged**
