### PR TITLE
Add teleport proxy addr to the kube config exec args

### PR DESCRIPTION
**Pull request by film42**
Because the `current-profile` file is used when `--proxy` is not
specified, it can be difficult to work with multiple clusters at once.
This allows the teleport proxy to be added as an exec arg to the kube
config, making opearting with multiple clusters as easy as changing the
kubectl context.

NOTE: Teleport already merges the kube config when `tsh login` is run
for different clusters. This change only improves the UX so that
updating `current-profile` is not required.

### CODE REVIEW

**Review by zmb3 — APPROVED** [review]

**Comment by zmb3** [comment]
This is a nice change, thanks @film42!

**Review by russjones — APPROVED** [review]

**Comment by zmb3** [comment]
Not necessary - we'll use the update branch button and push it through in the next day or two.

**Comment by film42** [comment]
Sounds good! Thank you!

**Pull request merged**
