### PR TITLE
Optionally allow cluster_name to override public_address being used f…

### PR DESCRIPTION
**Pull request by dheitman42**
…or cluster_name

### CODE REVIEW

**Comment by russjones** [comment]
@webvictim Can you review?

**Review by webvictim — CHANGES_REQUESTED** [review]
@dheitman42 Thanks for the PR - looks fine to me. Please resolve the conflict in `examples/chart/teleport/values.yaml` and re-request review.

**Comment by dheitman42** [comment]
Done and done.

**Review by webvictim — APPROVED** [review]

**Comment by webvictim** [comment]
@dheitman42 Please see linter failures - it looks like there are trailing spaces being appended somewhere in the changes that you made.

**Comment by russjones** [comment]
@webvictim Once this PR is merged, can you do a buddy backport PR to `branch/v7`?

**Comment by russjones** [comment]
Will merge in https://github.com/gravitational/teleport/pull/9323.

**Pull request closed without merging**
