### PR TITLE
Add local agent key support for Hardware Private keys

### LINKED ISSUE #17402: Add ssh-agent support to Hardware Key Support
Hardware Key Support can support agent forwarding with some [additional work](https://github.com/gravitational/teleport/blob/master/rfd/0080-hardware-key-support.md#agent-key-support).

### PR DESCRIPTION
**Pull request by Joerger**
This PR allows Hardware Private Keys to be added to the local key agent, which is just a keyring of `crypto.Signers`. This enables users to forward Hardware keys and connect to Teleport nodes from remote hosts:

```bash
< localhost > $ tsh ssh -o "ForwardAgent local" server01
Tap your YubiKey
< server01 > $ ssh-add -l
256 SHA256:NOjcGgdu4mQ0yUP1AtESzKWbHVJcvq7YjVjSFeLVQ+U teleport:proxy.example.com:root-cluster:dev (ECDSA-CERT)
256 SHA256:NOjcGgdu4mQ0yUP1AtESzKWbHVJcvq7YjVjSFeLVQ+U teleport:proxy.example.com:root-cluster:dev (ECDSA)
< server01 > $ ssh -p 3022 node.example.com
Tap your YubiKey
< node.example.com > $
```

Hardware Private Keys still cannot be added to a system SSH agent since this would require [Adding the key by smart card token](https://datatracker.ietf.org/doc/html/draft-miller-ssh-agent#section-4.2.5) which is not currently supported by `x/crypto/ssh/agent` and would require significant additional work.

Closes https://github.com/gravitational/teleport/issues/17402

### CODE REVIEW

**Comment by jakule** [comment]
@Joerger Can you resolve conflicts in this PR? I feel that the diff will change significantly.

**Review by jakule — APPROVED** [review]

**Comment by russjones** [comment]
@jakule Based off our discussion yesterday, I don't think this needs to be tagged with `merge-for-v12` right?

cc @r0mant @zmb3

**Comment by jakule** [comment]
> @jakule Based off our discussion yesterday, I don't think this needs to be tagged with `merge-for-v12` right?
> 
> cc @r0mant @zmb3

@russjones This PR is not related to the issue that we discussed yesterday. This PR adds support for hardware keys to our current key forwarding implementation. I think it's safe to merge it.

**Comment by Joerger** [comment]
@smallinsky @lxea Friendly reminder to review. This PR was stale for a while but is ready to be reviewed and merged now.

**Review by smallinsky — APPROVED** [review]

**Pull request merged**
