### PR TITLE
[v15]  Read the bearer token over websocket endpoints instead of query parameter #37520 

### PR DESCRIPTION
**Pull request by lxea**
Backport #37520 

Changelog: Read bearer token via websocket on websocket endpoints

### CODE REVIEW

**Review by ryanclark — DISMISSED** [review]

**Review by r0mant — APPROVED** [review]
@lxea Have you run a sanity test to verify this works on v15?

**Review by r0mant — CHANGES_REQUESTED** [review]
@zmb3 says that SSH access via web UI is not working with these changes.

**Comment by lxea** [comment]
> @zmb3 says that SSH access via web UI is not working with this changes.

fixed this now, i think i messed up some merge conflicts

**Review by r0mant — APPROVED** [review]
Confirmed this is working now.

**Review by zmb3 — APPROVED** [review]

**Pull request merged**
