### PR TITLE
[v6] Cache per-cluster SSH certificates under ~/.tsh

### LINKED ISSUE #5637: Implement RFD 19: Cluster Routing
https://github.com/gravitational/teleport/pull/5566

### PR DESCRIPTION
**Pull request by andrejtokarcik**
Backport of #5938.

```diff
 ~/.tsh/
 └── keys
    ├── one.example.com            --> Proxy hostname
    │   ├── certs.pem              --> TLS CA certs for the Teleport CA
    │   ├── foo                    --> RSA Private Key for user "foo"
    │   ├── foo.pub                --> Public Key
-   │   ├── foo-cert.pub           --> SSH certificate for proxies and nodes
    │   ├── foo-x509.pem           --> TLS client certificate for Auth Server
+   │   ├── foo-ssh                --> SSH certs for user "foo"
+   │   │   ├── root-cert.pub      --> SSH cert for Teleport cluster "root"
+   │   │   └── leaf-cert.pub      --> SSH cert for Teleport cluster "leaf"
```

When `-J` is provided, this also loads/reissues the SSH cert for the cluster associated with the jumphost's certificate. Fixes #5637.

### CODE REVIEW

**Comment by awly** [comment]
Let's sort out the edge case with relogin and `-J` before merging, and bundle that fix in this PR.

**Review by Joerger — CHANGES_REQUESTED** [review]
This PR needs to be bundled with this fix - #6214

**Comment by andrejtokarcik** [comment]
@Joerger `branch/v6` doesn't seem to include the keystore-related constants, functions like `Profile.SSHClientConfig`, etc., so is it really the case #6214 is applicable here?

**Comment by Joerger** [comment]
@andrejtokarcik It will be as soon as this PR passes CI and merges - #6131

**Review by Joerger — APPROVED** [review]

**Comment by andrejtokarcik** [comment]
#6214 is now incorporated.

Awaiting approval of #6213 for that to be incorporated as well.

**Review by russjones — APPROVED** [review]
Bot.

**Comment by flybyray** [comment]
> 
> 
> Backport of #5938.
> 
> ```diff
>  ~/.tsh/
>  └── keys
>     ├── one.example.com            --> Proxy hostname
>     │   ├── certs.pem              --> TLS CA certs for the Teleport CA
>     │   ├── foo                    --> RSA Private Key for user "foo"
>     │   ├── foo.pub                --> Public Key
> -   │   ├── foo-cert.pub           --> SSH certificate for proxies and nodes
>     │   ├── foo-x509.pem           --> TLS client certificate for Auth Server
> +   │   ├── foo-ssh                --> SSH certs for user "foo"
> +   │   │   ├── root-cert.pub      --> SSH cert for Teleport cluster "root"
> +   │   │   └── leaf-cert.pub      --> SSH cert for Teleport cluster "leaf"
> ```
> 
> When `-J` is provided, this also loads/reissues the SSH cert for the cluster associated with the jumphost's certificate. Fixes #5637.

https://github.com/gravitational/teleport/issues/6956

Brakes with a well known external tool `ssh-add` for simple usage when there is only cluster "root".
Can we have the old structure back by an option to the tsh client?

> ... "After loading a private key, ssh-add will try to load corresponding certificate information from the filename obtained by appending -cert.pub to the name of the private key file." ...
see: http://manpages.ubuntu.com/manpages/precise/en/man1/ssh-add.1.html

**Pull request merged**
