### PR TITLE
web: resource access request for `saml_idp_service_provider` 

### PR DESCRIPTION
**Pull request by flyinghermit**
The SAML apps are sent by the backend as "app" resource and shown as "apps" in the UI. To support resource access request, this PR adds the following changes in summary.

**Backend**:
- Adds `KindSAMLIdPServiceProvider` to `RequestableResourceKinds` constant.
- Updates presence service to fetch `saml_idp_service_provider` resource in `listResourcesWithSort`, which handles resource grouped under `RequiresFakePagination` such as `saml_idp_service_provider`.

**Frontend**:
- When an app resource is added, if the resource is a saml app `app.SamlApp`, the resource is added as `saml_idp_service_provider` kind so that the backend can properly handle the saml resource. The changes to support this are available in the `e` PR https://github.com/gravitational/teleport.e/pull/4767.
- Relevant resource access request types are updated to handle `saml_idp_service_provider` kind.

**Test changes**:
- Access request story.
- Manual testing (instructions below)

`e` counterpart: https://github.com/gravitational/teleport.e/pull/4767

Part of https://github.com/gravitational/teleport.e/issues/4723

---
<details><summary>Manual test instructions:</summary>

1. Create a role that grants access to SAML resource.
```
vi saml_all_access.yml
kind: role
metadata:
  name: saml_all_access
spec:
  allow:
    app_labels:
      '*': '*'
    rules:
    - resources:
      - saml_idp_service_provider
      verbs:
      - read
      - list
  options:
    ... default
version: v7

```
2. Create role that allow requesting access to the role created in step 1. 
```
vi resource_request_saml_all_access.yml
kind: role
metadata:
  name: resource_request_saml_all_access
spec:
  allow:
    request:
      search_as_roles:
      - saml_all_access
    rules:
    - resources:
      - saml_idp_service_provider
      verbs:
      - read
      - list
  options:
        ... default
version: v7
```

3. Grant a reviewer access to review `saml_all_access` role.
```
reviewer role:
spec:
  allow:
    review_requests:
      preview_as_roles:
      - saml_all_access
      roles:
      - saml_all_access
```
4. Grant `resource_request_saml_all_access` role to the user who wants to request access to SAML resource.
5. Remaining flow remains as is with every resource access request. -https://goteleport.com/docs/access-controls/access-requests/resource-requests/.
</details>

### CODE REVIEW

**Comment by flyinghermit** [comment]
Only addresses the Web UI. I will be following up with a separate PR to update Connect.

No changelog as this will be not backported to release branches and instead will be added to the "breaking changes" in `v17` once https://github.com/gravitational/teleport.e/issues/4723 is completed.

**Review by kimlisa — COMMENTED** [review]
i see mention of fake pagination, i thought that was like deprecated? cc @avatus (UI resource listing now uses ListUnifiedResources)

**Comment by flyinghermit** [comment]
Waiting to hear from @avatus that if the usage of `RequiresFakePagination` is really deprecated, but nowhere in the code mentions it as deprecated. Even then, the resources are only fetched with `ListUnifiedResources` initially but the resource access request dry run still hits `/accessrequest` endpoint, which ultimately invokes `PresenceService.ListResources`:
```
	switch {
	case req.RequiresFakePagination():
		return s.listResourcesWithSort(ctx, req)
	default:
		return s.listResources(ctx, req)
	}
```
The `saml_idp_service_provider` can be fetched with `PresenceService.listResources` (which uses raw backend get) but it does not fully implement the presence service. Cause the resource is manually added as opposed to other resources such as apps, server, database which are added to by their respective service proxy. That is why `saml_idp_service_provider`  was added to the `RequiresFakePagination` and in this PR, the `GetSAMLxxx` is added to the `PresenceService.listResourcesWithSort`.

**Review by avatus — APPROVED** [review]
Lisa is correct that we don't use fake pagination anymore when it comes to listing resources thanks to the unified resource cache, but this PR looks to just update the specific spots still calling ListResources (like an access request dry run) so in this case its fine.

**Review by kimlisa — APPROVED** [review]
unrelated to this PR, but i think we _should_ be  deprecating `ListResources` for `ListUnifiedResources` but maybe the former still has a particular use that i'm not seeing?

**Comment by flyinghermit** [comment]
Thank you both, for the review and approval. 

>  ... deprecating ListResources for ListUnifiedResources but maybe the former still has a particular use that i'm not seeing?

I think unpaged resource getter like `ListResources` is still required for dry run because that feature needs to fetch through all resources in order to verify the access request will succeed in future. Though, we can maybe update `ListUnifiedResources` to accommodate that and it would be nice to have a single method for this. 

OR, we can maybe do a dry run before even showing resource to user, removing the need for dry run after showing the resource entirely.

**Pull request merged**
