### PR TITLE
Pass JWTs on websocket requests, too

### PR DESCRIPTION
**Pull request by alexmv**

### CODE REVIEW

**Comment by alexmv** [comment]
I can't tell the Teleport-IntegrationTest failures because the Google Cloud Build output is not publicly readable.

**Comment by webvictim** [comment]
We're working on that :) The failure looks unrelated, though.

**Comment by alexmv** [comment]
Gentle ping on this?

**Comment by webvictim** [comment]
The best reviewer is @r0mant who is sadly out of the office right now.

**Review by r0mant — COMMENTED** [review]
@alexmv Thank you for your PR!

The implementation makes sense however we'd need to add a test covering this scenario before we can merge this. Ideally, extend [TestAppAccessRewriteHeadersRoot](https://github.com/gravitational/teleport/blob/3ff6889389bf74c3dcd3ad65f2665786e23d58be/integration/app_integration_test.go#L395) and [TestAppAccessRewriteHeadersLeaf](https://github.com/gravitational/teleport/blob/3ff6889389bf74c3dcd3ad65f2665786e23d58be/integration/app_integration_test.go#L501) to test this use-case.

Let us know if you would prefer us to take over the PR and help wrap it up. Thanks!

**Comment by alexmv** [comment]
You have a better understanding of the edit -> test cycle, so it' be great if you could finish this up  -- `make test` took quite a while to run, and I suspect there are faster ways to iterate.

I think running the tests you called out twice in a loop, with `Connection: upgrade` and `Upgrade: websocket` header the second time around, should suffice to exercise things.

**Comment by r0mant** [comment]
@alexmv Thank you again for your contribution! We've now taken over your PR (preserving your commit/authorship) in https://github.com/gravitational/teleport/pull/15667. Once that's reviewed and merged, we will backport it to the current release.

**Pull request closed without merging**
