### PR TITLE
Updated join command to correctly escape comments.

### LINKED ISSUE #4890: Error on using  token add command with app type
### Description

**What happened**:
The command given when a user runs `tctl tokens add --type=app` receives an error if it's copied into a command line.

```bash
teleport start \
   --roles=app \
   --token=3ed3d4e40e73d88b6d44f505 \
   --ca-pin=sha256:b4b56c31c201e5da92da11efcfb6195b73281a010d0c09 \
   --auth-server=app.example.com:3080 \
   --app-name=example-app                    \ # Change "example-app" to the name of your application.
   --app-uri=http://localhost:8080             # Change "http://localhost:8080" to the address of your application.
```

When you try to run this in a command line the first `#` causes an error.

```bash
$ teleport start \
>    --roles=app \
>    --token=9bf9fb0fedb88fc0da615d7 \
>    --ca-pin=sha256:b4b56c31c201e5da92da11efcfb6195b73281a010d0c09f7 \
>    --auth-server=app.example.com:3080 \
>    --app-name=example-app                    \ # Change "example-app" to the name of your application.
error: unexpected  #
$    --app-uri=http://localhost:8080             # Change "http://localhost:8080" to the address of your application.
```

**What you expected to happen**:

Like the other commands for nodes or tokens should be able to copy and paste without error.

**How to reproduce it (as minimally and precisely as possible)**:

Run `tctl tokens add --type=app`  and attempt to run the command given.

### Environment
- Teleport version (use `teleport version`): 5.0.rc1
- OS (e.g. from `/etc/os-release`): ubuntu

### PR DESCRIPTION
**Pull request by russjones**
**Description**

Bash does not support multi-line commands with comments within that command. Used backtick command substitution like recommended in this post to get the same result.

https://stackoverflow.com/a/12797512

The output now looks like:

```
$ tctl tokens add --type=app
The invite token: 0f3d377bc28d571a31559c04bdfa4ff6
This token will expire in 60 minutes

Fill out and run this command on a node to make the application available:

> teleport start \
   --roles=app \
   --token=0f3d377bc28d571a31559c04bdfa4ff6 \
   --ca-pin=sha256:4c08ecebc75c4636bb16d21c4368e6d4d78acca44e1d961e9ede7f8d856f8141 \
   --auth-server=proxy.example.com:3080 \
   --app-name=example-app                    `# Change "example-app" to the name of your application.` \
   --app-uri=http://localhost:8080           `# Change "http://localhost:8080" to the address of your application.`

Your application will be available at example-app.proxy.example.com:3080.

Please note:

  - This invitation token will expire in 60 minutes.
  - proxy.example.com:3080 must be reachable from the new application service.
  - Update DNS to point example-app.proxy.example.com:3080 to the Teleport proxy.
  - Add a TLS certificate for example-app.proxy.example.com:3080 to the Teleport proxy under "https_keypairs".
```

**Related Issues**

Fixes https://github.com/gravitational/teleport/issues/4890

### CODE REVIEW

**Review by r0mant — APPROVED** [review]
It's a shame you can't escape backticks inside backticks :)

**Comment by a-palchikov** [comment]
What about using a comment block preceding the actual bash command with the necessary explanations:
```
$ tctl tokens add --type=app
The invite token: 0f3d377bc28d571a31559c04bdfa4ff6
This token will expire in 60 minutes

Fill out and run this command on a node to make the application available:

# teleport start \
#   --roles=app \
#   --token=0f3d377bc28d571a31559c04bdfa4ff6 \
#   --ca-pin=sha256:4c08ecebc75c4636bb16d21c4368e6d4d78acca44e1d961e9ede7f8d856f8141 \
#   --auth-server=proxy.example.com:3080 \
#   --app-name=example-app \                  # Change "example-app" to the name of your application.
#   --app-uri=http://localhost:8080           # Change "http://localhost:8080" to the address of your application.


> teleport start \
   --roles=app \
   --token=0f3d377bc28d571a31559c04bdfa4ff6 \
   --ca-pin=sha256:4c08ecebc75c4636bb16d21c4368e6d4d78acca44e1d961e9ede7f8d856f8141 \
   --auth-server=proxy.example.com:3080 \
   --app-name=example-app \
   --app-uri=http://localhost:8080

Your application will be available at example-app.proxy.example.com:3080.

Please note:

  - This invitation token will expire in 60 minutes.
  - proxy.example.com:3080 must be reachable from the new application service.
  - Update DNS to point example-app.proxy.example.com:3080 to the Teleport proxy.
  - Add a TLS certificate for example-app.proxy.example.com:3080 to the Teleport proxy under "https_keypairs".
```
This way the first block is obviously a comment so it won't be used as a command and a bit of duplication is justified for the clarification benefit it brings.

**Comment by webvictim** [comment]
I think just printing it like this would be fine:

```
$ tctl tokens add --type=app
The invite token: 0f3d377bc28d571a31559c04bdfa4ff6
This token will expire in 60 minutes

Fill out and run this command on a node to make the application available, changing example values as appropriate:

> teleport start \
   --roles=app \
   --token=0f3d377bc28d571a31559c04bdfa4ff6 \
   --ca-pin=sha256:4c08ecebc75c4636bb16d21c4368e6d4d78acca44e1d961e9ede7f8d856f8141 \
   --auth-server=proxy.example.com:3080 \
   --app-name=example-app \
   --app-uri=http://localhost:8080

Your application will be available at example-app.proxy.example.com:3080.

Please note:

  - This invitation token will expire in 60 minutes.
  - proxy.example.com:3080 must be reachable from the new application service.
  - You must change 'example-app' to the name of your application.
  - You must change 'http://localhost:8080' to the address of your application.
  - Update DNS to point example-app.proxy.example.com:3080 to the Teleport proxy.
  - Add a TLS certificate for example-app.proxy.example.com:3080 to the Teleport proxy under "https_keypairs".
```

**Review by benarent — APPROVED** [review]
I do like some of these other proposals, but the inline comments make it very clear what needs to be changed vs a non-commented version. 

e.g. For Teleport Cloud, it's clear I only need to add two things to get up an running.
```
tctl tokens add --type=app
The invite token: 286299d6636823953b36c538xxxx
This token will expire in 60 minutes

Fill out and run this command on a node to make the application available:

> teleport start \
   --roles=app \
   --token=286299d6636823953b36c53866f14ff8 \
   --ca-pin=sha256:deaaec29ace4e8584606015dfa682501703141ea979fa5d30a1d508xxx \
   --auth-server=asteroid-sun.teleport.sh:443 \
   --app-name=example-app                    \ # Change "example-app" to the name of your application.
   --app-uri=http://localhost:8080             # Change "http://localhost:8080" to the address of your application.

Your application will be available at example-app.asteroid-sun.teleport.sh:443.

Please note:

  - This invitation token will expire in 60 minutes.
  - asteroid-sun.teleport.sh:443 must be reachable from the new application service.
  - Update DNS to point example-app.asteroid-sun.teleport.sh:443 to the Teleport proxy.
  - Add a TLS certificate for example-app.asteroid-sun.teleport.sh:443 to the Teleport proxy under "https_keypairs".
```

**Review by klizhentas — APPROVED** [review]

**Pull request merged**
