### PR TITLE
Add permalink to Docs Header Pages

### PR DESCRIPTION
**Pull request by benarent**
Screen Recording 2020-09-01 at 02 37 13 PM

### CODE REVIEW

**Comment by benarent** [comment]
retest this please

**Comment by benarent** [comment]
retest this please

**Comment by benarent** [comment]
retest this please

**Comment by webvictim** [comment]
As you've removed the `permalink` does this still do what it's intended to? (i.e. make things linkable)

**Comment by benarent** [comment]
I think it's being turned on an a different level now, I've tried it locally and when I had `permalink` on it showed up twice.

**Review by webvictim — APPROVED** [review]

**Pull request merged**
