### PR TITLE
Forward kubernetes errors to user when running in remote exec mode

### LINKED ISSUE #13023: Denied Kubernetes interactive sessions do not return the error to client
Expected behavior:
It is expected that any interactive `kubectl exec -it`  command that Kubernetes RBAC denies fails and returns the error to the user with the correct exit code.

Current behavior:
Interactive sessions return nothing to the user when they are denied and the exit code is always  `0`.

Bug details:

Given the following teleport user:
```
kind: role
version: v3
metadata:
  name: contractor
spec:
  allow:
    kubernetes_groups:
    - z4937-manual
    request:
      roles: ['dba']
---
kind: user
metadata:
  name: z4937m
spec:
  roles:
  - contractor
  status:
    is_locked: false
    lock_expires: "0001-01-01T00:00:00Z"
    locked_time: "0001-01-01T00:00:00Z"
  traits:
    logins:
    - z4937m
version: v2
```
and the following Kubernetes objects:
```
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: z4937-manual
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: z4937-manual
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: Group
  name: z4937-manual
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: z4937-manual
rules:
- apiGroups:
  - ""
  resources:
  - users
  - groups
  - serviceaccounts
  verbs:
  - impersonate
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
  - list
- apiGroups:
  - authorization.k8s.io
  resources:
  - selfsubjectaccessreviews
  verbs:
  - create
```

It is expected that any `kubectl exec -it`  fails and returns the error to the user.

The error is correctly returned by Kubernetes and caught by Teleport but it's never delivered to the user if the session is interactive.

https://github.com/gravitational/teleport/blob/ce4d6234ff29d96a63bedd4df55b2981e6680097/lib/kube/proxy/sess.go#L861

The user connection is already upgraded and we cannot write into the response writer.

Version: any  9.x.x

initially reported by @programmerq  on #12283

gz#5254

### PR DESCRIPTION
**Pull request by tigrato**
Fixes #13023

### CODE REVIEW

**Review by rosstimothy — COMMENTED** [review]
Is it possible to add tests for this?

**Comment by tigrato** [comment]
> Is it possible to add tests for this?

@xacrimon mentioned that in his last PR but the exec code has no testing

**Review by strideynet — APPROVED** [review]
Looks good. We should really get around to testing this code at some-point though...

**Review by programmerq — APPROVED** [review]
I just compiled this locally and brought my lab up again.

With a user that is not allowed to do a pod exec, I had the following output:

```
$ kubectl -v=7 -n z5254 exec pod/z5254-799db47856-k9h5d -- echo hello world
I0610 14:11:01.340730     116 loader.go:372] Config loaded from file:  /root/.kube/config
I0610 14:11:01.385173     116 round_trippers.go:463] GET https://z5254.telepath.cf:443/api/v1/namespaces/z5254/pods/z5254-799db47856-k9h5d
I0610 14:11:01.385227     116 round_trippers.go:469] Request Headers:
I0610 14:11:01.385240     116 round_trippers.go:473]     Accept: application/json, */*
I0610 14:11:01.385248     116 round_trippers.go:473]     User-Agent: kubectl/v1.24.1 (linux/amd64) kubernetes/3ddd0f4
I0610 14:11:01.581260     116 round_trippers.go:574] Response Status: 200 OK in 195 milliseconds
I0610 14:11:01.585179     116 podcmd.go:88] Defaulting container name to teleport
I0610 14:11:01.585751     116 round_trippers.go:463] POST https://z5254.telepath.cf:443/api/v1/namespaces/z5254/pods/z5254-799db47856-k9h5d/exec?command=echo&command=hello&command=world&container=teleport&stderr=true&stdout=true
I0610 14:11:01.585885     116 round_trippers.go:469] Request Headers:
I0610 14:11:01.585895     116 round_trippers.go:473]     User-Agent: kubectl/v1.24.1 (linux/amd64) kubernetes/3ddd0f4
I0610 14:11:01.585903     116 round_trippers.go:473]     X-Stream-Protocol-Version: v4.channel.k8s.io
I0610 14:11:01.585909     116 round_trippers.go:473]     X-Stream-Protocol-Version: v3.channel.k8s.io
I0610 14:11:01.585979     116 round_trippers.go:473]     X-Stream-Protocol-Version: v2.channel.k8s.io
I0610 14:11:01.586020     116 round_trippers.go:473]     X-Stream-Protocol-Version: channel.k8s.io
I0610 14:11:01.679015     116 round_trippers.go:574] Response Status: 101 Switching Protocols in 92 milliseconds
error: pods "z5254-799db47856-k9h5d" is forbidden: User "ro" cannot create resource "pods/exec" in API group "" in the namespace "z5254"
```

This is indeed the desired behavior.

The audit events that appeared during that failed request:

```json
{"ei":0,"event":"session.start","uid":"06eaed6c-92f0-44dc-be45-a5c03114ebf5","code":"T2000I","time":"2022-06-10T14:11:01.91Z","cluster_name":"z5254.telepath.cf","user":"ro","login":"ro","sid":"4d0cf6ed-2b85-48dc-b62b-684e20186af4","namespace":"default","server_id":"68dd828c-940b-4723-8bd9-7d859c288c89","server_hostname":"z5254.telepath.cf","addr.remote":"127.0.0.1:57146","proto":"kube","kubernetes_cluster":"z5254","kubernetes_users":["ro"],"kubernetes_groups":["system:authenticated","z5254ro"],"kubernetes_pod_name":"z5254-799db47856-k9h5d","kubernetes_pod_namespace":"z5254","kubernetes_container_name":"teleport","kubernetes_container_image":"programmerq/tp-10.0.0-dev:latest","kubernetes_node_name":"ip-192-168-76-77.us-east-2.compute.internal","initial_command":["echo","hello","world"],"session_recording":"node"}
{"ei":0,"event":"exec","uid":"c6787d35-e073-4595-938c-6ca9f6d7020f","code":"T3002E","time":"2022-06-10T14:11:01.916Z","cluster_name":"z5254.telepath.cf","user":"ro","login":"ro","addr.remote":"127.0.0.1:57146","proto":"kube","sid":"4d0cf6ed-2b85-48dc-b62b-684e20186af4","namespace":"default","server_id":"68dd828c-940b-4723-8bd9-7d859c288c89","server_hostname":"z5254.telepath.cf","command":"echo hello world","exitCode":"403","exitError":"pods \"z5254-799db47856-k9h5d\" is forbidden: User \"ro\" cannot create resource \"pods/exec\" in API group \"\" in the namespace \"z5254\"","kubernetes_cluster":"z5254","kubernetes_users":["ro"],"kubernetes_groups":["system:authenticated","z5254ro"],"kubernetes_pod_name":"z5254-799db47856-k9h5d","kubernetes_pod_namespace":"z5254","kubernetes_container_name":"teleport","kubernetes_container_image":"programmerq/tp-10.0.0-dev:latest","kubernetes_node_name":"ip-192-168-76-77.us-east-2.compute.internal"}
{"ei":0,"event":"session.end","uid":"16383a00-2ac3-42a7-9057-ae925e79a2bf","code":"T2004I","time":"2022-06-10T14:11:01.917Z","cluster_name":"z5254.telepath.cf","user":"ro","login":"ro","sid":"4d0cf6ed-2b85-48dc-b62b-684e20186af4","addr.remote":"127.0.0.1:57146","proto":"kube","namespace":"default","server_id":"68dd828c-940b-4723-8bd9-7d859c288c89","server_hostname":"z5254.telepath.cf","enhanced_recording":false,"interactive":false,"participants":null,"session_start":"2022-06-10T14:11:01.910023674Z","session_stop":"2022-06-10T14:11:01.915853922Z","kubernetes_cluster":"z5254","kubernetes_users":["ro"],"kubernetes_groups":["system:authenticated","z5254ro"],"kubernetes_pod_name":"z5254-799db47856-k9h5d","kubernetes_pod_namespace":"z5254","kubernetes_container_name":"teleport","kubernetes_container_image":"programmerq/tp-10.0.0-dev:latest","kubernetes_node_name":"ip-192-168-76-77.us-east-2.compute.internal","initial_command":["echo","hello","world"],"session_recording":"node"}
```

This is also the desired behavior.

LGTM!

**Review by r0mant — APPROVED** [review]

**Pull request merged**
