### PR TITLE
Query target version in discovery script

### PR DESCRIPTION
**Pull request by hugoShaka**
Unlike what's written in the file shebang, this is not bash but sh 🙃 .

I had to rewrite to bourne-shell compliant script.

I removed the `$PACKAGE_LIST` var entirely for 2 reasons:
- this cannot be safely pbuilt, passed and parsed by apt. A naive implementation would allow arbitrarily package install from the version server. A smarter implementation would use bash arrys. I did this initially but SSM doesn't run us as bash.
- the way to pin versions differs between apt/zypper and yum. One package list doesn't fit all distros.

The resulting script is a bit ugly.

changelog: Fix a bug when using automatic updates and the discovery service. The default install script now installs the correct teleport version by querying the version server.

### CODE REVIEW

**Review by fspmarshall — APPROVED** [review]
I think this is a good quick fix.  Long-run, lets add a subcommand to the upgrader to ask it to pull the target version, that way it can be the single source of truth for target version.

**Review by tigrato — APPROVED** [review]

**Comment by hugoShaka** [comment]
> I think this is a good quick fix. Long-run, lets add a subcommand to the upgrader to ask it to pull the target version, that way it can be the single source of truth for target version.

I agree, I think what roman suggested (having a subcommand in the teleport-upgrader package that does the install) sounds like a good idea.

The install flow would be
- install the updater
- run `teleport-upgrade install --proxy=foo.teleport.sh`
- the updater runs the apt/um/whatever logic to install the package

**Review by fspmarshall — APPROVED** [review]

**Review by marcoandredinis — CHANGES_REQUESTED** [review]
It seems that there's a typo in `TELEPORT_UPDATER_PACKAGE` var.

**Review by marcoandredinis — APPROVED** [review]
We must change the agentless script as well

**Comment by hugoShaka** [comment]
TIL, we install teleport for agentless, AND it updater. I'm not sure what advantage agentless discovery has over teleport at this point 🤷‍♂️

**Comment by marcoandredinis** [comment]
> TIL, we install teleport for agentless, AND it updater. I'm not sure what advantage agentless discovery has over teleport at this point 🤷‍♂️

It's only used for joining the cluster and configuring openssh.
It will also do cert rotations.

The true agentless mode is the EC2 ICE, but it only works for AWS EC2 and only a subset of distros.

**Review by marcoandredinis — APPROVED** [review]

**Pull request merged**
