### PR TITLE
Removes AD scripts

### PR DESCRIPTION
**Pull request by ibeckermayer**
Also removes the desktop discover flow, which relied on the AD scripts.

Follow on to https://github.com/gravitational/teleport/pull/34010

closes https://github.com/gravitational/teleport/issues/12791
closes https://github.com/gravitational/teleport/issues/20271

### CODE REVIEW

**Review by ryanclark — APPROVED** [review]
RIP

**Review by avatus — APPROVED** [review]
-3000 🤯

**Review by rudream — APPROVED** [review]

**Comment by zmb3** [comment]
Please double check the success criteria for this goal in slab.

**Comment by ibeckermayer** [comment]
@zmb3 I see, we want to convert this to a non-AD discover flow. Converting this to draft for now then.

**Pull request closed without merging**
