### PR TITLE
docs: Versions are out of date

### PR DESCRIPTION
**Pull request by webvictim**
Not sure what the actual procedure is supposed to be for updating these versions, but they hadn't been done in a while.

### CODE REVIEW

**Comment by webvictim** [comment]
Cloud version is already updated by https://github.com/gravitational/teleport/pull/23011

**Review by zmb3 — COMMENTED** [review]
These are generally updated directly on the release branches, IIRC.

**Comment by webvictim** [comment]
Makes sense, I just won't bother updating this in that case.

**Comment by alexfornuto** [comment]
FWIW, I'd like to re-open and update this. the `master` branch is still used for views of the next release, so having our example code use 11.x doesn't make sense. Not sure what version would make sense for pre-release, but since I use the `master` branch to write and test new docs, having it match the current version would make things easier.

**Comment by webvictim** [comment]
Technically `master` should be on something like `v13.0.0-dev` now, right?

**Comment by webvictim** [comment]
e

**Comment by alexfornuto** [comment]
> Technically `master` should be on something like `v13.0.0-dev` now, right?

Yes, either this or the current version would work for me.

**Review by alexfornuto — APPROVED** [review]

**Review by ptgott — APPROVED** [review]

**Pull request merged**
