### PR TITLE
Fixed enterprise and FIPS OS packages not uploading to OS package repositories when promoting in the context of private git repos

### PR DESCRIPTION
**Pull request by fheinecke**
This PR fixes a corner case of our publishing pipelines where Drone promotion runs that are in the context of a private repository (teleport-private) do not publish built DEB and RPM packages to APT and YUM repos.

Related issue: https://github.com/gravitational/teleport-private/issues/267

I'm not quite sure how to fully test this without actually triggering a release in a private repo... any suggestions?

### CODE REVIEW

**Comment by r0mant** [comment]
> I'm not quite sure how to fully test this without actually triggering a release in a private repo... any suggestions?

@fheinecke Yeah, trigger a release in the private repo? :)

**Comment by fheinecke** [comment]
> @fheinecke Yeah, trigger a release in the private repo? :)

@r0mant if I do so (and everything goes well) then doing so will publish a new minor version. There are protections in place to prevent dev tags from being published... and even if I bypassed those, it would result in a dev tag in the APT/YUM repos that may have unintended consequences. Are you sure that's the route we wanna go?

**Comment by r0mant** [comment]
@fheinecke Yeah, I keep forgetting we don't publish dev releases to these repos. Maybe a dumb idea but: would publishing an intentionally very old release version work? For example, tag it as `v1.1.1`, this way it would go through all normal pipelines but won't appear as a latest release anywhere. Would that work or will this mess up something else?

**Review by r0mant — APPROVED** [review]
lgtm assuming this works

**Review by tigrato — APPROVED** [review]

**Pull request merged**
