### PR TITLE
Initial user group object.

### PR DESCRIPTION
**Pull request by mdwn**
The user group object has been added to support the Okta appaccess integration feature. Please see https://github.com/gravitational/teleport.e/pull/609 for more information.

The local service for handling backend management of the user group objects has been added as well. This will be expanded upon in a later PR.

### CODE REVIEW

**Comment by zmb3** [comment]
What do you think about changing the name of the resource? It's not clear that it's a group of users. Could mean a group of resources or something else. `UserGroup` or `SAMLGroup` maybe?

Also, please connect with @rosstimothy to ensure that someone from the performance and scale team reviews this. Adding new resources can often break the cache if not done correctly.

**Comment by mdwn** [comment]
> What do you think about changing the name of the resource? It's not clear that it's a group of users. Could mean a group of resources or something else. `UserGroup` or `SAMLGroup` maybe?
> 
> Also, please connect with @rosstimothy to ensure that someone from the performance and scale team reviews this. Adding new resources can often break the cache if not done correctly.

I think UserGroup makes more sense here. I'll make sure to include him!

**Review by rosstimothy — COMMENTED** [review]
I don't see this being added to the cache here, will that be done in a follow up PR?

**Comment by mdwn** [comment]
> I don't see this being added to the cache here, will that be done in a follow up PR?

Yes, that's correct -- I planned on adding this into the cache when dealing with the API bits and pieces.

**Comment by mdwn** [comment]
Ping on this @rosstimothy, @rudream, @timothyb89

**Comment by mdwn** [comment]
Ping @rosstimothy @rudream @timothyb89.

**Review by rosstimothy — APPROVED** [review]

**Review by strideynet — APPROVED** [review]

**Pull request merged**
