### PR TITLE
feat(helm): expose securityContext as a value

### LINKED ISSUE #7766: Docker image mage run as root but psp dose not allow it in helmchart
### Description
The image `quay.io/gravitational/teleport:6` runs as root but the psp dose not allow it in the helm chart.

**What happened**:

Container dose not start.

```
Error: container has runAsNonRoot and image will run as root (pod: "teleport-cluster-86f5c579d-kxg5z_teleport-cluster(09a1c822-29e4-41c7-90ef-289942d3238b)", container: teleport)
```

**What you expected to happen**:

Run the pod without error.

### Reproduction Steps
```bash
helm repo add teleport https://charts.releases.teleport.dev

helm install teleport-cluster teleport/teleport-cluster --create-namespace --namespace=teleport-cluster \
  --set clusterName=rke2
```

### Server Details
- k8s version: rke2 v1.21.3+rke2r1

### LINKED ISSUE #7821: teleport-cluster helm chart should support running pods as non-root user
### What

Our helm chart should be able to start the teleport pods as a non-root user.

### How

The deployment template would have a section to render a securityContext with a non-root uid similar to the [teleport-kube-agent deployment template](https://github.com/gravitational/teleport/blob/a177241e89513fb15e6e2e66fb1f40183755ae08/examples/chart/teleport-kube-agent/templates/deployment.yaml#L52-L59).

### Why

Some environments require all software that can run as non-root to run as a non-root user. This common security policy is aligned with NIST 800-53r5 AC6 Least Privilege.

### Workaround

Currently, it is possible to implement a helm [post-renderer](https://helm.sh/docs/topics/advanced/#post-rendering) that can add the securitycontext to the rendered resources before creating them in the cluster. This is less than ideal since the `--post-renderer` flag and binary must be provided exactly the same way on every system that ever does a helm operation. The post-renderer does not follow the release at all. This means that if someone makes a small change to the values for the release, the post-renderer patch will not be applied if they forget to include it explicitly in the helm command.

gz#3157

### PR DESCRIPTION
**Pull request by daquinoaldo**
The PodSecurityPolicy specifies `MustRunAsNonRoot` but the image runs as root.
`Error: container has runAsNonRoot and image will run as root (pod: "<redacted>", container: teleport).`
We expose the securityContext to allow forcing to run as a non-root user such as 99 (nobody) and respect the psp.

Mitigates #7766

### CODE REVIEW

**Comment by webvictim** [comment]
@daquinoaldo What's actually generating this error? I don't believe Helm/Kubernetes themselves validate this.

Could you please add a unit test for this as per https://github.com/gravitational/teleport/blob/master/examples/chart/CONTRIBUTING.md? I'd like to make sure that we don't inadvertently revert this in future.

**Review by webvictim — CHANGES_REQUESTED** [review]
As per comment

**Comment by daquinoaldo** [comment]
@webvictim 

> What's actually generating this error? I don't believe Helm/Kubernetes themselves validate this.

`kubectl describe pod <POD_NAME>` shows this error among the Pod events.

The issue is that you are deploying a PodSecurityPolicy that states the container `mustRunAsUser`, but the image's user is `root`, so the container will run as root unless you force a different user. So Kubernetes won't allow running your Pod because it will run as root, and the policy state it must not.

In my previous comment, I edited the PSP to allow the container to run as root, but after some tests, I discovered we could run it as non-root. This new fix forces running it as non-root: I used the `nobody` user with UID `99`.
A different approach could be to create a user in the Dockerfile (`RUN adduser -u 123 teleport ...`) and then specify the container must run as such user (`USER 123`).

Note that the image seems to work fine using a non-root user, **but** when you set `proxyListenerMode: "multiplex"`, which uses port `443` (you must be root to use ports 1-1024).
I exposed the `securityContext` as a value to allow running as root. In this case, the issue with the PSP remains, so the user must still create a security policy on its own (which was my workaround before this PR).
However, you may want to change such port in release v10.0.0 because it's such a waste not running as root just because of the port. I can implement this change too if you want, but I need some help. I don't understand where you expose the port: there is no `targetPort: 443` in the service. If that port is somehow exposed, I think we should be able to make this change not so breaking by keeping the same external port (exposed by the service) and changing only the container port.

**Comment by webvictim** [comment]
This issue is tracked more broadly in https://github.com/gravitational/teleport/issues/5690 and https://github.com/gravitational/teleport/issues/2909.

Philosophically, I do agree that we ought not to run as `root` (the `teleport-kube-agent` chart [already does this](https://github.com/gravitational/teleport/blob/master/examples/chart/teleport-kube-agent/templates/deployment.yaml#L123-L130)) - however the Docker image still runs as the `root` user for backwards compatibility with use cases where people were running an `ssh_service` in Docker and might need to spawn sessions as `root`. Changing the Docker image itself to run as a non-root user is undesirable as it might break currently working setups. 

There's also the issue with port 443 as you mentioned, although we could switch to using 3080 inside the container and then map external requests from 443 -> 3080 using `targetPort` as discussed.

Changing this chart to run as a non-root user is likely to break installations where people are using a `PersistentVolumeClaim` for their cluster storage, as the container will no longer be running as the correct the UID/GID to read the files stored on the volume. We'd need some kind of `initContainer` (which does run as `root`) to run a `chown -R nobody:nobody /var/lib/teleport` before startup to prevent errors. The fact that this is tough to do and test in a way that doesn't break existing installations is, unfortunately, the reason i haven't done it.

**Comment by daquinoaldo** [comment]
@webvictim as you prefer, but mind that your Helm chart is currently broken for all the users who have Pod Security Policies enabled: it states the container must run as non-root, while you just explained why you don't want this behavior.

Anyway, I firmly believe that force running it as root when not necessary is not the right path, and I won't propose changes on PSP (at least, I won't use them).
What if I expose the `securityContext` as a value and set it to `null` as default instead? This way, users affected by this bug can force the image to run as non-root, on the condition they don't use features that require running as root. It's an opt-in approach that doesn't affect current users.

**Comment by webvictim** [comment]
@daquinoaldo Sure, I think that's a good compromise. Please update the PR.

**Comment by daquinoaldo** [comment]
@webvictim ready to go! 🚀

Do you have any idea about when this change will be published on a released chart? Any chance to get it in a `9.x` release maybe? It's not breaking anymore.

**Review by webvictim — COMMENTED** [review]
@daquinoaldo Thanks! Could you please also do the following:

- add the new `securityContext` value at the correct location in the `teleport-cluster` chart reference: https://github.com/gravitational/teleport/blob/master/docs/pages/kubernetes-access/helm/reference/teleport-cluster.mdx
- add an additional unit test which asserts that `securityContext` is not set in deployment.yaml when the value is a blank object `{}`

**Comment by daquinoaldo** [comment]
@webvictim ✅ Done.

Please note that `make -C build.assets lint-helm` seems not working.
```sh
$ make -C build.assets lint-helm   
make: *** No rule to make target `lint-helm'.  Stop.
```

Moreover, `make lint-helm` reports an error (correct, as PSPs are deprecated).
```sh
$ make lint-helm             
Using values from 'examples/chart/teleport-cluster/.lint/acme-off.yaml': ==> Linting examples/chart/teleport-cluster
[WARNING] templates/psp.yaml: policy/v1beta1 PodSecurityPolicy is deprecated in v1.21+, unavailable in v1.25+

Error: 1 chart(s) linted, 1 chart(s) failed
make: *** [lint-helm] Error 1
```

**Review by webvictim — APPROVED** [review]

**Review by r0mant — APPROVED** [review]

**Pull request closed without merging**
