### PR TITLE
fix build error on 32bit environment

### PR DESCRIPTION
**Pull request by gaoyifan**
fix the following compile error:

```
make -f version.mk setver
make[1]: Entering directory '/home/yifan/go_user/src/github.com/gravitational/teleport'
make[1]: Leaving directory '/home/yifan/go_user/src/github.com/gravitational/teleport'
go build -o build/teleport -i -ldflags -w ./tool/teleport
go build -o build/tctl -i -ldflags -w ./tool/tctl
# github.com/gravitational/teleport/vendor/github.com/buger/goterm
vendor/github.com/buger/goterm/terminal.go:106: constant 2147483648 overflows int
vendor/github.com/buger/goterm/terminal.go:110: constant 2147483648 overflows int
Makefile:34: recipe for target 'tctl' failed
make: *** [tctl] Error 2
```

### CODE REVIEW

**Comment by sofuture** [comment]
Hey @gaoyifan thanks for the patch! I think we'll probably make this change by vendoring a newer version of `github.com/buger/goterm` -- it looks like a PR with the same fix was just accepted there https://github.com/buger/goterm/pull/4

**Comment by sofuture** [comment]
Can you update this PR with a `godep update github.com/buger/goterm`?

**Comment by sofuture** [comment]
ok to test

**Comment by sofuture** [comment]
@kontsevoy gonna kick this over to you

**Comment by kontsevoy** [comment]
thanks @gaoyifan

**Pull request merged**
