### PR TITLE
[helm] add proxy_service.trust_x_forwarded_for option

### PR DESCRIPTION
**Pull request by greedy52**
Related PR
- #26623 
- #28461

### CODE REVIEW

**Comment by hugoShaka** [comment]
If I understand correctly, we want to set this field only when there's an L7 LB in front of Teleport, and if this is badly configured, either we have a security issue, or we cannot enforce IP restrictions.

I'm affraid the users will not get this right, especially because the first configuration they try will "just work". I would prefer this setting to be enabled automatically when the user configures the chart to use an ingress instead of a L4 LB. Can this be part of @webvictim 's [ingress PR](https://github.com/gravitational/teleport/pull/25815) instead and enabled automatically?

For more complex use cases (users with a L7 LB in front of the Kubernetes L4 LB) they can always set the `proxy.teleportConfig.proxy_service.trust_x_forwarded_for: true`.

**Comment by greedy52** [comment]
@hugoShaka it would be great if this change can somehow integrate into @webvictim 's ingress change somehow.

The reason I wanted a separate flag is L7 LB is only part of the requirement. The user must also ensure that the L7 LB is setting the "X-Forwarded-For" headers. For example, when adding an `alb` ingress, someone can technically set `alb.ingress.kubernetes.io/load-balancer-attributes: routing.http.xff_header_processing.mode=remove`. Other ingresses may require explicit settings to enable "X-Forwarded-For". Thus this setting default to false to require manual input.

Not sure what's the best way to communicate this and make this less error prune. What do you think?

**Comment by webvictim** [comment]
It's a trivial change for me to automatically set this when `ingress.enabled=true`:

```yaml
proxy_service:
  trust_x_forwarded_for: true
```

**Comment by hugoShaka** [comment]
If LBs exhibit a sane behaviour out of the box, we should be able to turn this on by default. Worst case scenario: the user will add `remove` the annotation to the LB (which is not currently supported by the chart, so it's not a breaking change) and traffic will be rejected. For power users (absolutely nobody) we can drop a few documentation lines in the chart ingress docs saying we enable this by default.

The most significant risk is a L7 LB happily propagating user-provided X-Forwarded-For headers without adding its IP in the middle. This would allow an attacker to forge the source IP. I checked GCP, AWS, Azure, IBM, Oracle, Alibaba, nginx-ingress-controller and they all default to some form of X-Forwarded-For (nginx-ingress-controller replaces by default instead of appending).

Enabling this by default will also add a new failure more: users chaining L7 LBs configured to append the headers. However, this seems niche and users chaining multiple proxies can always manually disable the feature.

**Comment by greedy52** [comment]
> If LBs exhibit a sane behaviour out of the box, we should be able to turn this on by default. Worst case scenario: the user will add `remove` the annotation to the LB (which is not currently supported by the chart, so it's not a breaking change) and traffic will be rejected. For power users (absolutely nobody) we can drop a few documentation lines in the chart ingress docs saying we enable this by default.
> 
> The most significant risk is a L7 LB happily propagating user-provided X-Forwarded-For headers without adding its IP in the middle. This would allow an attacker to forge the source IP. I checked GCP, AWS, Azure, IBM, Oracle, Alibaba, nginx-ingress-controller and they all default to some form of X-Forwarded-For (nginx-ingress-controller replaces by default instead of appending).
> 
> Enabling this by default will also add a new failure more: users chaining L7 LBs configured to append the headers. However, this seems niche and users chaining multiple proxies can always manually disable the feature.

Sounds good!

I will close this PR. @webvictim do you mind adding this to your ingress change then?

cc @smallinsky

**Comment by webvictim** [comment]
Yes, this has been added to #25815 :)

**Pull request closed without merging**
