### PR TITLE
Adds docs for Cloud-hosted Jira plugin

### PR DESCRIPTION
**Pull request by tcsc**
Adds documentation for the cloud-hosted Jira integration. This documentation is accessed by selecting the "cloud" scope on the page.

### CODE REVIEW

**Comment by ptgott** [comment]
Hi @tcsc, I have a PR to refresh the self-hosted Jira plugin instructions here: https://github.com/gravitational/teleport/pull/29827

The self-hosted instructions are currently out of date, and don't provide a series of steps that a user can follow all the way through.

I think we should merge that PR before adding the instructions for the managed plugin. I'm also happy to base these changes on to my PR.

What do you think?

**Review by r0mant — APPROVED** [review]

**Comment by tcsc** [comment]
I think it's probably better to get your update through the PR process (rather than add yet another chunk of stuff for people to object to in review) - but I have no objections to either approach.

**Review by ptgott — COMMENTED** [review]
I've looked at this in some more detail, and I think we should step back and take a look at how we organize our docs for managed and self-hosted Access Request plugins.

First, I'd really like to move away from `ScopedBlocks`, since users tend to find the scope switcher at the top of the page confusing. The vast majority of users stick with the default `oss` scope, meaning that if we merge this PR as-is, those users won't see that you can enable the cloud-hosted Jira plugin.

Second, are there docs for hosted plugins in the Web UI? If so, I think we can:
- Add a prominent explanation of hosted Access Request plugins in the Access Request Plugins [menu page](https://goteleport.com/docs/access-controls/access-request-plugins/), indicating that you can enable and configure a plugin via the "Enroll New Integration" tab
- Make it clear that the docs are only for users who are self-hosting their Access Request plugins
- Not include any other docs for hosted plugins on the docs site

If we go with this approach, I can take care of it in a separate PR.

Otherwise, if we want to include instructions for managed and self-hosted Access Request plugins in the same docs page, I would rather that we use `Tabs` than `ScopedBlock`s, since at least users will know that there are multiple possibilities.

What do you think?

**Comment by ptgott** [comment]
Closing since we ended up taking a different approach to documenting the hosted Jira plugin.

**Pull request closed without merging**
