### PR TITLE
Update `protoc-gen-terraform` to v3.0.0

### PR DESCRIPTION
**Pull request by eriktate**
Relates to #33288

This PR makes some necessary changes to update `protoc-gen-terraform` to `v3.0.0`. It's a large PR because it also adds a bunch of terraform provider reference documentation that was failing to generate before. For that reason, this is split into two commits. The first one contains the actual code/configuration changes required to move to `v3.0.0`. The second contains only the generated documentation changes. I don't think I can actually split this into multiple PRs due to the linter requiring terraform generation to run, but if there's a good way to make this smaller I'm happy to do that :+1:

changelog: Added missing field-level documentation to the terraform provider reference.

### CODE REVIEW

**Review by hugoShaka — APPROVED** [review]
LGTM and thank you so much for improving the provider and its documentation.

The prose linter is failing but you can ignore it. Don't rewrite every proto message.

The Go Linter is failing because it cannot install the correct version. Would you mind updating the `protoc-gen-tfschema` ref in the CI job? Edoardo pinned it in https://github.com/gravitational/teleport/pull/47268.

**Review by r0mant — APPROVED** [review]

**Review by marcoandredinis — APPROVED** [review]

**Review by tigrato — APPROVED** [review]

**Comment by tigrato** [comment]
@eriktate you also need to update the lint workflow and

**Review by rosstimothy — APPROVED** [review]

**Comment by hugoShaka** [comment]
As the proto files were updated, you must re-generate everything that depends on them:

```bash
make -C integrations/operator generate manifests crd-docs
make -C integrations/terraform gen-tfschema docs
```

**Comment by eriktate** [comment]
> The prose linter is failing but you can ignore it. Don't rewrite every proto message.

@hugoShaka I unfortunately missed this sentence and I already fixed the prose lint errors 😅 I can revert those if we really don't want to carry them through, but they were all fairly straightforward changes. There weren't really that many of them and pretty much all of them were either capitalizing `access list/request` or rewriting `auth server` to `Auth Service` or `Auth Service instance`.

**Pull request merged**
