### PR TITLE
Remove API aliases

### PR DESCRIPTION
**Pull request by Joerger**
This PR removes type aliases added for types moved to `/api/...` - [outlined in RFD](https://github.com/gravitational/teleport/blob/master/rfd/0010-api.md#approach)

e PR - https://github.com/gravitational/teleport.e/pull/266

Updates #6393

### CODE REVIEW

**Review by awly — APPROVED** [review]
This PR brings me joy, well done!

Can you also clean up:
- https://github.com/gravitational/teleport/blob/9835c6685e1e684d5ca3de3afb49e69b3c94df62/lib/auth/clt.go#L59-L63
- https://github.com/gravitational/teleport/blob/master/lib/utils/aliases.go

**Comment by Joerger** [comment]
> * https://github.com/gravitational/teleport/blob/9835c6685e1e684d5ca3de3afb49e69b3c94df62/lib/auth/clt.go#L59-L63
> * https://github.com/gravitational/teleport/blob/master/lib/utils/aliases.go

Yes thanks for reminding me, I'll do that in another PR to avoid eternally resolving merge conflicts on this PR.

**Review by andrejtokarcik — APPROVED** [review]

**Comment by Joerger** [comment]
@r0mant @russjones Bot

**Review by russjones — APPROVED** [review]
Bot.

**Pull request merged**
