### PR TITLE
Execute SSH on first server of a kind

### PR DESCRIPTION
**Pull request by klizhentas**
In most cases when you have many nodes of the same kind, you just want to SSH into any one.

### CODE REVIEW

**Comment by klizhentas** [comment]
retest this please

**Comment by klizhentas** [comment]
retest this please

**Comment by kontsevoy** [comment]
I will merge this with a slightly better implementation and more robust test (as part of merging new audit). Let is sit here for a day.

**Comment by klizhentas** [comment]
sure

**Comment by klizhentas** [comment]
testing Jenkins integration. 
retest this please

**Comment by kontsevoy** [comment]
This has been merged via 8a2d6c6baec4cca7c15038ad46966a288688af87

**Pull request closed without merging**
