### PR TITLE
Linting adjustment for comment-space complaint

### PR DESCRIPTION
**Pull request by thg-adamdean**
Small adjustment to allow for default linting to not be affected by the lack of a space between the comment symbol and first symbol of the yaml stanza.

Only 6 places where this happens, I've fixed in our setup but would like to remove the step by pushing it here.

### CODE REVIEW

**Comment by webvictim** [comment]
Is this a change in newer versions of Helm? The current linter has no issue with the comments in their existing form.

**Comment by thg-adamdean** [comment]
@webvictim seems to come in from `yamllint` 1.26.3.

**Review by webvictim — APPROVED** [review]
Cool - I'm OK with this minor change if it helps with linting overall. Thanks for the PR!

**Review by zmb3 — APPROVED** [review]

**Review by r0mant — APPROVED** [review]

**Pull request merged**
