### PR TITLE
Remove unused functions and methods throughout lib/...

### PR DESCRIPTION
**Pull request by awly**
This code is not caught by linters because it's exported and they assume
there's some external users.
Since teleport is relatively self-contained, we can tell for sure
whether something is called or not.

### CODE REVIEW

**Comment by r0mant** [comment]
@awly @russjones JFYI Be careful with this folks, some of it may be used by Gravity which vendors Teleport as a library.

**Comment by awly** [comment]
> @awly @russjones JFYI Be careful with this folks, some of it may be used by Gravity which vendors Teleport as a library.

@r0mant 
With some local hackery, I found and restored a few functions removed here that are used by gravity (`utils.FSWriteLock`, `utils.GenerateOTPURL` and `utils.GenerateQRCode`).
At least for OTP, I recommend copying the code over to gravity repo (not vendoring).

However, I wasn't able to build recent gravity with this branch of teleport. There seems to be a ton of incompatibilities not related to this PR (e.g. some expanded interface definitions in teleport).
JFYI, your next teleport dependency update might get painful.

**Comment by r0mant** [comment]
> JFYI, your next teleport dependency update might get painful.

Lol, I'm fully aware, thanks 😄

**Review by russjones — APPROVED** [review]
@r0mant This looks relatively safe. What do you think?

**Review by r0mant — APPROVED** [review]

**Pull request merged**
