### PR TITLE
update application access getting started video

### PR DESCRIPTION
**Pull request by rodgtr1**
Getting started video was about 2 years old. Created a new one to represent updated documentation. This PR is to change the video. Update: Working on a revision currently.

### CODE REVIEW

**Review by zmb3 — APPROVED** [review]

**Comment by zmb3** [comment]
@rodgtr1 I did notice a few things in this video.

- You forgot the `\` character when you added the `--labels` flag, so no labels were included on the app.
- You used `teleport app start` to start the service for the first time, but the systemd service that got installed probably just does a `teleport start`, and since you didn't generate a teleport.yaml things will probably stop working after a reboot.

**Comment by rodgtr1** [comment]
@zmb3 Good call out. I'll correct the first point now and recommit. For the second, how does this fit with the documentation flow? Do the docs need to be adjusted, or is it something I can rework and mention in addition to the what the docs state (what would be the correct flow)?

**Comment by zmb3** [comment]
What `teleport app start` and friends (`teleport db start`, etc) do is essentially generating a temporary config with all services other than app/db disabled, and then starting Teleport with that config. This config is never actually written to disk and is not visible to the user.

We've been trying to move away from this pattern for several reasons, but it ultimately boils down to this:

It doesn't create a natural progression where you learn more about Teleport the more you use it. Eventually you'll run into some configuration option that you need to set, but you've never had a teleport.yaml, so there's a big gap to fill with converting your `teleport app start` command into a proper configuration file.

Instead, what we prefer to do is something like this (using SSH as an example):

```
$ teleport node configure > /etc/teleport.yaml
$ teleport start --config=/etc/teleport.yaml
```

This approach allows those who are curious to poke around at the configuration file that was generated and naturally start to learn more, and doesn't require you to make major changes to the config as you grow and customize your cluster.

Unfortunately, we don't yet have an app-specific `teleport app configure` command, so you'd probably want to use the generic `teleport configure` command. Perhaps something along the lines of `teleport configure --roles=app --app-name=grafana --app-uri=http://localhost:8
080`

**Comment by rodgtr1** [comment]
@zmb3 Ahh, that's actually very helpful in filling some gaps that I've had, thanks for explaining. Normally with these 'getting-started' guides they serve as a video walkthrough of the docs. Should the docs be updated first then to reflect a yaml configure step or at least mention the non-persistence of the config? I ask because when I redo it I would have to give a "the docs say this...but here's actually what you need to know to make it work" kind of mention.

**Comment by rodgtr1** [comment]
@ptgott or @alexfornuto do you have any thoughts on the above dialog? Do you think something should be added re: the teleport.yaml and non-persistence? If so, I'll just close this PR and create a new one for that. Thanks in advance!

**Comment by ptgott** [comment]
@rodgtr1 I agree with what @zmb3 says, and also think any instructions that include `teleport start` should include systemd instructions as well (actually, should probably lead with running Teleport via systemd). Are you comfortable changing the docs to use this approach, or would you like @alexfornuto/me to edit the docs first?

**Comment by rodgtr1** [comment]
@ptgott Thanks for the input. I think if @alexfornuto has the time for it, his input would be much clearer than mine on this matter given his expertise in the docs.

**Comment by alexfornuto** [comment]
@rodgtr1 I think I could update the relevant section of the docs pretty quickly (sometime next week hopefully) to start the agent using the preferred methods. I'm not sure how y'all do your video processing, but I suspect if you still have the project it would be a minimal change to make and re-upload.

**Comment by rodgtr1** [comment]
Thanks @alexfornuto ! That sounds great, next week is fine.  I had to jump to another video in the meantime and will be at the AWS summit next week, so it may be the beginning of the following week before I can update the video, so no rush on it. I'll just leave this PR open then.

**Comment by alexfornuto** [comment]
#27489 provides a lot of update to this guide. I won't replicate my PR description here, but I'm hoping @rodgtr1 will agree that the updates make the Docker example complete and simple enough to be used in the video, instead of AWS.

P.S. I'd also be happy to be involved in the video production for this page.

**Comment by alexfornuto** [comment]
@rodgtr1 #24026 already updated this page's instructions for configuring and starting Teleport. #27489 now provides some small copy edits and an additional Docker instruction, but since your video is using AWS you can likely proceed without it.

**Review by ptgott — APPROVED** [review]

**Comment by alexfornuto** [comment]
It might be worth waiting for #28500 - No one seemed to notice that #24026 broke the ToC of this page, which is visible in your video.

**Comment by rodgtr1** [comment]
> It might be worth waiting for #28500 - No one seemed to notice that #24026 broke the ToC of this page, which is visible in your video.

Thanks @alexfornuto for mentioning this. I didn't even notice. I'll hold off for that and the rest of that PR to be resolved and merged and make adjustments then

**Comment by rodgtr1** [comment]
@ptgott @zmb3 Third time's a charm. New application access video id is pushed based on new docs. Approvals are still there from the last review, but just wanted to double check that this is good to go.

**Review by zmb3 — APPROVED** [review]

**Pull request merged**
