### PR TITLE
stricter `windows_desktop_service` config validation

### PR DESCRIPTION
**Pull request by ibeckermayer**
Adds stricter validation checks to the `windows_desktop_service` configuration section to help ensure that service itself can't get into an unpredictable state.

### CODE REVIEW

**Review by rosstimothy — APPROVED** [review]

**Comment by zmb3** [comment]
Why does this have all of Przemko's commits in it? Weren't those merged in #19806?

**Comment by ibeckermayer** [comment]
> Why does this have all of Przemko's commits in it? Weren't those merged in #19806?

It's because I branched off of that branch (before it was merged). It was merged with a squash, so the diff sees them as new commits. But really its only 63dffa57abb469a82e946a427c4bae335c9942a6 (and the merge commit 1d5a7a694468ae372b648d615765c0b1e1bd2c96) that are new.

@zmb3

**Review by sfreiberg — APPROVED** [review]

**Comment by zmb3** [comment]
@ibeckermayer do we still want this or should we just close it?

**Comment by ibeckermayer** [comment]
It wouldn't hurt but it's diverged enough from master that I would need to redo it. Going to close it for now.

**Pull request closed without merging**
