### PR TITLE
[v11] Add usage events for certificate issuance and additional session types (#20662)

### PR DESCRIPTION
**Pull request by timothyb89**
Backport of  #20662 for branch/v11

---

* Add usage events for certificate issuance and additional session types

This adds a new usage event for certificate issuance, emitted whenever a new user certificate is generated. These events include an anonymized username, TTL, and basic info about which requests are present on the certificate (e.g. db/app/k8s requests).

Additionally, this captures additional session event types from the audit log, including database, app, and desktop sessions, and also properly tags k8s exec sessions which were previously grouped together with SSH.

* Add `SessionStartV2` events, add `is_bot` flag to cert events

* Drop redundant `Event` prefix on `UsageCertificteIssued` event

* Rename `CertificateIssuedEvent` -> `UserCertificateIssuedEvent`

---

Also includes the v11 backport for #21606

### CODE REVIEW

**Comment by timothyb89** [comment]
There's a few backports missing for branch/v11 so some improvisation was needed here (specifically https://github.com/gravitational/teleport/pull/19564, https://github.com/gravitational/teleport/pull/20070). There's no js proto changes included here, I'm not sure where they live in this branch following the webassets merge.

**Review by espadolini — DISMISSED** [review]
Blocking until we have the server side running in prod.

**Comment by michellescripts** [comment]
I'm needing to backport some more prehog changes. Do we need a prehog prod deployment to unblock this? @espadolini @timothyb89

**Comment by timothyb89** [comment]
> I'm needing to backport some more prehog changes. Do we need a prehog prod deployment to unblock this? @espadolini @timothyb89

There was some additional talk about holding off due to some possible proto changes in these new events, though IMO we should just update the .proto the regular way given it's already released in v12. Otherwise, yeah, we were (are?) waiting on a new prehog deployment.

What do you think, @espadolini?

**Comment by espadolini** [comment]
v12 might be released but it's not currently in use; we should tweak the session kind for app session start to distinguish AWS console and TCP app access, and then backport that change together with this, IMO. It should be a Teleport-only change, so we don't need a two step thing.

**Comment by espadolini** [comment]
The backport for #21606 should be added to this PR.

**Review by espadolini — APPROVED** [review]

**Review by michellescripts — APPROVED** [review]

**Review by marcoandredinis — APPROVED** [review]

**Pull request merged**
