### PR TITLE
Move tsconfig.json to root dir, remove web Makefile and Dockerfile

### PR DESCRIPTION
**Pull request by ravicious**
TODO:

- [x] Figure out what to do with `COPY tsconfig.json` in `web/Dockerfile`.

At the moment, it looks like the TS language server has problems with recognizing imports when editing files inside e/web.

I figured this is probably because tsconfig.json is in web, so the lang server doesn't recognize it when editing files from e/web.

---

One remaining problem is that `web/Dockerfile` needs to copy this config within the container but it seems that we can't just do `COPY ../tsconfig.json`. https://stackoverflow.com/questions/27068596/how-to-include-files-outside-of-dockers-build-context

### CODE REVIEW

**Review by tigrato — APPROVED** [review]

**Review by mdwn — APPROVED** [review]

**Comment by ravicious** [comment]
@hatched Do we intend to keep using `web/Makefile` and `web/Dockerfile` after the merge?

AFAIR `web/Dockerfile` was used only by Make targets from `web/Makefile` and our CI checks.

From what I see, `docker-ui` from the root Makefile uses `build.assets/Dockerfile`. If `web/Dockerfile` is no longer needed then that would solve the remaining TODO item from this PR.

**Comment by hatched** [comment]
@ravicious I left it there until the merge was complete just in case we determined it was still needed. If you don't think it's necessary for doing any of the `packages/teleterm` stuff then it can be removed at this point.

**Comment by ravicious** [comment]
It looks like at the moment we're not running the web CI checks for the web code. But if we intend to use the buildbox image (just like the teleport CI checks seem to do) then yeah we can get rid of both the Makefile and Dockerfile.

**Comment by ravicious** [comment]
I have removed web/Dockerfile and web/Makefile. Also made a couple of changes in both readmes but this is not a comprehensive update, just changed what I spotted while changing the command for making a dockerized UI build in the main readme.

**Review by gzdunek — APPROVED** [review]

**Review by zmb3 — APPROVED** [review]

**Pull request merged**
