### PR TITLE
fix operator crashing on first startup

### PR DESCRIPTION
**Pull request by hugoShaka**
The operator crashes on startup because of a regression introduced in https://github.com/gravitational/teleport/pull/28391

This currently affects 13.2.0.

The issue happens because:
- the DeleteBot() endpoint returns an aggregate with 2+ `NotFoundError` errors
- ToGRPC does not support checking the aggregate type and sets the Unknown status code
- FromGRPC doesn't unpack into a trace.NotFoundError because status is not 5
- `trace.IsNotFound` returns false as this is not a NotFoundError anymore
- we expect a NotFoundError and fail because we got something else

The issue got unnoticed because:
- it was added during review and tested less extensively than the first changeset
- there's no integration test for this (actionable item: https://github.com/gravitational/teleport/issues/29006, but for now we need to fix the bug)
- this doesn't trigger if the bot is already here, this passed smoke tests

### CODE REVIEW

**Comment by hugoShaka** [comment]
Another approach is to call DeleteUser() and DeleteRole() directly instead of DeleteBot().

**Review by tigrato — APPROVED** [review]

**Review by marcoandredinis — APPROVED** [review]

**Review by strideynet — APPROVED** [review]

**Comment by zmb3** [comment]
Can we write a test for this?

**Comment by hugoShaka** [comment]
> Can we write a test for this?
Not within a day, this requires setting up a full integration test suite. As there's no integration test framework there this will delay the fix. I suggest we add the test the next time we touch the operator code.

**Comment by zmb3** [comment]
Please file an issue then so we don't lose track of this (who knows when the next time we touch this code will be?)

Regressions indicate a lack of test coverage, so any time we fix one we should be asking why it wasn't caught with automated testing and how we can fix it.

**Comment by hugoShaka** [comment]
> Please file an issue then so we don't lose track of this (who knows when the next time we touch this code will be?)

https://github.com/gravitational/teleport/issues/29006

**Pull request merged**
