### PR TITLE
fix SAML error text

### LINKED ISSUE #1377: SAML error message is repoted as OIDC
From a customer:

SAML erros are incorrectly reported as OIDC errors:

"/web/msg/error/login_failed?details=Unable+to+process+callback+from+OIDC+provider." when using SAML type.

### PR DESCRIPTION
**Pull request by alex-kovoy**
closes #1377

### CODE REVIEW

**Comment by alex-kovoy** [comment]
retest this please

**Comment by alex-kovoy** [comment]
retest this please

**Comment by alex-kovoy** [comment]
retest this please

**Comment by alex-kovoy** [comment]
retest this please

**Review by klizhentas — APPROVED** [review]

**Pull request merged**
